### ISSUE TITLE
gamingbolt.com - missed ads and social widgets

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1000]
> 2. On the website gamingbolt.com it shows buttons for Google Plus, StumbleUpon, and Reddit at the top of a page when viewing an article. It also shows ads at the bottom of the page under "Awesome Stuff that you might be interested in". These ads are from Crowd Ignite, a marketing platform that tracks content. These issues are not present in OS X, only in iOS.

**Comment by Alex-302** [comment]
added for empty rectangle on a rigth side(called as Hottest Game Trailers, but with ads)
```
gamingbolt.com##.small-ad
```

**Comment by ameshkov** [comment]
And what about social widgets?

Don't forget to change user agent to Safari on IPhone to see it (and also change the browser window size)

**Comment by Alex-302** [comment]
I see only text remains of widget at the top of a page
Added
```
gamingbolt.com##.pw-widget
```
