### ISSUE TITLE
[Android] CM Locker

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1002]
Ads in CM Locker app.

HTTP requests log + screenshot here: WZI-309-20699

**Comment by TPS** [comment]
Any possibility this may be helpful/similar to #869 & #870?

**Comment by Alex-302** [comment]
@TPS 
it looks like builtin ad, but I can't reproduce it. All requests in user's log was blocked.
Do you see the ad in this app?

**Comment by TPS** [comment]
I don't use the standalone, but what I reported in https://github.com/AdguardTeam/ExperimentalFilter/issues/869#issuecomment-152189932 is the more basic built-in-to-CleanMaster version, so perhaps same kind of issue?

**Comment by Alex-302** [comment]
@vbagirov 
please send this rules to user
```
||54.149.240.44^$empty
||221.228.204.21^$empty
||54.154.36.95^$empty
||52.25.174.151^$empty
```
