### ISSUE TITLE
gamingbolt.com - do not block links to social accounts on the main page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1004]
<img width="1053" alt="2015-11-30_1212" src="https://cloud.githubusercontent.com/assets/5947035/11467805/bbc11d54-975b-11e5-833b-1f8e5b4713bd.png">

**Comment by Alex-302** [comment]
added
gamingbolt.com#@#.social-icons

**Comment by ameshkov** [comment]
User feedback:
> On the website gamingbolt.com the links for YouTube, RSS, and Google Plus have returned. I'm glad these are on the page now, but the icons are not showing for YouTube and Google Plus -- they are just text. Also, the icons for Facebook and Twitter links are missing, and should not be blocked. This issue is occurring on iOS. On OS X none of the icons are showing at all, which is still an issue.

**Comment by ameshkov** [comment]
Also you'd better change ##.social-icons rule to ~gamingbolt.com instead of adding exception rule.

**Comment by Alex-302** [comment]
Fixed, and other #@# in Social Filter.
