### ISSUE TITLE
giga.de - videos autoplay

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1006]
http://www.giga.de/unternehmen/hp/news/hp-star-wars-special-edition-notebook-ab-sofort-in-deutschland-erhaeltlich
JYU-624-73732

**Comment by Alex-302** [comment]
The video doesn't start automatically on my side
http://imagizer.imageshack.com/img908/6899/PBIKFS.jpg
But we can't prevent this on on other sites, it is dangerously.
