### ISSUE TITLE
http://www.watchepisodes.com/ - missed popup ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1007]
Select openload.co there.

![image](https://cloud.githubusercontent.com/assets/5947035/11486171/5d129702-97c8-11e5-9f86-a98b4a1462e7.png)

**Comment by Alex-302** [comment]
Can't reproduce. Where I should click?

**Comment by ameshkov** [comment]
https://openload.co/f/7BZsMDTMfFQ/regular.show.s07e19.snow.tubing.720p.hdtv.x264-w4f.mkv.mp4

**Comment by Alex-302** [comment]
The rule from EasyList doesn't works
```
||terraclicks.com^$popup,third-party
```
Pupup url has no referrer.
http://www.terraclicks.com/watch?key=c0bf7affe608ffdbe9ad1a8b84e7e6a4
Add this rule?
```
||terraclicks.com^$popup
```

**Comment by ameshkov** [comment]
Yep

**Comment by Alex-302** [comment]
antiblock
@@/Advertisement.css$domain=openload.co
