### ISSUE TITLE
schneider-electric.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1009]
Блокируем лишнее.

Например, переходим на 
http://www.schneider-electric.com/products/ru/ru/82258-raspredelenie-energii-s-cifrovoj-podderzkoj/82261-avtomaticeskie-vyklucateli-i-vyklucateli-razediniteli-s-funkciej-peredaci-dannyh/1887-compact-nsx-630a/?APPLICATION=1002

В списке ниже кликаем на наименование. Привключенном Адгарде информация не отображается.

EUU-227-25126

**Comment by Alex-302** [comment]
Added to Spyware
@@||logi5.xiti.com/go.click$domain=schneider-electric.com
