### ISSUE TITLE
owners.acura.com - self promo should not be blocked

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1013]
> The website owners.acura.com has "ads" at the bottom right of the page that are incorrectly being blocked. These are not actually ads, but links to Acura's website for information on its own cars, so they should not be blocked. There is also an email subscription icon that is incorrectly being blocked. It is located on the bottom left in the "More Ways to Connect" section. Both of these issues occur on OS X and the iPad.

**Comment by Alex-302** [comment]
Added to English filter:
```
@@||owners.acura.com/static/img/content/ads/
```

**Comment by Alex-302** [comment]
And for email subscription:
```
~avito.ru,~gamingbolt.com,~acura.com##.social-icons
acura.com##.social-icons:not(.last)
```
