### ISSUE TITLE
[Extension] Missed ads - nu-stars.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1018]
http://www.nu-stars.com/stars-articles/1229-sekrety-krasoty-ot-zarubezhnyh-zvezd
http://f5.s.qip.ru/OgbqipZu.png
User has Chrome extension with Russian and English filters.
RKF-650-65462

**Comment by Bohdan-SUP** [comment]
Теперь остался только один блок - http://f6.s.qip.ru/Ogbqiq07.png
Повторяется и с программой в том числе.

**Comment by Alex-302** [comment]
Добавил
||nu-stars.com/images/banners/
