### ISSUE TITLE
[Android] Blank space on tinhte.vn

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1019]
1. http://snag.gy/56W7r.jpg
2. http://snag.gy/f86jF.jpg (high-quality filtering method, http proxy mode)

AZA-128-18251

**Comment by Alex-302** [comment]
Страницы с HTTPS не фильтруем. Можем только заблокировать сторонние домены.

**Comment by evgeniy-ADG** [comment]
Спасибо. Сообщил пользователю.
