### ISSUE TITLE
"Upvoted" Advertisements

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/ExperimentalFilter#1022]
All over Reddit, e.g., right sidebar 2× @ https://www.reddit.com/r/ting/comments/3u8vl6/my_wife_and_i_are_signing_up_with_ting_on_friday/

**Comment by Alex-302** [comment]
This?
http://imagizer.imageshack.com/img910/5197/8Lzw0T.jpg

**Comment by TPS** [comment]
No, this (in the shaded red)!:



On Sun, Dec 6, 2015, 4:30 AM Alex <notifications@github.com> wrote:

> This?
> http://imagizer.imageshack.com/img910/5197/8Lzw0T.jpg
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AdguardTeam/ExperimentalFilter/issues/1022#issuecomment-162291026>
> .
>
-- 

https://zhjf9h10ji3.ting.com/

**Comment by TPS** [comment]
No, _this_ (in shaded red)!

https://drive.google.com/file/d/0B9U-jNlL-z-uYUo3Y2hPamh6aUk/view

**Comment by Alex-302** [comment]
We can't filter HTTPS traffic at the moment.
