### ISSUE TITLE
sports.ru (ложное срабатывание)

### ISSUE THREAD

**Issue by Embos** [AdguardTeam/ExperimentalFilter#1023]
http://www.sports.ru/17/
Ложное срабатывание.
Причина в русском фильтре.
Ничего не происходит при нажатии на "поехали"
(adguard для win)

**Comment by Alex-302** [comment]
Добавил в фильтр аналитики
@@||stat.sports.ru/*.json$domain=sports.ru
сработавшее перенёс туда же.
