### ISSUE TITLE
ru.yandex.weatherplugin - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1024]
![photo286427237667940280](https://cloud.githubusercontent.com/assets/5947035/11573625/54993156-9a18-11e5-93de-cf1e30544873.jpg)

**Comment by Bohdan-SUP** [comment]
Логи тут TJD-695-72663

**Comment by Alex-302** [comment]
Похоже без поддержки HTTPS не заблокировать.

**Comment by ameshkov** [comment]
А что именно там не заблокировано

**Comment by Alex-302** [comment]
Сейчас
https://mobile.yandexadexchange.net/v1/ad
ответ зашифрован. Через винду блокируется нормально.

**Comment by ameshkov** [comment]
А чо мы домен не закосим? Судя по названию, он чисто рекламный.

**Comment by Alex-302** [comment]
ad в имени не заметил)
Добавил в моб
||yandexadexchange.net^$empty
