### ISSUE TITLE
softportal.com - missed top banner

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1026]

**Comment by Alex-302** [comment]
Ссылка же ведёт на страницу с описанием, на этом же сайте.

**Comment by ameshkov** [comment]
Не подходит это под селф промо.

Рекламируется конкретный продукт, а не сайт или его акция.

**Comment by Alex-302** [comment]
Адгардовский тоже косить, или для пользующихся расширением оставить?

**Comment by ameshkov** [comment]
Конечно косить, чо мы особенные что ли
