### ISSUE TITLE
aliexpress.com is broken by stealth mode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1027]
http://forum.adguard.com/showthread.php?7804-Adguard-for-Windows-Beta-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F-6-0-107-609&p=67329&viewfull=1#post67329

**Comment by Alex-302** [comment]
I will continue in the new topic on the forum
http://forum.adguard.com/showthread.php?7966
