### ISSUE TITLE
Background ad missed on dizilab.com and dizist.net

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1030]
dizilab.com --> http://snag.gy/QQ9kA.jpg
dizist.net --> http://snag.gy/uErXa.jpg

MED-357-74474

**Comment by Alex-302** [comment]
Added to Turkish filter
||savoy.storage.cubecdn.net/ps/dizilab/
User should to enable this filter, I think it is disabled now.
