### ISSUE TITLE
saddlebackleather.com is broken

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1035]
You are unable to choose size/color, zoom an image, read comments, add to a cart etc when Adguard is enabled.

1. On: http://snag.gy/ZGyhv.jpg
2. Off: http://snag.gy/ordXf.jpg

LGW-421-22558

**Comment by Alex-302** [comment]
fixed rule
```
#%#var addthis = { init: function() {}, addEventListener: function() {}, button: function() {}, counter: function() {}, update: function() {}, toolbox: function() {} };``
```
