### ISSUE TITLE
[Android] не воспроизводится видео на fs.to

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1036]
1. Если Adguard выключн, видео воспроизводится после просмотра 1-2 рекламных роликов. 
2. Со включенной зищитой, режим VPN, рекламы нет, но и видео не загружается: http://snag.gy/eAd76.jpg

CGN-379-48001

**Comment by Alex-302** [comment]
Проверьте со своей стороны такие правила:
```
@@||cxz.to^$jsinject
@@||fs.to^$jsinject
```

**Comment by evgeniy-ADG** [comment]
@Alex-302 Добавил. Видео аботает, но есть реклама перед.

**Comment by Alex-302** [comment]
А есть ещё жалобы на этот сайт? 
Юзеру можете посоветовать прогу FS Videobox c 4pda, на дроиде гораздо удобнее сайта.

**Comment by evgeniy-ADG** [comment]
Других нет, но у меня проблема повторяется.

**Comment by Alex-302** [comment]
ок, добавил исключения в моб фильтр. Но реклама будет, слишком хитро её сделали.
