### ISSUE TITLE
http://thedroidguy.com/ - missed share buttons

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1038]
http://thedroidguy.com/2014/04/setup-wifi-calling-android-device-88975

**Comment by Alex-302** [comment]
added
~facebook.com##a[onclick^="window.open('https://www.facebook.com/sharer.php"]
~twitter.com##a[onclick^="window.open('https://twitter.com/share"]
thedroidguy.com##.post-soc-count
thedroidguy.com###conversions-box
