### ISSUE TITLE
[Android] - reduktoren.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1039]
reduktoren.ru
https://www.dropbox.com/s/xpahnaffttbu39m/Screenshot_2015-12-05-07-56-22.png?dl=0
JYT-791-78327

**Comment by Alex-302** [comment]
сайт с очень низкой посещаемостью, поэтому правила добавил в ЭФ
```
reduktoren.ru##img[width="170"][height="248"]
reduktoren.ru##td > a > img[alt]:not([width])
||ddl.ru/img/pmko.gif
||reduktoren.ru/img/kranov.gif
```
Передайте, чтоб не забыл включить.
