### ISSUE TITLE
Разблокировать рекламу на http://retrofm.ru и http://radio7.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1041]
http://i.imgur.com/hKj59Lf.png
http://i.imgur.com/BkToWAQ.png
там самореклама и ничего более
UJQ-462-13111

**Comment by Alex-302** [comment]
Показ собственных баннеров реализован с использованием рекламной сети adwolf. Такое не разблокируем, т.к. не исключено появление обычной рекламы.

**Comment by Alex-302** [comment]
Юзеру можно передать
@@||adwolf.ru^$domain=retrofm.ru|radio7.ru
@@||retrofm.ru/template/Retro-2012/js/adwolf.js$domain=retrofm.ru

**Comment by ameshkov** [comment]
Если для разблокировки подобной саморекламы требуется разблокировать запросы к рекламным сетям, то помещаем это в полезную рекламу (со ссылкой на гитхаб конечно же).

Дело в том, что разблокировка рекламной сети может также разрешить и обычную рекламу на этом сайте, поэтому так.
