### ISSUE TITLE
http://www.moe-online.ru/ob/ is distorted 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1042]
1. Adguard is on 
![image](https://cloud.githubusercontent.com/assets/15856304/11607591/d7cacec6-9b54-11e5-8a37-d86aa2600776.png)
2. Adguard is off: 
![image](https://cloud.githubusercontent.com/assets/15856304/11607592/ec3943b0-9b54-11e5-9529-cbfb64fdf80c.png)

SVO-156-90947

**Comment by Alex-302** [comment]
добавил
@@/advert$domain=moe-online.ru
