### ISSUE TITLE
[Mac] sciencemag.org

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1043]
www.sciencemag.org
http://imgur.com/a/vrudk
QQC-712-34526

Issue is with Fanboy's Annoyances. Maybe we can apply an exception rule?

**Comment by Alex-302** [comment]
Added to exclusion list
sciencemag.org#@#.rssFeed

**Comment by Alex-302** [comment]
I will close after Fanboy's reply.
