### ISSUE TITLE
[iOS] скрыт логотип rutracker.org

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1045]
http://snag.gy/9AATK.jpg

YXC-787-19547

**Comment by Alex-302** [comment]
Кроме названия темы, расставляй плиз ещё соответствующие метки(справа - Labels), так удобнее выбирать по типу проблемы.

**Comment by Embos** [comment]
А эти Labels все могут расставлять или особый доступ нужен?

**Comment by evgeniy-ADG** [comment]
Не уверен, что у меня есть полномочия. На п. 3 у меня всё немного иначе: https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/

**Comment by Alex-302** [comment]
на сч

**Comment by Embos** [comment]
Мы не можем добавлять, в том числе и в своих темах.
Нужно открывать доступ к лейблам, если это возможно конечно.
![default](https://cloud.githubusercontent.com/assets/9648798/11613654/7eda53e4-9c4a-11e5-8209-9bccb9af9f84.jpg)

**Comment by Alex-302** [comment]
При клике по Labels ничего не открывается?

**Comment by Embos** [comment]
Ничего.

**Comment by Alex-302** [comment]
По проблеме - юзер включил фильтр BitBlock. Там логотипы на некоторых сайтах заблокированы сознательно. Довольно специфический фильтр.

**Comment by Alex-302** [comment]
Можете передать правило, если не захочет выключить фильтр
rutracker.org#@##logo
