### ISSUE TITLE
[Android] Minsk Transport - timetables блок внизу страницы

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1046]
У пользователя реклама (1), у меня в данный момент - серый блок (2). Можем ли мы убрать польностью?
1. http://snag.gy/Xw67a.jpg
2. http://snag.gy/uF6uL.jpg

OER-447-13406

**Comment by Alex-302** [comment]
Не убрать.

**Comment by Alex-302** [comment]
Нет новостей?

**Comment by evgeniy-ADG** [comment]
Нет.
