### ISSUE TITLE
my.velcom.by - add to exceptions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1048]
> На счёт my.velcom.by. Раньше, где-то месяца 3 назад, при включенной защите в телефоне и планшете, я не мог авторизоваться в биллинге. Постоянно крутился кружок. При выключении защиты всё было в порядке. Но тогда этому значению не придал. Вчера попробовал авторизоваться опять. Но то с выключенной и что с включенной защитой почему с планшета через Opera не пускало оО. Сейчас попробовал с Yandex браузера на Windows 7 с запущенным Adguard войти в my.velcom.by и не дало! Нажал на виджет снизу и добавил сайт в исключение и меня впустило в биллинг. Похоже нужно заносить и в обычный фильтр этот домен.

**Comment by Alex-302** [comment]
Добавил в русский
```
@@||my.velcom.by^$document
```
А откуда жалоба? Может удалённо зайти да посмотреть что ломается?

**Comment by ameshkov** [comment]
С 4пда
