### ISSUE TITLE
seasonvar.ru - missed ads in Firefox add-on

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1050]
http://forum.adguard.com/showthread.php?2228-Adguard-%D0%90%D0%BD%D1%82%D0%B8%D0%B1%D0%B0%D0%BD%D0%BD%D0%B5%D1%80&p=67797&viewfull=1#post67797

**Comment by Alex-302** [comment]
The ads should be blocked by the rule from Russian filter:
```
||smilered.com^$third-party
```
Replied on the forum.
Closed there.
