### ISSUE TITLE
sports.ru (пустое место от баннера)

### ISSUE THREAD

**Issue by Embos** [AdguardTeam/ExperimentalFilter#1052]
http://www.sports.ru/automoto/1035176127.html
Пустое место от баннера.
sports.ru##.right-first-banner-place

![22](https://cloud.githubusercontent.com/assets/9648798/11614889/60e910b4-9c72-11e5-89a8-b14537aba636.jpg)

**Comment by Alex-302** [comment]
добавил.
Для каждого баннера на одном сайте не нужно новую задачу открывать, лучше в одной.

**Comment by Embos** [comment]
Алекс серьезно? :)))
Если я сообщаю о нескольких проблемах на одной странице, то все мимо твоих глаз)
Об этом баннере я уже сообщал, читай:
https://github.com/AdguardTeam/ExperimentalFilter/issues/1032
Так что создаю тему на каждую проблему, или читай внимательней посты))

**Comment by Alex-302** [comment]
Там проглядел, но там же и ответить можно было)

**Comment by Embos** [comment]
А я и там сейчас отвечу (есть примечание).
Так что гоу туда)
