### ISSUE TITLE
community.us.playstation.com - missed social widgets

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1054]
Examples:
http://community.us.playstation.com/t5/UNCHARTED-4-A-Thief-s-End/Has-Harry-Flynn-been-recast/td-p/45508393

http://community.us.playstation.com/t5/UNCHARTED-4-A-Thief-s-End/MP-is-a-lot-different-than-past-games/td-p/45513813

**Comment by Alex-302** [comment]
added

**playstation.com**,3dnews.ru,9gag.com,adindex.ru,androidcentral.com,bbc.com,cloudflare.com,digitaltrends.com,disqus.com,filecore.co.nz,goqr.me,howstuffworks.com,ibtimes.co.uk,indiatimes.com,jamendo.com,rt.com,skidkaonline.ru,temp-mail.ru,truba.com,urbandictionary.com,versia.ru##.share
