### ISSUE TITLE
[Android] missed ad in Advanced Download Manager

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1064]
https://play.google.com/store/apps/details?id=com.scores365
http logs 
[debug.txt](https://github.com/AdguardTeam/ExperimentalFilter/files/56592/debug.txt)

![image](https://cloud.githubusercontent.com/assets/15856304/11681986/05054b32-9e6b-11e5-92b6-6429d32356a1.png)
![image](https://cloud.githubusercontent.com/assets/15856304/11682011/2034b686-9e6b-11e5-9e80-be366826463e.png)
SBL-331-27754

**Comment by Alex-302** [comment]
В scores365 вроде чисто. В ADM баннер встроен.
