### ISSUE TITLE
[Android] missed ad in Football Scores - 365Scores

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1065]
https://play.google.com/store/apps/details?id=com.scores365

http log
[debug.txt](https://github.com/AdguardTeam/ExperimentalFilter/files/56603/debug.txt)
![image](https://cloud.githubusercontent.com/assets/15856304/11682227/293d50f2-9e6c-11e5-9e2a-5534b60f816e.png)
![image](https://cloud.githubusercontent.com/assets/15856304/11682249/4298baa0-9e6c-11e5-9671-64e87fc06237.png)
SBL-331-27754

**Comment by Alex-302** [comment]
У меня чисто. У тебя повторяется?

**Comment by evgeniy-ADG** [comment]
Второй серин мой. Да.

**Comment by Alex-302** [comment]
А можешь запилить лог? В том что приаттачен вроде всё блокирвется. Не понятно пока.

**Comment by Alex-302** [comment]
Попробуй такие правила:
||d1rwptle2isgwu.cloudfront.net/AdsConfig/*.json
||nativeadssettings.365scores.com/api/NativeAds

**Comment by Alex-302** [comment]
Не проверяли?

**Comment by evgeniy-ADG** [comment]
Нет, я сегодня посмотрю.

**Comment by evgeniy-ADG** [comment]
AdChoice же, есть он с этими правилами.

**Comment by Alex-302** [comment]
А вход в фейсбук выполнен?

**Comment by evgeniy-ADG** [comment]
Да, через Хром и приложение есть, пользуюсь.

**Comment by Alex-302** [comment]
Видать если в приложении Фейсбука выполнен вход, то рекламный приоритет отдаётся ему.
AdChoices можно будет заблокировать только с поддержкой HTTPS.
Можно ещё такой вариант попробовать, но он с большой вероятностью что-нибудь поломает
||cloudfront.net^$empty

**Comment by Alex-302** [comment]
Пока закрываю,

**Comment by Alex-302** [comment]
C альфой уже чисто.
