### ISSUE TITLE
Adguard hides images on http://b-nn.ru/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1066]
1. off http://snag.gy/pBNEC.jpg
2. on http://snag.gy/HBrKs.jpg

full link http://b-nn.ru/supply/2741/?&ar=0,0&pr=0,0&o=d_r%20desc
HWS-957-58531

**Comment by Alex-302** [comment]
added to Russian
b-nn.ru#@#.ad_image
