### ISSUE TITLE
news.mail.ru - missed yandex.direct

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1068]
http://snag.gy/HchyW.jpg
http://snag.gy/lhuzO.jpg

VSB-821-45025

**Comment by Alex-302** [comment]
Сегодня поправил. Нужно обновить фильтры.

**Comment by evgeniy-ADG** [comment]
Я обновлял перед заведением задачи 100%, сейчас обновил еще раз - скрылось, спасибо.

**Comment by evgeniy-ADG** [comment]
А провеьте еще, не появляется ли у вас снова?
У пользователя есть, у меня нет:

![image](https://cloud.githubusercontent.com/assets/15856304/12070820/a66e8530-b093-11e5-821e-0aeaa96161df.png)
