### ISSUE TITLE
[Android] Missed ad in AVG чистильщик для андроида

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1069]
https://play.google.com/store/apps/details?id=com.avg.cleaner&hl=ru

http://snag.gy/caq9o.jpg
http://snag.gy/cFEXh.jpg

high-quality method

WSI-823-68743

**Comment by Alex-302** [comment]
У вас повторяется? У меня всё чисто.

**Comment by evgeniy-ADG** [comment]
Первы

**Comment by evgeniy-ADG** [comment]
http://snag.gy/hdCw9.jpg
[state(11).txt](https://github.com/AdguardTeam/ExperimentalFilter/files/60101/state.11.txt)
HTTP requests [debug(4).txt](https://github.com/AdguardTeam/ExperimentalFilter/files/60102/debug.4.txt)

**Comment by Alex-302** [comment]
Закрываю до реализации поддержки HTTPS

**Comment by Alex-302** [comment]
С альфой чисто.
