### ISSUE TITLE
[Android] - ivanovonews.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1070]
![ads](https://cloud.githubusercontent.com/assets/14153331/11699862/32d5271c-9ecf-11e5-97d2-55ec9a8036b3.png)
QRL-394-19463

**Comment by Alex-302** [comment]
добавил в русский. После завтрашнего обновления пусть отпишется
ivanovonews.ru###top-banners
ivanovonews.ru##.banner
ivanovonews.ru##.news-banner
