### ISSUE TITLE
[iOS] NFL.com won't load

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1071]
NFL.com does not load anything (just a blank white screen)
Logs here - MAM-679-76703

**Comment by evgeniy-ADG** [comment]
more related logs here RPP-903-20560

**Comment by evgeniy-ADG** [comment]
Now it works but has contains some missed Adchoice ads:
![image](https://cloud.githubusercontent.com/assets/15856304/12017594/5fc355aa-ad61-11e5-81a6-ff617b1e87bf.png)
UIF-108-37696

**Comment by Alex-302** [comment]
Пусть попробует
```
||graph.facebook.com/network_ads_common/
```

**Comment by evgeniy-ADG** [comment]
Написал, подождём.

**Comment by Alex-302** [comment]
А у вас повторяется на айфонах? Нужно чтоб был залогиненный фейсбук.

**Comment by Alex-302** [comment]
Дополнение - видео может ломаться
Добавил в фильтр Сафари
```
@@||googletagservices.com/tag/js/gpt.js$domain=nfl.com
@@||imasdk.googleapis.com/js/core/bridge*.html
```

**Comment by ameshkov** [comment]
So, what with it?

**Comment by ameshkov** [comment]
I see some missed ad placeholders on ipad.
Also the video is broken on article pages like that:
http://www.nfl.com/news/story/0ap3000000625817/article/belichick-i-will-never-underestimate-peyton-manning

Seems to be caused by blocking **googletagservices.com**

**Comment by Alex-302** [comment]
for nfl.com:
re-added to safari filter
```
@@||googletagservices.com/tag/js/gpt.js$domain=nfl.com
@@||imasdk.googleapis.com/js/core/bridge*.html
```
About placeholders  - I don't see them in Safari with iPad useragent

**Comment by ameshkov** [comment]
> About placeholders - I don't see them in Safari with iPad useragent

On the main page

**Comment by ameshkov** [comment]
I've checked a video player inside articles and now it is fixed, thanks.

**Comment by Alex-302** [comment]
added to mobile filter
nfl.com##.hp-tablet-cp-ad-row > div[class^="hp-tablet"]
