### ISSUE TITLE
www.swefilm.tv - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1072]
![1](https://cloud.githubusercontent.com/assets/5947035/11710809/fb059c9a-9f32-11e5-8138-dca6ec5e9514.jpg)
![2](https://cloud.githubusercontent.com/assets/5947035/11710811/fc6f1b7e-9f32-11e5-8044-680ebb760914.jpg)
![3](https://cloud.githubusercontent.com/assets/5947035/11710812/feb45160-9f32-11e5-8db8-aee1d2ead122.jpg)

**Comment by Alex-302** [comment]
Added
```
||swefilm.tv/template/img/topbanner.gif
swefilm.tv##.top_baner
swefilm.tv##a[href*="adquantix.com"]
```

**Comment by ameshkov** [comment]
The banners is back on swefilm:
![1](https://cloud.githubusercontent.com/assets/5947035/12488313/03da0788-c07c-11e5-943a-6b78d9666fa6.jpg)
![namnlos](https://cloud.githubusercontent.com/assets/5947035/12488315/0487ea1a-c07c-11e5-871d-2dd573c84302.jpg)

**Comment by Alex-302** [comment]
added
swefilm.tv##.moviez
swefilm.tv##.blue-btn

**Comment by ameshkov** [comment]
And again, new ads:

![swefilm1](https://cloud.githubusercontent.com/assets/5947035/12705631/6dc41276-c886-11e5-81e6-53c92d7fa734.jpg)
![swefilm](https://cloud.githubusercontent.com/assets/5947035/12705632/6e71c1d2-c886-11e5-9b24-51db3538089a.jpg)

**Comment by Alex-302** [comment]
old rules replaced by
```
swefilm.tv##a[href^="http://adsrvmedia.adk2x.com/"]
swefilm.tv##.ads_mainmid
||swefilm.tv/template/img/midads.png
swefilm.tv##.top-banner
||swefilm.tv/template/img/topbanner.png
```

**Comment by ameshkov** [comment]
Again:

![5](https://cloud.githubusercontent.com/assets/5947035/12875076/43f28244-cdf3-11e5-9679-262773579be6.jpg)
![namnlos 1](https://cloud.githubusercontent.com/assets/5947035/12875077/449fa00a-cdf3-11e5-8983-9b1c5647a8d1.jpg)

**Comment by Alex-302** [comment]
swefilm.tv##.moviez > a > img
