### ISSUE TITLE
Can't play videos on iltalehti.fi and istv.fi

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1073]
iltalehti.fi
1. on: http://snag.gy/9bCGs.jpg
2. off: http://snag.gy/VIDE7.jpg

istv.fi
1. on: http://snag.gy/jea4S.jpg
2. off: http://snag.gy/tUowk.jpg

GFZ-115-77301

**Comment by Alex-302** [comment]
Всегда спрашавайте список фильтров.
1. Добавил в фильтр аналитики:
```
@@||nexus.ensighten.com/alma/iltalehti/*$domain=iltalehti.fi
```
2. В английский:
```
@@||adserver.adtech.de/?adrawdata/*/noperf$domain=files.snstatic.fi
```
Проверь у себя эти правила на всякий случай.
