### ISSUE TITLE
genius.com - missed social buttons in mobile version of the website

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1075]
http://genius.com/Nirvana-in-bloom-lyrics

**Comment by Alex-302** [comment]
Added to Social filter
genius.com##.song_header-share_buttons
genius.com##.custom_share

**Comment by ameshkov** [comment]
More rules needed:
```
genius.com##facebook-share-button
genius.com##twitter-share-button
```

**Comment by Alex-302** [comment]
But they are hidden by
```
genius.com##.song_header-share_buttons
```
http://imagizer.imageshack.com/img908/3355/gCs5c0.jpg

**Comment by ameshkov** [comment]
Not everywhere:

<img width="504" alt="2015-12-19_1317" src="https://cloud.githubusercontent.com/assets/5947035/11912564/de9255cc-a652-11e5-894f-8dca01cbeaec.png">

**Comment by Alex-302** [comment]
Clicked anywhere, but can't find the way to this block

**Comment by ameshkov** [comment]
First you should change the user agent to iPhone.
Then go to http://genius.com/7624919
And click on any paragraph there

**Comment by Alex-302** [comment]
added
genius.com##[url="annotation.share_url"]
