### ISSUE TITLE
Приложение ВКонтакте "Спортивные точки"

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1077]
http://vk.com/app4214777_24975212

Не работает для Windows adguard.

"http://joxi.ru/YmE13VLuZZ706m
Не загружается список игроков справа. А так же при переходе на профиль." - слова от пользователя ВКонтакте

**Comment by Alex-302** [comment]
Добавил в русский:
```
@@||game.playdots.ru/ajax$document
```
Пусть юзер отпишется.

**Comment by vbagirov** [comment]
Пользователь пишет: 
"Раньше запросы не работали даже когда счетчика аналитики не был подключен. После вашей правки все заработало. Но стоило опять просто подрубить счетчик аналитики и этот запрос опять стал падать https://game.playdots.ru/index/getGamesAndGamers
http://joxi.ru/nAyLJz7uXYja72

Проблема похоже осталась только в этом месте. Так как на тот же профиль (который раньше не работал) теперь спокойно переходит"

**Comment by Alex-302** [comment]
добавил
@@||game.playdots.ru/index/getGamesAndGamers^$document
