### ISSUE TITLE
debridfast.com, getdebrid.com - anti-adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1079]
![image](https://cloud.githubusercontent.com/assets/15856304/11740156/507dd3f6-9ff9-11e5-8b5b-b10b2e64e9b0.png)
![image](https://cloud.githubusercontent.com/assets/15856304/11740165/5cdbc5a4-9ff9-11e5-8c83-f37f4d33cf24.png)
GCA-685-99603

**Comment by Alex-302** [comment]
added
||debridfast.com/blocker.js
||getdebrid.com/blocker.js
