### ISSUE TITLE
cnews.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1081]
Например: http://www.cnews.ru/news/top/2015-11-17_google_sozdaet_tri_novye_modeli_umnyh_ochkov

Пользователь утверждает, что на странице антиадблок, причем появляется именно после включения английского фильтра: http://screencast.com/t/ocgMfLpnp

Проблема наблюдается им в IE11

KOT-510-55312

**Comment by Alex-302** [comment]
Не повторилось.
