### ISSUE TITLE
[Android] pad.showname.jp/pad.apk app crashes

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1083]
It stops if you use Adguard with regular basic filter set, I can't launch the app even without Japanese filters.

![image](https://cloud.githubusercontent.com/assets/15856304/11749209/138efb28-a035-11e5-8fa4-3a1a376405e4.png)

What kind of logs we need?

CFM-351-35747

**Comment by Alex-302** [comment]
HTTP log and time of error.

**Comment by evgeniy-ADG** [comment]
[debug(3).txt](https://github.com/AdguardTeam/ExperimentalFilter/files/59934/debug.3.txt)
Check this one please. The app crashed at 01:06.

**Comment by Bohdan-SUP** [comment]
Logs here - LLL-464-57396

**Comment by Alex-302** [comment]
Please check this
@@||sp.ad.adlantis.jp/sp/load_app_ads?adlProtocolVersion

**Comment by evgeniy-ADG** [comment]
still crashes.

**Comment by Alex-302** [comment]
This rule must fix the problem
@@||sp.ad.adlantis.jp/sp/load_app_ads?

**Comment by evgeniy-ADG** [comment]
This one works!
