### ISSUE TITLE
Missed ads at kinobanda.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1087]
http://prntscr.com/9d7jcq
http://kinobanda.net/
ESP-547-61112

**Comment by Alex-302** [comment]
Добавил
||bequri.com/sys/js/$third-party

**Comment by evgeniy-ADG** [comment]
http://kinobanda.net
http://prntscr.com/absuzz

**Comment by Alex-302** [comment]
||koiper.com^$third-party
