### ISSUE TITLE
[Extension] Yandex direct at https://pogoda.yandex.ru/biysk/

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1089]
https://pogoda.yandex.ru/biysk/
http://f4.s.qip.ru/Ogbqiq8U.png
NMA-611-88982

**Comment by Alex-302** [comment]
У меня чисто
http://imagizer.imageshack.com/img908/3350/HdSmQl.jpg
Возможно DrWeb мешает.
Заявки от жителей Бийска лучше перепроверять, т.к. там живёт известный троль:)

**Comment by Alex-302** [comment]
Исправлено.

**Comment by Bohdan-SUP** [comment]
iOS теперь
![image1](https://cloud.githubusercontent.com/assets/14153331/12889075/e3289032-ce85-11e5-94de-3d466673be8b.PNG)

**Comment by Alex-302** [comment]
Эти баннеры убираются JS-ными правилами, которые в Сафари не поддерживаются(ограничение браузера)
Проверьте у себя в Сафари такое правило
```
pogoda.yandex.ru##div[class$="adbca_js_inited"]
```
Если сработает - добавлю.

**Comment by Alex-302** [comment]
@Bohdan-SUP

**Comment by Alex-302** [comment]
Добавил в русский. Если поможет - закрывай.

**Comment by Bohdan-SUP** [comment]
Работает.
