### ISSUE TITLE
[Android] - Weather Crave app

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1092]
https://play.google.com/store/apps/details?id=com.lachainemeteo.androidapp
http://imgur.com/oG7NZOC
Logs here - CKT-955-22424
Can't reproduce on my side.

**Comment by Alex-302** [comment]
Looks like Adchoises(Facebook ads)
Please try this rule(other ads)
||ligatus.com^$empty

**Comment by Alex-302** [comment]
Закрываю до реализации поддержки https
