### ISSUE TITLE
[Android] Banner missed in The Edmonton Oilers app

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1093]
https://play.google.com/store/apps/details?id=com.yinzcam.nhl.oilers&hl=en
http://snag.gy/hzpCT.jpg
HTTP requests log [debug (1).txt](https://github.com/AdguardTeam/ExperimentalFilter/files/60416/debug.1.txt)

PWV-360-61099

**Comment by Alex-302** [comment]
added
||yc-ads.s3.amazonaws.com^$empty
