### ISSUE TITLE
[iOS] can't play videos on giantbomb.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1097]
Videos cannot be played through safari browser on giantbomb.com with the following filters on:

English+Spyware+Social+Mobile ads+Easylist China

CZT-330-10946

**Comment by Alex-302** [comment]
the same problem is on Windows
Added to English:
```
@@||dw.cbsi.com/anonc.js$domain=giantbomb.com
@@||imasdk.googleapis.com/js/core/bridge*.html$domain=giantbomb.com
```
User should check this site after update.

**Comment by evgeniy-ADG** [comment]
I just have replied to the customer. Will update here.
