### ISSUE TITLE
amazon.com - missed social widgets in Mobile version of the website

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1101]
Example:
http://www.amazon.com/gp/aw/d/B00OQVZDJM/ref=s9_al_gw_g349_i2?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=mobile-1&pf_rd_r=0SZ200JV27P7X61FRT66&pf_rd_t=36701&pf_rd_p=2274306722&pf_rd_i=mobile

Under the product description.

```
amazon.com##.swf-sn-share-link
amazon.com###facebook
amazon.com###twitter
```

**Comment by Alex-302** [comment]
added
