### ISSUE TITLE
podrobnosti.ua - broken script

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1104]
http://forum.adguard.com/showthread.php?8160-Windows-6-0-107-609-%D0%9D%D0%B5%D0%BE%D1%82%D0%B2%D0%B5%D1%87%D0%B0%D1%8E%D1%89%D0%B8%D0%B9-%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B9-%D0%BD%D0%B0-http-podrobnosti-ua

**Comment by Alex-302** [comment]
I don't see the script error, but loading too long
I see this urls are in pending(~20sec)
(new Image).src = "http://edge0.itcons.net.ua:1935/castGeoEncr/image.gif";
(new Image).src = "http://edge1.itcons.net.ua:1935/castGeoEncr/image.gif";
Blocking of urls doesn't change this.

**Comment by ameshkov** [comment]
So?

**Comment by Alex-302** [comment]
Fixed by
||mmi.bemobile.ua^
