### ISSUE TITLE
[iOS] Ads missed on www.asiaone.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1106]
http://www.asiaone.com/mobile and singaporeseen.stomp.com.sg

![image](https://cloud.githubusercontent.com/assets/15856304/11778013/7c9aee66-a25a-11e5-9f70-06a74939bd7d.png)
![image](https://cloud.githubusercontent.com/assets/15856304/11778082/e8a45962-a25a-11e5-81e0-438f3d401b95.png)

OAD-755-97550

**Comment by amourchaleur** [comment]
Any idea when this can be fixed? Thanks!

**Comment by Alex-302** [comment]
@amourchaleur hi
I don't understand where are the ads. Can you describe or mark them on screenshots?

**Comment by amourchaleur** [comment]
The section where it says "shopping. See more deals on Qoo10" and the 4 pictures below it are the ads.

**Comment by Alex-302** [comment]
please check these rules in the User Filter
```
asiaone.com##section[id*="-qoo10-box-"]
asiaone.com#@#.main-ads
```
What about singaporeseen.stomp.com.sg ? Are there ads too?

**Comment by amourchaleur** [comment]
Added the rules. It's working. 

Yups singaporeseen.stomp.com.sg there are also ads. The ads are the section "shopping see more from Qoo10" and the 4 pictures below it. Thanks!

**Comment by amourchaleur** [comment]
I added asiaone.com##section[id*="-qoo10-box-"] into users filter which makes the ads disappear. 

asiaone.com#@#.main-ads can't be added into the user filters. There is a rule text can't be added error.

**Comment by Alex-302** [comment]
We will check this error.
The rules added to the English filter.

singaporeseen.stomp.com.sg
can you make a screenshot of ads? I don't see them. Are they only on mobile version of site, or desktop too?

**Comment by amourchaleur** [comment]
Okays. Please see this screenshot. I've highlight the ads. 

http://postimg.org/image/jkuvcm2gj/
It's on both versions mobile and desktop. 

And of you don't mind could you also help with this? The social media icons are still showing up on individual news articles. I've highlighted it in the screen shots 

http://postimg.org/image/o3jld1xb1/

Much appreciated. Thanks!

**Comment by Alex-302** [comment]
for ads
stomp.com.sg###block-boxes-q0010-widget

I need a url of the page with the social icons.
Check this rule
asiaone.com##.social-icon-bar
it is for
http://news.asiaone.com/news/asia/indonesian-police-say-new-year-terror-plot-foiled-5-held?utm_medium=Social&utm_source=Twitter&utm_campaign=Echobox&utm_term=Autofeed&link_time=1450599255#xtor=EchoBox

**Comment by amourchaleur** [comment]
Added asiaone.com##.social-icon-bar this is working. 

Tried stomp.com.sg###block-boxes-q0010-widget is not working. 

This is the URL http://www.straitstimes.com/asia/east-asia/many-feared-dead-after-18-buildings-collapse-in-landslide-at-china-industrial-park

**Comment by amourchaleur** [comment]
Edit: stomp.com.sg###block-boxes-q0010-widget is working for desktop version of the site but it leaves an empty space. On mobile version, this is not working at all. Thanks!

**Comment by Alex-302** [comment]
>Edit: stomp.com.sg###block-boxes-q0010-widget is working for desktop version of the site but it leaves an empty space.

I don't see it.

Added:
||stomp.com.sg/qoo10/
straitstimes.com##.field-name-social-media-buttons-bottom
asiaone.com##.view-aone2015-qoo10-box

**Comment by amourchaleur** [comment]
Please see empty space screenshot here http://postimg.org/image/fq4o32wff/

Working:
||stomp.com.sg/qoo10/
asiaone.com##.view-aone2015-qoo10-box

Not working:
straitstimes.com##.field-name-social-media-buttons-bottom
Social media icons are still showing up. 

Thanks!

**Comment by Alex-302** [comment]
Please check this rules:
 1. http://singaporeseen.stomp.com.sg/
```
||adtag.asiaone.com^
```
2. http://www.straitstimes.com/asia/east-asia/many-feared-dead-after-18-buildings-collapse-in-landslide-at-china-industrial-park
```
straitstimes.com##.a2a-buttons
```

**Comment by amourchaleur** [comment]
Both working. Thanks! All resolved!

**Comment by Alex-302** [comment]
That's good)

**Comment by Alex-302** [comment]
thу rules added to the English filter
