### ISSUE TITLE
[iOS] Blank space on forums.soompi.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1107]
http://forums.soompi.com/en/topic/375532-current-mainland-chinese-drama-2015-love-me-if-you-dare-when-he-comes-close-your-eyes-他来了请闭眼/?page=6

![image](https://cloud.githubusercontent.com/assets/15856304/11778055/b923026a-a25a-11e5-82ad-ee66b34bb6e8.png)

OAD-755-97550

**Comment by Alex-302** [comment]
added
soompi.com###ad-med-rect
