### ISSUE TITLE
Adguard breaks SurfEasy extension

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1109]
https://addons.opera.com/en/extensions/details/surfeasy-proxy-an-opera-software-company/?utm_medium=sm&utm_source=news_blog&utm_campaign=surfeasy_extension_announcement

Tested in Opera. Doesn't work with 5.10, works with 6.0 beta only when you disable Stealth mode

![image](https://cloud.githubusercontent.com/assets/15856304/11778747/189045e2-a25f-11e5-8a25-2a336adaccdf.png)

YME-232-89220

**Comment by Alex-302** [comment]
У меня с 6.0 работает. Stealth mode ломает только если включить сокрытие IP.

**Comment by Alex-302** [comment]
@ameshkov Можно в такой ситуации помочь?

**Comment by ameshkov** [comment]
@Alex-302 
Слишком специфично. А можешь посмотреть на background page расширения, куда оно там запросы отправляет?

Думаю можно подобрать фильтр, который это чинит. Но в основные фильтры не стоит добавлять, просто здесь в теме его оставим.

**Comment by Alex-302** [comment]
@ameshkov 
Помогло такое
@@||api.surfeasy.com/*/geo_lookup
Может всё же добавим?

**Comment by ameshkov** [comment]
Да, давай

**Comment by Alex-302** [comment]
Добавил.
