### ISSUE TITLE
[Android] Missed ad in НашеТВ app

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1110]
https://play.google.com/store/apps/details?id=com.kino.nashetv

![image](https://cloud.githubusercontent.com/assets/15856304/11781540/342a8146-a273-11e5-8ccb-7ba9b5d7635a.png)

  "enabledFilterIds" : [ 2, 3, 10, 1, 11 ],
  "environment" : "prod",
  "filteringQuality" : "FULL",

RIX-312-41978

**Comment by Alex-302** [comment]
||appclick.net^$empty
частично не работает в режиме VPN(блокируется с включенной фильтрацией DNS). В режиме прокси вообще не срабатывает. 
https://appclick.net/apromo.php?i=nashe&v=2&device=D5503
```
"items":[
{
"title":"Русское ТВ 150 каналов",
"url":"https://play.google.com/store/apps/details?id=com.mediamolodej.tvonline&utm_source=message",
"text":"Русское ТВ дает 150 каналов. Скачайте как резервное приложение. На всякий случай. Все бесплатно! Скачайте и попробуйте!",
"no":"Нет",
"yes":"Установить ТВ",
"show":"show1"
}
]
}
```
@ameshkov , в чём может быть дело?

**Comment by ameshkov** [comment]
Фигово. Это из-за того, что используется cloudflare для проксирования этого домена, а приложение использует старую версию TLS и не посылает название домена.

В общем надо ждать фильтрацию HTTPS полноценную.

**Comment by Alex-302** [comment]
закрываю до лучших времён

**Comment by Alex-302** [comment]
С альфой все заблокировано.
