### ISSUE TITLE
[Android] social buttons missed in Рамблер.Новости

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1111]
https://play.google.com/store/apps/details?id=ru.rambler.news&hl=ru

![image](https://cloud.githubusercontent.com/assets/15856304/11781833/7e520ba2-a275-11e5-9f2a-251a98664baf.png)

![image](https://cloud.githubusercontent.com/assets/15856304/11781841/8e686874-a275-11e5-8a4a-0ec69c4e4660.png)
IKT-454-52655

**Comment by Alex-302** [comment]
Там страницы преобразованы в формат JSON, не скрыть.
