### ISSUE TITLE
Banner Adv. on Windows10Update

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/ExperimentalFilter#1112]
On http://www.windows10update.com/ & succeeding pages,
1. Small banner ad near top
2. _Huge_ (almost) full-page banner near bottom just below page navigation

**Comment by Alex-302** [comment]
added
windows10update.com##.optin-monster-overlay
windows10update.com##a[rel="nofollow"][href^="http://home.zoolz.com/"] > img

**Comment by TPS** [comment]
@Alex-302 This works for small banner ad near top, but _not_ for giant picture ad toward bottom, headed __WINDOWS 10 BUSINESS TRAINING__.

**Comment by Alex-302** [comment]
@TPS 
added
windows10update.com##a[href^="http://www.windows10update.com/windows-10-business-training"]

**Comment by TPS** [comment]
_That_ got it!  Thanks! :bow:

**Comment by TPS** [comment]
@Alex-302 Another 1 made it through:  On http://www.windows10update.com/download-windows-10/ @ center-page, ![NetDNA Adv](http://4dm7pi3anfms2bn7sk7u16h1.wpengine.netdna-cdn.com/wp-content/uploads/2014/07/OptimizePC3.jpg) makes it through.…

**Comment by Alex-302** [comment]
added
windows10update.com##a[rel="nofollow"] > img[alt^="OptimizePC"]

**Comment by TPS** [comment]
Thanks!
