### ISSUE TITLE
softobase.com, besplatnyeprogrammy.ru - downloads are broken

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1118]
Examples:
http://www.besplatnyeprogrammy.ru/installpack.html/download#downloading
http://softobase.com/ru/fifa-15#download_tabs

**Comment by ameshkov** [comment]
To fix this:
```
@@||googletagmanager.com/gtm.js$domain=besplatnyeprogrammy.ru
```

**Comment by Alex-302** [comment]
It works. Added to analytics filter.

**Comment by ameshkov** [comment]
More websites with the same issue:
http://moiprogrammy.net/
http://www.freeversions.ru/
http://www.softhome.ru/
http://softmen.ru/
http://www.freeversion.ru/

**Comment by Alex-302** [comment]
added
```
@@||googletagmanager.com/gtm.js$domain=besplatnyeprogrammy.ru|softobase.com|freeversion.ru|softmen.ru|freeversions.ru|moiprogrammy.net
```
http://www.softhome.ru/ -  works without exclusion

**Comment by Kap1tan531** [comment]
https://tvoiprogrammy.ru/
https://mirprogramm.ru/
