### ISSUE TITLE
playground.ru - galleries are broken

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1120]
http://pix.playground.ru/witcher_3_wild_hunt/1397267/

> На примере странице http://pix.playground.ru/witch... в галереях сайта http://www.playground.ru/ при включенном Adguard не возможно осуществлять перелистывание изображений, а так же закрыть их. При отключение Adguard и перезагрузки страницы проблема пропадает, настройки заданы по умолчанию.

**Comment by Alex-302** [comment]
added to Social filter
@@||yastatic.net/share/share.js$domain=pix.playground.ru
~yandex.ru##a[href^="https://share.yandex.net/go.xml?service="]
