### ISSUE TITLE
askmen.com - missed social widgets

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1121]
> When viewing articles on askmen.com on iOS and OS X there are social widgets -- "Share" (for Facebook) and "Tweet" (for Twitter). Also if you scroll through an article there is a bar at the top of the page that appears, which includes share icons for Facebook, Twitter, and Tumblr (on iPhone it shows Whatsapp instead of Tumblr). Here is an example:

http://www.askmen.com/entertainment/special_feature_150/188_special_feature.html

**Comment by Alex-302** [comment]
added
askmen.com##.shareBlock
askmen.com##.share
