### ISSUE TITLE
news.am

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1126]
У пользователя черный экран вместо рекламы: http://screencast.com/t/JrT2OXg7YHz3

У меня воспроизвелась реклама.

Проверяли на странице http://news.am/rus/videos/3360.html

SDB-805-30596

**Comment by Alex-302** [comment]
Добавил в русский
||videochart.net/mnb/*.mp4
Желательно проверить тому, у кого чёрный экран висел.
