### ISSUE TITLE
[android] Youtube app

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#113]
Ads are not blocked in the app (sometimes)

**Comment by TPS** [comment]
Advanced notice: YouTube seems to be declaring war on ad-avoidance, & is rolling out unskippable ads.  (I surmise this may include ad-blocking countermeasures.)

Source: http://www.theverge.com/2016/4/26/11510472/youtube-unskippable-bumper-ads-announced

More info as I find it.
