### ISSUE TITLE
slashdot.org - do not remove "follow us" in

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1131]
<img width="417" alt="2015-12-19_1309" src="https://cloud.githubusercontent.com/assets/5947035/11912537/cff0cab8-a651-11e5-93d1-ebac11d62d2d.png">

**Comment by Alex-302** [comment]
fixed
~slashdot.org##.nav-social
~slashdot.org##.icon-facebook-squared

**Comment by ameshkov** [comment]
One more block in mobile version of the website:
<img width="502" alt="2015-12-20_1800" src="https://cloud.githubusercontent.com/assets/5947035/11918468/ab8952ba-a743-11e5-9c4b-240b91f7d434.png">

**Comment by Alex-302** [comment]
fixed
