### ISSUE TITLE
slashdot.org - missed share button on mobile website

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1132]
<img width="504" alt="2015-12-19_1310" src="https://cloud.githubusercontent.com/assets/5947035/11912546/1d325792-a652-11e5-8830-e99fa85c241a.png">

**Comment by Alex-302** [comment]
added
slashdot.org##.janrainSocialPlaceholder
slashdot.org##.share.tappable
