### ISSUE TITLE
Не воспроизводится видео на big.stb.ua

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1133]
http://big.stb.ua/episode/neslyhannye-rekordy-pohudeniya-uchastnikov-5-sezona-smotrite-v-sleduyushhej-programme/

![image](https://cloud.githubusercontent.com/assets/15856304/11917958/7c37b556-a725-11e5-8f75-5c8991801048.png)

"Браузер любой. Использую 6 версию, через журнал фильтрации выяснил что 
блокируется видео из набора фильтров счетчики и систем аналитики, а 
конкретно строчка в фильтре связанна с адресом bemobile.ua"

CPH-610-27267

**Comment by Alex-302** [comment]
На проверку
```
@@||source.mmi.bemobile.ua/cm/cm.js$domain=big.stb.ua
```

**Comment by evgeniy-ADG** [comment]
Не помогло.

**Comment by Alex-302** [comment]
плеер не появился, или такая картина?
http://imagizer.imageshack.com/img907/5758/kVSFej.jpg
у меня без фильтрации не играет

**Comment by evgeniy-ADG** [comment]
Не появляется плеер, как на моем скрине выше.

**Comment by Alex-302** [comment]
очень странно.
А так
@@||bemobile.ua^

**Comment by evgeniy-ADG** [comment]
А так - работает :) Плеер есть, видео в нем - тоже.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
проверь плиз ещё, переделал правила в фильтре аналитики.Только обновись сперва

**Comment by evgeniy-ADG** [comment]
@Alex-302 всё работает
