### ISSUE TITLE
Missed ad on topnews.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1134]
![image](https://cloud.githubusercontent.com/assets/15856304/11918322/a0be7aae-a734-11e5-992d-f5baa7997bb0.png)

Id=0 Name=User filter Version=0.0.0.0
Id=1 Name=Russian filter Version=1.0.29.41
Id=2 Name=English filter Version=1.0.73
Id Name=Filter for useful ads Version=1.0.0.84

LTM-335-74520

**Comment by Alex-302** [comment]
added
||ruschopi.ru^$third-party
