### ISSUE TITLE
[Android] rutor.org

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1136]
При клике по ссылке, чтобы прочитать описание Торрента вместо того чтоб открыть ссылку в текущем окне, открывается новое окно и после ряда редиректов в нем открывается реклама, скажем, онлайн казино Вулкан.

Ссылка на один из редиректов - http://hghit.com/direct?placement_id=722&param=%5Bany%5D

FBR-127-73383

**Comment by Embos** [comment]
Не только на Android, у меня на ПК тоже иногда выскакивает popup вулкан на руторе (и его официальных зеркалах)

**Comment by Alex-302** [comment]
Они часто домены меняют. Сейчас у меня чисто.

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/11994462/9807c4d6-aa47-11e5-912c-fc29bc3c2f8b.png)

ROW-258-47855

**Comment by Alex-302** [comment]
У меня чисто.
Если повторяется, сделай плиз лог HTTP запросов с указанием времени, или юзера попроси.

**Comment by evgeniy-ADG** [comment]
Я потестирую сайт, запишу логи.

**Comment by Alex-302** [comment]
Ну что там, есть реклама?

**Comment by Alex-302** [comment]
У меня чисто, включая пару зеркал. Закрываю.
