### ISSUE TITLE
[iOS] can't play videos on pornhub.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1142]
![image](https://cloud.githubusercontent.com/assets/15856304/11951959/b9ec7d9a-a89d-11e5-8d80-f30d7cc1cd69.png)
Не возможен просмотр видео , т.к все считается за рекламу 
Включая даже логотип сайта , меню поиска и т.д
Остаётся таким же в независимости изменения и отключения фильтров . Начинает работать только когда вообще отключаешь все фильтры для этого сайта 
![image](https://cloud.githubusercontent.com/assets/15856304/11951976/d24e30d6-a89d-11e5-80ac-c43f7503e664.png)
![image](https://cloud.githubusercontent.com/assets/15856304/11951980/d8d0b91a-a89d-11e5-84a0-24a1424ebe23.png)
![image](https://cloud.githubusercontent.com/assets/15856304/11951988/dfccb048-a89d-11e5-9779-139bd667144a.png)
OZI-161-38272
XSP-646-72932

**Comment by Alex-302** [comment]
added to safari
@@||static.pornhub.phncdn.com^$domain=pornhub.com
should be checked
