### ISSUE TITLE
VK app missed trackers

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1143]
tracker-api.my.com
m.vk.com/counters.php
api.vigo.ru

Check that app works ok if we block these.

**Comment by Alex-302** [comment]
I don't see these requests from VK app.
Added:
||tracker-api.my.com^$third-party
||api.vigo.ru^$third-party
||m.vk.com/counters.php

**Comment by ameshkov** [comment]
All three should be $empty

**Comment by Alex-302** [comment]
Fixed in mobile filter.
