### ISSUE TITLE
Missed ads on http://www.jpost.com/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1144]
![image](https://cloud.githubusercontent.com/assets/15856304/11954512/c4d2069e-a8b1-11e5-8e40-c17043f5c4d3.png)
![image](https://cloud.githubusercontent.com/assets/15856304/11954651/e0e45aac-a8b2-11e5-815a-b34f191991c6.png)

Id=0 Name=User filter Version=0.0.0.0
Id=2 Name=English filter Version=1.0.73.2
Id=3 Name=Spyware filter Version=1.0.4.20
Id=4 Name=Social media filter Version=1.0.7.74

I can reproduce it, the screenshot is mine.
Also, I see this notification when I open the site.

![image](https://cloud.githubusercontent.com/assets/15856304/11954601/8a6e4192-a8b2-11e5-92e0-7ce2681a8059.png)
XSP-646-72932

**Comment by Alex-302** [comment]
added
||zedo.com^$third-party
jpost.com##.social-icon-wrap
jpost.com##.hot-on-social-wrap
jpost.com##[data-social-title]
||zoomanalytics.co^$third-party

**Comment by Bohdan-SUP** [comment]
User states that issue still persisted.
However, he fixed it by adding "127.0.0.1 po.adonor.org" to hosts.
