### ISSUE TITLE
http://online.anidub.com/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1146]
Реклама в шапке сайта; слева под меню сайта; справа изображение, закрепленное на экране при прокрутке, появляется у тех кто использует блокираторы рекламы; пропадает кнопка Adguard на сайте, и его не возможно использовать.

![image](https://cloud.githubusercontent.com/assets/15856304/11954943/89672e6e-a8b5-11e5-803b-bb49babf0f52.png)
![image](https://cloud.githubusercontent.com/assets/15856304/11954944/91a15e10-a8b5-11e5-9aeb-05bdfa84c244.png)

OUE-770-36778
STR-806-68501

**Comment by Alex-302** [comment]
У вас повторилось? У меня чисто. Какие фильтры у юзера?

**Comment by evgeniy-ADG** [comment]
Повторилось. Два пользователя писало о проблеме.

**Comment by Embos** [comment]
У меня повторяется.
Adguard 6
(eng, rus, social, счетчики)

**Comment by Alex-302** [comment]
А дайте удалённый доступ, поправлю.

**Comment by evgeniy-ADG** [comment]
"Левый баннер исчез, правый (не корректно работающий) все еще на месте".

Доступ могу сегодня с 18 дать, если по времени ок.

**Comment by vbagirov** [comment]
На данный момент при включенном блокировщике пропадают изображения в верху страницы, а у одного из пользователей ещё и изображения в ленте: http://screencast.com/t/D68xouvRcW

https://adguard.com/ru/adguard-report/online.anidub.com/report.html#comment-2427061789

**Comment by vbagirov** [comment]
Ещё один пользователь добавляет:
"Стали блокироваться переключение серий и оценка серий , не показывает обновление на их странице в вк и твитере , так же не показывает постеров на главной странице"

**Comment by Alex-302** [comment]
Вроде поправил
