### ISSUE TITLE
[iOS] Missed ad on citilink.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1149]
Пропущена реклама на странице:
http://www.citilink.ru/catalog/computers_and_notebooks/parts/memory/?available=1&status=0&p=1&f=650_288d1gb,650_2816d1gb,1299_281,1299_282,2798_28,647_28DDR3,647_28DDR3L,9034_281600mgts,9034_281866mgts,9034_281333mgts,9034_282000mgts,9034_282133mgts,9034_282400mgts,9034_282666mgts,9034_282800mgts,9034_283000mgts,9034_283200mgts,9034_283300mgts,9034_283333mgts,9034_283400mgts,9034_283600mgts,9034_28800mgts

После 1 товара идёт теперь уже пустой блок, потому что реклама заблокирована. В полной версии можно убрать и его. Уберите и здесь, пожалуйста, чтобы было удобнее. Спасибо за вашу работу!

![image](https://cloud.githubusercontent.com/assets/15856304/11955965/29ad5ee4-a8bf-11e5-8451-13babae3f58b.png)
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.73.12 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.3.65 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.7.75 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.78 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.29.44 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.1.84 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.19 Enabled=YES

IOO-505-52659

**Comment by Alex-302** [comment]
Там самореклама и акции(разблокировал).
Юзеру можете передать правило
citilink.ru##.toggling_banners
