### ISSUE TITLE
kinogo.co

### ISSUE THREAD

**Issue by Embos** [AdguardTeam/ExperimentalFilter#1156]
http://kinogo.co/
Фоновая кликабельная реклама.
![default](https://cloud.githubusercontent.com/assets/9648798/11975008/43ab7084-a98b-11e5-804d-94c98c0a5760.jpg)

**Comment by evgeniy-ADG** [comment]
WNR-471-77662
HGW-867-37527

**Comment by Embos** [comment]
Пока Алекс среагирует, уже вся реклама пропадет.... очень долго
Алекс aka Cannot reproduce

**Comment by Alex-302** [comment]
Вчера исправлено было

**Comment by evgeniy-ADG** [comment]
Снова есть 

![image](https://cloud.githubusercontent.com/assets/15856304/12018753/e95f5328-ad6f-11e5-9436-84d074447c1c.png)

TNS-936-87053
