### ISSUE TITLE
[iOS] http://wi-fi.ru/desktop

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1158]
![image](https://cloud.githubusercontent.com/assets/15856304/11976576/1f6351dc-a982-11e5-804b-5b6be0767471.png)

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.72.92 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.16 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.72 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.23.47 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.84 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.29.36 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.1.78 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.19 Enabled=YES
ID1 Name="EasyList" Version=1.0.49.12 Enabled=YES
ID2 Name="ABPindo" Version=1.0.0.26 Enabled=YES
ID5 Name="RU AdList" Version=1.0.49.16 Enabled=YES
ID8 Name="EasyPrivacy" Version=1.0.49 Enabled=YES
ID1 Name="void.gr" Version=1.0.0.48 Enabled=YES
ID2 Name="Fanboy's Annoyances" Version=1.0.49.24 Enabled=YES
ID!5 Name="Fanboy's Enhanced Tracking List" Version=1.0.1 Enabled=YES
ID!0 Name="Spam404" Version=1.0.1.25 Enabled=YES
ID!3 Name="RU AdList: BitBlock" Version=1.0.45.99 Enabled=YES

BFY-981-93165
SEA-233-53758
GHX-914-41021

**Comment by Alex-302** [comment]
Пусть проверит такое правило и отпишется
||cdn.vmet.ro/brandings/*/index.html
А есть ещё такие жалобы?

**Comment by evgeniy-ADG** [comment]
Да.
SEA-233-53758
GHX-914-41021
GHX-914-41021

**Comment by Alex-302** [comment]
Странности. Такое только на iOS?

**Comment by evgeniy-ADG** [comment]
Я поискал по "wi-fi.ru" в CRM, конкретно с этой проблемой нашло только 3 обращениея по iOS.

**Comment by ameshkov** [comment]
Вот так лучше попробовать:
```
||cdn.vmet.ro/brandings/*/index.html$subdocument
```

**Comment by Alex-302** [comment]
Дополню:
```
||static.wi-fi.ru/brandings/rb/
||wi-fi.ru/ad_video/
```

**Comment by Alex-302** [comment]
Ну что там? Передавали правила?

**Comment by evgeniy-ADG** [comment]
Работают правила, можно закрывать.
