### ISSUE TITLE
https://novaposhta.ua/tracking - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1159]
![image](https://cloud.githubusercontent.com/assets/15856304/11978571/5439f3da-a995-11e5-993c-af37e987ed01.png)

Extension for Chrome, 
English filterVersion 1.0.73.24. Updated 23 december 2015 at 14:00.
Spyware filterVersion 1.0.4.25. Updated 22 december 2015 at 18:27.
Experimental filterVersion 1.0.23.54. Updated 23 december 2015 at 16:00.
Russian filterVersion 1.0.29.48. Updated 22 december 2015 at 18:27.
German filterVersion 1.0.22.37. Updated 22 december 2015 at 18:27.
Liste FRVersion 1.0.49.52. Updated 23 december 2015 at 16:02.
Juvander AdblockFinlandVersion 1.0.1.30. Updated 23 december 2015 at 12:02.
Adblock polskie regulyVersion 1.0.2.91. Updated 22 december 2015 at 20:05.

**Comment by Alex-302** [comment]
Сейчас/уже чисто.
