### ISSUE TITLE
Missed ad on http://www.boerse-online.de/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1164]
![image](https://cloud.githubusercontent.com/assets/15856304/11994408/6b6d15d0-aa46-11e5-9734-aac04d4a704e.png)

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.73.21 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.23 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.76 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.84 Enabled=NO
ID=6 Name="German filter" Version=1.0.22.36 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.1.85 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.19 Enabled=YES
ID1 Name="EasyList" Version=1.0.48.84 Enabled=NO
ID7 Name="EasyList Germany" Version=1.0.49.10 Enabled=NO
ID8 Name="EasyPrivacy" Version=1.0.48.71 Enabled=NO
ID2 Name="Fanboy's Annoyances" Version=1.0.49.45 Enabled=NO
ID 8 Name="Malware Domains" Version=1.0.49.28 Enabled=YES

FPG-649-56425

**Comment by Alex-302** [comment]
added to German
boerse-online.de###hvb-homepage-integration-container
||boerse-online.de/Images/b_partner/
