### ISSUE TITLE
[iOS] missed ads on vapenews.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1167]
http://vapenews.ru/blog/eliquid/

![image](https://cloud.githubusercontent.com/assets/15856304/11994676/726bf860-aa4b-11e5-9bc8-775ebc94a53c.png)

![image](https://cloud.githubusercontent.com/assets/15856304/11994679/79270794-aa4b-11e5-9593-904d96b029c3.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.73.23 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.25 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.77 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.78 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.29.48 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.1.86 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.19 Enabled=YES

VFR-555-96165

**Comment by Alex-302** [comment]
added to Russian filter
||vapenews.ru/adv/
