### ISSUE TITLE
rufilm.tv

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1169]
Видеореклама в плеере перед видео.

**Comment by Alex-302** [comment]
Реклама вшита в видео.

**Comment by vbagirov** [comment]
А точно ли вшита? Смотрится как отдельный ролик.

**Comment by Alex-302** [comment]
На таймер посмотри. Если отдельным роликом - дай ссылку где такое.

**Comment by Alex-302** [comment]
||roukel.com^$third-party

**Comment by Bohdan-SUP** [comment]
Branding is not blocked - http://prntscr.com/a8zhhi

**Comment by Alex-302** [comment]
||slowpoker.ru^$third-party

**Comment by Alex-302** [comment]
разные проблемы в одну задачу не стоит добавлять, желательно новую открывать
