### ISSUE TITLE
[iOS] iguides.ru 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1179]
![image](https://cloud.githubusercontent.com/assets/15856304/12002745/49dfa7b8-ab11-11e5-996f-32c35ca8c400.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.73.24 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.26 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.79 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.23.54 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.78 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.29.50 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.1.88 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.20 Enabled=YES
ID1 Name="EasyList" Version=1.0.46.61 Enabled=NO
ID5 Name="RU AdList" Version=1.0.46.62 Enabled=NO
ID 7 Name="Adblock Warning Removal List" Version=1.0.49.51 Enabled=YES
ID 9 Name="Prebake" Version=1.0.1 Enabled=NO
ID!1 Name="Anti-Adblock Killer | Reek" Version=1.0.1.55 Enabled=YES
ID!3 Name="RU AdList: BitBlock" Version=1.0.46.33 Enabled=YES

EEO-239-88831

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/12018553/130ae4ce-ad6d-11e5-9810-d5cf0de8ed11.png)
PGG-780-90457

**Comment by Alex-302** [comment]
Fixed
