### ISSUE TITLE
[iOS] reshil.org

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1184]
http://reshil.org/homework/10-klass/algebra/191
http://prntscr.com/9inz16

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.73.24 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.26 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.79 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.29.50 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.20 Enabled=YES

TUI-632-11334

**Comment by Alex-302** [comment]
added
reshil.org###trr
