### ISSUE TITLE
vulcun.com is broken

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1185]
adg on ![image](https://cloud.githubusercontent.com/assets/15856304/12007152/2490f29c-ac00-11e5-8d12-912c699d6670.png)
adg off
![image](https://cloud.githubusercontent.com/assets/15856304/12007153/3b3b8890-ac00-11e5-998b-ffd5f2343c8b.png)

reproduced on my side with basic set of filters

ZXZ-200-67069

**Comment by Alex-302** [comment]
Передайте юзеру, что он на форуме не в тот раздел писал. Нужно сюда:
http://forum.adguard.com/forumdisplay.php?71
Добавил в соц фильтр
```
@@||platform.twitter.com/oct.js$domain=vulcun.com
```
