### ISSUE TITLE
www.fast-torrent.ru - blocked elements appear again after blocking others

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1186]
1. Опишите действия для повторения ошибки Шаг 1: установил Adguard на свежеустановленую ОС Windows 10 Pro Шаг 2: на сайте http://www.fast-torrent.ru/ стал блокировать ненужные мне элементы Шаг 3: несколько элементов Adguard заблокировал, но когда я стал блокировать остальные элементы, предыдущие, которые я уже заблокировал, появились снова. Результат: программа сначала заблокировала элементы, но они появились снова. 2. Какой антивирус вы используете? Panda Free Antivirus 2016 (http://www.pandasecurity.com/ukraine/homeusers/solutions/free-antivirus/)

http://www.seedoff.net/ 
http://prntscr.com/9ic5rv
http://prntscr.com/9io2pb

more details here: VSZ-473-15123

**Comment by Alex-302** [comment]
Передай юзеру
```
||rublacklist.net/media/
||img.seedoff.net/banners/imghost/
```
