### ISSUE TITLE
nur.kz false positive 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1187]
![image](https://cloud.githubusercontent.com/assets/15856304/12007300/981a6760-ac06-11e5-87c5-c27388d535c5.png)

помогает отключения фильтра счетчиков и системной аналитики

GIM-248-11934

**Comment by Alex-302** [comment]
Добавил в счётчики
@@||i.onthe.io^$image,domain=nur.kz
Пусть отпишется
