### ISSUE TITLE
[iOS] appsliced.co - missed social buttons

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1188]
Pinterest share button not blocked.

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.73.20 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.23 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.76 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.84 Enabled=NO
ID Name="Mobile ads filter" Version=1.0.1.85 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.19 Enabled=YES
ID1 Name="EasyList" Version=1.0.49.35 Enabled=YES
ID8 Name="EasyPrivacy" Version=1.0.49.23 Enabled=YES
ID2 Name="Fanboy's Annoyances" Version=1.0.49.47 Enabled=YES
ID3 Name="Fanboy's Social Blocking List" Version=1.0.49.35 Enabled=NO
ID!5 Name="Fanboy's Enhanced Tracking List" Version=1.0.1 Enabled=YES
ID!1 Name="Anti-Adblock Killer | Reek" Version=1.0.1.55 Enabled=YES

MYC-480-14859

**Comment by Alex-302** [comment]
added
appsliced.co###sharing_bar
