### ISSUE TITLE
bobfilm.net - missed background ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1189]
![image](https://cloud.githubusercontent.com/assets/15856304/12009781/8d302ecc-ac90-11e5-8b0f-7638dfcb24fc.png)
Id=0 Name=User filter Version=0.0.0.0
Id=1 Name=Russian filter Version=1.0.28.77
Id=2 Name=English filter Version=1.0.71.63
Id=3 Name=Spyware filter Version=1.0.3.85
Id=4 Name=Social media filter Version=1.0.7.36
Id Name=Filter for useful ads Version=1.0.0.79
Id4 NameкsyList China Version=1.0.48.14

XTR-904-55133

**Comment by Alex-302** [comment]
Added
||viturek.com/sys/js/$third-party
