### ISSUE TITLE
com.dv.adm - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1191]
https://play.google.com/store/apps/details?id=com.dv.adm

User complaint:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=45566397

**Comment by Alex-302** [comment]
This app has builtin ads. But it is possible to prevent display them, if we return empty <html></html> to response of this request:
```
https://googleads.g.doubleclick.net/mads/gma?request_id=****
```
And need https support.

**Comment by ameshkov** [comment]
So we're waiting for HTTPS support

**Comment by Alex-302** [comment]
Closed. Waiting for version with https support.

**Comment by Alex-302** [comment]
This app is clean with alpha-version with https support.
