### ISSUE TITLE
comediansincarsgettingcoffee.com - missed share button

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1196]
> There is a grey "Share" button on iPad and OS X that includes share icons for Twitter, Facebook, Reddit, etc. By clicking the button, the icons are revealed, so the "Share" button itself should be blocked. It is located at the top of the page directly under the video player.

**Comment by Alex-302** [comment]
comediansincarsgettingcoffee.com##.video--share
