### ISSUE TITLE
cbsnews.com - missed share buttons on mobile website

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1198]
**IMPORTANT:** to see the mobile website clear cookies after changing the user agent

<img width="504" alt="2015-12-28_1850" src="https://cloud.githubusercontent.com/assets/5947035/12021087/05dea76e-ad94-11e5-978a-4f1d287b80ab.png">

**Comment by Alex-302** [comment]
added
cbsnews.com###floating-sharebar
But Adguard for Windows doesn't injects to the page.
