### ISSUE TITLE
twitch.tv - does not load stream on mobile

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1200]
Just choose any stream here:
http://www.twitch.tv/directory/game/Hearthstone%3A%20Heroes%20of%20Warcraft

Don't forget to change the user agent to iPhone

**Comment by Alex-302** [comment]
Added
```
@@||imasdk.googleapis.com/js/core/bridge*.html$domain-twitch.tv
```
