### ISSUE TITLE
fiveironfrenzy.com - missed social widgets

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1201]
> 1. When viewing an article on OS X there is a widget that should be blocked. The widget is on the left side of the page and shows a Tumblr share icon and a "..." icon. When clicking the "..." icon it shows a share button for just about every social media website.

> 2. On iOS and OS X, if you leave an article open for a bit, (switching tabs then coming back to the page helps, but it is not necessary) a pop-up appears that says "Share Five Iron Frenzy Share this with your friends!" and shows a bunch of share widgets. This pop-up should be blocked.

<img width="1101" alt="2015-12-28_1915" src="https://cloud.githubusercontent.com/assets/5947035/12021377/5b4938e2-ad97-11e5-8005-bf33c2c7e300.png">

**Comment by Alex-302** [comment]
It is WP plugin.
Added
/wp-content/plugins/monarch/$domain=~elegantthemes.com
