### ISSUE TITLE
Balance BY - broken by Adguard for Android

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1203]
> стоит это приложения Balance BY в нем есть баланс сбербанк онлайн когда работает Adguard не хочет обновлять провайдера как только вырублю его все нормально работает вырубаю в брандмауэре блок рекламы в Balance BY и видно что он пропускает трафик я так думаю когда нет скорости в инете и еще  Adguard режит трафик вот поэтому не идут обновления

**Comment by Alex-302** [comment]
Там крайне много запросов к рекламным сетям. Может прогу клинит иногда. У меня проверкой баланса телефона и интернета проблема не повторилась.
