### ISSUE TITLE
CWTV.com - anti-adblock script

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1207]
![image](https://cloud.githubusercontent.com/assets/15856304/12033120/2bb52032-ae28-11e5-9b15-efcaebc10705.png)

TCR-629-60019

**Comment by Alex-302** [comment]
Added
```
@@||partner.googleadservices.com/gpt/pubads_impl_$domain=cwtv.com
@@||googletagservices.com/tag/js/gpt.js$domain=cwtv.com
```
But ***need*** to check with US proxy/VPN
