### ISSUE TITLE
www.bild.de

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1208]
e.g.: http://www.bild.de/video/startseite/bildchannel-home/video-home-15713248.bild.html

video does not play with enable Adguard

**Comment by ameshkov** [comment]
@Alex-302 the problem is only in the desktop version of AG. The problem is in how they execute JS when the video is played.

What should be done in the filter:
1. Remove $$ rule, no need in it.
2. Add a try-catch clause to the js rule

**Comment by Alex-302** [comment]
thanks, fixed
