### ISSUE TITLE
vladtv.com - missed social widgets

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1209]
http://www.vladtv.com/article/215733/michael-jordan-pays-tribute-to-little-brother-kobe-in-final-charlotte

Look on the left side

**Comment by Alex-302** [comment]
Fix for top padding
```
vladtv.com#@##cmn_ad_tag_head
```
Added to Social filter:
```
vladtv.com##.sharing-buttons
```
