### ISSUE TITLE
пышаминфо.рф - заблокированы объявления на сайте объявлений

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1211]
Блок с объявлениями скрывается.
![image](https://cloud.githubusercontent.com/assets/15856304/12049236/5123581e-aeed-11e5-92fb-e6e279d6367d.png)

QOL-204-53396

**Comment by Alex-302** [comment]
Это ж реклама. На форуме ей объясняли уже.
