### ISSUE TITLE
sex-empire.tv, leporno.org - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1212]
http://sex-empire.tv/film/englich_film/6466-luchshie-francuzskie-aktrisy-best-of-les-actrices-francaises.html

![image](https://cloud.githubusercontent.com/assets/15856304/12049943/c739d9fc-aef6-11e5-96d2-ea9194ee08d2.png)

![image](https://cloud.githubusercontent.com/assets/15856304/12049951/dfc5a5e6-aef6-11e5-967d-5da2fa93c2fb.png)

DQX-216-75114

**Comment by Alex-302** [comment]
1.
```
||tubecontext.com^$popup,domain=sex-empire.tv
||f.sex-empire.tv/?x=
||sex-empire.tv//sticker?id=
||ruhotgirls.com/*/ad/$image
||tcpalace.com/*?AdId=$image
||sex-empire.tv/templates/dark/img/
```
2.
||doktorvit.com^$domain=leporno.org
||popvertising.com^$third-party
