### ISSUE TITLE
[iOS] sp-fan.ru missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1213]
![image](https://cloud.githubusercontent.com/assets/15856304/12050127/111a744e-aef9-11e5-889f-e8ce51fd7737.png)

RRZ-375-21935

**Comment by Alex-302** [comment]
У меня блокируется.

**Comment by Alex-302** [comment]
c упрощенными фильтрами тоже
