### ISSUE TITLE
[iOS] www.cultofmac.com - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1217]
Won't let me view the site unless I turn off adguard

Incorrect blocking on page:
http://www.cultofmac.com/400935/best-apple-tv-apps-2015/

UVI-263-99747

**Comment by Alex-302** [comment]
I see only anti-adblock message
Added to English filter
cultofmac.com##.adblock-notification-wrapper
User may to check it
