### ISSUE TITLE
[iOS] ecigtalk.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1221]
ecigtalk.ru/usercp.php 
Обновляем страницу, реклама в шапке сайта.

http://prntscr.com/9h43sm

JMO-468-97600

**Comment by Bohdan-SUP** [comment]
Дополнение от пользователя - "Заметил вот какую странность, при переходе на сайт с помощью закладки на рабочем столе реклама есть и после обновления исчезает (т.е. все по старому, проблема есть). При переходе на сайт с помощью закладки на экспресс панели браузера safari рекламы нет- блокировка работает корректно".

**Comment by Alex-302** [comment]
Здесь явно не в фильтрах проблема. Лучше в разделе iOS запили баг. Здесь закрою пока
