### ISSUE TITLE
[iOS] comnews.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1223]
comnews.ru/news - Реклама на странице, повторилось со стандартными фильтрами.

YJP-634-17511

**Comment by Alex-302** [comment]
@vbagirov 
Чтоб быстрее исправлялось - если в винде полностью повторяется иосная реклама, то в заголовке в [ ] указывай. Исключение - мобильные варианты сайтов

Добавил в русский
||comnews.ru/sites/default/files/banners/
