### ISSUE TITLE
origin.com - missing top panel

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1224]
Source complaint:
http://forum.adguard.com/showthread.php?8373-Adguard-%D0%B4%D0%BB%D1%8F-Windows-%D0%A0%D0%B5%D0%BB%D0%B8%D0%B7-%D0%BA%D0%B0%D0%BD%D0%B4%D0%B8%D0%B4%D0%B0%D1%82-Adguard-6-0&p=71263&viewfull=1#post71263

**Comment by Alex-302** [comment]
Adguard injected to JS.
Fixed
@@||akamaihd.net/origin-com-store-webassets/$script,document
