### ISSUE TITLE
cbsnews.com - blocked links to social accounts

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1225]
http://www.cbsnews.com/news/60-minutes-apple-tim-cook-charlie-rose/

<img width="1136" alt="2015-12-30_2042" src="https://cloud.githubusercontent.com/assets/5947035/12054606/ff13847e-af35-11e5-9c74-102692241675.png">

**Comment by Alex-302** [comment]
edit
~cbsnews.com,~avito.ru,~hh.ru##.social-icon
