### ISSUE TITLE
forbes.com - lots of issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1226]
@Alex-302 most of these issues aren't iOS specific (except the first).

> 1. When viewing an article on iOS there is a share icon (it looks like an arrow) in the upper right corner of the page. When tapping this arrow it shows icons for sharing via Facebook, Twitter, Google Plus, etc. Note that some of the social icons are just squares, but the links still work when you tap them. To avoid this, the arrow itself should be blocked.

> 2. On OS X there is a similar issue. When viewing an article there is a "Comment Now" section on the left side of the page. Right under this you will see an envelope for sharing via email. The main problem is next to that email icon there are links that are still clickable for sharing via Facebook, Twitter, Google Plus, etc. While the icons may appear invisible, they are not totally blocked. You can notice this by hovering your cursor right next to the email icon to see there is a clickable link, which leads to the share widget that should be blocked.

> 3. When viewing an article on iOS and OS X it incorrectly blocks links to the author's Facebook and Twitter pages. These are not sharing buttons so they should not be blocked. I've included an example below. In this article, the author (Liyan Chen) has links under the "Follow on Forbes" section under her name. Right now it only shows RSS and email, but should also show the Facebook and Twitter pages. Note on iPhone you have to tap "Full Bio" under the author's name to see the "Follow on Forbes" section.
http://www.forbes.com/sites/liyanchen/2015/12/21/the-most-profitable-industries-in-2016/

> 4. When viewing a picture gallery on iPad there is a Facebook Share icon at the bottom left of the image. Here is an example:
http://www.forbes.com/pictures/fjlj45glfg/berkshire-hathaway/

> 5. On iOS and OS X there is sometimes a Twitter share icon (it also says "Tweet This" on iPad and OS X) at the top left of an image when viewing an article. Here is an example:
http://www.forbes.com/sites/natalierobehmed/2015/12/21/hollywoods-best-actors-for-the-buck-2015-chris-evans-leads-mila-kunis-scarlett-johansson-and-more/

**Comment by Alex-302** [comment]
1. I don't see the sharing buttons for now;
2.
