### ISSUE TITLE
metrolyrics.com - missed share widgets (desktop)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1229]
http://www.metrolyrics.com/jingle-bells-lyrics-christmas-carols.html

<img width="1052" alt="2015-12-31_0251" src="https://cloud.githubusercontent.com/assets/5947035/12059296/716af498-af69-11e5-8074-db2287694adc.png">

**Comment by Alex-302** [comment]
added
metrolyrics.com##.js-share
metrolyrics.com##.js-sd-social
