### ISSUE TITLE
https://minigames.mail.ru missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1230]
Пропущена полезная реклама на https://minigames.mail.ru/balda?site_id=1_845_73930_13_
Скриншот: http://f6.s.qip.ru/Ogbqiqqb.png

SUL-354-98979

**Comment by Alex-302** [comment]
Replaced
@@||ad.mail.ru/adq/$domain=mail.ru
by
@@||ad.mail.ru/adq/$domain=mail.ru|~minigames.mail.ru

**Comment by evgeniy-ADG** [comment]
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13553430/bf3bdb90-e391-11e5-9806-a9da3fb3d2e1.png)

</details>

у нас тут баннер

**Comment by Alex-302** [comment]
@evgeniy-ADG 
не вижу. всегда нужна прямая ссылка

**Comment by evgeniy-ADG** [comment]
@Alex-302 

Вот ссылка https://minigames.mail.ru/
Только что проверил - есть.

**Comment by Alex-302** [comment]
minigames.mail.ru##div[class^="w-adv-"]
