### ISSUE TITLE
yandex direct

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1231]
Здравствуйте ! Пропуск рекламы наЯндекс погода.Появилась реклама(Яндекс.Директ.) на сайте Яндекс.Погода.Реклама проявляется в любом браузере.Помогает очистка куки и кэш,но ненадолго.После двух-трёх открытий данного сайта. Яндекс.Директ. появляется вновь.Програмама Adguard 6.0 установлена на чистую ось.С уважением.

![0a868370-aefe-11e5-9eea-d6111ec8f44b](https://cloud.githubusercontent.com/assets/15856304/12071115/fb600ba4-b0a2-11e5-81fd-67e8954f001c.png)
SPQ-874-92792

**Comment by Alex-302** [comment]
Правила уже в фильтре.
Пользователям расширения в фоксе придётся подождать, т.к. JS-ные правила зашиты в него(политика Мозиллы)
