### ISSUE TITLE
zpravy.idnes.cz

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1232]
http://zpravy.idnes.cz/nemecko-zprisni-proverovani-zadatelu-o-azyl-f37-/zahranicni.aspx?c=A151231_113003_zahranicni_cen
![adg1](https://cloud.githubusercontent.com/assets/14153331/12071527/67e5fdea-b0b9-11e5-9ea2-0ae365e97352.gif)

http://zpravy.idnes.cz/foto.aspx?r=zahranicni&c=A151231_132254_zahranicni_kha
![adg2](https://cloud.githubusercontent.com/assets/14153331/12071535/8546f6d2-b0b9-11e5-9bc3-6d6edb4f0302.gif)

GPG-555-49607

**Comment by Alex-302** [comment]
@Bohdan-SUP 
added:
```
||zpravy.idnes.cz/*.aspx?c=
zpravy.idnes.cz#%#Object.defineProperty(window, 'AdTrack', { get: function() { return; } }); 
```
user may test this rules
