### ISSUE TITLE
[iOS] m.finn.no

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1235]
http://m.finn.no/frontpage.html
"All I get is about:blank when trying to load items on this site".
NDE-558-12639

**Comment by Alex-302** [comment]
he may to check filter updates. This site works correctly on our iPad

**Comment by Hrti** [comment]
You need to try and open a listing on that page (search for something like "volkswagen passat" and try to open one of the listings by tapping on it. It just opens an about:blank tab. It loads correctly if long pressing and selecting "open in background though

**Comment by Alex-302** [comment]
@Hrti 
hi
please check this rule
```
@@||m.finn.no/*/ad.html?
```

**Comment by Hrti** [comment]
Added this rule to the user filter section of the app. Works a treat! +1:

**Comment by Alex-302** [comment]
added to safari filter
update will be tomorrow
