### ISSUE TITLE
[Android] Dictionary - Merriam-Webster missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1236]
sponsored by Taboola ![image](https://cloud.githubusercontent.com/assets/15856304/12080420/e1bb26b4-b261-11e5-826b-2570548b846c.png)

HOT-570-60376

**Comment by Alex-302** [comment]
added
||trc.taboola.com^$empty
||api.taboola.com/*/recommendations.get^$empty
