### ISSUE TITLE
http://www.chollisimo.com - missed share widgets (desktop)

### ISSUE THREAD

**Issue by Aokromes** [AdguardTeam/ExperimentalFilter#1238]
missed share widgets (desktop) http://i.imgur.com/gFJfxlb.jpg

**Comment by Alex-302** [comment]
Hi
It should be blocked by this rule
```
||static.addtoany.com$third-party
```
Which filters and version of Adguard are you using?

**Comment by Aokromes** [comment]
6.0.146.791 and all filters xd (i browse internet on a lot of languages)

**Comment by Alex-302** [comment]
You can open filter editor and enter to the search string **addtoany**. Then navigate in the filters.
If you will see the rules with @@ or/and #@# , copy-paste them here.

Or you can temporary disable all filters, except "Adguard filters".

**Comment by Aokromes** [comment]
http://i.imgur.com/qddqLnm.png
Btw, the problem is the buttons are missing with adguard, not they are missed to be blocked.

**Comment by Aokromes** [comment]
Disabling social filters fixes it :)

**Comment by Alex-302** [comment]
So you want to unlock them? I thought that you want to block it:)
If you want social buttons - you should disable social filter.
