### ISSUE TITLE
fishki.net missed social widget

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1239]
![image](https://cloud.githubusercontent.com/assets/15856304/12091032/90bb54d2-b2fc-11e5-81bf-8982b26e7475.png)

KIU-458-82402

**Comment by Alex-302** [comment]
Это ссылки на блоги, не блокируем их.
В блоке комментирования есть кнопки отправки коммента в соц сети, вот её заблокируем
fishki.net##.crosspost-to

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/12171762/4017e804-b501-11e5-9a44-3a5134057337.png)
А вот такие посты с (Р) мы можем блокировать?

**Comment by Alex-302** [comment]
Да. Правила в экспериментальном фильтре.
