### ISSUE TITLE
m.gamer.com.tw doesn't load with English filter and EasyList

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1240]
![image](https://cloud.githubusercontent.com/assets/15856304/12091186/d7017948-b2fd-11e5-9aac-5bc440dfbef2.png)

AOP-185-65881

**Comment by Alex-302** [comment]
user can disable EasyList, because our English filter is the fork of EasyList

**Comment by Alex-302** [comment]
@evgeniy-ADG user can disable EasyList, because our English filter is the fork of EasyList

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Fixed.
User(or you) may check it.
