### ISSUE TITLE
[iOS] kinogo.co - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1242]
![image](https://cloud.githubusercontent.com/assets/15856304/12091471/0b6525e8-b300-11e5-93c4-27c0f9e06fd1.png)

![image](https://cloud.githubusercontent.com/assets/15856304/12091475/12121f36-b300-11e5-89fd-e479beb091a2.png)

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.72.69 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.9 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.64 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.29.22 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.16 Enabled=YES

YBW-325-61806

**Comment by Alex-302** [comment]
Пусть обновит фильтры,
