### ISSUE TITLE
[Android] u-f.ru - annoying pop-up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1243]
![image](https://cloud.githubusercontent.com/assets/15856304/12091684/21854d70-b301-11e5-8c69-34ee309c4ab5.png)

on windows it looks more informative:
![image](https://cloud.githubusercontent.com/assets/15856304/12091713/4d9c2d52-b301-11e5-8d1e-bb8ab34439bb.png)

XUO-678-29504

**Comment by Alex-302** [comment]
added to social filter
u-f.ru##html > body > div#pp, html > body > div#pp-bg
