### ISSUE TITLE
http://steamidlemaster.com/ is broken

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1244]
adg on
![image](https://cloud.githubusercontent.com/assets/15856304/12091754/a9e72c1a-b301-11e5-8a2c-fba41b67f715.png)

adg on, english and russian filters off:
![image](https://cloud.githubusercontent.com/assets/15856304/12091863/607821be-b302-11e5-8fb1-614fa53256e5.png)

ZXZ-200-67069

**Comment by Alex-302** [comment]
added
@@||steamidlemaster.com/images/banner.jpg
