### ISSUE TITLE
http://www.nudeplayboygirls.com/ - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1248]
At the bottom of the webpage is a white box that says Close [X] if you click it to remove it, it takes you to other websites. http://www.nudeplayboygirls.com/

http://snag.gy/rQ62x.jpg

VXY-301-85965

**Comment by Alex-302** [comment]
added
nudeplayboygirls.com,bigjapanesetube.com,rushasiantube.com##html > body > div#topbar
