### ISSUE TITLE
[iOS] http://animeflv.net/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1251]
![image](https://cloud.githubusercontent.com/assets/15856304/12171911/56737d7e-b502-11e5-9ebd-19f3c8230bd5.png)

REP-424-24941

**Comment by Alex-302** [comment]
to mobile
||admin.appnext.com^$empty
to Safari filter
||admin.appnext.com^$third-party
