### ISSUE TITLE
[iOS] seasonvar.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1255]
http://seasonvar.ru/serial-12729-V_pustyne_smerti-1-season.html
http://prntscr.com/9n3i58
http://prntscr.com/9n3i7i
http://prntscr.com/9n3ib3

IRZ-965-53022

**Comment by Alex-302** [comment]
added to safari filter
||reactiv.$third-party
||psmardr.com^$third-party
||smilered.com^$third-party

**Comment by Bohdan-SUP** [comment]
It's there again:
http://imgur.com/TaanMHz

**Comment by Alex-302** [comment]
@Bohdan-SUP 
чисто вроде. Может фильтры старые?

**Comment by Bohdan-SUP** [comment]
Фильтры обновлял. У меня тоже не повторялось.

**Comment by Alex-302** [comment]
Значит юзеру надо обновить)
Закрываю пока.
