### ISSUE TITLE
missed adds at dailymail

### ISSUE THREAD

**Issue by Aokromes** [AdguardTeam/ExperimentalFilter#1256]
I get adds this page:
http://www.dailymail.co.uk/news/article-3270774/Life-size-caravan-built-entirely-Lego-bricks.html
http://i.imgur.com/NMg2Wo1.png

**Comment by Alex-302** [comment]
It is absolutely clean on my end.
And I don't see these banners without Adguard.

**Comment by Aokromes** [comment]
Maybe it was seasonal, no adds anymore.
