### ISSUE TITLE
www.sciencemag.org - misssed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1257]
![image](https://cloud.githubusercontent.com/assets/15856304/12215159/639bc09c-b665-11e5-849e-38241bb84da2.png)

The blank space on top and the social widget in the left

YHU-717-67433

**Comment by Alex-302** [comment]
Socials - not widgets, just links to blogs.
We can't remove blank space, because it is a style of few elements.
