### ISSUE TITLE
anitokyo.tv & grandhdcns.net missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1260]
Пропущена реклама на http://grandhdcns.net/smotret-video/171022365--23081559/
Скриншот: http://f4.s.qip.ru/Ogbqiqu2.png

Пропущена реклама на http://anitokyo.tv/anime/103-inicial-di-stadiya-pervaya-initial-d-first-stage.html
Скриншот: http://f3.s.qip.ru/Ogbqique.png

QXJ-370-13270

**Comment by Alex-302** [comment]
grandhdcns.net###link_fixed_new

второй чист. Детект блокировки убрал в ЭФ
