### ISSUE TITLE
[iOS] www.thenewslens.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1263]
black space in the bottom:
http://www.thenewslens.com/post/263608/?utm_source=IntlRSS&utm_medium=feed&utm_campaign=link

![image](https://cloud.githubusercontent.com/assets/15856304/12222628/6ce8546e-b776-11e5-9007-9e5869337280.png)
JNY-105-25974

**Comment by Alex-302** [comment]
added to mobile
thenewslens.com##html > body > div#bottombar
