### ISSUE TITLE
Check if it is possible to remove ads placeholders in com.mobstac.thehindu app

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1266]
https://play.google.com/store/apps/details?id=com.mobstac.thehindu

Source:
http://forum.xda-developers.com/showpost.php?p=64716578&postcount=538
http://forum.xda-developers.com/showpost.php?p=64737817&postcount=540

**Comment by Alex-302** [comment]
yes
added
||zedo.com^$empty
