### ISSUE TITLE
com.snailgameusa.tp - cannot load

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1267]
Source:
http://forum.adguard.com/showthread.php?8679-%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%B0-%D0%B2-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B8-com-snailgameusa-tp

**Comment by Alex-302** [comment]
bug
https://github.com/AdguardTeam/AdguardForAndroid/issues/273

closed there
