### ISSUE TITLE
[Android] Digitally Imported Radio doesn't work

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1268]
https://play.google.com/store/apps/details?id=com.audioaddict.di&hl=en

How it looks: http://prntscr.com/9octwb
Disabling ad filtering and adding to the pref.net.exclusions HELPS

NIM-371-56422

**Comment by Alex-302** [comment]
Лучше первым пунктом рекомендуйте выключить все фильтры, не выключая фильтрацию в настройках.

**Comment by Alex-302** [comment]
Заработало у него
