### ISSUE TITLE
leadia.ru - Adguard blocks too much

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1273]
Я менеджер компании Leadia.ru - партнерская программа для монетизации
сайтов.

Мы предлагаем нашим партнерам ряд промо продуктов (виджеты, формы,
баннеры), которые блокируются вашим сервисом.

Пример виджета: http://prntscr.com/9orqu2

Веб-мастера устанавливают наши промо, которые являются полезными для их
целевых посетителей, а из-за Adguard люди не видят форм, виджетов и тд и
покидают страницу, без ответа на свои вопросы.

Подскажите, что мы должны предпринять, чтобы устранить эту проблему?

Заранее благодарю. С уважением, 

VXU-877-50553

**Comment by Alex-302** [comment]
@evgeniy-ADG 
попроси у них пару сайтов где блокируется. На их сайте у меня открылся виджет.
И пусть посоветуют пользователям обновить фильтры, убрал пару правил.
Важно: если пользователь включил фильтр RU AdList, то жалобу следует писать сюда:
https://forums.lanik.us/viewforum.php?f=64

**Comment by evgeniy-ADG** [comment]
Попросил.

**Comment by evgeniy-ADG** [comment]
Здравствуйте. http://zaimyka.ru/ здесь блокируется наша форма...

http://kaskoinfo.ru/sudpract.html вот тут проверяли виджет.
http://rusjizn.ru/ тут есть наш виджет
http://profi-money.com/ и тут

Надеюсь этого будет достаточно, с уважением Татьяна

**Comment by Alex-302** [comment]
@evgeniy-ADG 
http://zaimyka.ru/ - без Адгарда виджета не вижу. Может он поломан на сайте, или не на главной странице?
На остальных есть.

**Comment by Bohdan-SUP** [comment]
На сайте http://kredit-2014.ru/ http://prntscr.com/a6jqqu
http://kreditibank.com/ http://prntscr.com/a6jrd4

Все промо с адресом api.lediacloud.com, form.leadiacloud.com или
static.leadia.ru

**Comment by Alex-302** [comment]
@Bohdan-SUP 
первого у меня и без Адгарда нет.
По второму - баннер оформлен по правилам рекламы - размер картинки и имя элемента. Сработали общие правила. Пока оставлю как есть
