### ISSUE TITLE
[iOS] niexxniexx.ctfile.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1277]
![image](https://cloud.githubusercontent.com/assets/15856304/12260133/b03f65ce-b922-11e5-9b68-845cdd28b716.png)

UOB-981-34824

**Comment by Alex-302** [comment]
когда юзеры дают прямые ссылки на страницы, сокращать не надо. Наоборот, лучше просить конкретные ссылки, а не только домены.
Добавил:
||keydot.net^$third-party
||pos.baidu.com^$third-party

**Comment by evgeniy-ADG** [comment]
Обычно полную ссылку указываю, здесь - потерял, виноват.
