### ISSUE TITLE
[Android] Star Touch - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1279]
https://play.google.com/store/apps/details?id=com.torontostar.startouch

![image](https://cloud.githubusercontent.com/assets/15856304/12261293/c75e0692-b928-11e5-85ac-a7f1344987a2.png)

  "enabledFilterIds" : [ 2, 3, 4, 11 ],
  "environment" : "prod",
  "filteringQuality" : "FULL",
  "filtersAutoUpdateEnabled" : true,

HTTP log is here: CLT-878-83648

**Comment by Alex-302** [comment]
added
||adgear.com^$empty
