### ISSUE TITLE
[Extension] auto.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1281]
Яндекс.директ в правой верхней части страницы при использовании расширения.

**Comment by Alex-302** [comment]
auto.ru##.sidebar_js_inited > div[class*="_layout_vertical sidebar__block"]

**Comment by vbagirov** [comment]
Снова реклама директа, на этот раз внизу страницы.

**Comment by Alex-302** [comment]
нужны скрин и ссылка

**Comment by vbagirov** [comment]
Всё ещё повторяется.

**Comment by Alex-302** [comment]
поправил
