### ISSUE TITLE
[NSFW] bubluoteka.org missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1286]
filteringQuality : "FULL"
"enabledFilterIds" : [ 2, 3, 4, 1, 11 ],

примеры рекламы:
http://prntscr.com/9pihqx
http://prntscr.com/9pihx4

ARR-465-76876

**Comment by Alex-302** [comment]
added to mobile
bubluoteka.org##body > div.d table[onclick^="window.open('"]

**Comment by Bohdan-SUP** [comment]
Now on iOS - HZQ-428-99211
![image1](https://cloud.githubusercontent.com/assets/14153331/12877922/f7d4fb90-ce23-11e5-999f-c89ee3cf3f01.PNG)

**Comment by Alex-302** [comment]
в фильтр Сафари
http://*.*.space/v/$third-party
в мобильный
bubluoteka.org##iframe[width="320"][height="50"]
