### ISSUE TITLE
Aguard blocks Livetex.ru chat on different sites

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1289]
1. https://www.ulmart.ru/
http://prntscr.com/9pmrrc
2. renault.ua 
how it is: http://prntscr.com/9pms3j
how it should be: http://prntscr.com/9pmsl8

BTE-205-68785

**Comment by Alex-302** [comment]
добавил в фильтр аналитики
@@||googletagmanager.com/gtm.js?$domain=renault.ua
По юлмарту - не нашёл где он должен быть

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/12354152/b59de938-bb9c-11e5-9414-6405df71ae1d.png)
Не надо логиниться, у меня чат есть. Иди сюда: http://www.ulmart.ru/help/post

**Comment by evgeniy-ADG** [comment]
renault.ua - обновил фильтры в расширении для Хрома, чата все равно нет.

**Comment by Alex-302** [comment]
обновление не сразу доступно

**Comment by Alex-302** [comment]
для юлмарта
||web-client.livetex.ru/css/blank.css
