### ISSUE TITLE
mega.nz

### ISSUE THREAD

**Issue by Aokromes** [AdguardTeam/ExperimentalFilter#1293]
error while loading mega.nz:

https://mega.nz/#!aYgiQQoD!gVpG6ncSWF2KrB0Yq5Ru_US4riNUAb6aGuLMfm2GNjg
http://i.imgur.com/3mq949c.png

**Comment by Alex-302** [comment]
Check this rule
```
@@||static.mega.co.nz/*/html/download_*.html$document
```

**Comment by Aokromes** [comment]
It don't must be:

```code
@@||static.mega.co.nz/*/html/*.html$document

**Comment by Alex-302** [comment]
Added to English filter
