### ISSUE TITLE
[iOS] kkiste.to - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1297]
Verpasste Anzeige auf der Seite:
http://kkiste.to/house-of-cards-stream.html

![image](https://cloud.githubusercontent.com/assets/15856304/12324658/ebaaa0be-bacc-11e5-9414-099e4b44d866.png)
^^
JFQ-223-81286

**Comment by Alex-302** [comment]
I don't see this ads

**Comment by Alex-302** [comment]
Added to mobile filter
||brokerbabe.com^$third-party
