### ISSUE TITLE
banki.ru - clean up mobile website

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1298]
<img width="1007" alt="00000965" src="https://cloud.githubusercontent.com/assets/5947035/12325442/5f6a2a8e-badb-11e5-8670-e3d01fdbe1d4.png">

**Comment by Alex-302** [comment]
Added to mobile filter.

**Comment by Alex-302** [comment]
The app banner is blocked in Experimental filter.
The blank rectangle is blocked with  quality mode.
