### ISSUE TITLE
Blocking advertising posts on vk.com

### ISSUE THREAD

**Issue by PaulMarkey1** [AdguardTeam/ExperimentalFilter#1300]
User request to create a script to block the advertising of posts in groups and news using keywords
http://forum.adguard.com/showthread.php?5498-%D0%9D%D0%BE%D0%B2%D1%8B%D0%B9-%D1%82%D0%B8%D0%BF-%D1%80%D0%B5%D0%BA%D0%BB%D0%B0%D0%BC%D1%8B-%D0%B2-%D1%81%D0%BE%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D1%85-%D1%81%D0%B5%D1%82%D1%8F%D1%85/page6

**Comment by ameshkov** [comment]
Moved to a proper repo:
https://github.com/AdguardTeam/Userscripts/issues/2
