### ISSUE TITLE
[iOS] profitconfidential.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1302]
http://www.profitconfidential.com/stock/aapl-stock-report-shows-how-apple-inc-dominated-holiday-sales/

Ads on the page.

**Comment by Alex-302** [comment]
Added
||exitintel.com^$third-party
profitconfidential.com##.spu-bg
profitconfidential.com##.spu-box
profitconfidential.com##.sidebar-ad-div
profitconfidential.com##iframe[name^="dianomi"]
Used may to check this site after update
