### ISSUE TITLE
http://fishki.net/ blocked useful elements

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1306]
Hет кнопки "отправить" при написании комментария.

http://fishki.net/1812055-kogda-doma-net-televizora-i-ty-tehnar.html

при выкл adguard - http://prntscr.com/9qbiks
при вкл - http://prntscr.com/9qbisi

OSB-837-70471

**Comment by Alex-302** [comment]
уже исправлено
