### ISSUE TITLE
[iOS] www.sparknotes.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1307]
Ad in far left
Missed ad on page:
http://www.sparknotes.com/lit/mangostreet/

![image](https://cloud.githubusercontent.com/assets/15856304/12348838/9aaa85a6-bb73-11e5-89cf-49b0d4ca1103.png)

GRK-533-82316

**Comment by Alex-302** [comment]
Added to English filter
||d3ax6xygyb5hn9.cloudfront.net^
