### ISSUE TITLE
http://edp.kiev.ua/ - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1308]
http://edp.kiev.ua/comme-des-garcons and others

Goods' images are blocked
![image](https://cloud.githubusercontent.com/assets/15856304/12355780/b3ce8a12-bba7-11e5-8412-ec1cd85622ad.png)

How it should be
![image](https://cloud.githubusercontent.com/assets/15856304/12355788/c040474a-bba7-11e5-86dc-410b9594f446.png)

**Comment by Alex-302** [comment]
fixed in experimental filter
