### ISSUE TITLE
[Android] www.bild.de - Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1309]
![Pic](http://i.imgur.com/6lFt9RO.png)

**Comment by Alex-302** [comment]
Please check:
```
@@||m.bild.de^$genericblock
```
or
```
@@||m.bild.de^$genericblock,generichide
```
or
```
@@||m.bild.de^$elemhide,urlblock
```

also you can check these rules foк blocking video ads
```
||adform.net/Banners/Stream/*.mp4$mp4
||serving-sys.com/BurstingRes/*.mp4$mp4
||ad.71i.de/images/*.mp4$mp4
||c.2mdn.net/videoplayback/id/*.mp4$mp4
```

**Comment by Alex-302** [comment]
waiting for reply

**Comment by Vincent-Michael** [comment]
I use current and look is fine for me:
```
@@||bild.de^$elemhide
@@||smartadserver.com/diff/*/partners/$domain=bild.de
@@||smartadserver.com/diff/*/smartad.js$domain=bild.de
@@||sascdn.com^$domain=bild.de,script
```

and i see no video ads

**Comment by Alex-302** [comment]
@Vincent-Michael can you check with little different first rule?
***@@||bild.de^$generichide***
@@||smartadserver.com/diff/*/partners/$domain=bild.de
@@||smartadserver.com/diff/*/smartad.js$domain=bild.de
@@||sascdn.com^$domain=bild.de,script

**Comment by Vincent-Michael** [comment]
> @Vincent-Michael can you check with little different first rule?
@@||bild.de^$generichide
@@||smartadserver.com/diff//partners/$domain=bild.de
@@||smartadserver.com/diff//smartad.js$domain=bild.de
@@||sascdn.com^$domain=bild.de,script

anti adblock again there

**Comment by Alex-302** [comment]
Thanks, added to Mobile filter.
