### ISSUE TITLE
[android] muzzone.org

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/ExperimentalFilter#131]
не блочится реклама, верхний блок 
что странно: на эмуляторе с ручной прокси блочится http://screencast.com/t/ZjdZvrYZO6jb
на телефоне с впном не блочится: https://www.dropbox.com/s/2m5rgvl5213c7jl/2014-10-21%2014.20.26.png?dl=0

**Comment by Alex-302** [comment]
Новый дизайн сайта. Чисто.
