### ISSUE TITLE
Adblocker detected at educationcanada.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1310]
http://www.educationcanada.com/
![screen shot 2016-01-16 at 11 26 04 am](https://cloud.githubusercontent.com/assets/14153331/12371675/fe7ccfaa-bc43-11e5-8238-59209cc073a1.png)
FJE-639-18360

**Comment by Alex-302** [comment]
It detects without Adguard on my end. Please check it on your side.

**Comment by Bohdan-SUP** [comment]
That's my screen at the top :)
Only disabling all filters helps for me. Checked on PC and Mac. Will request filters list from user.

**Comment by Alex-302** [comment]
Fixed.
