### ISSUE TITLE
[Android] Yandex direct at m.fishki.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1313]
Open any post and go to comments section. Any possibility to fix it without https support?
![screenshot_2016-01-16-14-50-57](https://cloud.githubusercontent.com/assets/14153331/12376361/486be902-bcf8-11e5-9f88-e6185d9100b4.png)
QNC-616-26687

**Comment by Alex-302** [comment]
Поправил. Нужно проверить авторизацию.
