### ISSUE TITLE
[Android] smart volume control app

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1314]
Install the app and go to 'settings - > colour settings'.
https://play.google.com/store/apps/details?id=cz.directservices.SmartVolumeControl
Logs here - RGW-677-58820

**Comment by Alex-302** [comment]
А в чём, собственно, проблема?
Сам вопрос из тикета тоже крайне желательно копировать.

**Comment by Bohdan-SUP** [comment]
![2016_01_15_18 13 47](https://cloud.githubusercontent.com/assets/14153331/12407264/3eba4054-be5e-11e5-9d57-d03223a590e2.jpg)

**Comment by Alex-302** [comment]
Так а что не так? Баннер их полной версии?
@Bohdan-SUP
