### ISSUE TITLE
[Android] can't access https://apps.admob.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1319]
![image](https://cloud.githubusercontent.com/assets/15856304/12387622/7d070c8a-bdd6-11e5-89fe-a0e7ef8e0949.png)

  "androidVersion" : "4.4.2 (sdk)",
  "whitelist" : [ ],
  "versionName" : "2.1.359",
  "currentWifiProxyConfiguration" : "host.8.0.36 portЂ80 manual",
  "enabledFilterIds" : [ 2, 3, 4, 5, 1, 6, 7, 8, 9, 13, 11, 102, 104, 105, 108, 109, 112, 113, 200, 216 ],
  "environment" : "prod",
  "filteringQuality" : "FULL",
IPJ-924-51676

I can reproduce the issue too, please see the screenshot.

**Comment by Alex-302** [comment]
Если юзеру нежно управлять рекламой, то пусть в исключения добавит
@@||admob.com^
