### ISSUE TITLE
rosecosmet.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1323]
Добавляем любой товар в корзину, жмем оформить заказ - появляется ошибка
http://prntscr.com/9jcwvx. После нажатия кнопки ОК на странице
корзины недоступны некоторые функции, в частности выбор доставки.
Это происходит только в гугл хроме, и только при включенной
защите.

PUW-942-82388

**Comment by Alex-302** [comment]
@@||rosecosmet.ru/quick-order$document
