### ISSUE TITLE
[Android] ExpenseIQ

### ISSUE THREAD

**Issue by skrivskithar** [AdguardTeam/ExperimentalFilter#1327]
https://play.google.com/store/apps/details?id=com.handyapps.expenseiq

Has ads in app and occasionally a pop up asking to check something:

![screenshot_2016-01-18-16-19-10](https://cloud.githubusercontent.com/assets/11478521/12400593/d18b2d4e-bdff-11e5-9b5d-3a9ec595140d.png)
![screenshot_2016-01-18-16-19-15](https://cloud.githubusercontent.com/assets/11478521/12400592/d18a785e-bdff-11e5-8321-94a8b182e45d.png)

(I'm using the paid version of adguard)

**Comment by Alex-302** [comment]
AdChoises?

**Comment by Alex-302** [comment]
We can't block it now. Waiting for HTTPS support.

**Comment by Alex-302** [comment]
It is clean with alpha version. But we can't remove ads placeholder.
