### ISSUE TITLE
[Android] Assistant for Android - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1332]
https://play.google.com/store/apps/details?id=com.advancedprocessmanager&hl=en

http://prntscr.com/9qr284
http://prntscr.com/9qr2gf

"deviceName" : "LENOVO Lenovo TAB 2 A8-50LC",
  "deviceSpeedRank" : 154,
  "dnsFilteringEnabled" : false,
  "enabledFilterIds" : [ 2, 3, 4, 5, 1, 11 ],
  "environment" : "prod",
  "filteringQuality" : "FULL",
  "filtersAutoUpdateEnabled" : true,
  "firewallConfiguration" : {
   "defaultPermissions" : [ "MOBILE", "WIFI", "AD_FILTERING" ],

HTTP logs: OAX-677-88241

**Comment by Alex-302** [comment]
Не AdChoices случайно?

**Comment by Alex-302** [comment]
Прикрою пока

**Comment by Alex-302** [comment]
C альфой чисто.
