### ISSUE TITLE
[iOS] cxz.to

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1333]
![image](https://cloud.githubusercontent.com/assets/15856304/12416402/ff0c1788-bea9-11e5-9782-6c1ecb520619.png)

Некорректная блокировка на странице:
http://cxz.to/cartoonserials/?sort=new&page=1

JOV-250-16289

**Comment by Alex-302** [comment]
Пусть проверит обновление через пол часа.

**Comment by evgeniy-ADG** [comment]
Спасибо. Отписал.
