### ISSUE TITLE
[Android] can't access appodeal.com with Mobile filter 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1334]
Мобильный фильтр намертво глушит доступ к сайту appodeal.com и его русской версии appodeal.ru. Даже добавление в белый список не помогает. Стало так недавно.

CET-666-57574

Скриншот сделать не могу, т. к. в мобильном хроме даже вкладка с сайтом не октрывается.

**Comment by Alex-302** [comment]
Иначе не заблокировать в приложениях эту рекламу.
Передайте
```
@@||appodeal.com^$empty
```

**Comment by evgeniy-ADG** [comment]
Done.
