### ISSUE TITLE
www.celebritybeautymagzine.com - popup

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1336]
![](https://cloud.githubusercontent.com/assets/15856304/12443771/0e7185dc-bf63-11e5-8891-a4c3a99d0012.png)

Repeated pop-up ad on closing page at http://www.celebritybeautymagzine.com/exclusive-int/report.html?t202id=6313&c1=&t202kw= coming from SE visitors redirects Chain of redirects found: [code][/code] reported by, luntrus adguard beta tester on Windows Vista

DXD-147-97712

**Comment by Alex-302** [comment]
added
celebritybeautymagzine.com###beforeyougo
celebritybeautymagzine.com##.glue_block_layer
