### ISSUE TITLE
espn.com - videos won't play

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1341]
Marked as iOS, but in fact the issue is with new Safari extension.

Source complaint:
http://forums.macrumors.com/threads/the-el-capitan-safari-9-content-blocker-thread.1924936/page-8#post-22485346

**Comment by Alex-302** [comment]
Added to Safari filter:
```
@@||adm.fwmrm.net/p/release/latest-JS/adm/prd/AdManager.js$domain=espn.go.com
@@||v.fwmrm.net/ad/*?prof=$domain=espn.go.com
@@||go.com/b/ss/wdgespcom,wdgespvideo,wdgespge/$domain=espn.go.com
@@||once.unicornmedia.com/now/*/content.once?$domain=espn.go.com
```
On iPad user in addition should to press play button(impossible to override it without js)
