### ISSUE TITLE
bloknot-krasnodar.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1342]
http://bloknot-krasnodar.ru/news/mchs-obyavilo-ekstrennoe-preduprezhdenie-na-kubani-682722 

Реклама сверху.

YEH-189-71418

**Comment by Alex-302** [comment]
added
||bloknot-krasnodar.ru/upload/bloknotadv/
bloknot-krasnodar.ru,bloknot-stavropol.ru##.html_banner
||bloknot-stavropol.ru/upload/bloknotadv/
