### ISSUE TITLE
com.getaction - missed full screen ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1346]
Ad screenshot:
http://s2.micp.ru/3dLuk.png

**Comment by Alex-302** [comment]
Can't reproduce. Maybe it show ads only active users?

**Comment by Alex-302** [comment]
I don't see network requests to images, and can't find image form banner in apk

**Comment by ameshkov** [comment]
Ok, let's resolve it then.
