### ISSUE TITLE
http://megashara.com/ - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1350]
http://megashara.com/tv/825649/sumerechnye_ohotniki_sezon_1_epizod_2_shadowhunters.html
http://f4.s.qip.ru/OgbqiqzI.png
автоматическое проигрывание фильма на всех страницах

![image](https://cloud.githubusercontent.com/assets/15856304/12506435/8c80a8b4-c0f7-11e5-9353-ebf4f33c94e5.png)

PQI-648-61442

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Другие метки тоже можно ставить:) снимать тоже, и переоткрывать

**Comment by evgeniy-ADG** [comment]
@Alex-302 окей, осваиваюсь, если что, говори :)

**Comment by Alex-302** [comment]
У меня здесь чисто. Пусть юзер обновления проверит.

**Comment by Alex-302** [comment]
Если у меня не повторилось, а у вас - да, то метку "Cannot reproduce" тоже можно снимать.

**Comment by Alex-302** [comment]
100% старые фильтры.
