### ISSUE TITLE
[iOS] kissanime.to

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1352]
"Ребята, здравствуйте, вот почему не блокируется кнопка закрыть, и на многих сайтах так. Можете исправить пожалуйста. А так ваш блокиратор лучший!!!"

![image](https://cloud.githubusercontent.com/assets/15856304/12506556/88a9b158-c0f8-11e5-8afa-e35422d11eda.png)

![image](https://cloud.githubusercontent.com/assets/15856304/12506563/94c570da-c0f8-11e5-9958-3436c6d75615.png)
Версия ОС: iOS 9.2
Версия Adguard: Adguard for iOS 1.0.4
DLT-133-15654

**Comment by Alex-302** [comment]
в пикете ссылка kissanime.to/m
Это очень важно, т.к. с десктопной версии не всегда перекрывает на мобильную.

Этот элемент на ios не скрыть, т.к. срабатывает дефект блокировки

**Comment by evgeniy-ADG** [comment]
Есть какой-то баг, который в процессе? Или оно совсем нерешаемо?

**Comment by Alex-302** [comment]
не поддерживаются правила javascript и изменение стилей элементов

**Comment by evgeniy-ADG** [comment]
Спасибо, отпишу пользователю.
