### ISSUE TITLE
[iOS] forbes.com - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1353]
Incorrect blocking on page:
http://www.forbes.com/forbes/welcome/

It won't let me enter the sight without disabling adguard

![image](https://cloud.githubusercontent.com/assets/15856304/12507106/3516da58-c0fc-11e5-8c32-9ee1ef7bc915.png)

DLA-524-31004

**Comment by Alex-302** [comment]
@evgeniy-ADG 
check this rules in private tab
```
@@||forbes.com^$elemhide
@@||forbesimg.com/scripts/advertisement.js
```

**Comment by Alex-302** [comment]
added it to Safari filter,
