### ISSUE TITLE
[iOS] www.hdblog.it

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1354]
The ad is blocked by the frame is still present, the same on Android
![image](https://cloud.githubusercontent.com/assets/15856304/12507437/7f21bd46-c0fe-11e5-9757-ce3ee07871ad.png)
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.75.50 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.54 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.15 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.87 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.2.16 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.32 Enabled=YES
ID1 Name="EasyList" Version=1.0.51.9 Enabled=YES
ID9 Name="EasyList Italy" Version=1.0.50.98 Enabled=YES

KBC-804-99070

**Comment by Alex-302** [comment]
added to English filter
hdblog.it##.banner_news_top_box
