### ISSUE TITLE
kinomassa.net

### ISSUE THREAD

**Issue by Fot0n** [AdguardTeam/ExperimentalFilter#1358]
Антиадблок на странице просмотра фильма, например:
http://kinomassa.net/26-petlya-vremeni.html

![image](https://cloud.githubusercontent.com/assets/15856304/12536306/f617973e-c2a9-11e5-91a3-be249902ed1f.png)

**Comment by Vincent-Michael** [comment]
try: @@||kinomassa.net/js/advert.js

**Comment by Alex-302** [comment]
Thanks, added.
