### ISSUE TITLE
[Windows] www.theguardian.com - Ad blocker banner on the header

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1359]
![Pic](http://i.imgur.com/5KFZmc7.png)

**Comment by Alex-302** [comment]
I don't see this block
http://imagizer.imageshack.com/img911/4684/T3bzfp.jpg

**Comment by Vincent-Michael** [comment]
Maybe only win 10?

**Comment by Aokromes** [comment]
http://i.imgur.com/mmUucvx.png

**Comment by Alex-302** [comment]
now I see it:)
added to experimental filter
theguardian.com##.adblock-sticky__message
