### ISSUE TITLE
[Windows] www.dailymail.co.uk - Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1362]
![Pic1](http://i.imgur.com/p4VxGmb.jpg)

**Comment by Alex-302** [comment]
I don't see any problems here.
Which filters are you using?

**Comment by Vincent-Michael** [comment]
this fuck trigger on "http://scripts.dailymail.co.uk/static/gunther/gunther-2138/sync_bundle--.js" (i disable this and my look is fine)

but but it kill top bar

**Comment by Alex-302** [comment]
I want the screenshot of antiadblock message.

**Comment by Vincent-Michael** [comment]
Version: 
![Version](http://i.imgur.com/AgLRYMg.png)

Filters:
![Filters](http://i.imgur.com/Po8XwPq.png)

Trigger this Ads at Adblock:
![Trigger](http://i.imgur.com/mBPeyaU.jpg)

**Comment by Vincent-Michael** [comment]
Update:
I use now to this filter:
```
dailymail.co.uk###top > a[href*="windowsphone.com/s?"]
dailymail.co.uk###content > div > iframe
```

dump without this filter: https://www.dropbox.com/s/52xvgp16e54o7lh/dailymail.co.uk.rar?dl=0

**Comment by Vincent-Michael** [comment]
http://scripts.dailymail.co.uk/static/mol-adverts/21/mol-adverts.js  i see this script generate this fuck ads ... 

I try now this rule:
```
||scripts.dailymail.co.uk/static/mol-adverts/
```
@Alex-302

**Comment by Alex-302** [comment]
@Vincent-Michael 
Added
```
||scripts.dailymail.co.uk/static/mol-adverts/
```
other rules are unnecessary now?

**Comment by Vincent-Michael** [comment]
@Alex-302 

I have again this strange rule bug ... 

Rule is english filter and no block:
![](http://i.imgur.com/RzEk3AB.png)

I add now same rule in user filer and now block:
![](http://i.imgur.com/f6kTPBH.png)

> other rules are unnecessary now?
nope

**Comment by Alex-302** [comment]
>I add now same rule in user filer and now block:

try to restart Adguard after removing rule from usef filter.

**Comment by Vincent-Michael** [comment]
> > I add now same rule in user filer and now block:

> try to restart Adguard after removing rule from usef filter.

useless, same with pc reboot and cache / cookie remove

**Comment by Vincent-Michael** [comment]
>> I add now same rule in user filer and now block:

> try to restart Adguard after removing rule from usef filter.

After pc reboot is fine

**Comment by Alex-302** [comment]
@Vincent-Michael 
I will exclude 
```
@@||scripts.dailymail.co.uk/static/mol-adverts/*/mol-adverts.js
```
because it breaks the comments
https://github.com/AdguardTeam/AdguardFilters/issues/1708#event-840885292
