### ISSUE TITLE
[iOS] www.vesti.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1364]
Пропущена реклама на странице:
http://www.vesti.ru/

![image](https://cloud.githubusercontent.com/assets/15856304/12535730/92c53952-c295-11e5-8f42-dfedc79a77ec.png)

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.73.30 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.28 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.81 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.23.55 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.84 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.29.54 Enabled=YES
ID=6 Name="German filter" Version=1.0.22.43 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.92.89 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.1.91 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.21 Enabled=YES
ID1 Name="EasyList" Version=1.0.49.71 Enabled=YES
ID!2 Name="RU AdList: Counters" Version=1.0.43.13 Enabled=NO
ID!3 Name="RU AdList: BitBlock" Version=1.0.43.39 Enabled=NO

MVT-748-81441

**Comment by Alex-302** [comment]
added to mobile filter
vesti.ru###rb_fs_wrapper__ID
