### ISSUE TITLE
liveinternet.ru - consider blocking radio player

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1365]
http://www.liveinternet.ru/users/5866111/post382625629/
![image](https://cloud.githubusercontent.com/assets/15856304/12535790/5514500a-c297-11e5-9860-73039d4e79e3.png)

сейчас пользователи сайта блокируют его вот так: http://www.aliveinternet.ru/post366654164/?upd
можем ли мы заблокировать его у себя?

KOZ-768-25821

**Comment by Alex-302** [comment]
Оно не стартует автоматом, так что пока не будем.

**Comment by Alex-302** [comment]
Вот так ещё можно
||radio.livenet.labs.moscow^

**Comment by evgeniy-ADG** [comment]
Передал пользователю.

**Comment by evgeniy-ADG** [comment]
Ей не помогло. Мне тоже:
![image](https://cloud.githubusercontent.com/assets/15856304/12670434/185222ea-c671-11e5-89d7-4bc9a1f6a749.png)

**Comment by Alex-302** [comment]
То правило для блокировки потока.
Вот:
liveinternet.ru##body > div#button

**Comment by evgeniy-ADG** [comment]
"и снова не помогло!((( точнее, помогло, раз 5 обновлений страницы его не было - а сейчас снова появился. такое чувство, что он самообучается и каждый раз находит новую лазейку, как бы обойти ваши фильтры."

**Comment by Alex-302** [comment]
У меня работает. Пусть другие правила в пользовательском выключит.
