### ISSUE TITLE
typekit.com/fonts - can't to log in if Adguard is running

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1367]
Я записал видео для двух браузеров - Opera и Firefox с включеной и выключеной защитой.
https://yadi.sk/d/xEOEsPAKncRky

LGV-766-44572

При отключении "сторонних куки" все работает

**Comment by Alex-302** [comment]
добавил
```
@@||adobelogin.com^
@@||adobeid-*.services.adobe.com^
```
желательно проверить
