### ISSUE TITLE
universarium.org/users/login - Adguard removes registration form

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1369]
how it is now 
![image](https://cloud.githubusercontent.com/assets/15856304/12535836/6a2c3aa0-c299-11e5-9d59-4d00606aecf6.png)
how it is when you add the site into the white list
![image](https://cloud.githubusercontent.com/assets/15856304/12535841/95fe0938-c299-11e5-832c-9dbad8941b0f.png)

filters set
![image](https://cloud.githubusercontent.com/assets/15856304/12535840/78c56f1e-c299-11e5-9313-fa36af869819.png)
AJC-989-49396

**Comment by Alex-302** [comment]
исправил в соц фильтре.
@@||yastatic.net/share/share.js$domain=universarium.org
