### ISSUE TITLE
[iOS] http://zfilm-hd.net missed pop-up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1370]
http://zfilm-hd.net/4905-boytes-hodyachih-mertvecov.html
![image](https://cloud.githubusercontent.com/assets/15856304/12535849/eb2f6cb2-c299-11e5-8bc5-e3725dc2104d.png)
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.73.17 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.23 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.76 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.29.46 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.19 Enabled=YES

KXN-102-11505

**Comment by Alex-302** [comment]
фильтры старые. Пусть вручную обновит

**Comment by Alex-302** [comment]
можешь у себя ещё проверить. Если чисто - закрывай

**Comment by evgeniy-ADG** [comment]
Попросил обновиться и проверить. Если что, дам знать.
