### ISSUE TITLE
http://fishki.net/ false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1371]
Добрый день! Подскажите, на сайте "http://fishki.net/" в конце постов есть ссылка, например, "Показать ещё 43 комментария (из 477)", при включенной программе Adguard она не открывается (ведет себя не как ссылка). Если выключаю программу - то все нормально. Можно это исправить или это воспринимается программой как "реклама"? Раньше (неделя или 2 назад) такого не было. П.С. Пробовал в разных браузерах (Опера, Хром, ИнтернетЭксплорер)

![image](https://cloud.githubusercontent.com/assets/15856304/12535954/f97f5738-c29d-11e5-9454-cc996e70d868.png)

NFW-643-66713

**Comment by Alex-302** [comment]
added
```
@@||fishki.net/comment/more/$document
```
