### ISSUE TITLE
idevice.ro - remove ads placeholders

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1377]
Also don't forget about .floating_banner_bottom

Source:
http://forums.macrumors.com/threads/ios-9-content-blockers-mini-reviews.1918483/page-20#post-22500641

**Comment by Alex-302** [comment]
There was the anti-adblock script, so elemhide is disabled. But now it is not triggered.
Removed the exclusion.

**Comment by Alex-302** [comment]
Waiting for user's reply.

**Comment by Alex-302** [comment]
We can't remove placeholders in iOS, because Anti-AdBlock script looks for visibility of HTML element div[id="adsense"]
For other OS/Browsers added
```
idevice.ro#%#var AG_AntiAntiBlock = function() { var baseCreateElement = document.createElement; document.createElement = function(name) { if (name && name.match(/div|font|center/i)) { return null; } else { return baseCreateElement(name); } } };
idevice.ro#%#AG_onLoad(function() { AG_AntiAntiBlock(); });
```
