### ISSUE TITLE
Can't login via facebook on pinterest.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1379]
K сожалению автоматическая авторизация непроизошла и на
https://www.pinterest.com/
Такого раньше небыло. Это произходит после установки Adguard 6 RC.
JEA-547-65672

У нас повторилось:
![image](https://cloud.githubusercontent.com/assets/15856304/12546522/0cd8a900-c353-11e5-8da6-cd953154eb19.png)

Помогает отключение куки

**Comment by Alex-302** [comment]
У него Stealth Mode включен?

**Comment by Alex-302** [comment]
У меня вход не получается и без Адгарда, пишет "Укажите свой адрес эл. почты."

**Comment by evgeniy-ADG** [comment]
Да, есть антитреккинг, помогает отключения блокировки соронних куки. У нас в поддержке повторилось, скрин наш.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
проверь такое правило
```
@@||facebook.com/*/dialog/oauth
```

**Comment by Alex-302** [comment]
если сработает - закрывай, в фильт добавил

**Comment by evgeniy-ADG** [comment]
Thank you, it works.
