### ISSUE TITLE
[iOS]  Spiegel.de and Tagesschau.de

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1382]
There are still issues with social buttons within articles on Spiegel.de and Tagesschau.de:
http://m.spiegel.de/panorama/gesellschaft/a-1073585.html
http://www.tagesschau.de/ausland/blizzard-usa-103.html

![image](https://cloud.githubusercontent.com/assets/15856304/12547969/fc85c5de-c35b-11e5-91ac-a89281ebb4e1.png)
![image](https://cloud.githubusercontent.com/assets/15856304/12547979/06f09404-c35c-11e5-8946-13051d0b00ed.png)

EJW-151-29240

**Comment by Alex-302** [comment]
The first is clean
For second - added:
tagesschau.de##.modSharing
