### ISSUE TITLE
Broken interface - pear-advert.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1384]
Повторилось только в Chrome, в Safari/Firefox всё хорошо.
Помогает только полное отключение фильтрации.

![screen shot 2016-01-25 at 7 27 55 pm](https://cloud.githubusercontent.com/assets/14153331/12558722/cd1dc06a-c399-11e5-994d-e022cc1878ee.png)

AYU-940-49278

**Comment by Alex-302** [comment]
added
@@||pear-advert.ru/$domain=pear-advert.ru
