### ISSUE TITLE
[iOS] www.channelnewsasia.com - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1387]
![image](https://cloud.githubusercontent.com/assets/15856304/12579859/cb1a5a04-c433-11e5-86f1-54909e9530c9.png)

http://www.channelnewsasia.com/mobile
TBM-914-48921

**Comment by Alex-302** [comment]
Are you sure? Looks like their own link.

**Comment by amourchaleur** [comment]
The link actually goes to a page which contains all their sponsors and advertisments brands. Kinda like their new technique.

**Comment by amourchaleur** [comment]
If u guys think it's not an ad then it's okays, I'll just try to hide it the next time thanks!

**Comment by Alex-302** [comment]
>>The link actually goes to a page which contains all their sponsors and advertisments brands. Kinda like their new technique.
Added
```
channelnewsasia.com##a[href="http://www.channelnewsasia.com/premier"]
```
