### ISSUE TITLE
fs.to

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1388]
Реклама на сайте.

https://adguard.com/ru/adguard-report/fs.to/report.html#comment-2479476664

**Comment by evgeniy-ADG** [comment]
Сразу при открытии любой страницы сайта fs.to иконка помощника есть. Но через несколько секунд, когда реклама начинает подгружаться иконка исчезает. 
Данная ситуация во всех браузерах.

**Comment by Alex-302** [comment]
@evgeniy-ADG  
Пока не переоткрывай. Заниматься сейчас не будем, т.к. занимает много времени, и решение работает не больше двух дней.
Если что - глянем.
