### ISSUE TITLE
[iOS] www.dailymail.co.uk  missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1389]
![image](https://cloud.githubusercontent.com/assets/15856304/12612572/5922e0a0-c4fc-11e5-98d5-ac0e19e28b51.png)

http://www.dailymail.co.uk/home/index.html

YLX-255-77470

**Comment by Alex-302** [comment]
1. Banners of the site apps we add to Experimental filter
```
||mol.im/i/mobileimages/
```
2. Just links to the blogs. We don't block them

**Comment by Alex-302** [comment]
Removed this rule
https://forum.adguard.com/index.php?threads/dailymail-co-uk.11984/
