### ISSUE TITLE
http://m.bmwusa.com/#home - false positive 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1391]
Unable to click links within this website with Adguard enabled (the menu icon in the top left does not work either). 

XON-550-97242

**Comment by Alex-302** [comment]
Can't reproduce with user's filter list.
Need to be checked on the real device.

**Comment by ameshkov** [comment]
@Alex-302 go get ipad here:)

**Comment by Alex-302** [comment]
added to mobile filter 
```
@@||2o7.net/b/ss/bmwmobiledev$image
```
