### ISSUE TITLE
Adguard breaks www.lotto-bw.de

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1395]
It works only if you disable adguard and kill services in the task manager. The issue is specific for FF, Chrome and maybe other browsers, but the site works fine in Edge.

![image](https://cloud.githubusercontent.com/assets/15856304/12622166/c91454ae-c52c-11e5-8fca-a2c0431a50aa.png)
It says: General System error An error has occurred. Please contact the Customer Service, tel. 0711 81000-444

After unloading services or in Edge: 
![image](https://cloud.githubusercontent.com/assets/15856304/12622217/efa221fa-c52c-11e5-8d76-0e39c6f4ad55.png)

**Comment by Alex-302** [comment]
Please check this rule in private tab
```
@@||lotto-bw.de^$jsinject
```

**Comment by Alex-302** [comment]
Added to German filter. If it helps - close this issue.
