### ISSUE TITLE
[Windows] www.windowscentral.com - missed ad

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1397]
![Pic](http://i.imgur.com/Ux5W57l.png)

**Comment by Alex-302** [comment]
added
||windowscentral.com/sites/all/modules/mbn_offers/

**Comment by Vincent-Michael** [comment]
this rule is for me useless (i see still this ads) @Alex-302

i have better look via:
windowscentral.com###media-module

**Comment by Alex-302** [comment]
Maybe you see another ads? This banner loaded by
http://www.windowscentral.com/sites/all/modules/mbn_offers/mbn_offers.php

**Comment by Vincent-Michael** [comment]
i think this ads trigger only win with apps support

**Comment by Alex-302** [comment]
I checked it in Windows with Adguard app.
Can you save full page in IE?(mht or html+images)

**Comment by Vincent-Michael** [comment]
https://www.dropbox.com/s/08givw98fbhxea1/windowscentral.com.rar?dl=0
done, but save with firefox (i have no IE xD) @Alex-302

**Comment by Alex-302** [comment]
But where is not blocked ads?
These?
http://ipic.su/img/img7/fs/kiss_430kb.1454350607.png

**Comment by Vincent-Michael** [comment]
yea and order today xxx text

**Comment by Alex-302** [comment]
added
```
windowscentral.com##a[href^="http://clkuk.tradedoubler.com/click?"]
windowscentral.com##a[href^="http://www.amazon.com/gp/new-releases?tag=mbn"]
windowscentral.com###msny15banner
```
Please check them in User Filter

**Comment by Vincent-Michael** [comment]
![random](http://i.imgur.com/0iHRbmu.jpg) is random

**Comment by Alex-302** [comment]
added
```
windowscentral.com###msny15banner
windowscentral.com##a[href^="http://www.amazon.com/gp/new-releases?tag=mbn"]
windowscentral.com##a[href*="tradedoubler.com/click?"]
```

**Comment by Vincent-Michael** [comment]
look is now fine:

![Pic](http://i.imgur.com/L1X3Uwk.jpg)
