### ISSUE TITLE
mangareader.net- consider removing self advert

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1400]
It shows the Play Market icon, but leads to another site when you click it.
![image](https://cloud.githubusercontent.com/assets/15856304/12643673/43e1cfce-c5c6-11e5-8097-a434f5431101.png)
It disappear once closed but the customer wants to have a rule to block it permanently. If we can't add it to our filter, can we give a rule to our customer? Thank you.

AMB-447-64133

**Comment by Alex-302** [comment]
I don't see it.
He can try to enable Experimental filter.

**Comment by evgeniy-ADG** [comment]
Sorry, it's mangareader_.net_, not ._com_ as I wrote before. Sorry, that's my fault. Kindly check again  mangareader.net, the banner persists with experimental filter enabled.

**Comment by Alex-302** [comment]
mangareader.net###googleModal > a[href="http://www.animemobile.com/MangaApp/"]
added to experimental filter
