### ISSUE TITLE
prostitutka-ket.livejournal.com - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1405]
![image](https://cloud.githubusercontent.com/assets/15856304/12674108/cee1f61c-c689-11e5-949e-09c38ba61b25.png)

http://prostitutka-ket.livejournal.com/226773.html Ads weren't blocked enough

NXX-883-87239

**Comment by Alex-302** [comment]
added
prostitutka-ket.livejournal.com##dl[class="sidebar-block sidebar-custom"]
