### ISSUE TITLE
ru.investing.com - blank space

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1406]
http://ru.investing.com/currencies/usd-rub-commentary
![image](https://cloud.githubusercontent.com/assets/15856304/12675388/96f0bb0e-c692-11e5-8cbf-fd32652950b1.png)

logs and more pics here: MLN-929-40373

**Comment by Alex-302** [comment]
У меня чисто. У вас повторяется?

**Comment by Bohdan-SUP** [comment]
А можно это убрать?
http://prntscr.com/ae78r2

**Comment by Alex-302** [comment]
да, в ЭФ
investing.com###sideNotificationZone
