### ISSUE TITLE
[Windows] wetteronline.de - false positive

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1408]
Break:
![Pic1](http://i.imgur.com/hUmwIF5.png)

Should:
![Pic2](http://i.imgur.com/Vf5Zntk.png)

**Comment by Alex-302** [comment]
Removed that rule.

**Comment by Vincent-Michael** [comment]
break via "||st.wetteronline.de/dr/*/css/p_*.css" @Alex-302

**Comment by Alex-302** [comment]
Yes, it is that rule:)
I will remove ads little later
