### ISSUE TITLE
[Windows] www.sueddeutsche.de - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1411]
![Pic1](http://i.imgur.com/ni2VsS5.png)

Update1:
Better look with disable rule:
@@||sueddeutsche.de^$elemhide

![Pic2](http://i.imgur.com/5p147Su.png)

Update2:
Disable Rule:
@@||sueddeutsche.de^$elemhide
Add Rule:
 ||polpix.sueddeutsche.de

Look now:
![Pic3](http://i.imgur.com/Oe7NK9m.png)

**Comment by Alex-302** [comment]
added to German
sueddeutsche.de#%#window.blockAdBlock = function() {};
