### ISSUE TITLE
[Windows] www.benchmarkreviews.com - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1412]
![Pic](http://i.imgur.com/Favn5fg.jpg)

I use current:
benchmarkreviews.com#$#html > body { background-image: none!important; }
benchmarkreviews.com###sidebar2

**Comment by Alex-302** [comment]
added:
- to English
```
benchmarkreviews.com#%#Object.defineProperty(window, 'bg_backgrounds', { get: function() { return []; } });
benchmarkreviews.com#$#html > body { background-image: none!important; }
```
- to Experimental filter
```
benchmarkreviews.com###content > div#sidebar2 > div
```

**Comment by Vincent-Michael** [comment]
@Alex-302 
why added you in english filter:
`benchmarkreviews.com#$#body { background-image: none!important; }`

why not?
`benchmarkreviews.com#$#html > body { background-image: none!important; }`

without html is ads still there

**Comment by Alex-302** [comment]
because in Chrome extension we use Shadow DOM for element hiding rules, and the first element in selector now is BODY, html > body is not working now. Added both now.

**Comment by Vincent-Michael** [comment]
okay, ty
