### ISSUE TITLE
[Windows] www.wowhead.com - Missed Ads / Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1414]
![Pic](http://i.imgur.com/xOam038.jpg)

Site: http://www.wowhead.com/zones=1

I use current:
wowhead.com#%#AG_onLoad(function() {document.getElementById("header-expandsite").click();});

**Comment by Alex-302** [comment]
We can just hide them:
```
wowhead.com###news-block-group
wowhead.com##.news-right .block-bg
wowhead.com##.news-right .vertical-bg
wowhead.com##.horizontal-bg
```
