### ISSUE TITLE
mycanal.fr pop up should not be blocked

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1415]
http://www.mycanal.fr/guide-tv/grille-tv/pid782-grille-tv-complete.html?chaines=301
![adguard on](https://cloud.githubusercontent.com/assets/14153331/12698372/97c47946-c7a3-11e5-9104-0862dc0887a3.png)
![adguard off](https://cloud.githubusercontent.com/assets/14153331/12698371/97aadf22-c7a3-11e5-9825-2fd76a0d8f6b.png)
QXW-351-35338

**Comment by Vincent-Michael** [comment]
try:
@@||mycanal.fr^$elemhide,jsinject

**Comment by Alex-302** [comment]
@Vincent-Michael 
too wide rule. Adguard for Win breaks Ajax by injections(JS, CSS)
Added to English:
```
@@||mycanal.fr/library/Pelican/Ajax/$document
```
