### ISSUE TITLE
[Windows] www.thinkcomputers.org - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1416]
![Pic](http://i.imgur.com/wr4zmDz.jpg)

I use current:
thinkcomputers.org#$#html > body.myatu_bgm_body { background-image: none !important; }
thinkcomputers.org##.myatu_bgm_fs
||thinkcomputers.org/wp-content/plugins/background-manager

**Comment by Alex-302** [comment]
added
||thinkcomputers.org/wp-content/uploads/an-temp/
thinkcomputers.org#$#html > body.myatu_bgm_body { background-image: none !important; }
thinkcomputers.org#%#window.myatu_bgm = 0; - for clickable backgroung
