### ISSUE TITLE
[Windows] www.phonearena.com - Missed Ads / Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1418]
![Pic](http://i.imgur.com/H6AmoWZ.jpg)

I use current:
phonearena.com##.adblock_awareness

**Comment by ameshkov** [comment]
@Vincent-Michael we'll add this rule to the "Experimental Filter".

In future we plan to introduce new "Annoyances" filter which will block such "gentle" anti-adblock messages. For now we collect such rules in the experimental filter.
