### ISSUE TITLE
[iOS] berlindailysun.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1421]
http://berlindailysun.com/index.php?option=com_content&view=article&id=56698:food-co-op-group-taking-next-step&catid=103&Itemid=442
ZCH-137-12027

**Comment by Alex-302** [comment]
I can't access to this site with any proxies
```
403: Access Forbidden
Your location (RU) has been blacklisted.
```

**Comment by Alex-302** [comment]
Added to German filter:
berlindailysun.com##.bannergroup
||berlindailysun.com/images/banners/
