### ISSUE TITLE
bmcxsvt.appspot.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1424]
http://bmcxsvt.appspot.com/elektrosnabzhenie-zagorodnogo-doma-shema.html
http://prntscr.com/9x45tw
при закрытии центрального окна, есть переход на olx, какие-то фишинговые сайты и др.
JJO-853-37070

**Comment by Alex-302** [comment]
добавил
||abdmi.ru^$third-party
