### ISSUE TITLE
[Android] Ad in File Manager

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1429]
It's the same banner on all tabs, that lead to developer's website. Still, can we block it?
https://play.google.com/store/apps/details?id=com.mobisystems.fileman
![file_manager](https://cloud.githubusercontent.com/assets/14153331/12708233/12fb1d38-c8a6-11e5-92de-3d02ffec97d2.png)
QKU-773-49427
AEQ-503-83067

**Comment by Alex-302** [comment]
It is the self-promo, looks like builtin
