### ISSUE TITLE
"TMS - Torrent search, extension" doesn't work when Adguard is enabled

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1430]
https://chrome.google.com/webstore/detail/tms-torrent-search-extens/ngcldkkokhibdmeamidppdknbhegmhdh?hl=uk
Это расширение. Проблема во всех хромо-браузерах.

Поиск по некоторым сайтам не работает, как будто сайт не работает.
Проверил, проблема возникает когда подключен фильтр easylist, для повторения проблемы у себя добавьте сайт http://tapochek.net/ и подключите фильтр easylist, после этого поиск через расширение должен не работать. В поиск не нужно писать tapochek.net))) его нужно добавить в список трекеров, и поиск по нему не будет работать через расширение. И еще для поиска по сайте тапочек, оказывается нужно быть зарегистрированным на том сайте, и расширение предложит авторизироватся, но там регистрация по инвайтам, поэтому вам не получится запустить поиск у себя... Но есть другой способ по которому так-же можно понять что нет соединения с сайтом, при поиске по сайте с отключенным adguard расширение предлагает авторизироватся, а вот если он включен, то нет даже предложения авторизации.

ZTS-940-97147

**Comment by Alex-302** [comment]
http://imagizer.imageshack.com/img921/4575/w9GIjl.jpg
у меня всё нормально ищет

**Comment by evgeniy-ADG** [comment]
> Вижу там отписали, напишите пусть попробуют с ruadlist, и на счет easyprivacy и piratbit вы там ничего не написали. Проблема с easyprivacy и пиратбит есть, только-что проверил (перед этим проверил обновления)...
> 
> А на счет тапочек тут сложнее, снял даже видео (прикрепить к ответу не получается так-что вот http://rghost.ru/private/6VYTPnR6j/e8735172809e40881fb840a2bd10ea5c пароль bob). Вот из за таких проблем (которые показаны на видео) постоянно возникает желание удалить adguard и дальше пользоваться расширением.. в расширении, если отключаешь какой-то фильтр, то сразу понятно что проблема из за него, в программе же вообще бред происходит, тоже самое было и с 2ip.ru...
>

**Comment by Alex-302** [comment]
не скачивается видео. Попросите на rusfolder.com загрузить, например.

**Comment by evgeniy-ADG** [comment]
у емня скачался, вот он в зипе

[adguard.zip](https://github.com/AdguardTeam/ExperimentalFilter/files/121681/adguard.zip)

**Comment by Alex-302** [comment]
исключил из RU Adlist:
||tapochek.net^$subdocument
в исключения EasyPrivacy
@@||tapochek.net/tracker.php
с третьим фильтром проблем не было.
Попросите сделать скрин журнала с включенным одним фильтром FanBoy's.

Вообще RU ADlist включать вместе с нашим русским смысла нет, а проблемы могут возникнуть. Нужно выбрать что-то одно(наш русский:) )

**Comment by Alex-302** [comment]
@evgeniy-ADG

**Comment by temptestfree** [comment]
@Alex-302 проблем с тапочками больше нет... Проблема была не со всеми фильтрами, на видео просто показал странное поведение программы, т.к. в расширении при отключении фильтров сразу понятно из за какого была проблема, а в программе, можно отключить даже все а проблема не исчезнет, а потом включить все и проблемы как будто и не было.

Но осталась еще проблема с фильтром EasyPrivacy, и поиском по сайту Piratbit через расширение.

**Comment by Alex-302** [comment]
пойдёт. Добавил.
