### ISSUE TITLE
4pda.ru - the new message form is broken

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1431]
Правило ||s.4pda.to/*.css?_=2| ломает форму написания поста на форуме 4pda.

![image](https://cloud.githubusercontent.com/assets/15856304/12712133/a610ec88-c8ce-11e5-9f97-4cff3277ef98.png)

Как должно быть:
![image](https://cloud.githubusercontent.com/assets/15856304/12712139/b05ea680-c8ce-11e5-9022-30d083645413.png)

FUS-163-38191

**Comment by Alex-302** [comment]
Эх...
Убрал пока.

**Comment by Serzh-SUP** [comment]
# У этого же пользователя появилась еще одна проблема на 4PDA.

> 
На форме просмотра профиля пользователя есть подраздел "Контакты". С отключенным Adguard там отображается как минимум значок лички (QMS). С включённым Adguard никаких контактов нет :
>
![adguard_off](https://cloud.githubusercontent.com/assets/16462533/12744185/7b7ab3dc-c99b-11e5-8185-70d0d0b2d0fb.png)
![adguard_on](https://cloud.githubusercontent.com/assets/16462533/12744186/7b7e5410-c99b-11e5-8ff1-5918bcc04e11.png)

**Comment by Alex-302** [comment]
Поправил. Пусть ждёт обновления.
