### ISSUE TITLE
androidcentral.com - missed banner

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1435]
![image](https://cloud.githubusercontent.com/assets/15856304/12718336/b306032e-c8f6-11e5-8ea7-d8169bb4a16f.png)

1. Enter the address of a page or site: http://www.androidcentral.com/five-months-moto-x-plays-marshmallow-update-makes-it-phone-worth-considering 
2. Describe the place on the page with ads that haven't been blocked (example: a banner in the lower left corner): Horizontal banner on the top of the article body.
TTB-486-81223

**Comment by Alex-302** [comment]
added
androidcentral.com##a[href^="http://www.amazon.com/gp/new-releases?tag=mbn"]
