### ISSUE TITLE
[iOS] missed ads in google search results

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1436]
![image](https://cloud.githubusercontent.com/assets/15856304/12718468/7d736098-c8f7-11e5-9c55-e01413b99498.png)

"I've noticed ads are starting to slip through on google.com. If you search for certain terms such as "homefront", "bank of america", or "nexus" the first result will be a link with the word "Ad" next to it in yellow. I don't think this can be remedied simply by blocking the ad results for these specific terms -- it appears to be a more general element that needs to be blocked.

Missed ad on page:
https://www.google.com/search?q=nexus&ie=UTF-8&oe=UTF-8&hl=en-us&client=safari"

OBJ-622-19048

**Comment by Alex-302** [comment]
I can't reproduce this in Safari with iPhone user-agent.
Please check on iPhone.

**Comment by Serzh-SUP** [comment]
@Alex-302 
Протестил, проблемы нет.
![20160204_221329000_ios](https://cloud.githubusercontent.com/assets/16462533/12831647/0b6b7ac2-cb9e-11e5-8390-347c3af0e193.png)
![20160204_221459000_ios](https://cloud.githubusercontent.com/assets/16462533/12831648/0b6ed988-cb9e-11e5-96c3-ff16df5d5ba2.png)

**Comment by evgeniy-ADG** [comment]
> Is it possibly a localization issue that varies by country? It's definitely still an issue, in fact I'm continuing to see it with more and more search terms on google.com. Remember sometimes the ads are at the top of the page and sometimes they are at the bottom.

**Comment by Alex-302** [comment]
А откуда юзер? Проверил с VPN США - чисто вроде.

**Comment by evgeniy-ADG** [comment]
another complaint: CKZ-901-91611

**Comment by ameshkov** [comment]
The same issue:
#1619

**Comment by Alex-302** [comment]
Added
to mobile filter
```
google.ae,google.at,google.be,google.by,google.ca,google.ch,google.cl,google.cn,google.co.id,google.co.in,google.co.jp,google.co.th,google.co.uk,google.co.ve,google.co.za,google.com,google.com.ar,google.com.au,google.com.bd,google.com.br,google.com.co,google.com.eg,google.com.hk,google.com.mx,google.com.my,google.com.ng,google.com.pe,google.com.ph,google.com.pk,google.com.sa,google.com.sg,google.com.tr,google.com.tw,google.com.ua,google.com.vn,google.de,google.dk,google.ee,google.es,google.fr,google.gr,google.hu,google.ie,google.it,google.nl,google.no,google.pl,google.pt,google.ro,google.rs,google.ru,google.se,google.sk,google.tn##.ads-ad
google.ae,google.at,google.be,google.by,google.ca,google.ch,google.cl,google.cn,google.co.id,google.co.in,google.co.jp,google.co.th,google.co.uk,google.co.ve,google.co.za,google.com,google.com.ar,google.com.au,google.com.bd,google.com.br,google.com.co,google.com.eg,google.com.hk,google.com.mx,google.com.my,google.com.ng,google.com.pe,google.com.ph,google.com.pk,google.com.sa,google.com.sg,google.com.tr,google.com.tw,google.com.ua,google.com.vn,google.de,google.dk,google.ee,google.es,google.fr,google.gr,google.hu,google.ie,google.it,google.nl,google.no,google.pl,google.pt,google.ro,google.rs,google.ru,google.se,google.sk,google.tn###tads
google.ae,google.at,google.be,google.by,google.ca,google.ch,google.cl,google.cn,google.co.id,google.co.in,google.co.jp,google.co.th,google.co.uk,google.co.ve,google.co.za,google.com,google.com.ar,google.com.au,google.com.bd,google.com.br,google.com.co,google.com.eg,google.com.hk,google.com.mx,google.com.my,google.com.ng,google.com.pe,google.com.ph,google.com.pk,google.com.sa,google.com.sg,google.com.tr,google.com.tw,google.com.ua,google.com.vn,google.de,google.dk,google.ee,google.es,google.fr,google.gr,google.hu,google.ie,google.it,google.nl,google.no,google.pl,google.pt,google.ro,google.rs,google.ru,google.se,google.sk,google.tn###tadsb
```
Don't know why they are absent in Safari extension filter

**Comment by ameshkov** [comment]
I've just checked it in Safari for OS X and it seems that for some reason ads are not filtered on google.com at all with the following filters:
English
Spyware
Social
Safari filter
Mobile ads

**Comment by ameshkov** [comment]
There is a mistake in rules converter that transforms one of the rules into a wide exception allowing ads on google.

**Comment by Alex-302** [comment]
Should I remove these rules?

**Comment by ameshkov** [comment]
Yes, there's no need in them in mobile ads filter

**Comment by ameshkov** [comment]
Something is wrong with English filter, I just don't know what exactly

**Comment by Alex-302** [comment]
done

**Comment by ameshkov** [comment]
I suppose that's the problem:
```
@@||google.*/search?sclient=*&q=$xmlhttprequest
```

**Comment by ameshkov** [comment]
Ok, I think I've found it.

I'd better file a bug report.

**Comment by ameshkov** [comment]
Bug report:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/176

**Comment by ameshkov** [comment]
Ok I was wrong, here is the problem:
```
@@||www.google.*/search?$subdocument,~third-party
```

Again, subdocument. It just works as $document in iOS

**Comment by ameshkov** [comment]
This rule should be excluded from English filter

**Comment by Alex-302** [comment]
excluded

**Comment by evgeniy-ADG** [comment]
QMV-889-65305

> I updated my filters - even removed and added them again - and am still seeing ads on Google. Screenshot attached. 

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13700071/4889fa8c-e787-11e5-8fd9-7f7f67858687.png)

**Comment by evgeniy-ADG** [comment]
RDL-428-41023
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13700851/301f4402-e78c-11e5-858a-8fc7c2b7ca8e.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.73.62 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.32 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.87 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.84 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.29.66 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.1.96 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.25 Enabled=YES

**Comment by Alex-302** [comment]
@evgeniy-ADG 
какой домен? У них пол сотни адресов, и реклама может отличаться.

**Comment by evgeniy-ADG** [comment]
1. https://www.google.com/search?q=apple&ie=UTF-8&oe=UTF-8&hl=en&client=safari
2. https://www.google.ru/search?q=уроки+игры+на+баяне&newwindow=1&safe=strict&client=safari&hl=ru-ru&prmd=vin&source=lnms&tbm=vid&sa=X&ved=0ahUKEwiu3oSV6LLLAhWiQpoKHSnEAawQ_AUICCgB&biw=320&bih=460

**Comment by Alex-302** [comment]
ага, вижу

**Comment by Alex-302** [comment]
проверь, или передай юзеру, пусть ответит
```
google.ae,google.at,google.be,google.by,google.ca,google.ch,google.cl,google.cn,google.co.id,google.co.in,google.co.jp,google.co.th,google.co.uk,google.co.ve,google.co.za,google.com,google.com.ar,google.com.au,google.com.bd,google.com.br,google.com.co,google.com.eg,google.com.hk,google.com.mx,google.com.my,google.com.ng,google.com.pe,google.com.ph,google.com.pk,google.com.sa,google.com.sg,google.com.tr,google.com.tw,google.com.ua,google.com.vn,google.de,google.dk,google.ee,google.es,google.fr,google.gr,google.hu,google.ie,google.it,google.nl,google.no,google.pl,google.pt,google.ro,google.rs,google.ru,google.se,google.sk,google.tn##.ads-ad
```

**Comment by Alex-302** [comment]
пока в фильтр сафари добавил

**Comment by Alex-302** [comment]
@evgeniy-ADG 
ну что, не ответили?

**Comment by ameshkov** [comment]
Это правило есть уже в фильтре

**Comment by ameshkov** [comment]
Зачем его добавлять то

**Comment by ameshkov** [comment]
Лех, ну стопудово же ровно та же проблема с subdocument, небось уже не эксклюдится.

**Comment by ameshkov** [comment]
А, ядрена мать, парни:
ID� Name="Filter for useful ads" Version=1.0.0.84 Enabled=YES


У него же полезная реклама включена. В чем вопрос?

**Comment by Alex-302** [comment]
как всё оказалось прозаично)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
попроси юзера чтоб фильтр полезной рекламы выключил, и напиши ему для чего он предназначен

**Comment by evgeniy-ADG** [comment]
@ameshkov @Alex-302  Ok, sorry

![image](https://cloud.githubusercontent.com/assets/15856304/13991188/d7b2957e-f11f-11e5-9f40-b260156854a4.png)

ID Name="Filter for useful ads" Version=1.0.0.87 Enabled=NO

NIT-657-93714 - what about this case?..

**Comment by Alex-302** [comment]
@evgeniy-ADG 
I don't have iphone. Could you check or ask colleagues to check?

**Comment by ameshkov** [comment]
@evgeniy-ADG could you please check it on your side too?

I can't reproduce this on my end.

**Comment by worldsdream** [comment]
I have the same on my ios device. Ads showing in top like your screenshots.

**Comment by Alex-302** [comment]
@worldsdream 
filter of useful ads is turned off?

**Comment by worldsdream** [comment]
@alex-302
Yes it's off

**Comment by Alex-302** [comment]
@worldsdream 
do you have a mac? If yes - could you please to check this site in Safari with mobile user agent?

**Comment by worldsdream** [comment]
@alex-302
Yes i have windows and mac. 
I did change user agent to safari ios 8.1 iphone
I dont see any ads?

**Comment by Alex-302** [comment]
heh... I dot't know how to help you.

**Comment by worldsdream** [comment]
Weird. Now i do see the ads. What do you need now? Do you want teamviewer? Is that easier for you? If yes. Pm me in adguard forum.

**Comment by ameshkov** [comment]
The issue is caused by the EasyList rule:
```
@@||www.google.*/search?$subdocument,~third-party
```

The root cause: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/176

We've already excluded in from the English filter.
Let's transform the EasyList a bit on our side and remove this rule from it as well.

**Comment by Alex-302** [comment]
Excluded this rule from EasyList.
@worldsdream 
Please check for filters update after 30.

**Comment by worldsdream** [comment]
@ameshkov @alex-302

Fixed. Great job! 

RESOLVED
