### ISSUE TITLE
[iOS] www.netall.ru

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1445]
Пропущена реклама: 
www.netall.ru/gnn/130/573/index.html
![image-02-02-16-15-01](https://cloud.githubusercontent.com/assets/16462533/12761240/cc3b57f2-c9f2-11e5-9cf4-5df4831b39a1.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
||b.netall.ru^
