### ISSUE TITLE
[Windows] Authorization www.pfrf.ru/eservices/lkzl/

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1446]
### https://www.pfrf.ru/eservices/lkzl/

> помогает отключение куки в антитрек
![83xduze](https://cloud.githubusercontent.com/assets/16462533/12761840/448c86e8-c9f5-11e5-9eb4-ed31f7296ebb.png)

**Comment by Alex-302** [comment]
Без данных для входа починить будет сложно.
Передайте такое правило на проверку:
```
@@||esia.gosuslugi.ru^
```
Если помогло - закрывайте, правило добавил.

**Comment by Alex-302** [comment]
Не забывай, плиз, про метки. С ними смотреть удобнее.

**Comment by Serzh-SUP** [comment]
@Alex-302 мне помогло, скажу чтоб обновили фильтры.
