### ISSUE TITLE
cricfree.tv - anti-adblock script

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1449]
http://cricfree.tv/sky-sports-2-live-stream

![image](https://cloud.githubusercontent.com/assets/15856304/12780411/7b01dc06-ca76-11e5-9bd9-b0cc927e9038.png)

AJV-117-70714

**Comment by Alex-302** [comment]
It doesn't work
http://imagizer.imageshack.com/img921/2251/oy4upv.jpg

**Comment by khalidsmbzu** [comment]
It also happens to me when I checks this "Hide your referrer from third-parties" option in "Stealth Mode". BTW I am using v6.0.183.953....

See this screenshot of the same web address when I had aforementioned option is checked in Adguard.....  

![new](https://cloud.githubusercontent.com/assets/17052473/12794451/cb08c812-cabd-11e5-8694-c1d893357b68.PNG)

**Comment by khalidsmbzu** [comment]
I just checked again and link is working fine but you have to unckeck "Hide your referrer from third-parties" option in "Stealth Mode".... Look at this screenshot......
![new](https://cloud.githubusercontent.com/assets/17052473/12794504/200ba76c-cabe-11e5-848b-f0ca50a84d54.PNG)

**Comment by Alex-302** [comment]
http://i.imgur.com/izjUz5d.png
still not works. Maybe stream is dead?

**Comment by khalidsmbzu** [comment]
Its working flawlessly....... Maybe sometime it got interrupted. But you can switch between different channel lists as you can see on the left side of the website. Most of them gives the same Ad Block warning issue and don't allow you to get control over flash player on which stream is being played.... Try to switch between Sky Sports 1,2,3,4,5... All of them are experiencing the same issue.....

**Comment by Alex-302** [comment]
Added to English filter
```
@@||biggestplayer.cachefly.net/ad300.html
@@||biggestplayer.cachefly.net/cricad.html
```
