### ISSUE TITLE
[Windows] www.pcgamesn.com - missed ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1451]
![Pic](http://i.imgur.com/5n9a0x0.jpg)

**Comment by Alex-302** [comment]
added to English
||cdn.pcgamesn.com/sites/default/files/WoWs.jpg
pcgamesn.com##.ad_bgskin
to Social filter
pcgamesn.com##div[data-share-url]
