### ISSUE TITLE
[Windows] s-globus.ru & kinomax.ru места в зале

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1452]
## Не работает форма выбора мест в зале.
![globus](https://cloud.githubusercontent.com/assets/16462533/12795116/3d69fcb6-cac1-11e5-9413-95094d7ffe3c.png)
![kinomax](https://cloud.githubusercontent.com/assets/16462533/12795117/3d6e6792-cac1-11e5-8bdb-7672f2700adf.png)

**Comment by Alex-302** [comment]
@Serzh-SUP 
нужны прямые ссылки(если юзер их приводит - то их нужно тоже копировать)
Перешёл по тем, что на скринах - первый не отркылся, на втором не нашёл куда жать, или обязательно регаться?

**Comment by Alex-302** [comment]
Второй поправил:
```
@@||kinomax.ru/order/checkstatus?$document
```
Метки поменял, т.к. проблема не в антитрекинге. Ломается программой.

**Comment by Serzh-SUP** [comment]
@Alex-302 
ссылки не давал, я сам искал, извиняюсь, нужно было копирнуть.

**Comment by Serzh-SUP** [comment]
В данный момент при выборе бронирования, форма появляется, выбор времени и дата...Следующий шаг не переходит, не переходит и виснет с откл. Adguard. Сосяк сайта. Закрываю.
