### ISSUE TITLE
[Windows] Adblock on the website

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1455]
> ### На сайте: http://bigcinema.tv/series/vtoroy-shans-serial-2016-second-chance.html
> ### блокируется просмотр видео.
![2016-02-04 13-48-10 1 2016 second chance online - mozilla fi](https://cloud.githubusercontent.com/assets/16462533/12814253/50217e26-cb46-11e5-89cc-d3c7e52419e2.png)

**Comment by Alex-302** [comment]
добавил
@@||bigcinema.tv/templates/framework/js/bc/advertising.js
