### ISSUE TITLE
Broken search at hifi.fr

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1456]
http://www.hifi.fr/7-enceinte-colonne
![adguard on](https://cloud.githubusercontent.com/assets/14153331/12819567/40f849ac-cb64-11e5-92c4-78d3a55e3c0e.png)
![adguard off](https://cloud.githubusercontent.com/assets/14153331/12819568/41033bc8-cb64-11e5-8b7b-c4705c602fe5.png)
KSO-369-80330

**Comment by Alex-302** [comment]
fixed in English filter
@@||hifi.fr/pm_advancedsearch$document
