### ISSUE TITLE
baskino.club / baskino.com - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1458]
![image](https://cloud.githubusercontent.com/assets/15856304/12828265/77a6cafa-cb8c-11e5-94f1-4d69543cdb63.png)

LOP-653-84344

**Comment by Bohdan-SUP** [comment]
Seems to be fixed now. Will ask for confirmation.

**Comment by Alex-302** [comment]
Added
||seilope.com/sys/js/
||varinitconfique.ru^$third-party
