### ISSUE TITLE
[iOS] timesofisrael.com 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1459]
![image](https://cloud.githubusercontent.com/assets/15856304/12829491/190b5946-cb93-11e5-8dae-deee1f52b720.png)

XDA-265-23199

**Comment by Alex-302** [comment]
added to Safari filter
||d3nvrqlo8rj1kw.cloudfront.net^
to Mobile
timesofisrael.com##.b320x50
He should check for updates
