### ISSUE TITLE
Custom filter rule request for http://www.livejournal.com/

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1461]
http://www.livejournal.com/
![screen shot 2016-02-05 at 11 41 53 am](https://cloud.githubusercontent.com/assets/14153331/12842777/8e57b676-cbfd-11e5-8a97-cec3f30da177.png)
Requester here - QJC-926-94929

**Comment by Alex-302** [comment]
на выбор
livejournal.com##.b-discoverytimes-wrapper
livejournal.com##.discovery__popular
livejournal.com##div[lj-widget-top-journals]
livejournal.com##div[lj-widget-top-communities]
первые два - для элементов на скрине, 3 и 4 скрывают ещё блоки справа
