### ISSUE TITLE
[Windows] Ломается страница best-download.org

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1463]
> ### http://best-download.org
Как есть:
![2016-02-05 13-05-47 best-download org - mozilla firefox](https://cloud.githubusercontent.com/assets/16462533/12844753/0c4fcbfc-cc0a-11e5-9040-0444cdee78b2.png)
Как должно:
![2016-02-05 13-08-26 best-download org - mozilla firefox](https://cloud.githubusercontent.com/assets/16462533/12844764/1c68baee-cc0a-11e5-870d-a984cda00132.png)

**Comment by Alex-302** [comment]
нет смысла чинить. Это заглушка на пустом домене, и пользы от неё нет. Справа в углу надпись, что продаётся. Таких доменов тыщи.

**Comment by Alex-302** [comment]
***In progress*** - это моя метка:) Ставлю, чтоб не забыть о тикетах которые не висят безответными
