### ISSUE TITLE
[NSFW] [Mac] pornhub.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1464]
http://www.pornhub.com
![adguard on](https://cloud.githubusercontent.com/assets/14153331/12846114/5746799a-cc13-11e5-833b-f56fe5f9881e.png)
ONZ-910-63557

**Comment by Alex-302** [comment]
Фильтры свежие?
Проверь такое(из фильтра Сафари)
@@||static.pornhub.phncdn.com^$domain=pornhub.com

**Comment by evgeniy-ADG** [comment]
I asked him to try the rule.

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/12973317/2532dcd2-d0b4-11e5-97eb-c2159ec7cf74.png)
![image](https://cloud.githubusercontent.com/assets/15856304/12973330/47501442-d0b4-11e5-9f63-88f9fdecf553.png)

he said that the side is broken still now

**Comment by Alex-302** [comment]
Does he try this rule from previous message?
```
@@||static.pornhub.phncdn.com^$domain=pornhub.com
```

**Comment by evgeniy-ADG** [comment]
Now I'm not sure too, it was forwarded to him before. I asked again, will update. :\

**Comment by Bohdan-SUP** [comment]
I asked for additional clarification.

**Comment by Bohdan-SUP** [comment]
So the issue is video-player now. It works fine for me, though.
Here is a screen recording:
https://www.dropbox.com/s/15d76de8iriyahe/PORNHUB%203.mov?dl=0

**Comment by evgeniy-ADG** [comment]
> I have forgotten to tell I am on Mac version and Safari.
> 
> I have this problem on http://www.pornhub.com
> And at the top of this site there is a menu with links to other porn sites that for most of them did not accept adblockers, so the video content is blocked.
> By example :
> http://www.redtube.com
> http://www.youporn.com
> http://www.tube8.com
> http://www.xtube.com
> 
> I know you are working on a way to prevent this type of site from blocking the content when they detect an adblocker.
> So I suppose I will wait you have released this function for adguard.

**Comment by Alex-302** [comment]
I can't reproduce this problem now. Maybe filters are too old?
Did user check exclusions from previous messages?

**Comment by Bohdan-SUP** [comment]
It was ABP Japanese. We should put some warning for that filter.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
скоро переделаю тот фильтр и в наш фильтр перенесу. Попроси его выключить этот фильтр, если по японским сайтам не ходит

**Comment by Bohdan-SUP** [comment]
Так и сделали. Эту задачу закрываю тогда.
