### ISSUE TITLE
Anti-adblock at telegraaf.nl

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1465]
telegraaf.nl
![screen shot 2016-02-05 at 2 55 30 pm](https://cloud.githubusercontent.com/assets/14153331/12846968/ac7b345a-cc18-11e5-80b6-7e454c48aa00.png)
WJS-679-31180

**Comment by Vincent-Michael** [comment]
try:
telegraaf.nl#%#window.canRunAds = function() {};

**Comment by Alex-302** [comment]
@@||telegraaf.tcdn.nl/javascript/showads*.js
this is better, because Safari doesn't support JS rules, end this script contains only the marker
```
var canRunAds = true;
```
