### ISSUE TITLE
Breaks TP-Link web interface

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1468]
192.168.137.100 is the address

ADG is off:
![image](https://cloud.githubusercontent.com/assets/15856304/12851432/7478cd96-cc32-11e5-9732-2bffbf6b9f73.png)

ADS is on: 
![image](https://cloud.githubusercontent.com/assets/15856304/12851456/8c4b7c16-cc32-11e5-972f-1a597a49b9e2.png)
MKN-523-82519

**Comment by Alex-302** [comment]
У меня тоже на тплинке тупит долго, но в итоге загружвется где-то за минуту. Исключения не помлгают.

**Comment by Alex-302** [comment]
@ameshkov 
если принесу свой роутер, поможет чем-то?

**Comment by ameshkov** [comment]
Лучше полных логов собери

**Comment by Alex-302** [comment]
[Logs.zip](https://github.com/AdguardTeam/ExperimentalFilter/files/119547/Logs.zip)
вот логи

**Comment by Serzh-SUP** [comment]
Примерно та же проблема, прогружается, но долго очень. Тоже TP-Link
У меня повторилось и у нескольких пользователей.
> ip 192.168.0.1 

![xkrfbvh](https://cloud.githubusercontent.com/assets/16462533/12867584/d4a9afc4-ccf9-11e5-98a7-d478de1790b0.png)

**Comment by imzod** [comment]
То же самое, долго грузит 192.168.0.1
![2016-02-05 19-49-24 tl-wr940n tl-wr941nd - google chrome 2](https://cloud.githubusercontent.com/assets/17099318/12867692/14eeef1a-cd16-11e5-8403-b77864a9c8de.png)

**Comment by Bohdan-SUP** [comment]
Логи тут - RLZ-436-71029

**Comment by ameshkov** [comment]
@Alex-302 запилишь нам задачу в Adguard для Windows?

**Comment by Alex-302** [comment]
сделал
https://github.com/AdguardTeam/AdguardForWindows/issues/844
здесь закрываю тогда
