### ISSUE TITLE
[iOS] http://unogs.com/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1469]
![image](https://cloud.githubusercontent.com/assets/15856304/12851960/53075116-cc35-11e5-9666-54c35a086172.png)

The ad is displayed in the centre of the page and rotates between grey panels (looks like misloaded ads) and an ad for Smatflix. Here's a screenshot.
TKO-282-67071

**Comment by Alex-302** [comment]
added to English
unogs.com##.advert
