### ISSUE TITLE
[Windows] www.cowcotland.com - Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1471]
![pic](http://i.imgur.com/ffy9em2.png)

**Comment by Alex-302** [comment]
Added (this CSS contains the style, which hide yellow message)
@@||cowcotland.com/themes/v2/style/blogads.css
Fixing images
@@||cowcotland.com/scripjs.php$document
@@||cowcotland.com/scripjs.php
