### ISSUE TITLE
[Windows] www.torrentfreak.com - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1472]
![pic](http://i.imgur.com/eDyZXiz.jpg)

I use current:
torrentfreak.com###sidebar > aside.widg.widget_text

**Comment by Alex-302** [comment]
For the User filter, because code of element is similar to useful elements
```
torrentfreak.com###sidebar > .widg.widget_text
```

**Comment by adranger** [comment]
@Alex-302  Please test `torrentfreak.com##.widget-1`.

**Comment by Alex-302** [comment]
ok
