### ISSUE TITLE
[Windows]  www.damngeeky.com - Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1473]
![pic](http://i.imgur.com/9QLhLLD.jpg)

I use current:
||flexinetsolutions.com/cdn/js/detectab.js$domain=damngeeky.com
damngeeky.com##.google-trending

**Comment by Alex-302** [comment]
added to experimental filter
damngeeky.com##.google-trending
