### ISSUE TITLE
[Android] es.rafalense.themes

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1474]
https://play.google.com/store/apps/details?id=es.rafalense.themes
https://www.dropbox.com/s/q9g5ti16kb09jyv/Screenshot_2016-02-06-16-33-36.png?dl=0
Logs - NZI-683-17795

**Comment by Alex-302** [comment]
фейсбучная же, по HTTPS грузится. Ждать осталось не долго.

**Comment by Alex-302** [comment]
С альфой чисто.
