### ISSUE TITLE
[Android] Crossy Road

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1475]
The app crashes when Adguard is running in the background.
https://play.google.com/store/apps/details?id=com.yodo1.crossyroad
Logs HWO-228-46268

**Comment by Alex-302** [comment]
Need more detail description.
How can I reproduce this issue?

**Comment by evgeniy-ADG** [comment]
У меня не повторялось.

**Comment by Alex-302** [comment]
Can't reproduce too.
