### ISSUE TITLE
abc7.com - can't watch images

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1476]
![image](https://cloud.githubusercontent.com/assets/15856304/12871518/cfe86334-cd87-11e5-95c2-9f3163f10ef3.png)

If you click on a paticaluar image it doesn't show too
![image](https://cloud.githubusercontent.com/assets/15856304/12871516/820a2634-cd87-11e5-9c95-882330695d35.png)

http://abc7.com/pets/photos-dog-with-short-spine-has-big-heart/1180076/

**Comment by Alex-302** [comment]
added to spyware filter
```
@@||tags.bkrtx.com/js/bk-coretag.js^$domain=abc7.com
```
