### ISSUE TITLE
bcaa.ua

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1477]
На сайте bcaa.ua к любым продуктам невозможно отправить отзыв, так как ничего не происходит. При отключении AdGuard после добавления отзыва появляется AJAX с текстом «Отзыв отправлен на проверку».
ZHU-933-37341

**Comment by Alex-302** [comment]
в русский
@@||bcaa.ua/interactive/ajax.php$document
