### ISSUE TITLE
deezer.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1478]
deezer.com
![off](https://cloud.githubusercontent.com/assets/14153331/12877242/01fa031e-ce19-11e5-8112-fce44b551b24.png)
![on](https://cloud.githubusercontent.com/assets/14153331/12877243/0214026e-ce19-11e5-8583-f32056e6a4a6.png)
TWX-321-57539

**Comment by Alex-302** [comment]
добавил
@@||deezer.com/images/cover/
