### ISSUE TITLE
Plants vs. Zombies 2 missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1479]
https://play.google.com/store/apps/details?id=com.ea.game.pvz2_row

Source:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=46870669

**Comment by Alex-302** [comment]
I don't see ads after 3 levels.
Wrote to user.

**Comment by Bohdan-SUP** [comment]
http://prntscr.com/a3fydh
Logs here - NQZ-652-87297

**Comment by Alex-302** [comment]
Fixed
