### ISSUE TITLE
[iOS] [Windows] raf.su Missed Ads 

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1484]
> Прямая ссылка на которой реклама:
> http://www.raf.su/rally

**`Реклама всплыла, как на iOS, так и на Windows`**

![image1](https://cloud.githubusercontent.com/assets/16462533/12888550/6ea4d54c-ce83-11e5-8c08-e036ea2e85b3.png)

**Comment by Alex-302** [comment]
Добавил в русский
||bw95vpjda.ru^$third-party
