### ISSUE TITLE
Broken interface - tottenhotspur.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1487]
http://ww1.tottenhotspur.com/
![on](https://cloud.githubusercontent.com/assets/14153331/12892233/d803ef0e-ce93-11e5-98d6-ffe30e716762.png)
![off](https://cloud.githubusercontent.com/assets/14153331/12892232/d801196e-ce93-11e5-81eb-12680eaf5abb.png)
HDU-169-50806

**Comment by Alex-302** [comment]
It is domain for sell.
Did you open these links?
