### ISSUE TITLE
[iOS] Missed Ads

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1490]
> http://wap.vsekratko.ru/sochinenie/saltykov_shhedrin/raznoe_4/

> http://antisochinenie.ru/%D1%81%D0%BE%D1%87%D0%B8%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F/%D0%A1%D0%B0%D0%BB%D1%82%D1%8B%D0%BA%D0%BE%D0%B2-%D0%A9%D0%B5%D0%B4%D1%80%D0%B8%D0%BD/%C2%AB%D0%A1%D0%9A%D0%90%D0%97%D0%9A%D0%90_%E2%80%94_%D0%9B%D0%9E%D0%96%D0%AC,_%D0%94%D0%90_%D0%92_%D0%9D%D0%95%D0%99_%D0%9D%D0%90%D0%9C%D0%95%D0%9A!..%C2%B

![image](https://cloud.githubusercontent.com/assets/16462533/12917868/85db790c-cf44-11e5-8775-5d2ea1ea97f0.PNG)
![image1](https://cloud.githubusercontent.com/assets/16462533/12917867/85d177ea-cf44-11e5-9cca-4acb683564a2.png)

**Comment by Alex-302** [comment]
C wap.vsekratko.ru не повторяется(проверял на дроиде), заблокировал в моб фильтре баннер из шапки, на фоне попапа который.

Для второго в русский добавил
||tizerads.ru^$third-party
Отстыпы от рекламы не убрать, т.к. всё сломается.
