### ISSUE TITLE
[Windows] www.schoener-wohnen.de - Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1492]
![Pic](http://i.imgur.com/gpQwxxC.png)
e.g. http://www.schoener-wohnen.de/einrichten/raeume/34487-bstr-die-15-besten-wohntipps-fuer-die-kueche#96470-img-die-passende-kuechenform-finden

I use current:
||laterpay.net^$domain=schoener-wohnen.de

**Comment by Alex-302** [comment]
added
