### ISSUE TITLE
[Windows] www.essen-und-trinken.de - Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1494]
![Pic](http://i.imgur.com/PXp0262.png)
e.g. http://www.essen-und-trinken.de/rezept/379894/haehnchenroellchen-mit-paprikagemuese.html

I use current:
||laterpay.net^$domain=essen-und-trinken.de

**Comment by Alex-302** [comment]
Added, but I don't see this message.
