### ISSUE TITLE
http://update.vsegonet.com/ - ads, popups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1495]
![image](https://cloud.githubusercontent.com/assets/15856304/12942494/50922368-cfe4-11e5-9545-f51ee5371282.png)

![image](https://cloud.githubusercontent.com/assets/15856304/12942499/592e749a-cfe4-11e5-8f58-5c529e0e0cc5.png)

CEE-621-93904

**Comment by Alex-302** [comment]
added
||ppund.vsegonet.com^
