### ISSUE TITLE
login.wi-fi.ru - anti adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1497]
https://login.wi-fi.ru/am/error/?adblock.enabled
http://prntscr.com/a1cyyt

Сайт не пропускает пользователей из-за использования блокировщика.

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.75.15 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.50 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.7 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.30.11 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.2.11 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.30 Enabled=YES

**Comment by Alex-302** [comment]
Только пользователи айфонов жалуются? От андроидов жалоб нет?

**Comment by evgeniy-ADG** [comment]
Вроде не жалуются.

**Comment by Bohdan-SUP** [comment]
Логи - LSM-118-40041 и ZLA-320-66254

**Comment by Alex-302** [comment]
Логи iOS в данном случае бесполезны, запросы не логируются.

**Comment by onega** [comment]
После обновления AdGuard до 1.0.5 начались серьёзные проблемы с антиблокировщиком, предыдущая версия на другом устройстве с авторизацией справляется без пробем. Тикет #LSM-118-40041

**Comment by Alex-302** [comment]
Версия ни при чём. Проблема может быть только в фильтрах и стороннем блокировщике.

**Comment by Serzh-SUP** [comment]
Проблема решена обновление фильтров.
