### ISSUE TITLE
apkpure.com - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1498]
![image](https://cloud.githubusercontent.com/assets/15856304/12944629/0150a98e-cff1-11e5-9d71-1323d9e45bcf.png)

https://apkpure.com/
http://prntscr.com/a1d1a0

при откл русского фильтра
http://prntscr.com/a1d165

**Comment by Alex-302** [comment]
добавил в русский
apkpure.com#@#.banner-search
