### ISSUE TITLE
[iOS] forum.krasmama.ru missed ads

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1501]
### http://forum.krasmama.ru/
![image1](https://cloud.githubusercontent.com/assets/16462533/12948771/de0d8340-d00c-11e5-8c4d-6a82978a1b76.png)

**Comment by Alex-302** [comment]
добавил в русский
||lamma.24ex.net^$third-party
в аналитику
||forum.krasmama.ru/js/adv_cnt_
||log.krs-ix.ru^
