### ISSUE TITLE
[Windows] play.google.com unstable site's functionality

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1503]
Не загружается play.google.com
Так и висит:
![2016-02-10 21-31-34 google play - google chrome](https://cloud.githubusercontent.com/assets/16462533/12959213/2e2b7270-d03e-11e5-81f0-6b188863fc7e.png)

**Comment by Alex-302** [comment]
Мало информации. От конкретного фильтра зависит, антатрекинга или с выключенными фильтрами и антатрекингом так же?

**Comment by evgeniy-ADG** [comment]
С Антитреккингом у меня все ок
![image](https://cloud.githubusercontent.com/assets/15856304/12965039/18fc6788-d05c-11e5-84b3-6c75aad22d0b.png)
![image](https://cloud.githubusercontent.com/assets/15856304/12965064/39c631b0-d05c-11e5-9386-3195915755d6.png)
![image](https://cloud.githubusercontent.com/assets/15856304/12965081/49886262-d05c-11e5-8384-0f4c9e804171.png)

**Comment by Alex-302** [comment]
У меня не повторилось с этими фильтрами и полностью включенным антитрекингом.

**Comment by Serzh-SUP** [comment]
Фильтры базовые, антитрекинг вкл./выкл. одинаково, ходишь по разделам: приложения, фильмы, музыка, как на первом скрине, висит стрелка обновления.

**Comment by evgeniy-ADG** [comment]
переустанови
![image](https://cloud.githubusercontent.com/assets/15856304/12973623/5e75e1cc-d0b6-11e5-93b4-e3d28237d956.png)

**Comment by Alex-302** [comment]
@Serzh-SUP 
это у тебя так?
Попробуй фильтры с конца списка выключать с проверкой. Можно без антитрекинга. У меня никак не повторяется.
Может не в фильтре дело, а сам Адгард что-то портит(редко, но бывает такое)

**Comment by Serzh-SUP** [comment]
@Alex-302 
Да, у меня, проблема так и осталась. отключения фильтров не помогло. Я просто добавил в исключения.
