### ISSUE TITLE
icefilms.info

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1506]
- Go to http://www.icefilms.info/
- Click on search in top-right.
- Another tab opens with tabs - http://tinypic.com/r/dcd1lc/9
EZW-306-81935

**Comment by Alex-302** [comment]
added to English
||data.shipboardserviceberrysiltstone.info^$third-party

**Comment by Bohdan-SUP** [comment]
Still happens on a Mac.
Also, I have no assistant on the page.
And this ad is not blocked:
![screen shot 2016-02-14 at 5 09 14 pm](https://cloud.githubusercontent.com/assets/14153331/13034419/c964ae76-d33d-11e5-8460-d2dd67c6166b.png)

**Comment by Alex-302** [comment]
Added
icefilms.info###adrightside

About assistant - you can open a bug. It is not filters problem now.
