### ISSUE TITLE
[iOS] lifehacker.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1507]
http://lifehacker.ru/2016/02/10/akrasia/
![image1](https://cloud.githubusercontent.com/assets/14153331/12967519/ef3335f8-d06f-11e5-9e45-0b001ddc61ff.PNG)
UXY-286-38933

**Comment by Alex-302** [comment]
добавил в русский
```
lifehacker.ru##.jetpack-image-container > a[href^="http://lfhk.ru/"]
```
@Bohdan-SUP @evgeniy-ADG @Bohdan-SUP 
Большие скрины прячте по возможности под тэг, плиз
```
<details> 

</details>
```
Будет вот так:
<details> 
![image1](https://cloud.githubusercontent.com/assets/14153331/12967519/ef3335f8-d06f-11e5-9e45-0b001ddc61ff.PNG)
</details>
а то на ноуте прокручивать два экрана приходится:)
