### ISSUE TITLE
[Windows] www.autobild.de - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1508]
![Pic](http://i.imgur.com/1iEuFFt.jpg)

e.g. http://www.autobild.de/artikel/land-rover-discovery-2017-vorschau-8585239.html

I use current:
autobild.de#%#window.uabInject = function() {};
autobild.de##.teaserbox.rectangle
autobild.de##.partnerlabel

**Comment by Alex-302** [comment]
added
