### ISSUE TITLE
for-ua.com missed ads

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1510]
http://for-ua.com/article/1105564
Повторилось с базовыми фильтрами.
![default](https://cloud.githubusercontent.com/assets/16462533/12973736/48b1bde2-d0b7-11e5-9cc5-755abcc17c9f.png)

**Comment by Alex-302** [comment]
добавил
for-ua.com##div[style^="width:250px;height:360px;"]
for-ua.com##noindex a > img
