### ISSUE TITLE
cont.ws - missed yandex.direct add

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1512]
С недавнего времени начала лезть назойливая видеореклама на сайте cont.ws 
Исходный код одной из страниц и скриншот страницы с рекламой в прилагаемом архиве.

[reklama (1).zip](https://github.com/AdguardTeam/ExperimentalFilter/files/126229/reklama.1.zip)

PGO-506-46998

**Comment by Alex-302** [comment]
добавил
||seedr.com^$domain=cont.ws
