### ISSUE TITLE
http://medinsult.ru/ & http://rubook.org/ missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1513]
http://medinsult.ru/golovnaya-bol/tochechnyj-massazh.html
![image](https://cloud.githubusercontent.com/assets/15856304/12975418/22ca7f30-d0c4-11e5-9393-fba90982f001.png)

http://rubook.org/book.php?book=112121&page=2
![image](https://cloud.githubusercontent.com/assets/15856304/12975425/2cf5389c-d0c4-11e5-9ac5-59b3bc2dde20.png)

CIP-965-80989

**Comment by Alex-302** [comment]
добавил
||medinsult.ru/teasers/
medinsult.ru##.teaser-wrapper
.rubook.biz^$script
