### ISSUE TITLE
farsroid.com, androidiha.net - unwanted popup

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1514]
http://androidiha.net/

When I click on the next page (page 2, 3, 4, ...) of this website, it opens a popup, leading to (http://androidiha.net/forum/)

http://www.farsroid.com

Again, When I click on the next page (page 2, 3, 4, ...) of this website, it opens a popup, leading to (https://janebi.com/)

ZBW-976-69314

**Comment by Alex-302** [comment]
androidiha.net - can't confirm it.
For the second:
||farsroid.com/file/PopM.js

**Comment by rayman3003** [comment]
ok, thanks
