### ISSUE TITLE
[Windows] www.gala.de - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1516]
![Pic](http://i.imgur.com/u4uYtId.jpg)

I use current:
gala.de#%#window.uabInject = function() {};

**Comment by Alex-302** [comment]
||leadiacloud.com^$domain=ya-dandy.com

**Comment by Vincent-Michael** [comment]
wrong rule? ^^

**Comment by Alex-302** [comment]
Wrong issue:)
Added you rule to German filter.
