### ISSUE TITLE
[Windows] www.brigitte.de - Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1517]
![Pic](http://i.imgur.com/0mEHkOs.png)

I use current:
```
@@||img1.brigitte.de/*/ad_bomb/*.png
```
"http://img1.brigitte.de/2ffd03e75315a94de447b4bb332dbff0/v3/ad_bomb/IMe1CKwRKV4.png"

**Comment by Alex-302** [comment]
Yes, we use it as alternate of #%#window.uabInject = function() {};

**Comment by Alex-302** [comment]
Added
