### ISSUE TITLE
No Assistant at msnbc.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1520]
msnbc.com
Is it in exclusions list?
<details>
![msnbc](https://cloud.githubusercontent.com/assets/14153331/12997317/c550e592-d140-11e5-9aa6-178f70d97413.png)
</details>
KDV-337-96214

**Comment by Alex-302** [comment]
Partially. It was broken by javascript rules.
I will remove this old rule
```
@@||msnbc.com^$jsinject
```
You can disable it and check the videos, and close issue if it ok.

**Comment by Bohdan-SUP** [comment]
Works like a charm.
