### ISSUE TITLE
[Android] dailycaller.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1521]
dailycaller.com - белая страница, при отключении Английского фильтра - все ок

> Здраствуйте ! При попытке открыть сайт http://dailycaller.com/ через несколько секунд все его содержимое пропадает и виден только чистый лист. Последние версии adguard и фильтры на mac os и android. Браузер Chrome на обоих операционках. Если отключить adguard сайты работают. Обращал несколько раз на других сайтах такое поведение, но не придал значения. В чем причина

XXC-607-63555

**Comment by Alex-302** [comment]
добавил в англ
dailycaller.com#@#.adblock
