### ISSUE TITLE
Can't access mts.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1522]
Нет доступа к сайту с ряда браузеров, помогает лишь отключение фильтрации для браузера.

у меня в мозилле, даже с выкл адгардом - не работает
http://prntscr.com/a26vuf

а если отключить "фильтрацию приложения" - то работает
http://prntscr.com/a26wy7

XLV-669-27211

**Comment by Alex-302** [comment]
У меня сразу открылся. С фильтрами такое точно не связано. Сама программа может в некоторых случаях с фоксом не корректно работает, или вообще на сайте проблема.

**Comment by evgeniy-ADG** [comment]
У меня вчера вечеорм не работало в эдже и в фоксе. попробую еще раз вечером и напишу. Но есть/была проблема...

**Comment by Alex-302** [comment]
@evgeniy-ADG 
если можешь - включи подробное логирование, и когда повторится глюк - пришли его с временем появления ошибки.

**Comment by evgeniy-ADG** [comment]
[Logs.zip](https://github.com/AdguardTeam/ExperimentalFilter/files/129195/Logs.zip)
17:04

**Comment by Alex-302** [comment]
@ameshkov Можешь глянуть в чём проблема? Не пойму на что смотреть там.

**Comment by evgeniy-ADG** [comment]
Уже работает.
