### ISSUE TITLE
[iOS] moscow.fas.gov.ru - blocked useful elements

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1525]
http://moscow.fas.gov.ru/poll/14152

http://moscow.fas.gov.ru/poll/14152

видимо как должно быть
http://prntscr.com/a28p5i

и как есть с Адгард
http://prntscr.com/a28pal

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.77.9 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.81 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.53 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.30.93 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.2.38 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.43 Enabled=YES

**Comment by Alex-302** [comment]
@@||fas.gov.ru/sites/all/themes/fasregion/img/banner/
