### ISSUE TITLE
http://openspeedtest.com/ - missed ads and anot-adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1527]
wow.

http://openspeedtest.com/

<details>
![msnbc](https://cloud.githubusercontent.com/assets/15856304/13005322/edd56af8-d189-11e5-8342-6eafe0056071.png)

**Comment by Vincent-Michael** [comment]
try:
@@||openspeedtest.com/adsbygoogle.js

**Comment by Alex-302** [comment]
Thanks
Added to Experimental filter(because it does not break the page)
