### ISSUE TITLE
fishki.net - adg blocks videos

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1528]
http://fishki.net/1845778-ljubov--jeto-ne-to-chto-pokazyvajut-v-kino.html
получилось зафиксировать
http://prntscr.com/a295h6

WMN-464-25181

**Comment by Alex-302** [comment]
с расширением или с прогой? У меня не повторяется(проматывал вниз/вверх)
Можешь скриншот кода элемента сделать?

**Comment by Alex-302** [comment]
а, видео ж блокируем

**Comment by Alex-302** [comment]
добавил в русский
@@||out.pladform.ru/player$domain=fishki.net
