### ISSUE TITLE
kinopoisk.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1529]
Вырезается прозрачная подложка в шапке сайта. 

Как сейчас: http://screencast.com/t/YchHodIwfMOJ
Какая она до вырезания: http://screencast.com/t/Qcp3xOMjanC

MGI-919-11154

**Comment by Alex-302** [comment]
Попроси проверить такое правило
```
@@||st.kp.yandex.net/images/bnnr/brand/*.png$domain=kinopoisk.ru
```

**Comment by vbagirov** [comment]
Всё работает.

**Comment by Alex-302** [comment]
добавил
