### ISSUE TITLE
DU browser ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1531]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=46891461

@Alex-302 is it possible to block?

![7541493](https://cloud.githubusercontent.com/assets/5947035/13006935/782afdea-d19d-11e5-9244-1dcc79c133c1.png)

**Comment by Alex-302** [comment]
yes. This self-ad is annoying, so I added the rules to English filter
```
||mobile-global.baidu.com/mbrowser/promotion/get_advertisement_conf?
||rts.mobula.sdk.duapps.com^$empty
||bmbs.baidu.com/reportinfo.php$empty
||mobile-global.baidu.com/mbrowser/stat/$empty
```
But if they loaded, they will displayed from cache. Need reinstall this app.

**Comment by ameshkov** [comment]
English? Why not mobile?

**Comment by Alex-302** [comment]
They was added in mobile filter:) Mistake in my comment.
