### ISSUE TITLE
moviefull-hd.com - anti adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1532]
<details>
**
![image](https://cloud.githubusercontent.com/assets/15856304/13007086/5bfb20d4-d196-11e5-8569-c0d89ded07e0.png)
**
</details>
JAE-268-39791

**Comment by Alex-302** [comment]
@@||moviefull-hd.com^$generichide
moviefull-hd.com##a[onclick*="adstract."]
