### ISSUE TITLE
http://tinypic.com - can't upload an image with Hide you IP option

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1534]
On the site - http://tinypic.com/ I get the the following - http://tinypic.com/r/jfvw94/9 if I attempt to upload an image when "Hide your IP Address" is enabled in "Stealth Mode".

![image](https://cloud.githubusercontent.com/assets/15856304/13007199/43ec8f86-d197-11e5-913c-8f174d2b2a6b.png)

**Comment by Alex-302** [comment]
Added
```
@@||tinypic.com/upload.php
```
Check it please
