### ISSUE TITLE
[Windows] www.damngeeky.com - Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1536]
![Pic](http://i.imgur.com/lz92ro0.png)
http://www.damngeeky.com/2016/02/12/39547/innovation-award-for-lego-prosthetic-arm-that-lets-children-design-their-own-hand.html

I use current:
||flexinetsolutions.com/cdn/js/detectab.js$domain=damngeeky.com

**Comment by Alex-302** [comment]
Added to Experimental.
