### ISSUE TITLE
[Windows] www.wdr.de - False Positive

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1537]
![Pic](http://i.imgur.com/JGEyrtG.png)
http://www1.wdr.de/studio/duesseldorf/cyberangriff-lukaskrankenhaus-neuss-100.html

I use current:
@@||wdr.ivwbox.de/cgi-bin/ivw/CP/

**Comment by Alex-302** [comment]
Ok.
Added
@@||wdr.ivwbox.de/cgi-bin/ivw/CP/$domain=wdr.de
