### ISSUE TITLE
[android] ru.more.play app is broken

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#154]
При включенной фильтрации перестаёт работать приложение Okko фильмы (https://play.google.com/store/apps/details?id=ru.more.play), вернее перестают проигрываться, собственно, фильмы, выдается ошибка подключения к сети. Проблема остаётся как и режиме VPN, так и в режиме HTTP прокси и в обеих версиях Adguard. Вероятно в фильтры попали адресы сервиса Okko, не могу только сообразить, какие адреса в белый список добавить.

**Comment by Alex-302** [comment]
Видать что-то поменяли - приложение заработало без смены IP, трейлеры воспроизводятся без проблем.
Как-то можно у юзера уточнить?

**Comment by ameshkov** [comment]
Да вряд ли, проблема то старая очень.
