### ISSUE TITLE
[iOS] pda.rg.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1542]
http://pda.rg.ru/2016/02/13/reg-cfo/na-moskve-reke-zagorelsia-debarkader.html
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/13029016/6d9b06a4-d288-11e5-81b7-a84e1a1971d1.png)

![image-3](https://cloud.githubusercontent.com/assets/14153331/13029010/4ae55ae2-d288-11e5-8c2b-59456ad96012.png)
</details>
NGM-872-30643

**Comment by Alex-302** [comment]
Чисто должно быть.
Передай правила на проверку:
```
||i-vengo.com^$empty
rg.ru###yandex_ads_hor_pda
||partner.mediametrics.ru^$third-party
||adfox.ru^$third-party 
```

**Comment by Alex-302** [comment]
@Bohdan-SUP 
не ответил юзер?

**Comment by Bohdan-SUP** [comment]
Передал правила.

**Comment by Bohdan-SUP** [comment]
@Alex-302 добавь в фильтры правила.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
добавил
