### ISSUE TITLE
Video ad on sport-express.ru on Android

### ISSUE THREAD

**Issue by dtitbd** [AdguardTeam/ExperimentalFilter#1543]
![screenshot_2016-02-14-00-29-19](https://cloud.githubusercontent.com/assets/17032471/13029585/31a4307e-d2b2-11e5-84bc-0bdb92862ba3.png)
Иногда автовоспроизводится, иногда нет, но рекламой от этого быть не перестает.
Встречается и в новостях, и в статьях.
Ссылка на пример: http://www.sport-express.ru/speed-skating/reviews/966562/

**Comment by Alex-302** [comment]
Добавил:
||seedr.com^$domain=cont.ws|vc.ru|sport-express.ru
Проверьте, скопировав в собственный фильтр.

**Comment by dtitbd** [comment]
Вроде все ок.
Она просто не всегда появляется, поэтому со 100% уверенностью не могу сказать.
Попробовал с десяток новостей и статей разных разделов - ни разу не встретил.
