### ISSUE TITLE
Реклама на сайте http://kinohd.net/

### ISSUE THREAD

**Issue by Ordos-hoka** [AdguardTeam/ExperimentalFilter#1544]
Реклама в верхней части страниц сайта http://kinohd.net/
Adguard 2.1.359; режим: локальный VPN, быстрый; фильтры по умолчанию; android 4.2.2 root
![screenshot_2016-02-14-09-13-10](https://cloud.githubusercontent.com/assets/17230584/13032576/129d1b88-d301-11e5-90c1-14ea56dc209f.jpg)

**Comment by Alex-302** [comment]
||brokeloy.com^$third-party
добавил
