### ISSUE TITLE
[Windows] www.gamestar.de - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1546]
![Pic](http://i.imgur.com/cj2wCwq.png)
http://www.gamestar.de/hardware/praxis/2568163/die_besten_gaming_gehaeuse.html

I use current:
gamestar.de##.teaserRight.ads_outer

**Comment by Alex-302** [comment]
added
gamestar.de##div[class$="ads_outer"]
