### ISSUE TITLE
[Windows] www.tweaktown.com - Anti Adblock Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1550]
![Pic](http://i.imgur.com/sNxTTpq.png)
http://www.tweaktown.com/news/50369/quantum-break-exclusive-windows-store-reach-steam/index.html

I use current:
||tweaktown.com/scripts/navigation.js
(need remove cache)

**Comment by Alex-302** [comment]
Doesn't this rule break something?

**Comment by Vincent-Michael** [comment]
we can also use:
```
||tweaktown.com/xyz?p=
```

**Comment by Alex-302** [comment]
Added
||tweaktown.com/xyz?p=

**Comment by Vincent-Michael** [comment]
I have strange bug... This filter works only for me in user filter and not in english filter (its 1:1 same)
