### ISSUE TITLE
[Android] m.gd.ru - registration message blocks the page

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1552]
Здравствуйте. На сайте http://m.gd.ru/articles/3678-red-oborotnyy-kapital-kompanii появляется блокирующее страницу сообщение о регистрации. Создайте, пожалуйста, фильтр, чтобы подобные окна не мешали чтению материала сайта. Заранее благодарен.

![image](https://cloud.githubusercontent.com/assets/15856304/13046790/a4dfbe3c-d3e3-11e5-9772-3f603f3f2635.png)

Можем убрать?

YLP-689-87110

**Comment by Alex-302** [comment]
Да, в экспериментальном фильтре. Позже отделится в отдельный фильтр для мусора.
Добавил
m.gd.ru##.megaShadow
