### ISSUE TITLE
www.videokub.me - redirects to 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1553]
> Здравствуйте Когда запускаешь проигрывания видео начинают открываются разные нежелательные сайты со включенным Adguard не помогает http://www.videokub.me/videos/115041/borodach-6-seriya-12-02-2016/

http://www.videokub.me/videos/115041/borodach-6-seriya-12-02-2016/
http://prntscr.com/a2n5wx

вылазит такой блок, с которого идет перенаправление

KME-687-84822

**Comment by Alex-302** [comment]
||videokub.me/myc/search.php$popup
videokub.me#%#document.cookie = "mycp=1";
