### ISSUE TITLE
http://www.techhive.com/ is broken

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1554]
Adguard makes techhive.com inoperable. Clicking on all the links does not respond at all. Ctrl-click on a link does not open a new tab and doesn't respond. Please fix.

RQI-159-59807

**Comment by Alex-302** [comment]
Fixed.
@@||b.scorecardresearch.com/r$domain=techhive.com
@@||pcworldcommunication.d2.sc.omtrdc.net/b/ss/$domain=techhive.com
