### ISSUE TITLE
news.mail.ru - blocked useful ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1558]
Id=0 Name=User filter Version=0.0.0.0
Id=1 Name=Russian filter Version=1.0.30.80
Id=2 Name=English filter Version=1.0.76.75
Id Name=Filter for useful ads Version=1.0.0.88
Id7 Name­block Polska Version=1.0.0.52

нет полезной рекламы
https://news.mail.ru/?from=menu
http://prntscr.com/a3gpfu

GGM-170-91743

**Comment by Alex-302** [comment]
Она не полезная. Добавляем только контекстную и саморекламу.
