### ISSUE TITLE
rasp.yandex.ru - broken by Adguard

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1561]
> При включенном Адгарде блокируются интерфейсные элементы: https://yadi.sk/i/HhDuOQN0otP5f
Посмотреть можно, например, здесь: https://rasp.yandex.ru/informers/informer/
> Или на каком-нибудь сайте, где вставлены расписания: http://northwind.pro/index/instrumentarij/0-14#post000038 
> При выключенном Адгарде все элементы работают.

**Comment by Alex-302** [comment]
removed from Russian filter
```
/informer*.js$third-party,domain=~as-roma.ru|~rublacklist.net|~topnews.ru|~transitcard.ru
/informer.js?
/informer.php$third-party,domain=~petrolplus.ru|~transitcard.ru
```

**Comment by ameshkov** [comment]
Nice, thank you!
