### ISSUE TITLE
[Windows] www.custompcreview.com - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1564]
![Pic](http://i.imgur.com/lFH29ku.jpg)

I use current:
```
custompcreview.com#$#html > body { background-image: none!important; cursor: default!important; }
custompcreview.com#%#Object.defineProperty(window, 'bg_backgrounds', { get: function() { return []; } });

```

**Comment by Alex-302** [comment]
added
custompcreview.com#$#body { background-size: 0px!important; cursor: default!important; }
custompcreview.com#%#Object.defineProperty(window, 'bg_backgrounds', { get: function() { return []; } });
without HTML, because we can't select it with Shadow-DOM
