### ISSUE TITLE
[iOS] ykt.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1565]
При нажатии на ссылки в разделе форумы появляется прозрачный квадрат с ссылкой на рекламу

<details>
![image2](https://cloud.githubusercontent.com/assets/14153331/13060578/42f5a06c-d43b-11e5-9e6b-2ac4265e982b.PNG)
![image1](https://cloud.githubusercontent.com/assets/14153331/13060577/42f31ba8-d43b-11e5-878e-39a046080569.PNG)

</details>
DCP-418-76205

**Comment by Alex-302** [comment]
Эта проблема на стороне сайта.

**Comment by Alex-302** [comment]
От баннера сверху:
ykt.ru##iframe[name^="adv"]
