### ISSUE TITLE
[Android] rus.delfi.lv

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1566]
rus.delfi.lv
<details>
![screenshot_2016-02-15-09-40-49](https://cloud.githubusercontent.com/assets/14153331/13065505/b483a42a-d465-11e5-839c-a966067a2fa2.png)
</details>
CIT-388-45053

**Comment by Alex-302** [comment]
добавил
delfi.lv##div[class^="adsAdmin-"]
