### ISSUE TITLE
[Android] SpeedTest Master

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1567]
https://play.google.com/store/apps/details?id=com.quickbird.speedtestmaster

Реклама в приложении. Скриншоты:
https://scontent-frt3-1.xx.fbcdn.net/hphotos-xtp1/v/t34.0-0/p206x206/12721923_571438246347114_1793027479_n.jpg?oh=400773d9701073d06124d3c78bb3a262&oe=56C46EFF

https://scontent-frt3-1.xx.fbcdn.net/hphotos-xfp1/v/t34.0-0/p206x206/12736377_571438239680448_867429977_n.jpg?oh=2263f1de699b3f81abed598ea5c35b04&oe=56C546CC

**Comment by Alex-302** [comment]
@vbagirov 
не рабочие скрины. Реклама, случайно, не Ad Choices? Её только после реализыции поддержки HTTPS будем блокировать.

**Comment by Alex-302** [comment]
добавил
||debojuagug1sf.cloudfront.net^$empty
