### ISSUE TITLE
coub.dirty.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1569]
При попытке проиграть коуб (например https://coub.dirty.ru/pylesos-1005062/) плеер не реагирует на клики при включенном Адгарде.

http://forum.adguard.com/showthread.php?9182

**Comment by ameshkov** [comment]
Проблема в блокировке вот этого запроса:
[url]http://coubsecureassets-a.akamaihd.net/assets/adfox.asyn.code.ver3-2ac82101515cb4971a2e2f05df26c29d.js[/url]

Правило, которое решает проблему:
@@||coubsecureassets-a.akamaihd.net/assets/

**Comment by Alex-302** [comment]
Добавил в английский

**Comment by Bohdan-SUP** [comment]
http://www.yaplakal.com/forum28/topic1318618.html
при отключении Русского фильтра - нормальное отображение страницы, при отключении Английского - проигрывается видео от Coube:
http://prntscr.com/a5o8ij

При включенных фильтрах (неправильное отображение):
http://prntscr.com/a5o917

**Comment by Alex-302** [comment]
На форуме отписал, ещё один адрес разблокировал.
