### ISSUE TITLE
[iOS] www.imore.com - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1572]
Missed ad on page:
http://www.imore.com/how-block-ads-your-iphone-or-ipad

![image](https://cloud.githubusercontent.com/assets/15856304/13104235/8bda120c-d564-11e5-8206-0e62f029897d.png)

FAX-228-30964

**Comment by Alex-302** [comment]
I don't see this ad. Without Adguard Google ads here. Where does he live?

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/13859091/5852c31a-ec8a-11e5-8e54-9f9acbc37290.png)
US

**Comment by Alex-302** [comment]
added to English filter
imore.com##div[class^="zone"] > a > img
