### ISSUE TITLE
libertyalliance.com - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1573]
![image](https://cloud.githubusercontent.com/assets/15856304/13104965/2b22f3c0-d569-11e5-9e9e-625ee9fca661.png)

The same "sponsored content" as [here](https://github.com/AdguardTeam/ExperimentalFilter/issues/1426)

**Comment by Alex-302** [comment]
added
libertyalliance.com#%#Object.defineProperty(window, 'zy', { get: function() { return {}; } });
libertyalliance.com##.textwidget .zone .nb
