### ISSUE TITLE
sportmediaset.mediaset.it - videos won't play

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1574]
The [link](http://www.sportmediaset.mediaset.it/video/calcio/1_gol_serie_a/fiorentina-inter-2-1_75447-2016.shtml).

I would like to point out that with the application open you can not view the videos. with the application turned off instead of videos you see properly, there must be some problem with the old advertisement filter. the browser you use is Cm browser with a z3 compact and the web address with the reported problem is the following:http://www.sportmediaset.mediaset.it/video/calcio/1_gol_serie_a/fiorentina-inter-2-1_75447-2016.shtml

  "enabledFilterIds" : [ 2, 3, 4, 5, 10, 1, 6, 11, 104 ], HQ mode.

**Comment by Alex-302** [comment]
Added
@@||video.bal.ad.dotandad.com/mediamond_vm.jsp$domain=video.mediaset.it
