### ISSUE TITLE
seedoff.tv - popups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1577]
Вашу блокировку учатся обходить. конкретно на сайте seedoff.tv при клике на подраздел открывается новый браузер с рекламой типа игрового казино или другая чушь

идет перенаправление с категорий
http://prntscr.com/a4cwva
http://prntscr.com/a4cuhq

**Comment by Alex-302** [comment]
||cf-track.info^$popup
