### ISSUE TITLE
[iOS] baskino.club - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1578]
http://baskino.club/serial/12620-oblasti-tmy.html
http://prntscr.com/a4cre7

**Comment by Alex-302** [comment]
Добавил в русский
||getelem.ru^$third-party

**Comment by evgeniy-ADG** [comment]
Снова пропущено
@Serzh-SUP можешь скрин запилить?

**Comment by Alex-302** [comment]
||bold-in.ru^$third-party
