### ISSUE TITLE
newnavitel.blogspot.ru - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1579]
С включённым Adguard пропадают ссылки на скачивание скинов.

http://newnavitel.blogspot.ru/p/skin_6617.html

при включенном Английском фильтре:
http://prntscr.com/a4ca0z

при отключении фильтра:
http://prntscr.com/a4cabp

**Comment by Alex-302** [comment]
Добавил в русский
newnavitel.blogspot.ru#@##AdSense1
