### ISSUE TITLE
www.birminghammail.co.uk - anti adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1580]
http://www.birminghammail.co.uk/sport/football/football-news/aston-villa-birmingham-city-players-10891085

![image](https://cloud.githubusercontent.com/assets/15856304/13107767/f03167ba-d577-11e5-8795-ee842c59e88f.png)

PXQ-345-52500

**Comment by Vincent-Michael** [comment]
try:

birminghammail.co.uk#%#window.checkState = function() {};

**Comment by Alex-302** [comment]
added
