### ISSUE TITLE
alpha.lanet.tv - playback issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1582]
В общем, да, прерывается при воспроизведении. Сайт сам сильно альфа, но с нами - прерывается звук.

Доступно лишь в Украине и только в сети Lanet. Что нужно, чтобы решить вопрос?

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Пусть попробуют выключить все фильтры, оставив включенной саму защиту. Если проблема останется - то либо сам сайт не допилили, либо баг(менее вероятно).
Видео по какому протоколу?

**Comment by evgeniy-ADG** [comment]
попробую - отпишусь.
![image](https://cloud.githubusercontent.com/assets/15856304/13176345/3a903392-d71a-11e5-8583-51a4ee47e8fd.png)

**Comment by evgeniy-ADG** [comment]
У меня уже все ок. Странно, вчера рили прерывалось :)

**Comment by Alex-302** [comment]
Закрываю тогда.
