### ISSUE TITLE
Problem with ad filtering in apps (Speedtest Master)

### ISSUE THREAD

**Issue by Dariamag** [AdguardTeam/ExperimentalFilter#1585]
Android user has Premium license but claims that ads are not filtered in some apps.
Here is one if them: Speedtest Master (https://play.google.com/store/apps/details?id=com.quickbird.speedtestmaster)

Ads:
https://scontent-frt3-1.xx.fbcdn.net/hphotos-xfp1/v/t34.0-12/12736377_571438239680448_867429977_n.jpg?oh=3509ae4749d021baf310a2336ad47d1b&oe=56C8145F

https://scontent-frt3-1.xx.fbcdn.net/hphotos-xtp1/v/t34.0-12/12721923_571438246347114_1793027479_n.jpg?oh=31121f1d85b463d48279e6a29bd014c3&oe=56C85398

**Comment by Alex-302** [comment]
уже оказывается есть задача
https://github.com/AdguardTeam/ExperimentalFilter/issues/1567
здесь закрою
