### ISSUE TITLE
http://fast-bit.org - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1586]
реклама на зеркалах сайта rutor.org (в данный момент http://fast-bit.org) как на самой странице, так и в виде открывающихся дополнительных окон. Фильтры адгарда свежие, сжатие трафика в хроме не включено. Уровень логгирования выставлен специально - записывать всё.
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13139114/9a411aaa-d633-11e5-81c5-3a8991c31ba6.png)
</details>
PZH-284-78606

**Comment by Alex-302** [comment]
на этот домен зайти не могу, на другое зеркало перебрасывает.

**Comment by evgeniy-ADG** [comment]
У меня уже тоже.

**Comment by Alex-302** [comment]
Уточни у юзера, может фильтры старые. Официальные зеркала обычно используют одинаковые рекламные домены.

**Comment by paskardv** [comment]
Фильтры актуальные, проблема не в фильтрах. Просто спкстя какое то время (неделя, две непрерывной работы - не удалось установить точно причины и зависимости) отключается фильтрация рекламы. Выключение и включение защиты не помогает, только ребут устройства. Возможно, это какая то проблема в долгой работе vpn на самом планшете, не знаю. 
Обсуждение на 4pda http://4pda.ru/forum/index.php?showtopic=601691&view=findpost&p=47175825

**Comment by Alex-302** [comment]
Тогда данная проблема не для этого раздела.
Можете отписать сюда:
https://github.com/AdguardTeam/AdguardForAndroid/issues

**Comment by paskardv** [comment]
Раздел не я определяю, если проблема попала не в тот раздел - переместите в 
нужный, зачем закрывать?

Отправлено из AquaMail для Андроида
http://www.aqua-mail.com


Alex <notifications@github.com> 29 февраля 2016 г. 18:37:08 написал:
