### ISSUE TITLE
appdn.net - anti-adblock

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1589]
Currently there is an $elemhide rule in the EasyList, but it's not enough.

There're two options.
1. Remove $elemhide rule and block anti-adblock message
2. Remove $elemhide, use $generichide instead and add two rules below:
```
@@||appdn.net/wp-content/plugins/chilly-pot/assets/js/advertisement.min.js
@@||advert-serv.johnmorris.me/adserver/adlogger_tracker.php
```

**Comment by Alex-302** [comment]
Third solution:
```
appdn.net#%#AG_onLoad(function() { closeAdbuddy(); }); 
```
Added:
```
@@||appdn.net/wp-content/plugins/chilly-pot/assets/js/advertisement.min.js
@@||appdn.net^$generichide 
```
removed:
```
@@||appdn.net^$elemhide
```
This rule is unnecessary
@@||advert-serv.johnmorris.me/adserver/adlogger_tracker.php
