### ISSUE TITLE
torrentfx.ru - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1591]
http://torrentfx.ru/filmy/trillery/7643-i-gryanul-shtorm-2016-webrip.html

у меня такой баннер поверх страницы и никуда не деться, снизу еще реклама
http://prntscr.com/a4s4to

DYG-122-19588

**Comment by Alex1188** [comment]
Если речь про Андроид, то добавил
```
||torrentfx.ru/templates/torrentfx/js/admitads.js
```

**Comment by Alex-302** [comment]
Если речь про Андроид, то добавил
```
||torrentfx.ru/templates/torrentfx/js/admitads.js
```
