### ISSUE TITLE
[Stealth Mode] can't login on gitter.im through github.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1592]
Пользователь не может авторизоваться в gitter.im через github.com
помогает снятие опции "Блокировать сторонние куки"

[Скринкаст](https://cloud.mail.ru/public/DKxQ/CnxFyy7Zj)

VBP-252-78222

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Добавил
```
@@||github.com/login/
@@||github.com/login?
```
Передай на проверку. Жду ответа.

**Comment by Alex-302** [comment]
Если работает - закрывай.
Только метку Fixed поставь, чтоб не путалось с закрытыми по иным причинам.
