### ISSUE TITLE
[Stealth Mode] 'Hide your IP' blocks access to the site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1594]
http://www.kerio.ru/
http://prntscr.com/a4tlva

![image](https://cloud.githubusercontent.com/assets/15856304/13145017/9bde8866-d656-11e5-8b77-a7dc28e3e00e.png)

HSY-299-42770

**Comment by Alex-302** [comment]
Здесь только весь сайт исключать
```
@@kerio.ru^
```
В будущем появится возможность менять IP

**Comment by Bohdan-SUP** [comment]
Another one:
https://www.origin.com/ru-ru/store/
http://prntscr.com/a5noa8

**Comment by Alex-302** [comment]
Аналогичная проблема. Либо ждать добавления вышеописанной функции, либо выключить сокрытие IP. Или сайты в исключения добавить
@@||origin.com^
