### ISSUE TITLE
fishki.net - some functions are broken

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1595]
Не работают тесты на fishki.net , по типу таких http://fishki.net/1853151-test-kakoj-zhe-u-vas-psihologicheskij-vozrast-10-voprosov.html

http://prntscr.com/a4u7x3

Помогает приостановление защиты

EDZ-965-27271

**Comment by Alex-302** [comment]
Добавил.
