### ISSUE TITLE
[Windows] www.tweaktown.com - Rule load not

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1596]
Rule does not load in english filter:
```
||tweaktown.com/xyz?p=
```
Rule only works in user filter ...
I use 1:1 same filter.

Only English filter:
![](http://i.imgur.com/Do2ACjX.png)

With user filter:
![](http://i.imgur.com/2cG2J8g.png)

**Comment by Alex-302** [comment]
please, check for updates. This rule is really in English filter.

**Comment by Vincent-Michael** [comment]
apparently now fixed ... i saw before few days because somehow whitespace @Alex-302
