### ISSUE TITLE
[Windows] www.cityam.com - Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1597]
![](http://i.imgur.com/JoaJWYr.png)
http://www.cityam.com/234921/eu-referendum-prime-minister-david-cameron-says-he-will-be-batting-for-britain-at-two-day-make-or-break-european-council-meeting

**Comment by Alex-302** [comment]
Added
```
cityam.com#%#Object.defineProperty(window, 'isAdBlockOn', { get: function() { return function() { }; } }); 
```
