### ISSUE TITLE
[Stealth mode] can't access the site with a social network wneh 'block third-party cookies' is enabled

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1598]
При авторизации из соц сетей
https://ru.wargaming.net/id/signin/?next=/id/openid/447720239674880972/&trust_root=https%3A//worldoftanks.ru/#
http://prntscr.com/9l4yhf

HJO-758-38537

**Comment by Alex-302** [comment]
@evgeniy-ADG 
какой способ авторизации? И повторяется ли без блокировки куков?

**Comment by Bohdan-SUP** [comment]
любой способ авторизации (лог/пароль, соц сети)
При отключении "Блокировать куки" проблема исчезает.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
У нас не повторилось.
У юзера английский фильтр включен?

**Comment by Bohdan-SUP** [comment]
Английский фильтр на ситуацию не влияет.
Помогает @@||ru.wargaming.net^$stealth

**Comment by Alex-302** [comment]
ок, добавил
