### ISSUE TITLE
[Windows][Chrome] www.wired.com - Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1599]
![](http://i.imgur.com/0ZWHbqp.png)
http://www.wired.com/2016/02/youre-probably-listening-to-spotify-wrong-be-a-power-user/

Script:
"http://www.wired.com/assets/load?scripts=true&c=1&load%5B%5D=jquery,cn-library,cn-mobile,jquery-devices,cn-events,cn-fe-stats-omniture-scode,cn-fe-stats-omniture,cn-fe-ecom,cn-fe-ecomfw,cn-fe-promotheus,cn-fe-ads-dart-bundled,plugin-global-min,wired-reviews-nav&ver=1455828505"

I use current:
wired.com#%#window.sniffAdBlock = function() {};

Note:
http://forum.adguard.com/showthread.php?9233-Resolved-wired-com-Adblock-detection
this help only for me on firefox
(maybe again some rules are removed)

**Comment by Alex-302** [comment]
Thanks for information:)
Old rules replaced by
```
wired.com#%#Object.defineProperty(window, 'sniffAdBlock', { get: function() { return function() { }; } });
```
