### ISSUE TITLE
[Windows] www.theguardian.com - Anti Adblock Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1600]
![](http://i.imgur.com/FvqXDbK.png)
http://www.theguardian.com/international

Script:
"https://assets.guim.co.uk/javascripts/0f120a372bdf0816c96f6e635765a9eb/app.js"

i try current:
theguardian.com#@#.ad_unit

**Comment by Alex-302** [comment]
thanks, added
