### ISSUE TITLE
[Windows] http://www.newpct.com/ http://www.newpct1.com/

### ISSUE THREAD

**Issue by Aokromes** [AdguardTeam/ExperimentalFilter#1602]
Browser: Opera 37.
OS: Windows 10.
Adguard: 6.0.189.984

They have added overlays stopping access to adguard shield so it's hard to add new rules to block popups on click, also clicking some links opens new unwanted pages before you can reach legit domain.

**Comment by Alex-302** [comment]
I need the screenshot? I have no problems with assistant 
http://imagizer.imageshack.com/img924/5530/yjEOBV.jpg

**Comment by Aokromes** [comment]
http://i.imgur.com/yAZfdEo.jpg
NSFW link when i try to click shield: http://i.imgur.com/9L5iMng.jpg

**Comment by Vincent-Michael** [comment]
try:
For popups:
```
||d29lpg037v41oq.cloudfront.net$domain=newpct.com|newpct1.com
```
For idiot test:
```
newpct.com###content-trailer > div > div > div[style="z-index:98;width:300px;height:250px;position:absolute;top:90px;left:150px;"]
newpct1.com##.entry-right > div > div > div[style="z-index:98;width:300px;height:250px;position:absolute;top:85px;left:140px;"]
```

**Comment by Alex-302** [comment]
thanks
added:
```
||d29lpg037v41oq.cloudfront.net^$domain=newpct.com|newpct1.com
||s3.amazonaws.com/*/secure.js$domain=newpct.com|newpct1.com
||albopa.work^$third-party
```
