### ISSUE TITLE
No assistant at mvideo.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1605]
http://www.mvideo.ru/avtoakustika/avtomagnitoly-224/f/category=avtomagnitoly-s-navigaciei-1255
http://prntscr.com/a5mcc0
EKI-185-16454

**Comment by Vincent-Michael** [comment]
blame rule "@@||mvideo.ru^$document" in russian filter

**Comment by Alex-302** [comment]
@Bohdan-SUP 
there is no other way to fix the filter on the left side
http://www.mvideo.ru/televizory-i-cifrovoe-tv/televizory-65
