### ISSUE TITLE
[Windows] www.netzwelt.de - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1609]
![](http://i.imgur.com/6RiDI0U.png)
http://www.netzwelt.de/samsung-galaxy-s7/157405-galaxy-s7-saturn-prospekt-zeigt-geheimes-samsung-smartphone.html

I try current:
||widgets.outbrain.com/outbrain.js$domain=netzwelt.de

**Comment by Alex-302** [comment]
Added, but I don't see this Ad.
