### ISSUE TITLE
www.dnsleaktest.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#161]
С включенным Adguard не показывает результаты теста. 

ULV-905-64462

**Comment by Alex-302** [comment]
Проверь вот такое правило:
@@||dnsleaktest.com^$content,jsinject,elemhide

**Comment by vbagirov** [comment]
Работает, в ЭФ занесешь?

**Comment by Alex-302** [comment]
Работает только если добавляешь правило, или без него тоже? В фильтр не добавлял.
