### ISSUE TITLE
[Windows] www.creativeuncut.com - Anti Adblock Script / Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1610]
![](http://i.imgur.com/n3Giqo8.png)
http://www.creativeuncut.com/gallery-01/ff7-tifa.html

![](http://i.imgur.com/zzIuUsJ.png)
http://www.creativeuncut.com/gallery-01/ff7-tifa.html

![](http://i.imgur.com/SglGQ5v.png)
http://www.creativeuncut.com/

I use current:
For skip countdown page:
```
||creativeuncut.com/int/interstitial.js
```

For  Anti Adblocker message:
```
creativeuncut.com###g_abox
creativeuncut.com###abox-s_i
```

**Comment by Alex-302** [comment]
thanks.
The first rule is added to English filter, other - to Experimental, because this message doesn't break the page.
