### ISSUE TITLE
google.com - missed ads on iOS

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1619]
Ads are missing on both iPad and iPhone, but not on OS X.

A message from customer:
> Here are a couple of screenshots that show ads when doing a search on Google's website on iOS. These occur regardless of whether or not you use the URL bar to search. The first screenshot is a search done on the mobile version of the website and the second is a search done in desktop mode. I cut off the second screenshot on purpose since it lists locations nearby (for privacy reasons) but as you can see there is also an ad on the right side of that screenshot with the same yellow "Ad" marker.

**Comment by ameshkov** [comment]
![image1](https://cloud.githubusercontent.com/assets/5947035/13235633/09dec264-d9d0-11e5-93da-ed73e0926b79.png)
![image2](https://cloud.githubusercontent.com/assets/5947035/13235636/0ae773e0-d9d0-11e5-85fc-a86f19ff9670.png)

**Comment by ameshkov** [comment]
Closing this as a duplicate

**Comment by ameshkov** [comment]
Ok I was wrong, here is the problem:
```
@@||www.google.*/search?$subdocument,~third-party
```

Again, subdocument...

**Comment by evgeniy-ADG** [comment]
QMV-889-65305

> I updated my filters - even removed and added them again - and am still seeing ads on Google. Screenshot attached. 

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13700071/4889fa8c-e787-11e5-8fd9-7f7f67858687.png)
