### ISSUE TITLE
[iOS] gaeubote.de

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1621]
gaeubote.de - KVO-325-70603
![image1](https://cloud.githubusercontent.com/assets/14153331/13236348/682dc95e-d9cc-11e5-9435-7892ec36adc4.JPG)

**Comment by Alex-302** [comment]
Added to German filter:
```
gaeubote.de##.werbung_oben_rechts
```
Cookie notification is blocked in Experimental filter
