### ISSUE TITLE
TubeMate-missed ads again

### ISSUE THREAD

**Issue by Buratino22** [AdguardTeam/ExperimentalFilter#1622]
http://4pda.ru/forum/index.php?showtopic=190669

http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=44447108

**Comment by Buratino22** [comment]
[``]( #url)

**Comment by Alex-302** [comment]
Не повторяестя. Нужен свежий лог HTTP-запросов с точным временем появления рекламы. Перед снятием лога нужно вычистить кэш приложения.

**Comment by Buratino22** [comment]
Отправил "чистый"лог,  Номер заявки: QSB-266-88695
Три раза запускал приложение с очисткой кэша-на втором вылез баннер..

**Comment by Bohdan-SUP** [comment]
Новый лог - SEK-868-60356

**Comment by Alex-302** [comment]
@Bohdan-SUP 
не вижу лога. В какой он системе? Время появления рекламы не указано?

**Comment by ameshkov** [comment]
Here is a rule:
```
||tm1.hoiplay.com^
```

**Comment by Alex-302** [comment]
added
