### ISSUE TITLE
[Android] AdWords app

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1623]
https://play.google.com/store/apps/details?id=com.google.android.apps.adwords
You get a connection error.
Logs are here - MOV-337-57825

**Comment by Alex-302** [comment]
@Bohdan-SUP 
передай, чтоб попробовал в файерволе выключить фильтрацию приложения. Если не поможет - пусть там же щёлкнет по приложению и запишет имя пакета(package name) и введёт его в pref.net.exclusions. Правил-исключений не будет, т.к. гугловая реклама разблокируется.

**Comment by evgeniy-ADG** [comment]
написал.

**Comment by evgeniy-ADG** [comment]
> Если отключить то запускается, запись в низкоуровневых настройках не помогла.
> При vpn фильтрации не работает, а при http работает...

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Т.к. прога для работы с рекламой, то лучше её исключить из фильтрации.
Запили плиз в дроидовом разделе запрос на исключение.

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/327

**Comment by Alex-302** [comment]
Спасибо. Здесь тогда закрываю.
