### ISSUE TITLE
google.com - when useful ads filter is enabled, click on a contextual ad leads to "about:blank"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1626]
http://forum.adguard.com/showthread.php?9242-Filter-quot-Useful-Ads-quot-seems-to-not-be-working-on-my-iPad-air-2

**Comment by Alex-302** [comment]
can't reproduce on Mac OS with mobile user-agent

**Comment by ameshkov** [comment]
Seems that the issue is specific to iOS

**Comment by Alex-302** [comment]
ok. moved to Safari filter

**Comment by Alex-302** [comment]
messed  issues:)

**Comment by johnathonm1981** [comment]
Hi,

Is it possible to completely remove the "useful ads" listings from the search results complexly similarly to what is done with the desktop version. It is just polluting the search results for users who do not want those ads at all. This way functionality is mirrored across the platform.

This an iOS issue specific to safari.

JM

**Comment by ameshkov** [comment]
Hm, maybe I didn't get it right in the first place.

"Filter for useful ads" is a filter which **unblocks** contextual ads for all search engines. If you want it to be blocked, do not turn that filter on (it is turned off by default).

**Comment by johnathonm1981** [comment]
That filter is the most confusing of all the filters my friend. Shouldn't read enable useful ads rather then filter useful ads? 

I apologize for the misunderstanding, but that set of filter rules just doesn't make sense.

So my suggestion is to rename that selection to unblock or show useful ads.

Thank you and I take responsibility. I will post it on the forum too.

**Comment by ameshkov** [comment]
I think I understand why you have turned it on before. Due to #1436 google ads were not blocked for some time (until today by the way).

**Comment by johnathonm1981** [comment]
Oh, ok, so there was also a real issue. But I am serious and implore you to change the name of that useful ads setting to make it more obvious that it would "enable" them. In the context of the rest of that menu it would make the most sense that you would turn that on to filter those ads. I simple word change of Enable Useful Filters would go leaps and bounds in making it clear.

Thank you again.

**Comment by johnathonm1981** [comment]
Yeah, that is what was happening in my google searches, funny thing is none of them actually worked if I clicked on them by accident.

**Comment by ameshkov** [comment]
Something like "Unblock Useful Ads Filter"?

**Comment by johnathonm1981** [comment]
I think keep it simple - Enable Display of Useful Ads or Enable to Display Useful Ads, or Exclude Useful Ads from Filters, Something that makes it clear that turning it on will make it obvious this will let the useful ads through. As it reads right now, it reads as if this is what you need to turn on to filter useful ads altogether.
