### ISSUE TITLE
[iOS] www.westernunion.com - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1627]
Incorrect blocking on page:
https://www.westernunion.com/au/en/home.html

We hide the log in block on top
![image](https://cloud.githubusercontent.com/assets/15856304/13262024/790bbf02-da6b-11e5-8c02-cee520673450.png)

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.77.86 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.84 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.67 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.46 Enabled=YES

**Comment by Alex-302** [comment]
added
@@||mpsnare.iesnare.com/snare.js$domain=westernunion.com
should to be checked
