### ISSUE TITLE
[Windows] www.geek.com - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1628]
![](http://i.imgur.com/wikNDTz.png)
http://www.geek.com/mobile/oppo-supervooc-can-recharge-a-phone-in-just-15-minutes-1647990/

I use current:
||cdn.taboola.com/libtrc/ziffdavis-network15-geek/loader.js$domain=geek.com

**Comment by Alex-302** [comment]
added
