### ISSUE TITLE
[Android] dailyuploads.net - pop up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1630]
https://dailyuploads.net/qu87ouaidj4a

a lot of redirections and then this:

![image](https://cloud.githubusercontent.com/assets/15856304/13264541/5a440ff0-da77-11e5-930e-76d7978a5934.png)

"enabledFilterIds" : [ 2, 3, 4, 10, 11 ],

**Comment by Alex-302** [comment]
@evgeniy-ADG 
can't reproduce, but you can try
```
||moboland.net^$empty
```

**Comment by evgeniy-ADG** [comment]
it helped with that particular page but her's another one: http://
revclouds.com/i3jwheubctat

**Comment by Alex-302** [comment]
added
+
||cloudfront.net/?$domain=revclouds.com
||s3.amazonaws.com/*/secure.js$domain=newpct.com|newpct1.com|revclouds.com

**Comment by Alex-302** [comment]
They can't work on Android, because HTTPS
