### ISSUE TITLE
[Stealth mode] can't access support.apple.com with 'hide your IP' enabled

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1633]
http://prntscr.com/a7e214

the [link](https://support.apple.com/en-us/HT202039)

**Comment by Alex-302** [comment]
I can't resolve this. Maybe fake IP is blacklisted.
Please file a bug in AdguardForWindows

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/AdguardForWindows/issues/906
