### ISSUE TITLE
[Stealth Mode] yandex self-advert remains after being closed

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1636]
![image](https://cloud.githubusercontent.com/assets/15856304/13298690/7ebf43ee-db40-11e5-8cbc-048ce68accde.png)

SOU-481-28289

**Comment by Alex-302** [comment]
Фильтры бы попросили. Надоедливую саморекламу только в ЭФ блокируем. Нужно его включить.

**Comment by evgeniy-ADG** [comment]
Спросил. Так дело в том, что оно снова вылазит, если его скрыть. Вроде бы, должнобыть так, что раз скроешь и оно скроется, не?.. Как у нас на сайте с желтой плашкой Адгард 6.

**Comment by Alex-302** [comment]
ЭФ включить надо чтоб убрать этот баннер.
Если закрыть, то не появится только если данные браузера не очишать. С блокировкой кук антитрекингом  и без ЭФ у меня баннер не появляется.

**Comment by evgeniy-ADG** [comment]
Порешали отключением фильтра полезной рекламы Х(

**Comment by Alex-302** [comment]
странно. Ну ок
