### ISSUE TITLE
[Mac] ntv.ru video player

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1637]
http://www.ntv.ru/novosti/1607198/
1. Go to page -> click on "play" -> get the 'loading' -> click again and the video starts.
2. Disabling Ad Blocker helps immediately.

Adguard 1.2.0, OS X: 10.11.3, Safari: 9.0.3, works fine in Chrome.
I wasn't able to reproduce it on my side.
Logs here - MGD-118-37778

**Comment by Alex-302** [comment]
Can't reproduce too, with user's filters.
