### ISSUE TITLE
unbiased.co.uk - links don't work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1639]
https://www.unbiased.co.uk/advisers/financial-adviser/hebrides#/4432390

**Comment by Alex-302** [comment]
added to spyware filter
```
@@||googletagmanager.com/gtm.js$domain=unbiased.co.uk
```

**Comment by ameshkov** [comment]
How many issues do we have with Google tag manager?
Maybe we should simply remove this rule?
