### ISSUE TITLE
Adguard blocks authorization on https://popsters.ru/#/vk

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1643]
Our users complained that our app doesn`t work with turned on AdGuard.
We use OAuth authorization using social media in our tool and AdGuard
blocks widjets.
So, we don`t have any ads in our tool.
Our tool:
https://popsters.ru/
https://popsters.us/
Pages with that problems:
https://popsters.ru/#/vk
https://popsters.us/#/vk (fb, pn, cb, fk, yt and other similar pages)

WWW-462-71677

**Comment by Alex-302** [comment]
added
```
@@||vk.com/widget_auth.php
```
removed
```
~vk.com,~vkontakte.ru###vk_auth
```
