### ISSUE TITLE
http://market.yandex.ua/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1644]
![image](https://cloud.githubusercontent.com/assets/15856304/13336163/54cb6dbe-dc1d-11e5-856d-451aacdf18d4.png)

у меня птворяется, базовый набор фильтров.

GKY-758-61520

**Comment by Alex-302** [comment]
рекламный домен полностью блокируем, т.к. https. После выхода версии с его поддержкой, можно будет. Пока закрою.
