### ISSUE TITLE
[iOS] lockerdome.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1645]
The website does not load at all -- it is literally blank with Adguard enabled.
Logs here - DOU-166-28694

**Comment by Alex-302** [comment]
looks like a bug
https://github.com/AdguardTeam/AdguardForWindows/issues/910
temporary solution for user:
```
@@||lockerdome.com^$domain=lockerdome.com
```

**Comment by Alex-302** [comment]
Old rule is replaced by
||lockerdome.com^$domain=~lockerdome.com
