### ISSUE TITLE
[Windows] www.inside-handy.de - false positive

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1648]
![](http://i.imgur.com/ALiH9aU.png)

Rule ".gif|$popup,domain=autozeitung.de|formel1.de|fremdwort.de|inside-handy.de|motorsport-total.com|news.de|seniorbook.de" kill current logo from page

**Comment by Alex-302** [comment]
Added
@@||cdn.inside-handy.de/ih/top/
