### ISSUE TITLE
[Android] spiegel.de and sueddeutshe.de

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1649]
spiegel.de 
![screenshot_2016-02-26-13-01-32_kindlephoto-1752989](https://cloud.githubusercontent.com/assets/14153331/13372045/1cebf026-dd3f-11e5-8d12-527a51a36ca8.jpg)

sueddeutshe.de
![screenshot_2016-02-26-13-12-46_kindlephoto-2631070](https://cloud.githubusercontent.com/assets/14153331/13372043/15cca2cc-dd3f-11e5-99cc-11087e1f1ab8.jpg)

Requester - DCS-552-57245

**Comment by Alex-302** [comment]
spiegel.de  - these icons - just links to their blogs, so we don't block them
for sueddeutshe.de added
```
sueddeutshe.de##li[onclick^="window.open('https://www.facebook.com/sharer/sharer.php"]
```
if you want to remove it, add
```
sueddeutshe.de###article-sidebar-wrapper
```
