### ISSUE TITLE
chia-anime.tv - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1656]
![image](https://cloud.githubusercontent.com/assets/15856304/13378371/19f39bc0-de0d-11e5-9439-5591865e518e.png)

the [link](http://www.chia-anime.tv/ixion-saga-dt-episode-12-english-subbed/)

**Comment by Alex-302** [comment]
added
chia-anime.com##div#aad > *
