### ISSUE TITLE
[iOS] m.yingshidaquan.cc - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1658]
The [link](http://m.yingshidaquan.cc/index.php)
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13378469/939a13b6-de10-11e5-97bc-664d2f56ba20.png)
</details>

the [link](http://m.yingshidaquan.cc/index.php)
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13378474/bdce7438-de10-11e5-8d99-40e4ee1d93b5.png)
)
</details>

IOV-758-65096

**Comment by Alex-302** [comment]
1. Added to mobile filter for the first banner:
```
m.yingshidaquan.cc##.topmessage
```
I don't see onher banners.
2. 
```
m.yingshidaquan.cc##.banner
```
