### ISSUE TITLE
[iOS] 770ww.com - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1660]
[http://www.770ww.com](http://www.770ww.com)
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13378506/7ee37cd6-de11-11e5-9d6d-d5e944a05a24.png)
</details>

[http://www.770ww.com/html/article/170634.html](http://www.770ww.com/html/article/170634.html)
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13378509/93139eca-de11-11e5-8fa0-3ffee2e02b57.png)
</details>

GMU-623-70423

**Comment by Alex-302** [comment]
added
||470kk.com/js/indextop.js
||470kk.com/js/config.js
