### ISSUE TITLE
[iOS] wapbaike.baidu.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1663]
The [link](http://wapbaike.baidu.com/view/17387.htm?adapt=1&fr=aladdin)

![image](https://cloud.githubusercontent.com/assets/15856304/13378573/275d3914-de13-11e5-828e-8ba32989b7d2.png)

GMU-623-70423

**Comment by Alex-302** [comment]
added
wapbaike.baidu.com##a[onclick^="Mixedor.mixedOpen"]
