### ISSUE TITLE
http://ivbt.ru/ - assistant is disabled on the site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1665]
http://ivbt.ru/viewtopic.php?t=238028
Не отображается помощник на сайте

Не открывается вкладка с скриншотами
http://prntscr.com/a8kvc6
Помогает отключение "Фильтра счетчиков и аналитики"
http://prntscr.com/a8kv2e

JXC-664-48426

**Comment by Alex-302** [comment]
проблема в русском. Убрал
ivbt.ru#%#function setTimeout() {};

**Comment by Alex-302** [comment]
Помощник у меня отображается.
