### ISSUE TITLE
http://www.transport.md/main.asp - no assistant, missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1668]
![image](https://cloud.githubusercontent.com/assets/15856304/13378838/21123c40-de1c-11e5-845b-3a2e472f6377.png)

YLQ-575-58516

**Comment by Alex-302** [comment]
добавил
transport.md##a[href^="/banner_sys/"]
||transport.md/banner_sys/
