### ISSUE TITLE
[iOS] forbes.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1671]
http://www.forbes.com/forbes/welcome/#5a1aa41d30c6
![image](https://cloud.githubusercontent.com/assets/14153331/13379734/9c95f144-de36-11e5-867e-c50cbdf4db04.png)
![image](https://cloud.githubusercontent.com/assets/14153331/13379737/a5110a8e-de36-11e5-91f4-4e20ac3a6902.png)
APU-309-11326

**Comment by Alex-302** [comment]
We can't block them in Safari, because adblock detection here.
