### ISSUE TITLE
www.vogue.it

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1673]
the [link](http://www.vogue.it/en/uomo-vogue/beauty/2013/05/profumi-maggio-#ad-image270927)

Can't go to the next image:

![image](https://cloud.githubusercontent.com/assets/15856304/13382688/bcc53a90-de83-11e5-8afd-4cc6cb04719b.png)

Most likely, EasyList Italy is a culprit here.
UPD. No, it's not.

**Comment by Alex-302** [comment]
added

**Comment by evgeniy-ADG** [comment]
не работает.

**Comment by Alex-302** [comment]
не то закрыл:)

**Comment by Alex-302** [comment]
added to Spyware filter
@@||googletagmanager.com/gtm.js$domain=vogue.it
