### ISSUE TITLE
[iOS] Missed Ads optwear.ru/forum/

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1675]
**Пропущена реклама на http://www.optwear.ru/forum/**
Такая же история и на Windows. Реклама пропущена и нет помощника.

![img_1949 png](https://cloud.githubusercontent.com/assets/16462533/13393676/b365a3fa-deeb-11e5-9e82-27968e0f77ac.jpg)

**Comment by Alex-302** [comment]
из-за этого не блокируется
https://github.com/AdguardTeam/ExperimentalFilter/issues/690
Исключение убрал, завтра нужно будет уточнить у юзера из #690 про работоспособность сайта после обновления фильтровю


Добавил:
optwear.ru##a[onclick^="countAdClick"]

**Comment by Serzh-SUP** [comment]
@Alex-302 фильтры обновил и на ios и на win все также.

**Comment by Alex-302** [comment]
@Serzh-SUP 
Покажи скрин. Там один баннер их, с описанием как заказывать.

**Comment by Alex-302** [comment]
Альфа-версия вроде блокирует.

**Comment by Serzh-SUP** [comment]
Скрин с Винды.
![img_8753](https://cloud.githubusercontent.com/assets/16462533/14844761/6bb1fb9a-0c62-11e6-8031-ffad94f284da.JPG)

**Comment by Alex-302** [comment]
в высшей мере странно. Уж директ-то должен блокироваться. Баннеры сверху скрыты правилом
`optwear.ru##a[onclick^="countAdClick"]`
Можно через тимвивер глянуть?

**Comment by Serzh-SUP** [comment]
@Alex-302 
Это правило все убрало!

**Comment by Alex-302** [comment]
оно же в русском фильтре
