### ISSUE TITLE
tv-mir.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1679]
http://tv-mir.net/60-khl.html

http://prntscr.com/a9brjs
http://prntscr.com/a9br9n

**Comment by Alex-302** [comment]
||mytomatosoup.com^$third-party
||binpartner.com/branding/$third-party

**Comment by Serzh-SUP** [comment]
У этого же пользователя.
Реклама на:
http://present-dv.ru/

**Comment by Alex-302** [comment]
present-dv.ru##.banner-group
present-dv.ru##body > div.layout-container > div.layout-pub
