### ISSUE TITLE
[Android] WomanLog app

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1680]
https://play.google.com/store/apps/details?id=com.womanlog
Logs here - JRH-422-45848
<details>
![2016-02-26 07 22 56](https://cloud.githubusercontent.com/assets/14153331/13413811/2e960b90-df56-11e5-8bc8-f6c08f21df63.jpg)
![2016-02-26 07 22 41](https://cloud.githubusercontent.com/assets/14153331/13413812/2e98af1c-df56-11e5-8c55-bb582391bbe4.jpg)
</details>

**Comment by Alex-302** [comment]
Фейсбучная. Надо ждать версии с поддержной https

**Comment by Alex-302** [comment]
альфа-версия блокирует
