### ISSUE TITLE
ABP Japanese breaks Google Music

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1686]
STR
1. Go to AdGuard settings
2. Turn Ad Blocker - ABP Japanese Filters ON
3. Login to https://play.google.com/music/
4. Select any song you like and press PLAY

AR - 
![1](https://cloud.githubusercontent.com/assets/14153331/13437565/9754ebfa-dfed-11e5-95e9-fc24bf25d515.png)
![2](https://cloud.githubusercontent.com/assets/14153331/13437566/975523f4-dfed-11e5-879e-50ad6be08c86.png)

**Comment by Alex-302** [comment]
need remote access. I don't have account and valid credit card for register.

**Comment by Alex-302** [comment]
added to exclusion list for this filter
@@|http:*?*&ip=$domain=play.google.com
