### ISSUE TITLE
[Windows] www.mimikama.at - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1687]
![](http://i.imgur.com/1BMVKiw.png)
http://www.mimikama.at/allgemein/vorsicht-offizielle-warnung-vor-computervirus-locky-ist-selber-ein-trojaner/

I use current:
```
||static.plista.com/async.js$domain=mimikama.at
```

**Comment by Alex-302** [comment]
added
