### ISSUE TITLE
http://www.sdarot.pm/ - missed popup

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1688]
![image](https://cloud.githubusercontent.com/assets/15856304/13469230/19536868-e0af-11e5-9f39-367cf40b0898.png)

Если нажать на текстовку/кнопки, то раз через раз вылазит какое-то окно (перенаправление, как пишет пользователь)

VJD-966-16209

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Не понятно что он прямоугольником выделил, и что стрелкой. Sdarot нажимал - открывается этот же сайт, а если картинку левее - то другой сайт. Уточни что он имеет в виду.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
bump

**Comment by evgeniy-ADG** [comment]
это я выделил ) это у меня повторилось. жмешь на тот СТАРДОСТ и выскакивает попап

**Comment by Alex-302** [comment]
добавил
||treemedia.co.il/sdarot2
