### ISSUE TITLE
[Windows] bessporno.tv - missed popup

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1690]
При нажатии на видео по ссылке: bessporno.tv вылетает рекламное окно.
Фильтры базовые. Проверено.

**Comment by Alex-302** [comment]
добавил
bessporno.tv#%#window.eval = function() {};
||temphilltop.net^$third-party

**Comment by lost2020** [comment]
алекс
реклама у видео при начале в каждом на этих сайтах также
https://topporno.tv/new-videos
https://bessporno.tv
https://hotfiesta.tv/last

**Comment by Alex-302** [comment]
два заблокированы. Остальные поправил.
