### ISSUE TITLE
[Windows] world-art.ru missed ads

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1691]
Пропущена реклама на http://www.world-art.ru/animation/rating_top.php
Скриншот: http://f2.s.qip.ru/Ogbqir4V.png

**Comment by Alex-302** [comment]
добавил
world-art.ru##table[width="1000"][height="256"] > tbody

**Comment by Bohdan-SUP** [comment]
http://www.world-art.ru/animation/rating_top.php
http://prntscr.com/ak6ms3

**Comment by Alex-302** [comment]
заменил на 
```
world-art.ru##noindex > table[height="251"]
```
