### ISSUE TITLE
[Windows] www.pcgamesn.com - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1692]
![](http://i.imgur.com/ql1TgJO.jpg)
http://www.pcgamesn.com/

I use current:
```
||cdn.pcgamesn.com/sites/default/files/js/js_*.js
```

**Comment by Alex-302** [comment]
added
||cdn.pcgamesn.com/sites/default/files/TalismanHH
Your rule will break some functions, it is library.
