### ISSUE TITLE
qiwi.com - there's no Assistant

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1694]
https://qiwi.com/
http://prntscr.com/aanck4

> Я вам уже писал ваша программа не работает на сайте : https://qiwi.com/ Я поставил не бета а обычную версию и она нормально заработала. Сегодня вышла опять новая. Как только она обновилась то так же перестала
> работать. Хочу вам с полной уверенностью сказать что на сайте https://qiwi.com/ помощник Adguard вообще не работает
> ни бета ни обычная версия. Надеюсь вы найдете решение этой проблемы. Пробовал на другом компьютере тоже но никаких
> результатов нет.

**Comment by Alex-302** [comment]
Сайт в исключениях HTTPS в целях безопасности.
Можно дополнительно установить  расширение, и им можно будет заблокировать ненужные элементы.
