### ISSUE TITLE
[iOS] Bing.com

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1696]
Проблема такая:
В Safari, заходим на  bing.com вводим поиск "чего-либо", поиск срабатывает нормально, все находит. Но перейти по ссылке не получается, просто открывается пустая страница "about:blank".  Тестировал на базовых фильтрах, помогает отключение "русского фильтра", тогда переход по найдем ссылкам, срабатывает.

**Comment by Alex-302** [comment]
@Serzh-SUP 
нужен пример ссылки. Полезная реклама разрешена? И по какому типу ссылки переходили?

**Comment by Alex-302** [comment]
@Serzh-SUP 
ну что там?

**Comment by Alex-302** [comment]
bump

**Comment by Serzh-SUP** [comment]
@Alex-302 
Полезная реклама, что разрешена, что не разрешена - одинаково.
Переход обыкновенный, открыл поисковик, что-то нашел, нажал на ссылку и все.
Пример: [link](http://www.bing.com/search?q=%D0%BF%D0%B0%D1%80%D1%83%D1%81&qs=n&form=QBLH&pq=%D0%BF%D0%B0%D1%80%D1%83%D1%81&sc=0-0&sp=-1&sk=&cvid=24CC9CE753A7422CB5B4630F48C55A9E)

**Comment by Alex-302** [comment]
@Serzh-SUP 
у меня устройства нет, а в эмуляторе всё нормально. Попроси юзера выключить все фильтры и проверить только с одним английским. Если ок - пусть включает по одному с проверкой. Как найдёт проблемный - пусть отпишется.

**Comment by Alex-302** [comment]
ну и список фильтров огласи, он в state.txt должен быть(если юзер прислал)

**Comment by Serzh-SUP** [comment]
@Alex-302 
Сейчас все срабатывает хорошо! Закрываю.
