### ISSUE TITLE
[Android] - androidcentral.com - missed ad of Amazon

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1698]
"enabledFilterIds" : [ 2, 3, 4, 5, 11 ],
  "environment" : "prod",
  "filteringQuality" : "FULL",
  "filtersAutoUpdateEnabled" : true,
  "firewallConfiguration" : {
    "defaultPermissions" : [ "MOBILE", "WIFI", "AD_FILTERING" ],

![image](https://cloud.githubusercontent.com/assets/15856304/13524952/dea8b480-e206-11e5-8ba0-c755223e1f00.png)

FWH-398-14767

**Comment by Alex-302** [comment]
added to Mobile filter
androidcentral.com##a[href^="http://www.amazon.com/gp/"]
