### ISSUE TITLE
[Windows] kissanime.to - Whitespace

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1702]
![](http://i.imgur.com/nK63DK6.png)
https://kissanime.to/Anime/Gate-Jieitai-Kanochi-nite-Kaku-Tatakaeri-Enryuu-hen/Episode-021?id=123426

I use current:
kissanime.to##.divCloseBut
kissanime.to###adsIfrme6
kissanime.to###adsIfrme7
kissanime.to###adsIfrme8
kissanime.to###adsIfrme9
kissanime.to###adsIfrme11

Note:
adsIfrme10 is current adblock check

**Comment by Alex-302** [comment]
As you can see in the html code, they can change detection to other adsIfrme.
We can override detection by JS
```
kissanime.to##iframe[id^="adsIfrme"]
kissanime.to#%#AG_onLoad(function() { for (var key in window) { if (key.indexOf('DoDetect') == 0) { window[key] = function() { }; } }; }); 
```
