### ISSUE TITLE
[Android] westseattleblog.com - can't access 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1709]
I can't seem to even access this website with the filter running: http://westseattleblog.com Is there any way to allow a whitelist, or do you have any idea as to why the filter is blacking out the entire site?
![image](https://cloud.githubusercontent.com/assets/15856304/13553943/b68bd48a-e3a2-11e5-890c-8656807afab9.png)

RNX-426-76383

**Comment by evgeniy-ADG** [comment]
confirmed, can't access.

**Comment by Alex-302** [comment]
added to mobile filter
```
westseattleblog.com#@#.custom-ad
westseattleblog.com#@#.header-ad
```
