### ISSUE TITLE
[Windows] www.kitguru.net - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1712]
![](http://i.imgur.com/6jHRvwA.jpg)
http://www.kitguru.net/

Script:
http://www.kitguru.net/,qkitguru_wrapjs==1,aver==4.3.3+wp-includes,_js,_comment-reply.min.js,qver==4.3.3.pagespeed.jc.H1oeGxlakb.js

**Comment by Alex-302** [comment]
Part of script is builtin to the page.
We can block it by
kitguru.net#%#window.eval = function() {};
