### ISSUE TITLE
[Windows] www.pcworld.co.nz - Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1713]
![](http://i.imgur.com/44h6czW.png)
http://www.pcworld.co.nz/article/595415/dropbox-has-half-billion-users-it-needs-more-paying-businesses/

Script:
http://cdn.pcworld.co.nz/compressor-staticfiles/adsmin/idg_gpt_pipeline_generated.js

I use current:
```
pcworld.co.nz#@#.adsbox
```

**Comment by Alex-302** [comment]
this url is blocked by 
```
/adsmin/*
```
Can you check again? I don't see antiadblock message.

**Comment by Vincent-Michael** [comment]
strange, now works

**Comment by Alex-302** [comment]
Maybe it is a recently added rule.
