### ISSUE TITLE
[Stealth mode] esia.gosuslugi.ru - block third-party cookies

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1714]
The [link](https://esia.gosuslugi.ru/idp/rlogin?cc=bp)

При включенной защите не могу войти в свой аккаунт на нескольких сайтах, на других все хорошо. Авторизация на esia.gosuslugi.ru прошла успешно при выключенном пункте
- блокировать сторонние cookies

**Comment by Alex-302** [comment]
Английский фильтр включен?
Передай на проверку
```
@@||esia.gosuslugi.ru/idp/login/$document
```

**Comment by Alex-302** [comment]
@evgeniy-ADG 
ну что там?

**Comment by evgeniy-ADG** [comment]
ждем

**Comment by Serzh-SUP** [comment]
@Alex-302 
@evgeniy-ADG 
В общем, говорит, что не работает у него...
https://qcrm.cc/#/customer/1184330

**Comment by Alex-302** [comment]
@Serzh-SUP 
а спроси на счёт удалённого доступа.

**Comment by Alex-302** [comment]
и такое правило можно проверить
@@||esia.gosuslugi.ru/idp/login/

**Comment by Alex-302** [comment]
У нас работает.

**Comment by Serzh-SUP** [comment]
@Alex-302 
Последнее правило не помогло.
Доступ предоставить отказался.

**Comment by Alex-302** [comment]
@Serzh-SUP 
на "нет" и суда нет.
Пусть установит бету и добавит правило
```
@@||gosuslugi.ru^$stealth
```
