### ISSUE TITLE
Yaplakal android app - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1715]
https://play.google.com/store/apps/details?id=com.belous.v.yapikplus

http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=47774171

**Comment by Alex-302** [comment]
Maybe user does't have license key.

**Comment by Alex-302** [comment]
http://4pda.ru/forum/index.php?showtopic=601691&view=findpost&p=47802682
