### ISSUE TITLE
watchseries.li

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1723]
Steps to reproduce:

1) Go to watchseries.li
2) Choose any series and episode
3) Click on any link on a screen like this: http://screencast.com/t/oaTWcdCT
4) Click on 'Watch for free'
5) Popup comes up

**Comment by Alex-302** [comment]
I don't see ads there. When you click on 'Watch for free' the player opens in new tab.

**Comment by vbagirov** [comment]
Try to click on the video player once the video is already started. There will be an ad in new window.

**Comment by Alex-302** [comment]
still can't repruduce

**Comment by Alex-302** [comment]
Check this rule
||allmyvideos.net/player/popout.js

**Comment by vbagirov** [comment]
Looks like it works.

**Comment by Alex-302** [comment]
added
