### ISSUE TITLE
m.imore.com - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1724]
the [link](http://m.imore.com/sleephealth-uses-ibms-watson-health-cloud-study-how-you-sleep)

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13669172/34476c20-e6ca-11e5-9829-f8e33aed74cc.png)

<details>
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.78.72 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.94 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.79 Enabled=YES
ID Name="Turkish filter" Version=1.0.1.41 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.2.61 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID1 Name="EasyList" Version=1.0.53.78 Enabled=YES
ID8 Name="EasyPrivacy" Version=1.0.53.66 Enabled=YES
ID2 Name="Fanboy's Annoyances" Version=1.0.53.89 Enabled=YES
ID3 Name="Fanboy's Social Blocking List" Version=1.0.53.78 Enabled=YES
ID!5 Name="Fanboy's Enhanced Tracking List" Version=1.0.1.29 Enabled=YES
ID 4 Name="Peter Lowe's list" Version=1.0.1.91 Enabled=YES
ID 7 Name="Adblock Warning Removal List" Version=1.0.53.83 Enabled=YES
ID 8 Name="Malware Domains" Version=1.0.53.69 Enabled=YES
ID!0 Name="Spam404" Version=1.0.1.26 Enabled=YES
ID!1 Name="Anti-Adblock Killer | Reek" Version=1.0.1.58 Enabled=YES

**Comment by Alex-302** [comment]
added
```
imore.com##a[href^="https://www.amazon.com/b?"]
imore.com##a[href^="http://www.anrdoezrs.net/click"]
imore.com##a[href^="http://www.amazon.com/gp/"]
```
