### ISSUE TITLE
[Android] AliExpress Shopping App

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1728]
https://play.google.com/store/apps/details?id=com.alibaba.aliexpresshd&hl=ru

Реклама в приложении. Скриншот и предполагаемые правила от Андрея на форуме:

http://forum.adguard.com/showthread.php?9484-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B0%D0%BB%D0%B8%D1%8D%D0%BA%D1%81%D0%BF%D1%80%D0%B5%D1%81%D1%81-%D0%B1%D0%B5%D1%81%D1%8F%D1%87%D0%B8%D0%B9-%D0%B1%D0%B0%D0%BD%D0%BD%D0%B5%D1%80&p=78344#post78344

Возможно ли убрать рекламу?

**Comment by Alex-302** [comment]
Не убрать.
