### ISSUE TITLE
lady.mail.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1729]
Реклама "Циклоферона" на сайте фоном при переходе по ссылкам сайта.

**Comment by Alex-302** [comment]
исправлено недавно

**Comment by shurmosha** [comment]
ничего у вас не исправлено..реклама сия проходит периодически при наведении курсора в левый угол верхний сайта форум леди мэйл ру ..вот скрин и время там после вашего убирания и сегодня уже вылезала эта видео реклама
![default](https://cloud.githubusercontent.com/assets/17802561/13724820/762354a4-e8a2-11e5-977f-cad3f353cea6.PNG)

**Comment by Alex-302** [comment]
@shurmosha 
а дайте прямую ссылку. И покажите куда наводить надо, а то не получается вызвать рекламу.

**Comment by shurmosha** [comment]
вот вам ссылки с ютуба ..с другой рекламой,но смысл тот же
https://www.youtube.com/watch?v=IEpEaeIttQ0
https://www.youtube.com/watch?v=G4nt56azTGw
https://www.youtube.com/watch?v=EXf1LQwzFjg

**Comment by Alex-302** [comment]
попробуйте такое правило
```
lady.mail.ru##div[id^="rb_vid_"]
```
у себя в коде этого элемента не вижу, по второму видео ориентировался

**Comment by shurmosha** [comment]
если бы я знал,что с этим делать!!!!  и куда сие пихать..

**Comment by shurmosha** [comment]
внес в список-посмотрю,что будет..а так попробую снять коды элементов или же можете посмотреть сами по тим вьюеру

**Comment by Alex-302** [comment]
пока скрин делал вы уже разобрались) Но выложу всё же)
http://ipic.su/img/img7/fs/kiss_78kb.1457813737.png

**Comment by shurmosha** [comment]
спасибо..будем поглядеть,что будет далее

**Comment by Alex-302** [comment]
если больше не будет рекламы - отпишитесь, добавлю в основной фильтр

**Comment by shurmosha** [comment]
хорошо...два-три дня посмотрю...так как она периодически вылезает и нет определённости...может два дня не быть,а может только ночью вылезать..спасибо

**Comment by shurmosha** [comment]
добрый день! ничем не могу порадовать-вот скри
![default](https://cloud.githubusercontent.com/assets/17802561/13729076/3ae51d32-e93d-11e5-81b7-a035d33f5a90.PNG)
н сегодняшний

**Comment by shurmosha** [comment]
может сие поможет
![1](https://cloud.githubusercontent.com/assets/17802561/13729120/52e1f6a2-e93e-11e5-8c1c-76f6a8d4ae18.PNG)

**Comment by Alex-302** [comment]
удалённо нужно смотреть

**Comment by shurmosha** [comment]
да ради бога...токмо я не ведаю,когда эта хрень опять появится....тим вьюер стоит у меня

**Comment by Alex-302** [comment]
появится - не закрывайте вкладку. Подключусь - гляну. 
Правило пусть будет включено(и пользовательский фильтр соответственно)
lady.mail.ru##div[id^="rb_vid_"]

**Comment by shurmosha** [comment]
а,если сие возникнет ночью  али послезавтра???

**Comment by Alex-302** [comment]
Разве заглавными? Всё строчными было, как на скрине и видео. Из-за заглавных наверное и не работало, в таких правиах регистр должен быть как у элемента.

Если ноутбук - можно вкладку оставить. Если днём вылезет - часов с 11 до полуночи можно писать.

**Comment by shurmosha** [comment]
lady.mail.ru ## ДИВ [ID = "rb_vid_"]
lady.mail.ru##div[id^="rb_vid_"]
как-то так..можете сами посмотреть в переписке....
хорошо,я ноут ещё погоняю часов до трёх ночи

**Comment by Alex-302** [comment]
а, тэг(div) и атрибут(id) можно в любом регистре набирать, а имя(rb_vid_) - регистрозависимое.

**Comment by shurmosha** [comment]
пусть будет и то и другое

**Comment by shurmosha** [comment]
адвклинер периодически вот такое выискивает и удаляет,а оно опять вылезает с хрома...может,хром чего чудит?
![-](https://cloud.githubusercontent.com/assets/17802561/13758716/dfb45f7c-ea3b-11e5-9663-9f1e4e8bf9e4.PNG)

**Comment by shurmosha** [comment]
добрый вечер...вот уже второй день гоняю и на ноуте и на системнике-пробоев пока нет

**Comment by Alex-302** [comment]
ок, закрываю тогда. Правило добавил в фильтр, завтра можно будет удалить из пользовательского

**Comment by shurmosha** [comment]
я тут новичок..если будут проблемы-новую тему создавать?? али сюда писать..и -вопрос...выше дал скрин-возможно из -за этого???

**Comment by shurmosha** [comment]
а ,если забуду удалить-будут проблемы??

**Comment by Alex-302** [comment]
можно удалять
если появится - пишите сюда
