### ISSUE TITLE
avaxhm.com - missed pop-up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1730]
The [link](http://avaxhm.com/software/platform/apple_mac)

![image](https://cloud.githubusercontent.com/assets/15856304/13699390/bbc2ba84-e782-11e5-8f15-0fde98dd66e9.png)

Pressing Details causes popups

QTX-603-77228

**Comment by Alex-302** [comment]
fixed
