### ISSUE TITLE
Nimbus Note can't sync 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1731]
[Nimbus Note](https://play.google.com/store/apps/details?id=com.bvblogic.nimbusnote)

Не работает синхронизация с облаком nimbus.everhelper.me
Установки Adguard стандартные, при включенном синхронизация зависает, при
отключении защиты проходит без проблем. Ошибок никаких не выдаёт.

HTTP лог тут: KSV-295-19691

**Comment by Alex-302** [comment]
нужно описание как повторить. Что с чем синхронизируется, последовательность действий в общем.
Ну и очень желательно проверить без фильтров, не выклюая защиту.

**Comment by Alex-302** [comment]
Разобрался вроде. С Адгардом и фильтрами автоматическая синхронизация работает мгновенно.  При ручной - крутится значёк, не зависимо от того включен Адгард, или нет.

**Comment by evgeniy-ADG** [comment]
Мы напишем пользователю. У нас - проблема есть.

> проблема только в синхронизации файлов. не всегда все файлы синхронизируются с облаком (автоматом и  вручную ). если отключить адгард то сразу файл летит на облако

**Comment by Alex-302** [comment]
Фотка тоже моментально улетает, через пару секунд на сайте видна.

**Comment by evgeniy-ADG** [comment]
vgavrish [1:03 PM] 
отключение фильтров не повлияло
проблема такая, зависает колесико при ручном обновлении, 
не работает синхронизация, если заметка создана на сервере (в телефоне после ручного или автообновления не появляется).

[1:04] 
помогает только отключение адг

**Comment by Alex-302** [comment]
@evgeniy-ADG 
значит баг. Запилишь?

**Comment by evgeniy-ADG** [comment]
Запилю

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/ExperimentalFilter/issues/1731
