### ISSUE TITLE
super-kino.org - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1732]
![image](https://cloud.githubusercontent.com/assets/15856304/13700671/fc87552c-e78a-11e5-8aac-cc0758ba576f.png)

<details>
AppVersion: 6.0.204.1025
Main settings: 
Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:6 Name: German filter Url: http://adguard.com/ru/filter-rules.html?id=6
FilterId:8 Name: Dutch filter Url: http://adguard.com/ru/filter-rules.html?id=8
FilterId:10 Name: Filter for useful ads Url: http://adguard.com/ru/filter-rules.html?id
FilterId:105 Name: EasyList Czech and Slovak Url: https://raw.github.com/tomasko126/easylistczechandslovak/master/filters.txt
FilterId:111 Name: Latvian List Url: https://notabug.org/latvian-list/adblock-latvian/raw/master/lists/latvian-list.txt
FilterId:114 Name: ROList Url: http://www.zoso.ro/pages/rolist.txt
FilterId:117 Name: Adblock Polska Url: https://raw.githubusercontent.com/adblockpolska/Adblock_PL_List/master/adblock_polska.txt
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Tdi
Ads Blocked: 24291, Trackers Blocked: 16504
Filtering Mode: Driver
Application lifetime: 302.18:33:04.6562654
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false

**Comment by Alex-302** [comment]
added
||metaliners.ru^$third-party
