### ISSUE TITLE
[Stealth mode] Hide your IP blocks access to emirates.com/ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1734]
http://www.emirates.com/ru/
http://prntscr.com/advb5k
MUX-232-14805

**Comment by Alex-302** [comment]
как писал ранее, текущий подставной ip в блеклистах. Если на главную страницу сайта не пускает, задачи можно не создавать. Я это не исправлю. Поможет только полное исключение сайта
@@||domain.com^
