### ISSUE TITLE
http://new-rutor.pp.ua

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1737]
http://new-rutor.pp.ua
![screen shot 2016-03-11 at 7 53 36 pm](https://cloud.githubusercontent.com/assets/14153331/13710593/0104a3a6-e7c3-11e5-8ff8-4af3d389b678.png)
![2016-03-08_204852](https://cloud.githubusercontent.com/assets/14153331/13710604/0f1b2e74-e7c3-11e5-80c2-9222c0bd7980.jpg)
QXD-987-85115

**Comment by Alex-302** [comment]
||picts.new-rutor.pp.ua^
