### ISSUE TITLE
macos-app.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1738]
macos-app.com
![screen shot 2016-03-11 at 8 05 31 pm](https://cloud.githubusercontent.com/assets/14153331/13710968/d652e5ee-e7c4-11e5-94ba-a04d74f01ddc.png)
iOS request here - WJM-252-63476
reproduced on other platforms as well

**Comment by Vincent-Michael** [comment]
try:
```
||macos-app.com/wp-content/uploads/an-temp/
```

**Comment by Alex-302** [comment]
added
