### ISSUE TITLE
[Windows] www.wired.com - Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1741]
![](http://i.imgur.com/F6ePKb5.png)
http://www.wired.com/2016/03/didnt-know-much-loved-autocorrect-gonne/

Scroll and wait :P

Script:
http://www.wired.com/assets/load?scripts=true&c=1&load%5B%5D=jquery-sonar,wpcom-lazy-load-images,outbrain,blockadblock,tracking,ads,wired&ver=1457722268

I use current:
```
wired.com#%#Object.defineProperty(window, 'blockAdBlock', { get: function() { return function() { }; } });
```

Note:
Other rules are still valid

**Comment by Alex-302** [comment]
thanks, added
