### ISSUE TITLE
[Android] tw.com.gamer.android.activecenter

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1742]
https://play.google.com/store/apps/details?id=tw.com.gamer.android.activecenter
Logs - ULT-331-49653
<details>
![screenshot_2016-03-05-14-06-13](https://cloud.githubusercontent.com/assets/14153331/13725239/5f95dc32-e8a4-11e5-8799-aeb254b60631.png)
</details>

**Comment by Alex-302** [comment]
@Bohdan-SUP 
только первая кактинка рекламная?

**Comment by Bohdan-SUP** [comment]
Только блок сверху:
![5f95dc32-e8a4-11e5-8799-aeb254b60631](https://cloud.githubusercontent.com/assets/14153331/14696539/9fe9119c-0784-11e6-9e92-ed6d02e8a7e6.png)

**Comment by Alex-302** [comment]
@Bohdan-SUP 
повторить не получается.
Передай на пробу
||bahamut.com.tw/JS/ad/
В мобильный добавил, интересует ответ.

**Comment by Alex-302** [comment]
Если помогло - закрывай.

**Comment by Bohdan-SUP** [comment]
Передал.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
ну что?

**Comment by Bohdan-SUP** [comment]
No reply. I'll reopen if needed.
