### ISSUE TITLE
gotennis.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1743]
http://www.gotennis.ru/
http://prntscr.com/ae78u8
WRG-365-18993

**Comment by Alex-302** [comment]
gotennis.ru###vv_moduleFacebook_overlay

**Comment by Noisia12** [comment]
Реклама
![1](https://user-images.githubusercontent.com/33414806/34474839-4f64aa70-ef9e-11e7-923c-05cf62c9cbb4.jpg)
