### ISSUE TITLE
http://qtv.ua/ru/igronavty/ - blocked images

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1746]
![image](https://cloud.githubusercontent.com/assets/15856304/13731809/7851b8f4-e97b-11e5-92cf-f74dcd968c1c.png)

Works fine without filtering:

![image](https://cloud.githubusercontent.com/assets/15856304/13731811/94c79102-e97b-11e5-9a3b-6f4435505581.png)

**Comment by Alex-302** [comment]
-300x250$domain=~qtv.ua
