### ISSUE TITLE
[iOS] http://www.sport.es/es/ - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1749]
> The browser tries to charge the webpage, but it doesn't charge at all and start to charge it again. The browser is looping.
> This website is a sports newspaper and the problem only occur when trying to enter to the mobile site. If you enter to the desktop version there isn't any problem and all ads are blocked.

![image](https://cloud.githubusercontent.com/assets/15856304/13742604/5e6f51de-e9e5-11e5-8555-b454485cfaf1.png)

<details>

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.79.6 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.3 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.88 Enabled=NO
ID=5 Name="Experimental filter" Version=1.0.24.35 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.31.78 Enabled=YES
ID=6 Name="German filter" Version=1.0.24.10 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.92.93 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.8.70 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.16 Enabled=YES
ID Name="Turkish filter" Version=1.0.1.45 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.2.69 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID8 Name="EasyPrivacy" Version=1.0.53.97 Enabled=YES
ID!5 Name="Fanboy's Enhanced Tracking List" Version=1.0.1.30 Enabled=YES
ID 2 Name="Filtros Nauscopicos" Version=1.0.0.5 Enabled=YES
ID 8 Name="Malware Domains" Version=1.0.54 Enabled=YES
ID 9 Name="Prebake" Version=1.0.1.8 Enabled=YES
ID!0 Name="Spam404" Version=1.0.1.26 Enabled=YES

**Comment by Alex-302** [comment]
added to mobile filter
@@||bc.marfeel.com/statics/marfeel/gardac.js$domain=sport.es
Waiting for user's reply.
