### ISSUE TITLE
[Adguard for Mac] di.se

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1754]
Scrolling on the main page is broken. It will stop working once the site is fully loaded. Happens on Mac and Windows.

http://forum.adguard.com/showthread.php?9585

**Comment by Alex-302** [comment]
@vbagirov 
Removed:
```
di.se###header_overlay
di.se###message_modal
```
Added:
```
||login.di.se/assets/adblk.js
```
About Assistant - please file a bug.
