### ISSUE TITLE
quoidenoeuf.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1757]
http://quoidenoeuf.com/15-prenoms-de-filles-ont-lair-daimer-poils/
![image](https://cloud.githubusercontent.com/assets/14153331/13787300/152143fc-eae4-11e5-9b83-65147b0d44f2.png)
QCD-321-47133

**Comment by Alex-302** [comment]
@Bohdan-SUP 
проверь такое
```
quoidenoeuf.com##.pub
```
можно на дроиде. 
Отдельно интересует работоспособность сайта(этой ссылки) с вкл соц фильтром.

**Comment by Bohdan-SUP** [comment]
С соц. фильтром не показывает картинки - правило не помогло.

http://quoidenoeuf.com/il-vend-sa-lamborghini-sur-leboncoin-fr-lannonce-est-a-mourir-de-rire/
![screen shot 2016-03-17 at 4 33 17 am](https://cloud.githubusercontent.com/assets/14153331/13834644/67bf684e-ebf9-11e5-8335-ac302cfd8114.png)
![screen shot 2016-03-17 at 4 32 48 am](https://cloud.githubusercontent.com/assets/14153331/13834645/67d5fb5e-ebf9-11e5-868b-8eeb8166149d.png)

**Comment by Alex-302** [comment]
Правило помогло - остатки баннера с первого скрина исчезли. Отсутствие картинок - вторая проблема. Исправил.
