### ISSUE TITLE
[Windows] www.pcwelt.de - false positive 

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1758]
![](http://i.imgur.com/W1GJoqd.png)
http://www.pcwelt.de/

Rule "pcwelt.de###ad_mpu + div" kill this box

and can you maybe also this "-Anzeige-" box in sidebar blocks :)

**Comment by Alex-302** [comment]
Removed this rule. Blocking of these ads is dangerous.
Added
pcwelt.de$$div[class="box"][tag-content="-Anzeige-"] 
will works only with desktop Adguard
