### ISSUE TITLE
[iOS] Missed Ads https://touch.health.mail.ru

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1761]
Повторилось на iOS
Фильтры базовые, обновлены.
[Link](https://touch.health.mail.ru/news/lishniy_ves_vedet_k_problemam_s_pamyatyu/?from=pm)
![image1](https://cloud.githubusercontent.com/assets/16462533/13807000/8c65cec8-eb67-11e5-89e1-959876dcfa33.PNG)

**Comment by Alex-302** [comment]
У вас повторяется?(можно на дроиде) У меня чисто всё.
Убрал другой баннер
health.mail.ru##div[class$="trg-b-banner-block"]

**Comment by Serzh-SUP** [comment]
@Alex-302 Больше не повторяется.
