### ISSUE TITLE
[Stealth mode] TurboBit.net - block third-party cookies

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1763]
Переходим на http://cwer.ws/node/396615/
Скачиваем с TurboBit.net. -> Выбираем простое скачивание -> Нажимаем "Нет, спасибо": 
http://prntscr.com/aflv27
После этого страница только обновляется и не происходит скачивание.

Помогает отключение опции "Блокировать сторонние куки-файлы"

**Comment by Alex-302** [comment]
юзер ошибается. Здесь блокировка кук ничего не может сломать.

**Comment by Serzh-SUP** [comment]
Сегодня у меня работает. А вчера, лично пробовал и не работало с вкл. антитрекингом.
