### ISSUE TITLE
translate.ru app - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1767]
translate.ru
https://play.google.com/store/apps/details?id=com.promt.pmtappfree&hl=ru
http://prntscr.com/aeav69
![image](https://cloud.githubusercontent.com/assets/15856304/13817231/1b016548-eb9a-11e5-8a50-22236ae179b7.png)

HTTP requests log: FPC-818-12565

**Comment by Alex-302** [comment]
Встроено.
