### ISSUE TITLE
http://ogoa.ru/, skyscanner app - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1769]
1. ogoa.ru мобильная версия. не убирает рекламный блок (там, где манготур, почти под самой шапкой). добавление собственного правила не помогло (может не так что сделал). 
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13821523/b3eaccbc-ebaa-11e5-850d-6eb01e7d4379.png)

</details>
2. также не вырезана реклама в приложении skyscanner (версия 2.0.17) режим хттп, быстрый (качественный тоже не помог), рут
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13821535/be119784-ebaa-11e5-9bb2-e57cf9081582.png)

</details>
state.txt
<details>
{
  "advancedPreferences" : {
  },
  "androidVersion" : "4.4.2 (sdk)",
  "appLanguage" : "ru",
  "applicationId" : "9dc6eb3d49ebcc95",
  "whitelist" : [ ],
  "versionName" : "2.1.359",
  "currentWifiProxyConfiguration" : "port=0 manual",
  "deviceName" : "samsung GT-I9190",
  "userfilter" : [ "ogoa.ru###main_content_section > DIV:fi­rst-child > DIV.headerinner > DIV.header­inner1:first-child\n\n        ", "##ogoa.ru/reklama/*", "ogoa.ru###main_content_section > DIV:fir­st-child", "$$a[href=\"mangotour.ru\"][parent-elements=\"table\"]" ],
  "updateChannel" : "RELEASE",
  "enabledFilterIds" : [ 2, 3, 4, 5, 1, 11 ],
  "environment" : "prod",
  "filteringQuality" : "SPEEDY",
  "statisticsInfo" : "Blocked threats:0; Blocked banners:19291; Traffic saved:590869504;",
  "firewallConfiguration" : {
    "defaultPermissions" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
    "permissionsMap" : {
      "com.yandex.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.DolphinTranslate" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "jp.ddo.pigsty.Habit_Browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.showip" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatgo.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.addons.box" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.baidu.browserhd.inter" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.browserfaster" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "ru.yandex.shell" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.MorningCoffee" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.ip" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.whois" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.jiubang.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.nubelacorp.javelin" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.id" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.addons.evernotesshare" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.twitter" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.tabswitcher" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.android.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.metalasfook.nochromo" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.baidu.browser.inter" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.engine" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.web.browser.android" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.fevdev.nakedbrowserpro" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "cn.mozilla.firefox" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.alexa" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.sec.android.app.sbrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "me.android.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.YoutubeSearch" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.browser.beta" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.rocket.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.uc.browser.hd" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.mypdf" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.browser.flfoxpro" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.TabHistory" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.addons.dropbox" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.gcp" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.browser.yandex" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.textadjust" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "explore.web.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.theme.ocean" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.chrome.beta" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatgo.license.key" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.TabMixPlus" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.explore.web.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.linkbubble.playstore" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "acr.browser.barebones" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.mx.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.mozilla.fennec" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.cleanmaster.security" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.tablet" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.TunnyBrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.th" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.brightness" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.mx.browser.tablet" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.jbak.superbrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "net.fast.web.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.android.elex" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "nu.tommie.inbrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.yandex.browser.beta" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.ksmobile.cb" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.express.web" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.asus.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.uc.browser.en" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.appdream.cloud" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.eBaySearch" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.en" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.fb" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.UltimateFlag" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.mozilla.firefox" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.us" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.cloudmosa.puffinFree" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.shinyshake" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.fevdev.nakedbrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "internetexplorer.browser.webexplorer" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.UCMobile.intl" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.ScreenCut" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.droid.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.license.key" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.battery.saver" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.swe.atego.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.yandex.browser.alpha" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.ninesky.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "jp.ddo.pigsty.HabitBrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "acr.browser.lightning" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.tencent.ibibo.mtt" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.pm" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.addons.skitch" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.DolphinFM" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.mini.android.yandex" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.chrome.dev" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.zero" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.addons.pocket" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.amazon.cloud9" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.tabreload" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.ghostery.android.ghostery" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.ilegendsoft.mercury" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.cloudmosa.puffin" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.mozilla.firefox_beta" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "ru.mail.amigo" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.TunnyBrowser.Theme.EnNightModeV10" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.tint" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.mini.android" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.chrome.deviceextras.samsung" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.browser.flashfox" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "nextapp.atlas" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.DolphinReader" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.BookmarksWidget" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.UCMobile.intl.x86" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.browser.classic" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.easyweb.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.adblockplus.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.android.chrome" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.htc.sense.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.rtsw.easydownloader" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.vionika.firephoenix" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.whatsapp" : [ "MOBILE", "WIFI" ],
      "com.viber.voip" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "ru.raiffeisennews" : [ "MOBILE", "WIFI" ],
      "com.skype.raider" : [ "MOBILE", "WIFI", "AD_FILTERING" ]
    },
    "firewallEnabled" : true,
    "notifyForegroundAppBlocked" : true,
    "filterAppsTraffic" : true,
    "version" : 1
  },
  "installerPackage" : null,
  "kernelVersion" : "3.4.0-3021741",
  "sourceApk" : "/data/app/com.adguard.android-1.apk",
  "referrer" : null,
  "proxyPort" : 8080,
  "proxySetupManualMode" : false,
  "proxyMode" : true,
  "sendAnonymousStatistics" : false,
  "showUsefulAds" : false,
  "premium" : true,
  "filtersAutoUpdateEnabled" : true,
  "trial" : false,
  "dnsFilteringEnabled" : false,
  "deviceSpeedRank" : 671,
  "browsingSecurityEnabled" : true,
  "autoStartEnabled" : true
}

**Comment by Alex-302** [comment]
ogoa.ru##.rekl_table
ogoa.ru##div[id^="re_banner"]

по второму - нужна последовательность действий. У меня поиск другое выдаёт, и без рекламы.
И разные проблемы в одну задачу не стоит объединять.
