### ISSUE TITLE
Проверить правило

### ISSUE THREAD

**Issue by Embos** [AdguardTeam/ExperimentalFilter#1771]
Пересобирал для себя правила для рутрекера
А это правило в русском фильтре корректное? Синтаксис норм?
`rutracker.org###sidebar1 a[href="info.php?show=advert"]`
смущает пробел

**Comment by Alex-302** [comment]
корректное, но не нужное. Удалил. Пробел означает, что между #sidebar1 и a[href="info.php?show=advert"] могут быть какие-то элементы
