### ISSUE TITLE
[Windows] www.notebooksbilliger.de - Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1772]
![](http://i.imgur.com/6VT5vK9.png)
http://www.notebooksbilliger.de/microsoft+office+365+personal+257919/incrpc/lastseen

Should:
![](http://i.imgur.com/6ev0g3z.png)

I use current:
```
@@||notebooksbilliger.de^$generichide,genericblock
```

**Comment by Alex-302** [comment]
It is just picture. $generichide,genericblock will unblock too many requests.
Added to Experimental filter:
```
notebooksbilliger.de###wideSkyBanner
```
