### ISSUE TITLE
[Windows] http://abo.ua

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1773]
При включенной фильтрации Adguard на портале интернет магазина:
http://abo.ua/bolgarki-uglovye-shlifmashiny/ 
не работает выборка по категориям и при попытке перейти на следующие страницы с товарами появляется всплывающее окно с надписью "Функция AjaxResult может принимать только JSON"

Повторилось и в хроме. Отключение антитрекинга не решило проблему, фильтры базовые, расширений в браузере нет.

![default](https://cloud.githubusercontent.com/assets/16462533/13845656/186a77e2-ec4a-11e5-832d-cc972176718e.jpg)

**Comment by Alex-302** [comment]
исправил
@@||abo.ua/*/?ajax$document

**Comment by evgeniy-ADG** [comment]
1. Переходим в http://abo.ua/bolgarki-uglovye-shlifmashiny/

2. Нажимаем на любую кнопку для перехода к следующей странице (например 15) > получаем "Функция AjaxResult может принимать только JSON" > нажимаем "Ok" > жмем следующую кнопку (например 2) > получаем всплывашку ""Функция AjaxResult может принимать только JSON" с чекбоксом "Предотвратить создание дополнительных диалоговых окон на этой странице" > нажимаем Ok

3. В выборке категорий выбираем параметр товара, где страниц с товаром будем больше одной (Например "частота вращения диска" - "11000 - 12000 об/минуту") > Нажимаем на любую кнопку для перехода к следующей странице (например 3) > осуществляется переход на необходимую страницу > Нажимаем на любую кнопку для перехода к следующей странице (например 7) > получаем всплывашку "Функция AjaxResult может принимать только JSON" > нажимаем "Ok" > Нажимаем на любую кнопку для перехода к следующей странице (например 5) > получаем всплывашку ""Функция AjaxResult может принимать только JSON" с чекбоксом "Предотвратить создание дополнительных диалоговых окон на этой странице"1. Переходим в http://abo.ua/bolgarki-uglovye-shlifmashiny/

2. Нажимаем на любую кнопку для перехода к следующей странице (например 15) > получаем "Функция AjaxResult может принимать только JSON" > нажимаем "Ok" > жмем следующую кнопку (например 2) > получаем всплывашку ""Функция AjaxResult может принимать только JSON" с чекбоксом "Предотвратить создание дополнительных диалоговых окон на этой странице" > нажимаем Ok

3. В выборке категорий выбираем параметр товара, где страниц с товаром будем больше одной (Например "частота вращения диска" - "11000 - 12000 об/минуту") > Нажимаем на любую кнопку для перехода к следующей странице (например 3) > осуществляется переход на необходимую страницу > Нажимаем на любую кнопку для перехода к следующей странице (например 7) > получаем всплывашку "Функция AjaxResult может принимать только JSON" > нажимаем "Ok" > Нажимаем на любую кнопку для перехода к следующей странице (например 5) > получаем всплывашку ""Функция AjaxResult может принимать только JSON" с чекбоксом "Предотвратить создание дополнительных диалоговых окон на этой странице"a1. Переходим в http://abo.ua/bolgarki-uglovye-shlifmashiny/

2. Нажимаем на любую кнопку для перехода к следующей странице (например 15) > получаем "Функция AjaxResult может принимать только JSON" > нажимаем "Ok" > жмем следующую кнопку (например 2) > получаем всплывашку ""Функция AjaxResult может принимать только JSON" с чекбоксом "Предотвратить создание дополнительных диалоговых окон на этой странице" > нажимаем Ok

3. В выборке категорий выбираем параметр товара, где страниц с товаром будем больше одной (Например "частота вращения диска" - "11000 - 12000 об/минуту") > Нажимаем на любую кнопку для перехода к следующей странице (например 3) > осуществляется переход на необходимую страницу > Нажимаем на любую кнопку для перехода к следующей странице (например 7) > получаем всплывашку "Функция AjaxResult может принимать только JSON" > нажимаем "Ok" > Нажимаем на любую кнопку для перехода к следующей странице (например 5) > получаем всплывашку ""Функция AjaxResult может принимать только JSON" с чекбоксом "Предотвратить создание дополнительных диалоговых окон на этой странице"

**Comment by Alex-302** [comment]
заменил на 
@@||abo.ua/*ajax=$document
