### ISSUE TITLE
[Windows] www.stern.de - Missed Video Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1774]
![](http://i.imgur.com/uIF6py3.png)
http://www.stern.de/tv/endlose-kopfschmerzen--wie-eine-17-jaehrige-mit-chronischer-migraene-lebt-6746684.html

**Comment by Alex-302** [comment]
Can't confirm. Which filters are you using?

**Comment by Vincent-Michael** [comment]
![](http://i.imgur.com/SC5lo2i.png)

Ads trigger rnd

**Comment by Alex-302** [comment]
confirmed. It is VAST ad.
Added to Experimental filter:
```
||homad-global-configs.schneevonmorgen.com.s3.amazonaws.com/www.stern.de/config.json$replace=/"enabled": true\,/"enabled": false\,/i
||damoh.aws.stern.de^$replace=/(<VAST(.|\s)*?>)(.|\s)*<\/VAST>/\$1<\/VAST>/
```
Please check them of few videos.
