### ISSUE TITLE
[Stealth mode] www.imdb.com - player doesn't start when "Hide your referer" is enabled

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1776]
The [link](http://www.imdb.com/video/imdb/vi2461970201?ref_=tt_ov_vi)

![image](https://cloud.githubusercontent.com/assets/15856304/13858015/4c33f5f4-ec85-11e5-8858-1b61f2f38767.png)

**Comment by Alex-302** [comment]
added
@@||media-imdb.com/images/*/prod/*.js$domain=imdb.com
