### ISSUE TITLE
[iOS] finanzen.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1778]
http://www.finanzen.net/ - on top and right
BCF-879-70252
![img_0492](https://cloud.githubusercontent.com/assets/14153331/13858983/c4926338-ec89-11e5-893c-a33854f8a566.PNG)

**Comment by Alex-302** [comment]
@@||finanzen.net^$elemhide
added to Safari filter
