### ISSUE TITLE
https://play.google.com/store/apps/details?id=ru.mts.mymts&hl=ru

### ISSUE THREAD

**Issue by gps22** [AdguardTeam/ExperimentalFilter#1779]
![screenshot_2016-03-18-10-47-23](https://cloud.githubusercontent.com/assets/17922579/13871996/72368160-ed00-11e5-8c14-7e6340a6b7cd.png)
Not blocked banners

**Comment by Alex-302** [comment]
@gps22 
это ж их собственные.

**Comment by gps22** [comment]
Ну вроде -да,но их все больше и больше с каждой новой версией..Я думал это тоже можно отфильтровать.


С уважением,
Сергей Фролов
serg.froloff@mail.ru

**Comment by Alex-302** [comment]
попробую заблокировать. Если получится - дам правила.

**Comment by Alex-302** [comment]
а, не выйдет у меня - мтсом не пользуюсь, и рядом никто.
Переключите в Адгарде в расширенных настройках уровень логирования - записывать HTTP запросы, закройте приложение МТС, и через минуту запустите его снова. Вышлите лог с указанием времени запуска.

**Comment by gps22** [comment]
вроде отправил  время 18.02 мск    Номер заявки:  XZV-677-65691



С уважением,
Сергей Фролов
serg.froloff@mail.ru

**Comment by Alex-302** [comment]
они по HTTPS работают, и в логе ничего не видно.
Если хотите, можете установить тестовую альфа-версию
https://github.com/AdguardTeam/AdguardForAndroid/releases
и включить фильтрацию HTTPS

**Comment by gps22** [comment]
Да ладно,наверное не стоит...я думал проще все выйдет....шут с этим приложением...В любом случае спасибо за содействие.



С уважением,
Сергей Фролов
serg.froloff@mail.ru

**Comment by Alex-302** [comment]
ок тогда
