### ISSUE TITLE
[Android] soap4.me - video playback issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1782]
soap4.me 
На сайте soap4.me на устройстве c ОС Android при попытке просмотра онлайн видео минуты 2-3 идет воспроизведение, а потом останавливается. Продолжить возможно только после выключения защиты Adguard. Добавление soap4.me в белый список в настройках программы проблему не решает. 

Сообщений об ошибке нет

logs ISZ-358-36832

**Comment by Alex-302** [comment]
@evgeniy-ADG 
если без фильтров не работает, то нужно пилить баг. Запроси полный лог с указанием времени начала воспроизмедения и возникновения проблемы.
Как придёт лог - эту проблему можно будет закрыть, и открыть в дроидовом раздее.

**Comment by Alex-302** [comment]
@evgeniy-ADG

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/416
