### ISSUE TITLE
[Android] Lifehacker.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1786]
Website is not displayed correctly (http://screencast.com/t/Y6lFGJg9UB) when high-quality filtering is enabled. 

Originally posted on: http://forum.adguard.com/showthread.php?9655-Troubles-with-Lifehacker-website

**Comment by Alex-302** [comment]
Looks like a bug. The pagу is broken by Adguard CSS and JS injections.

**Comment by vbagirov** [comment]
Transferred this tasak to AdguardforAndroid repository: https://github.com/AdguardTeam/AdguardForAndroid/issues/377
