### ISSUE TITLE
[Windows] www.prosieben.de - Missed Video Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1788]
![](http://i.imgur.com/P8c9iyz.png)
http://www.prosieben.de/tv/supergirl/video/13-trailer-folge-3-supergirl-in-gefahr-clip

**Comment by Alex-302** [comment]
@Vincent-Michael 
could you provide me remote access? I can't fix it with VPN...

**Comment by Vincent-Michael** [comment]
you have pm on forum @Alex-302

**Comment by Alex-302** [comment]
@ameshkov Could you please help with video ad? I don't see requests of it.
The same issue:
http://www.clipfish.de/special/spielfilme/video/4300502/game-of-death-wesley-snipes/
http://www.myvideo.de/serien/circus-halligalli/staffel-7/folge-8-staffel-7-episode-8-m-12185200

**Comment by ameshkov** [comment]
@Alex-302 
It seems they load ads somehow inside the Flash using some non-standard protocol.

First of all, let's trick them and hide flash from them:
```
#%#window.ActiveXObject = undefined;
#%#navigator.mimeTypes['application/x-shockwave-flash'] = undefined;
```

In this case they'll switch to HTML5 player and you'll see an ad request, something like this:
```
http://vod-akamai-psd2-dcp.p7s1digital.de/progressive/01/nPOZonu3CzPX8Qdh-qSP8ZVB02MvrTTYbKzAFSEx2LxD0Uh0ONYsKHh2_dYdtfgylHfTczVDTVuJgaq6Ss1rMu0n7M4l0GE8P-UiiwIILuOeJhSOOchqD1Ymq5q4JP4KpnwmaHUKj4Q-sTmozXQoXQ/v.ism/x.mp4?hdnea=st=1458900088~exp=1458986488~acl=%2Fprogressive%2F01%2FnPOZonu3CzPX8Qdh-qSP8ZVB02MvrTTYbKzAFSEx2LxD0Uh0ONYsKHh2_dYdtfgylHfTczVDTVuJgaq6Ss1rMu0n7M4l0GE8P-UiiwIILuOeJhSOOchqD1Ymq5q4JP4KpnwmaHUKj4Q-sTmozXQoXQ%2Fv.ism%2Fx.mp4%2A~hmac=ec8c60b304c95445074d9d332271115e653a84ffbec1f29833790471d8127666&access_token=prosieben&video=
```

That's not all, but at least we now see ad requests.

**Comment by Vincent-Michael** [comment]
@Alex-302 
i found current only rule for flash player via:
``` ||abpxy.p7s1dns.net ```

but but i need also rule for ff other and this use HTML5  :/

**Comment by Alex-302** [comment]
@Vincent-Michael 
it was in German filter, but few sites was broken. We can't block it for specific domain, becuse it use WebSocket

**Comment by Vincent-Michael** [comment]
I found away to block ... I will test a 1-2 weeks :)

**Comment by ameshkov** [comment]
@Alex-302 no referrer in WebSocket requests?

**Comment by Alex-302** [comment]
@ameshkov 
I don't see WS now, but never seen a referrer before.

**Comment by Alex-302** [comment]
For clipfish.de - the VAST config is in this file, but it is in exclusions and replace rule doesn't work. Too much exclusions loaded from Easylist

http://de-ipd.videoplaza.tv/proxy/distributor/v2?rt=vp_3.0&pf=fl_21.0.0.197&cv=as3_2.4.15.23.1.0-ku&t=overlay,class%3D3,vpaid%2Cvpo%3Dl%2Cview%3Ddesktop%2Cvpc%3Db%2Cdevice%3Ddesktop%2Ctouch%3D0%2Cip_flash%3D0%2Chtml5%3D1%2Casync%3D1%2Cthc%3D4483a8bc.52f445ca4b00d%2Cw_b_schoen%3Dnein%2Cw_kk_b%3D1%2Cw_hh_schoen%3Dnein%2Cw_kk_hh%3D1%2Cw_m_schoen%3Dja%2Cw_kk_m%3D1%2Cw_k_schoen%3Dnein%2Cw_kk_k%3D1%2Cw_f_schoen%3Dnein%2Cw_s_schoen%3Dnein%2Cw_do_schoen%3Dnein%2Cw_h_schoen%3Dnein%2Cw_l_schoen%3Dnein%2Cresponsive%3Dfalse%2Ctheme%3Dspielfilme%2Cpack%3Dprofcon%2Cdc_ref%3Dhttp%3A%2F%2Fwww.clipfish.de%2F%2Cplayerseite%3Dja%2Cvideolength%3D5505%2Cvpvpcd%3D1%2Cvpvpcc%3D1%2Cvpvpcb%3D1%2Cvpvpca%3D1%2Cj4%3D1%2Cj4%3D2%2Cj5%3D0%2Cj5%3D1%2Cj5%3D2%2Cj5%3D3%2Cj5%3D4%2Cj5%3D5%2Cj5%3D6%2C&s=rtl_clipfish%2Fspielfilme&cf=long_form&cd=5505&vwt=955&vht=539&vbw=14652&tt=p,m,o,po,pa,se,s&bp=600,1200,2400,3600&obp=60&ru=http%3A%2F%2Fwww.clipfish.de&xpb=1&rnd=835538890975

**Comment by Vincent-Michael** [comment]
i use current this rule for my test:
```
myvideo.de,prosieben.de,prosiebenmaxx.de,sat1.de,kabeleins.de,sat1gold.de,sixx.de#%#Object.defineProperty(window, 'SIMAD', { get: function() { return function() { }; } });
prosieben.de,prosiebenmaxx.de,sat1.de,kabeleins.de,sat1gold.de,sixx.de###modal-overlay
```

**Comment by ameshkov** [comment]
@Alex-302 could you please check it?

**Comment by Alex-302** [comment]
@ameshkov 
it works, but many errors in console. Maybe exist different way to break window.SIMAD ?

**Comment by ameshkov** [comment]
Nope, defineproperty is really good solution. What are these errors?

**Comment by Alex-302** [comment]
@ameshkov 
just requests to undefined functions

added to German filter
