### ISSUE TITLE
[iOS] my-thinking.ru - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1789]
http://my-thinking.ru/user/1557/articles
http://prntscr.com/agrkzb
<details> 
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.76.49 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.70 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.40 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.30.68 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.40 Enabled=YES

**Comment by Alex-302** [comment]
@evgeniy-ADG 
добавил в русский
||ads.people-group.net^$third-party
Нужен ответ юзера после обновления фильтров.
