### ISSUE TITLE
www.bolshoyvopros.ru - missed white blocks

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1790]
http://www.bolshoyvopros.ru/questions/964333-zvuko-bukvennyj-foneticheskij-razbor-slova-ruchej-kak-sdelat.html
http://prntscr.com/agse8h

![image](https://cloud.githubusercontent.com/assets/15856304/13883935/6305b326-ed34-11e5-834e-9bcdad1463f2.png)

тут небольшие белые блоки, там была реклама, возможно и у пользователя они остались
у него не блокирует в браузере Яндек

**Comment by Alex-302** [comment]
добавил
в фильтр соц сетей:
bolshoyvopros.ru##div[class^="likes"]
в русский
bolshoyvopros.ru##div[class^="adbl_cont"]
