### ISSUE TITLE
kudago.com - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1791]
https://kudago.com/msk/list/8-neobychnyh-moskovskih-fastfudov/
http://prntscr.com/agstov
"Читайте книги вместе Лабиринт.ру" и ниже -- это реклама

ISY-258-47145

**Comment by Alex-302** [comment]
@evgeniy-ADG 
добавил в русский фильтр
kudago.com##.special_links
Пусть юзер отпишется после обновления. Мне не на чем проверить, только дроид.
