### ISSUE TITLE
http://worldbloger.com/ - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1792]
http://worldbloger.com/medblog-gemorroi/?utm_source=kadamdir.ru&utm_medium=gemorroi&utm_campaign=1025112&utm_content=1380559

http://prntscr.com/agtbvj
http://prntscr.com/agtc66

при нажатии на меню сайта или другие ссылки на статьи, идет переход на другой сайт:
http://prntscr.com/agtchq

**Comment by Alex-302** [comment]
Эта задумка такая. Сайт посвящён впариванию противогемморойного ковра:)
Про лечение гепатита вообще улыбнуло.

Короче в фильтры не пойдёт такое. А юзер лучше пусть в больничку сходит.
