### ISSUE TITLE
nl.express.live - anti adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1793]
http://nl.express.live/2016/03/15/96150artificiele-intelligentie-politie-google/

![image](https://cloud.githubusercontent.com/assets/15856304/13884938/d8534324-ed38-11e5-99e2-5d46cc08b548.png)

**Comment by Vincent-Michael** [comment]
try:

```
||nl.express.live/wp-content/uploads/sites/*/an-temp/
```

**Comment by Alex-302** [comment]
Added to Experimental filter:
/wp-content/*/an-temp/*
