### ISSUE TITLE
Gizmodo.com or any kinja.com - the site is broken when Adg is on

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1795]
![image](https://cloud.githubusercontent.com/assets/15856304/13886160/3f50e1ee-ed3e-11e5-80e5-5fd4a86ea768.png)

Gizmodo.com or any kinja.com site. Chrome or opera. Open browser with
adguard enabled, go to site. Result, site broken, screenshot attached.

AGL-898-84771

**Comment by Alex-302** [comment]
temporary added:
@@||gizmodo.com^$document
@@||kinja.com^$document
this issue is fixed in new alpha version
