### ISSUE TITLE
[Windows] www.speedtest.net - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1796]
![](http://i.imgur.com/rvRkd0G.png)
http://www.speedtest.net/

![](http://i.imgur.com/CzmYow3.png)

![](http://i.imgur.com/4mpUSKN.png)

Overlay block buttons

I use current:
```
speedtest.net##div[class^="dfp-eot-"]
```

**Comment by Alex-302** [comment]
added
