### ISSUE TITLE
jandan.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1799]
http://jandan.net/
EasyList + EasyList China + EasyPrivacy
![screen shot 2016-03-19 at 5 10 34 am](https://cloud.githubusercontent.com/assets/14153331/13896355/51bb9f6a-ed91-11e5-9e86-b24940ac8127.png)

Request - CIX-803-72677

**Comment by Alex-302** [comment]
@Bohdan-SUP 
added to our English filter
User must enable our English filter.
