### ISSUE TITLE
ruadlist css fixes - take a look

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#180]
https://userstyles.org/styles/101141/ru-adlist-css-fixes

http://forum.adguard.com/showthread.php?3009

Посмотри пожалуйста на стили, которые Lain написал для RuAdList.
Имеет смысл для русского фильтра похожие правила написать. Там буквально десяток сайтов.

**Comment by Alex-302** [comment]
Здесь закрываю. Правила обработал. Ещё раз пересмотрю и будет норм.
