### ISSUE TITLE
https://www.flickr.com/ - can't share uploaded pics

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1800]
1. Open Flickr https://www.flickr.com/cameraroll/
2. Upload some pic
3. Try to share it: http://prntscr.com/ah90c4
4. See the issue: http://prntscr.com/ah90gt
5. Disable Adguard ad do steps 1-3, see how it should be: http://prntscr.com/ah90qm

**Comment by Alex-302** [comment]
@evgeniy-ADG 
need the filters list

**Comment by evgeniy-ADG** [comment]
включен руский, англ, спайвер, соушл, германский, изи лист чехия-словкая и изи лист италия

**Comment by Alex-302** [comment]
@evgeniy-ADG 
антитрекинг включен? Попроси без соц фильтра проверить

**Comment by Alex-302** [comment]
@evgeniy-ADG 
это не ложное. Фильтр соц сетей блокирует кнопки шаринга. Заблокировал кнопку вызова этого диалога в соц фильтре.
Если юзеру нужны эти кнопки, передай исключения
```
flickr.com#@#.share-panel 
flickr.com#@#.fluid-share-cameraroll-view
```
