### ISSUE TITLE
[Stealth mode] https://web.whatsapp.com - Block Web RTC breaks the site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1803]
Блокировка входа на сайт - https://web.whatsapp.com/
Такие действия:
1. Переходим на сайт и сканируем QR код приложением whatsapp на Андроид:
http://prntscr.com/ah70cc
2. Идет переход на главную страницу, но в итоге колесо загрузки страницы продолжает крутится до бесконечности и страница не загружается:
http://prntscr.com/ah700i

Помогает отключение опции в Антитрекинге - БлокироватьWeb RTC:
http://prntscr.com/ah6zsk

**Comment by Alex-302** [comment]
@evgeniy-ADG 
лучше в виндовый раздел перенеси, т.к. помогает толькое исключение всего домена
@@||web.whatsapp.com^

**Comment by Bohdan-SUP** [comment]
Same trouble on a Mac. We should consider whitelisting it.

**Comment by Alex-302** [comment]
please check it
```
@@||web.whatsapp.com^$stealth
```

**Comment by evgeniy-ADG** [comment]
Передал правило пользователю.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
не ответил?

**Comment by evgeniy-ADG** [comment]
Все работает!

**Comment by Alex-302** [comment]
Добавил.
