### ISSUE TITLE
www.costumenational.com - can't open online chat

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1804]
[Link](http://www.costumenational.com/on/demandware.store/Sites-costume-Site/default/Home-Show)

The chat doesn't open when Adg is on. How it should be:

![image](https://cloud.githubusercontent.com/assets/15856304/13901636/f79c3754-ee32-11e5-93c3-27ed37548215.png)

**Comment by Vincent-Michael** [comment]
try:
```
@@||googletagmanager.com/gtm.js^$domain=costumenational.com
```

**Comment by Alex-302** [comment]
thanks, added to spyware filter
