### ISSUE TITLE
[Windows] www.theguardian.com - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1807]
![](http://i.imgur.com/n3WPIgG.jpg)
http://www.theguardian.com/money/2016/mar/18/banned-by-amazon-returning-faulty-goods-blocked-credit-balance

I use current:
```
theguardian.com##div[aria-describedby="site-message__message"]
```

**Comment by Alex-302** [comment]
added
theguardian.com##.js-adblock-sticky
theguardian.com##div[class$="adblock-message"]

**Comment by Vincent-Michael** [comment]
![](http://i.imgur.com/lsGrxgj.jpg)

your rule is for me useless and are no ad block message @Alex-302

**Comment by Alex-302** [comment]
it was actual when I checked. Removed.
