### ISSUE TITLE
ixbt.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1809]
Некорректное отображение 
http://www.ixbt.com/video4/games-nfs-radeon.shtml
http://prntscr.com/ahjdvk
http://prntscr.com/ahjdzf

Помогает отключение Русского фильтра 

также можно поправить шапку сайта:
http://prntscr.com/ahjear

**Comment by Vincent-Michael** [comment]
for header:
```
ixbt.com#$#body > .limiter { padding-top: 0px!important; }
```

**Comment by Alex-302** [comment]
thanks, added
+ for adblock detection
ixbt.com#%#fuckAdBlock = function() {};
