### ISSUE TITLE
gamayun.ipb.su

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1810]
http://gamayun.ipb.su/index.php?act=idx
http://prntscr.com/ahjelq
VXS-749-46683

**Comment by Vincent-Michael** [comment]
try:
```
||power.freeimg.ru^$domain=gamayun.ipb.su
```

**Comment by Alex-302** [comment]
the most safety variant:
||freeimg.ru/protJS/
because it can't block useful urls, and will work after changing subdomain name

/protJS/ is used in popular Russian ads
