### ISSUE TITLE
usatoday.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1814]
http://www.usatoday.com/
![usatoday](https://cloud.githubusercontent.com/assets/14153331/13914683/a956bafc-ef58-11e5-8aba-41d77524eba1.jpg)
ODD-694-35190

**Comment by Vincent-Michael** [comment]
http://forum.adguard.com/showthread.php?9679-Missing-text-on-http-www-usatoday-com&highlight=usatoday.com

**Comment by Alex-302** [comment]
added
@@||static.chartbeat.com/js/chartbeat_mab.js^$domain=usatoday.com
