### ISSUE TITLE
[iOS] blogdoiphone.com - blank page

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1817]
Incorrect blocking on page:
http://blogdoiphone.com/2016/03/iphone-se-rumor-mutante/

The page doesn't load at all when Adguard is active.

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.79.36 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.7 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.94 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.16 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.2.74 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID1 Name="EasyList" Version=1.0.54.31 Enabled=YES
ID8 Name="EasyPrivacy" Version=1.0.54.21 Enabled=YES
ID 7 Name="Adblock Warning Removal List" Version=1.0.54.38 Enabled=YES
ID 8 Name="Malware Domains" Version=1.0.54.24 Enabled=YES
ID!0 Name="Spam404" Version=1.0.1.26 Enabled=YES
ID!1 Name="Anti-Adblock Killer | Reek" Version=1.0.1.58 Enabled=YES

**Comment by Alex-302** [comment]
added to mobile filter
blogdoiphone.com#@#.header-ad
blogdoiphone.com#@#.custom-ad
