### ISSUE TITLE
[iOS] https://www.viu.com/ - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1818]
Incorrect blocking on page:
https://www.viu.com/ott/hk/

Web page not function properly 

![image](https://cloud.githubusercontent.com/assets/15856304/13934095/fb998578-efb8-11e5-9cc9-33fef8800175.png)

**Comment by Alex-302** [comment]
@@||viu.com/ott/*/js/tracking/tracking.js$domain=viu.com
added to spyware filter
