### ISSUE TITLE
[Windows] www.4players.de - Missed Video Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1819]
![](http://i.imgur.com/DDZSFg2.png)
http://www.4players.de/4players.php/spielinfonews/Allgemein/37293/2157183/Batman_-_A_Telltale_Games_Series-Erste_Details_Man_kann_fast_ueberall_als_Bruce_Wayne_oder_Batman_agieren_vergleichbar_mit_Wolf_Among_Us.html

I use current:
```

Add:
||s3.amazonaws.com/homad-global-configs.schneevonmorgen.com/www.4players.de/config.json$replace=/"enabled": true\,/"enabled": false\,/i
||s3.amazonaws.com/homad-global-configs.schneevonmorgen.com/global_config.json$replace=/"enabled": true\,/"enabled": false\,/i,domain=4players.de
||damoh.4players.de^$replace=/(<VAST(.|\s)*?>)(.|\s)*<\/VAST>/\$1<\/VAST>/
```

Remove / Disable:
```
||schneevonmorgen.com/www.4players.de/config.json$replace=/"enabled": true\,/"enabled": false\,/i,domain=4players.de
```

**Comment by Alex-302** [comment]
@Vincent-Michael 
it is blocked by EF on my end. Could you check again?

**Comment by Vincent-Michael** [comment]
without my rule play always ads @Alex-302 

![](http://i.imgur.com/AkqZt8k.png)

**Comment by Alex-302** [comment]
ok, added
