### ISSUE TITLE
3dnews.ru (Annoyance)

### ISSUE THREAD

**Issue by Embos** [AdguardTeam/ExperimentalFilter#1822]
http://www.3dnews.ru/
![default](https://cloud.githubusercontent.com/assets/9648798/13935738/d11e4988-efda-11e5-9870-11b8a96d9570.png)

Как удалить блок ютуба справа? Я стандартным правилом ## скрыл этот раздел и казалось что все норм, но страница все равно грузит ютубный ролик под капотом. Может где-то скрипт еще нужно прибить?

**Comment by Vincent-Michael** [comment]
try:
```
3dnews.ru###youtube-chunk-wrapper
```

**Comment by Embos** [comment]
Да я же сказал что правило вида ## не помогает до конца. Взгляни под капот. Видео все равно загружается, хотя его и не видно.
![default](https://cloud.githubusercontent.com/assets/9648798/13942990/40368698-f01a-11e5-8e6f-29256cdee90b.png)

**Comment by Vincent-Michael** [comment]
```
youtube.com/player_api^$domain=3dnews.ru
```
but can maybe pages with youtube embeddable break

**Comment by Embos** [comment]
`||googleapis.com^*%3DUCkTigzIFeWMpiubcQlnkyYw$domain=3dnews.ru`

Источник:
https://hg.adblockplus.org/ruadlist/rev/ed1e19e13817#l1.30

**Comment by Alex-302** [comment]
Нет смысла. Видео сменят и понадобится новое правило.

**Comment by Embos** [comment]
Ну и что, видео меняется, а правило работает
`||googleapis.com^*%3DUCkTigzIFeWMpiubcQlnkyYw$domain=3dnews.ru`

**Comment by Alex-302** [comment]
Ну добавь в пользовательский. Никто же не мешает.

**Comment by Embos** [comment]
так я сразу добавил. И сюда пришел чтобы получить правило, так как не хватает навыка составления подобных правил.
Просто известил, что правило норм работает.

**Comment by Alex-302** [comment]
Если бы по урлу можно было догадаться, к чему имеет отновшение, для экспериментального фильтра подошло бы. А так не хочется добавлять.

**Comment by Embos** [comment]
Алекс эти символы - это id канала 3dnews на ютубе.
http://www.youtube.com/channel/UCkTigzIFeWMpiubcQlnkyYw

причем это правило не ломает страницы подобные этим
http://www.3dnews.ru/930322
