### ISSUE TITLE
[Windows] specific website's module (so called photo editor) doesn't work.

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/ExperimentalFilter#1823]
www.fotovramku.ru

Please refer to TICKET ID DCD-994-31625 for more details

![1](https://cloud.githubusercontent.com/assets/17472907/13947495/08a09176-f02c-11e5-90f0-2d4227e04079.PNG)

**Comment by Alex-302** [comment]
added
@@||fotovramku.ru/engine/ajax/$document
