### ISSUE TITLE
[Windows] ad blocking rule advice requested

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/ExperimentalFilter#1824]
TICKET ID  PQH-752-56679

www.livejournal.com
![screen1](https://cloud.githubusercontent.com/assets/17472907/13954473/f630b95a-f051-11e5-8e6b-44031b0b9502.jpg)

www.kungurov.livejournal.com
![screen2](https://cloud.githubusercontent.com/assets/17472907/13954492/1029ded6-f052-11e5-862a-1913cd39e877.jpg)

www.dolboeb.livejournal.com
![screen3](https://cloud.githubusercontent.com/assets/17472907/13954497/153d89d6-f052-11e5-82f9-b28d6c351ea5.jpg)

**Comment by Vincent-Michael** [comment]
i have only ads on 2.link

**Comment by Alex-302** [comment]
для пользовательского
livejournal.com##.b-discoverytimes-wrapper
