### ISSUE TITLE
[Windows] www.mobilegeeks.de - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1825]
![](http://i.imgur.com/fK0TLuU.jpg)
http://www.mobilegeeks.de/artikel/groessenvergleich-apple-iphone-se-vs-iphone-4-iphone-6s-galaxy-s7/

I use current:
```
mobilegeeks.de##.ha-header > div[style="background:#000000;"]
```

**Comment by Alex-302** [comment]
added
