### ISSUE TITLE
/www.lefigaro.fr/ - anti adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1826]
http://www.lefigaro.fr/flash-eco/2016/03/21/97002-20160321FILWWW00217-repli-de-7-des-prix-du-porc-en-2015.php

![image](https://cloud.githubusercontent.com/assets/15856304/13961019/6e298502-f063-11e5-93bf-553cd3c6c6de.png)

**Comment by Vincent-Michael** [comment]
```
lefigaro.fr#%#adisplaynormal = function() {};
```

**Comment by Alex-302** [comment]
we can fix it without JS, if unblock also
http://a.f1g.fr/build/2/adsense.js
Added
```
lefigaro.fr##.fig-adgps
@@||f1g.fr/build/*/adsense.js
@@||foglio.basilic.io/ad/basilic.adsense.js
```
