### ISSUE TITLE
www.syl.ru - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1827]
http://www.syl.ru/article/194637/new_batareyka-dlya-materinskoy-platyi-batareyka-dlya-bios-materinskoy-platyi

![image](https://cloud.githubusercontent.com/assets/15856304/13964171/2b789db6-f071-11e5-864e-118bb39e8b00.png)

**Comment by Vincent-Michael** [comment]
try:
```
||api.cloudleadia.com/wnew.js^$domain=syl.ru
```

**Comment by Alex-302** [comment]
это не реклама. Решили не блокировать такое.
