### ISSUE TITLE
[Windows] www.kitguru.net - white space /  false positive

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1828]
![](http://i.imgur.com/odLYINq.png)
http://www.kitguru.net/

I use current:

``` kitguru.net##div[id^="adflash-"] ```

and rule ```kitguru.net#%#window.eval = function() {};```

break current search / adguard assistant

I test current:

```
kitguru.net#%#AG_onLoad(function() { jQuery(function() { jQuery('body').unbind('click').removeAttr("body").css("cursor","default"); }); });
kitguru.net#$#body { background-image: none !important; } 
```

**Comment by Alex-302** [comment]
removed: 
kitguru.net#%#window.eval = function() {};
added: 
kitguru.net##div[id^="adflash-"]
kitguru.net#$#body { background-image: none !important; }
kitguru.net#%#AG_onLoad(function() { jQuery(function() { jQuery('body').unbind('click').removeAttr("body").css("cursor","default"); }); });
