### ISSUE TITLE
[Stealth mode] hide third-party cookies hides notifications on youtube

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1829]
На сайте Youtube блокируются оповещения Google в правой верхней части экрана, если поставлена галочка в Adguard блокировать сторонние cookie.

<details>
ads is on
![image](https://cloud.githubusercontent.com/assets/15856304/13968785/4e76e8fc-f087-11e5-9414-89bb3cda6f87.png)

ads is off
![image](https://cloud.githubusercontent.com/assets/15856304/13968797/5a8e355a-f087-11e5-9fb6-556c96efd64c.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
А при каких условиях эти нотификации должны выходить?

**Comment by evgeniy-ADG** [comment]
коммент, новость какая-то в канале, на которы подписан, например. как везде у гугл. возможно, оно и с гугл+ и другими проявляется. проблема в том, что оно просит войти, чтобы посмотреть уведомления.

**Comment by Alex-302** [comment]
Слабо верится что блокировка куков ломает уведомления. При переходе с другого сайта может авториизация слетать, т.к. куки ютуба в данном случае сторонние. Про это открыт баг
https://github.com/AdguardTeam/AdguardForWindows/issues/955

**Comment by evgeniy-ADG** [comment]
On YouTube, the adblocker seems to disable the notifications. At the YouTube homepage, there is a bell icon at the top right of the window. Clicking that normally opens up notifications, such as comments on videos. After installing and using Adguard, clicking the bell now gives an error message from Google saying: "Please sign in to view your notifications." This message displays even if the user is signed in. I hope this can be resolved.

Having all options enabled in Stealth Mode, then unchecking "Block third-party cookies" fixed the issue with YouTube notifications.
I really appreciate the support. I will keep checking out the blog for future updates.
