### ISSUE TITLE
http://vetton.ru/ - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1830]
![image](https://cloud.githubusercontent.com/assets/15856304/13969312/c921842e-f08a-11e5-80ff-23efde363939.png)

1. Открываем сайт
2. Переходим в любой раздел - пустая страница
3. Обновлдяем страницу контрол+ф5 -  появляются фото
4. Отключаем фильтрацию - все ок

**Comment by Alex-302** [comment]
Временно добавил частичное исключение:
@@||vetton.ru^$jsinject,elemhide
