### ISSUE TITLE
[Windows] www.gamestar.de - Missed Video Ads / Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1831]
![](http://i.imgur.com/pICZEg1.png)
http://www.gamestar.de/news/3269761/20_jahre_horror.html

I use current:
```gamestar.de#%#window.blockAdBlock = function() {};```

fix video ads and anti adblock

**Comment by Alex-302** [comment]
The first is added.
But video ad is blocked on my end. Could you check again?

**Comment by Vincent-Michael** [comment]
video ad trigger via anti adblock and is with rule also fixed @Alex-302

**Comment by Alex-302** [comment]
ok
