### ISSUE TITLE
[Windows] www.bleepingcomputer.com - overlay

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1833]
![](http://i.imgur.com/HESilJR.png)
http://www.bleepingcomputer.com/forums/t/607593/surprise-ransomware-support-and-help-topic-encrypted-filesnotepad/

I use current:
```
||bleepstatic.com/js/jquery/jquery.simplemodal.*.min.js
```

**Comment by Alex-302** [comment]
added to EF
