### ISSUE TITLE
www.moje-filmy.tk - missed ads in video

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1835]
http://www.moje-filmy.tk/film/transformers-wiek-zaglady-1

![image](https://cloud.githubusercontent.com/assets/15856304/13995743/2f2ec2ce-f133-11e5-9599-d0077a25c222.png)

YQV-845-46773
please delete
<details> 
Login: jocaloy@flemail.ru Password: start12388

**Comment by Alex-302** [comment]
added, but this rule will not works with browser extensions
||get-contents.video-ads.tk/files/*.mp4$domain=moje-filmy.tk,mp4
