### ISSUE TITLE
vogelz.ru - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1837]
http://vogelz.ru/rasskazy/charushin-e/kak-malchik-zhenya-nauchilsya-govorit-bukvu-r/
http://prntscr.com/aj1kof

**Comment by Vincent-Michael** [comment]
```
vogelz.ru###center_rightbar
```

**Comment by Alex-302** [comment]
added +
||convergator.net^$third-party
||vogelz.ru/images/banners/
