### ISSUE TITLE
Willdev.in login trouble 

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1843]
https://willdev.in/
при нажатии на "Проверит скилл" не отображаются значки соц сетей для авторизации:
http://prntscr.com/aj40p9
http://prntscr.com/aj40fm

Мешает фильтр Виджетов

**Comment by Alex-302** [comment]
@Bohdan-SUP 
добавил
willdev.in#@#.social-icons
нужно проверить
