### ISSUE TITLE
[Windows] www.europe1.fr - Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1846]
![](http://i.imgur.com/3CLrllP.png)
http://www.europe1.fr/international/salah-abdeslam-veut-sexpliquer-en-france-le-plus-vite-possible-selon-son-avocat-2701651

``` ||cdn-analytics.ladmedia.fr/europe1/ablocker/$domain=europe1.fr ```

**Comment by Alex-302** [comment]
added
