### ISSUE TITLE
sports.ru (False Positive, Windows)

### ISSUE THREAD

**Issue by Embos** [AdguardTeam/ExperimentalFilter#1847]
http://www.sports.ru/tribuna/blogs/saltis/919573.html
Английский фильтр чего-то ломает.
Блок комментариев не загружается, без английского фильтра все норм.
(Допускаю, что возможно нужна авторизация для повтора)

**Comment by Alex-302** [comment]
да вроде загружается. Когда включен один ангийский фильтр, повторяется?

**Comment by Embos** [comment]
Сейчас уже все нормально. Хотя до этого много раз перепроверял.
Извиняюсь.

**Comment by Alex-302** [comment]
Аналогично.

**Comment by Embos** [comment]
Можешь закрыть, чтобы глаза не мазолила)
