### ISSUE TITLE
[Android] Flixster app

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1848]
https://play.google.com/store/apps/details?id=net.flixster.android

"s0.2mdn.net
platform-cdn.sharethrough.com
www.googletagmanager.com

are not blocked on flixster app for android".

Originally from: http://forum.adguard.com/showthread.php?9505

**Comment by Alex-302** [comment]
Нельзя 1 и 3 целиком блокировать, сайты ломаться будут.
2 - неизвестно что.
