### ISSUE TITLE
[Windows] www.tvnow.de - browser differences

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1850]
![](http://i.imgur.com/nObJcm5.png)
http://www.tvnow.de/

with ff trigger:
![](http://i.imgur.com/wQEg8iC.png)
and on chrome is fine

I use current:

tvnow.de there again remove:
```
@@||cdn.videoplaza.tv/*/homadConfigVideoplaza-*.json$domain=tvnow.de|rtl2.de|bilder.static-fra.de|toggo.de
```

and replace with:
```
@@||cdn.videoplaza.tv/*/homadConfigVideoplaza-tvnow.json
```

i need still in german filter (without this stuck videoplay):
```
@@||tvnow.de^$elemhide
```

**Comment by Alex-302** [comment]
thanks, added
