### ISSUE TITLE
http://sprashivai.ru/ (Инжект ломает?)

### ISSUE THREAD

**Issue by Embos** [AdguardTeam/ExperimentalFilter#1851]
http://sprashivai.ru/

С вкл. Adguard сайт пишет "Ошибка сервера 500"
С выкл. Adguard все норм (фильтры не причем, помогает только откл. защиты)

В IE11 также.

Скрины:
![01](https://cloud.githubusercontent.com/assets/9648798/14044815/4a2d189e-f2b6-11e5-8b8e-7964ae5320af.png)

![02](https://cloud.githubusercontent.com/assets/9648798/14044767/dc881adc-f2b5-11e5-9fc9-d482f4bd5c60.png)

Подобные задачи лучше куда кидать? В фильтры или в Adguard для Windows?

**Comment by Alex-302** [comment]
Похоже скрытие IP в антитрекинге включено.
Подобное можно в этот раздел кидать. Если что, продублируем куда надо.

**Comment by Embos** [comment]
Нет, антитрекингом не пользовался и не включал.

**Comment by Alex-302** [comment]
Попробуй выключить все фильтры и проверить в приватном режиме. Не поможет - выключи все расширения Адгарда и проверь так же.

**Comment by Embos** [comment]
Я не могу поймать закономерность... Может с сайтом что-то не так. То все норм, то ошибка 500.
и Adguard тут видимо не причем. Снимаю претензии)
