### ISSUE TITLE
[iOS] medanalog.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1854]
http://medanalog.ru/active/fosfolipidyi/rezalyut-pro
http://prntscr.com/ajv1ky

ZEE-305-87516

**Comment by Alex-302** [comment]
это ж вроде виджет тех чуваков, которые жаловались что блокируем.
Заблокировал в ЭФ:
```
||api.leadiacloud.com^$domain=medanalog.ru
```
не забудь передать юзеру чтоб включил этот фильтр.
