### ISSUE TITLE
http://playpuls.pl/ missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1855]
![image](https://cloud.githubusercontent.com/assets/15856304/14050761/adf58e46-f2c6-11e5-871c-5e60f61ad833.png)

http://playpuls.pl/seriale/dokumentalne/z-archiwum-policji

**Comment by Vincent-Michael** [comment]
```
playpuls.pl#%#AG_onLoad(function() { adData  = null; });
```

**Comment by Alex-302** [comment]
@Vincent-Michael 
the player is broken with your rule. Please check it again, and second variant(it works on my end):
```
playpuls.pl#%#Object.defineProperty(window, 'ads', { get: function() { return {}; } }); 
```

**Comment by Vincent-Michael** [comment]
strange (i had no problems), but you rule is also fine ^^

**Comment by Alex-302** [comment]
ok, added)
