### ISSUE TITLE
[Android] MTS RU app - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1856]
https://play.google.com/store/apps/details?id=ru.mts.mymts

![image](https://cloud.githubusercontent.com/assets/15856304/14053686/b40e4c72-f2db-11e5-9f6b-167f2f1e8228.png)

"enabledFilterIds" : [ 2, 3, 4, 1, 11 ],

**Comment by Alex-302** [comment]
У меня нет МТС, следовательно не смогу авторизоваться. Если пользователь согласится установить бету, попроси сделать лог HTTP запросов(в одной из задач описал как его делать) с указанием времени запуска приложения.

**Comment by Alex-302** [comment]
Там не HTML, поэтому не убрать
