### ISSUE TITLE
cbc.ca - videos are blocked

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1858]
it seems that we're blocking the whole player while blocking ads in it

the link: http://www.cbc.ca/beta/news/canada/manitoba/chase-martens-search-effort-resumes-1.3507279

adguard on
![image](https://cloud.githubusercontent.com/assets/15856304/14054939/2db59846-f2e6-11e5-9945-c2e1dedd45f4.png)

and on (ot shows 30 sec ads before the main video)
![image](https://cloud.githubusercontent.com/assets/15856304/14054944/4236c8f8-f2e6-11e5-816b-77032f0a4b8a.png)

**Comment by Alex-302** [comment]
added to Mobile filter
```
@@||pdk.theplatform.com/*/pdk/js/plugins/doubleclick.js$domain=cbc.ca
@@||imasdk.googleapis.com/js/core/*$domain=cbc.ca
@@||sb.scorecardresearch.com/*/plugins/streamsense_plugin_theplatform.js$domain=cbc.ca
```
