### ISSUE TITLE
http://m.telegraaf.nl/ - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1859]
![image](https://cloud.githubusercontent.com/assets/15856304/14055276/4c660a66-f2e9-11e5-8224-beda4b4f44bd.png)

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.80.4 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.11 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.13 Enabled=YES
ID=6 Name="German filter" Version=1.0.24.36 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.8.70 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.2.89 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID1 Name="EasyList" Version=1.0.54.85 Enabled=YES
ID6 Name="EasyList Dutch" Version=1.0.54.97 Enabled=YES

**Comment by evgeniy-ADG** [comment]
requested a direct link

**Comment by Alex-302** [comment]
Looks like the main page.
Added to Dutch filter:
||m.telegraaf.nl/static/lib/bva-widget.html
