### ISSUE TITLE
sports.ru (annoyance)

### ISSUE THREAD

**Issue by Embos** [AdguardTeam/ExperimentalFilter#1861]
http://www.sports.ru/
Не могу сам избавиться от этого всплывающего сообщения, помогите.

![default](https://cloud.githubusercontent.com/assets/9648798/14060493/d32b10f2-f387-11e5-8741-bb1a35cf3013.png)

**Comment by Alex-302** [comment]
надоедливое сообщение, добавил в ЭФ
sports.ru##.notifications-subscribe-popup

**Comment by Embos** [comment]
А вот и нет Алекс - не все так просто.
Такое простое правило я бы сам сделал.
При таком правиле скроллинг ломается (его вообще нет)

**Comment by Alex-302** [comment]
проверь такие
sports.ru#$#.modal_state_open { overflow: auto!important; }
sports.ru##.notifications-subscribe-popup

**Comment by Embos** [comment]
Спасибо! Так нормально.

**Comment by Alex-302** [comment]
ок, добавил. В Сафари блокировать не будет, первое правило не поддерживается.
