### ISSUE TITLE
Transportoid app - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1866]
The [link](https://play.google.com/store/apps/details?id=com.transportoid)

![image](https://cloud.githubusercontent.com/assets/15856304/14065094/502e0cf2-f424-11e5-81f0-7332526b170a.png)

Reproduced with beta with HTTPs filtering enabled.

RVI-479-68768

**Comment by Alex-302** [comment]
||mad.mobisky.pl^$empty
added
please check it
