### ISSUE TITLE
androeed.ru - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1871]
We're blocking "Send" button, it's not available when Adguard is enabled:

![image](https://cloud.githubusercontent.com/assets/15856304/14067824/096588d8-f477-11e5-9ea1-5e11468f54c8.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
а данных для входа нет? Регистрация мутная, не хочется их клиента ставить.
Попроси чтоб сделал тестовый акк.

**Comment by evgeniy-ADG** [comment]
vidjanim@gmail.com
qwerty1

Помогает отключение фильтра "Виджетов соц сетей" и кнопка появляется

**Comment by Alex-302** [comment]
Исправил
~facebook.com,~androeed.ru##input.fb

**Comment by Alex-302** [comment]
Можно в пользовательском проверить
```
androeed.ru#@#input.fb
```
