### ISSUE TITLE
[Windows] www.pcgamesn.com - Missed Ads / Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1872]
![](http://i.imgur.com/4VqlxAM.jpg)
http://www.pcgamesn.com/doom/new-doom-trailer-focuses-on-demon-death-and-chainsaw-massacres-ahead-of-may-release-date

I use current:
Add:
```
@@||pcgamesn.com^$generichide
pcgamesn.com###pcgn_custom_slots
```

Remove:
```
||cdn.pcgamesn.com/sites/default/files/TalismanHH
||cdn.pcgamesn.com/sites/default/files/WoWs.jpg
```

i try already:
``` #%#Object.defineProperty(window, 'blockAdBlock', { get: function() { return function() { }; } }); ```
but has bad lock :/

**Comment by Alex-302** [comment]
thanks, added
