### ISSUE TITLE
[iOS] Missed Ad http://l2on.net

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1874]
Проверка со стандартным, обновленным набором фильтров
[Link](http://l2on.net/?c=market)
![image1](https://cloud.githubusercontent.com/assets/16462533/14077784/1368d62e-f4f8-11e5-8697-9221cb26c09e.PNG)

**Comment by Alex-302** [comment]
||l2on.net/img/friends/cashpass_
||l2on.net/img/friends/funpay_
