### ISSUE TITLE
sports.ru (annoyance)

### ISSUE THREAD

**Issue by Embos** [AdguardTeam/ExperimentalFilter#1875]
Сегодня опять проблема проявилась.
Подробнее тут https://github.com/AdguardTeam/ExperimentalFilter/issues/1861

К примеру тут
http://www.sports.ru/stat/football/center/

Прокрутка сломалась. Подправить бы правила в экспериментальном.

**Comment by Alex-302** [comment]
удалил их. Они прокрутку включают только после закрытия

**Comment by Embos** [comment]
Решения вообще что ли нет?

**Comment by Alex-302** [comment]
>Решения вообще что ли нет?
лучше не трогать, чтоб не лишиться возможности читать.
