### ISSUE TITLE
https://wpmienphi.com/ - anti adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1877]
https://wpmienphi.com/

![image](https://cloud.githubusercontent.com/assets/15856304/14107003/f3234842-f5bd-11e5-827e-e066da345bdf.png)

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.80.47 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.15 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.18 Enabled=NO
ID=8 Name="Dutch filter" Version=1.0.8.70 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.2.93 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID1 Name="EasyList" Version=1.0.55.5 Enabled=NO
ID2 Name="Fanboy's Annoyances" Version=1.0.55.16 Enabled=NO
ID 7 Name="Adblock Warning Removal List" Version=1.0.55.10 Enabled=NO
ID 9 Name="Prebake" Version=1.0.1.10 Enabled=NO
ID!0 Name="Spam404" Version=1.0.1.27 Enabled=YES
ID!1 Name="Anti-Adblock Killer | Reek" Version=1.0.1.59 Enabled=YES

**Comment by worldsdream** [comment]
Hi,

i already did make an issue on the official reek github page:
https://github.com/reek/anti-adblock-killer/issues/1238

**Comment by Alex-302** [comment]
@worldsdream 
hi
please check this rule
```
@@||wpmienphi.com^$generichide
```

**Comment by worldsdream** [comment]
@alex-302
I already did report it to aaklist reek on github and he fixed it. So you dont need to add this anymore? It's working now great

**Comment by worldsdream** [comment]
Nevermind my last comment, it does not work because he didn't push an update i guess. 

I did add your code to user filter. But that didn't help.

**Comment by Alex-302** [comment]
@worldsdream 
didn't you make a mistake?
Please check this:
```
@@||wpmienphi.com^$elemhide
```

**Comment by worldsdream** [comment]
I copy and pasted it. I also cleared safari caches completely. Still the same. 

We can wait for reek to update his list and this should be fixed right?

**Comment by Alex-302** [comment]
No, we want fix it without third-party filters:)
This rule works on my end in Firefox.
Check this please:
```
@@||wpmienphi.com^$generichide
@@||pagead2.googlesyndication.com/pagead/show_ads.js$domain=wpmienphi.com
```

**Comment by worldsdream** [comment]
Ok i understand

I did add those both. It didn't work.

**Comment by Alex-302** [comment]
hmmm...
check without
ID=3 Name="Spyware filter" Version=1.0.5.15 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.8.70 Enabled=YES
ID� Name="Mobile ads filter" Version=1.0.2.93 Enabled=YES
ID� Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID!0 Name="Spam404" Version=1.0.1.27 Enabled=YES
ID!1 Name="Anti-Adblock Killer | Reek" Version=1.0.1.59 Enabled=YES

**Comment by worldsdream** [comment]
Ok i only enabled adguard english
I added those 2 lines. 

Now the homepage does let me in. But the page is not really mobile view anymore. Clicking on a post. Does give me the warning again.

**Comment by Alex-302** [comment]
very strange. These rules can't change view of site, only unblock one url end disable element hiding

**Comment by Alex-302** [comment]
@worldsdream 
any news? Still doesn't work?

**Comment by worldsdream** [comment]
@alex-302
I just checked. It works great. Resolved!

**Comment by Alex-302** [comment]
ok, thanks)
