### ISSUE TITLE
ilan.memurlar.net - slider is blocked

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1878]
http://ilan.memurlar.net/
Slide has been blocked by adguard. 

![image](https://cloud.githubusercontent.com/assets/15856304/14107166/1c10e042-f5bf-11e5-82da-14d3e72949f4.png)

**Comment by Alex-302** [comment]
added to English filter
@@||ilan.memurlar.net/common/job/advert/images/*/headline.jpg|
