### ISSUE TITLE
news.sportbox.ru - video is blocked in Adguard for Windows and Android

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#188]
http://news.sportbox.ru/Vidy_sporta/Hokkej/spbvideo_NI492798_Superseriya-Rossiya-Kanada-Molodezhnie-sbornie-Match-2?ci=173363
---
http://4pda.ru/pages/go/?u=http%3A%2F%2Fnews.sportbox.ru%2FVidy_sporta%2FAvtosport%2FFormula_1%2Fspbvideo_NI526441_Aleksej_Popov_Kvat_poboretsa_za_Gran_pri_Malajzii%3Fci%3D201298

**Comment by Alex-302** [comment]
Говорят, что сейчас всё работает.
Здесь пока закрываю. Если что - на форуме тема открыта
http://forum.adguard.com/showthread.php?4987
