### ISSUE TITLE
http://lifemebel.ru/ - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1880]
http://lifemebel.ru/catalog/stoly/dlya_kuhni/
При выборе опций и нажатии Выбрать, начинает вечно крутится колесико:
http://prntscr.com/alfhud

Помогает только отключение защиты.

ZOV-652-40578

**Comment by Alex-302** [comment]
посоветуй сегодняшнюю бету. Там исправлена проблема с инжектами куда не следует

**Comment by evgeniy-ADG** [comment]
Работает.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
если кто-то с релизной версией жалуется на нерабочие фильтры типа этого, можно советовать бету
