### ISSUE TITLE
akvabaza.ucoz.ru - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1883]
Пропущена реклама на странице:
http://akvabaza.ucoz.ru/index/0-74

![image](https://cloud.githubusercontent.com/assets/15856304/14123085/7d014f02-f607-11e5-96aa-e9f5fe4a9d0a.png)

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.73.24 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.5.15 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.16 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.32.33 Enabled=YES
ID=6 Name="German filter" Version=1.0.22.37 Enabled=NO
ID Name="Mobile ads filter" Version=1.0.2.92 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID1 Name="EasyList" Version=1.0.51.18 Enabled=NO
ID5 Name="RU AdList" Version=1.0.55.7 Enabled=YES
ID!2 Name="RU AdList: Counters" Version=1.0.47.79 Enabled=NO
ID!3 Name="RU AdList: BitBlock" Version=1.0.48.5 Enabled=NO

**Comment by Alex-302** [comment]
@evgeniy-ADG 
у него английский фильтр выключен. Эта реклама блокируется именно им.

**Comment by Alex-302** [comment]
Подгружаемые рекламные домены добавил в мобильный фильтр, но передай ему, что английский фильтр выключать не стоит.
