### ISSUE TITLE
tut.by annoyance + antiadblock

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1885]
Link - tut.by

Screenshots - http://prntscr.com/alvths
при попытке заблокировать нижний элемент:
http://prntscr.com/alvskd

Reporter - WKB-193-45257

**Comment by Alex-302** [comment]
tut.by##body > div[style^="background-color: #000;bottom: 0;left: 0;opacity: 0.5;position: fixed;right: 0;top: 0;z-index:"]
tut.by##div[style^="box-sizing: border-box;left: 0;max-height: 100%;position: fixed;right: 0;text-align: center;top: 70px;z-index:"]

**Comment by Alex-302** [comment]
сообщения не вижу. Детект убрал.
