### ISSUE TITLE
https://tickets.oebb.at/en/ticket - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1888]
Adguard filters too much, i.e. removes 2 input boxes to enter depature and arrival station

![image](https://cloud.githubusercontent.com/assets/15856304/14156453/27494592-f6cf-11e5-88ab-f745f61aa976.png)

![image](https://cloud.githubusercontent.com/assets/15856304/14156461/2fd2562c-f6cf-11e5-8af0-0d64447c31f4.png)

**Comment by Alex-302** [comment]
added
@@||tickets.oebb.at^$generichide
