### ISSUE TITLE
vk.com - please create a custom rule for our user

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1889]
![image](https://cloud.githubusercontent.com/assets/15856304/14156978/c61d27cc-f6d1-11e5-8c5c-f26dd55585f1.png)

He wants to hide 2 blocks on the site. 2.5 is installed.

**Comment by evgeniy-ADG** [comment]
1. Не было блока рекламы слева.
2. Не было списка возможных друзей, т.е. этот блок нужно убрать полностью.
3. В списке групп не было блока с рекламой групп, чтобы мои сообщества как бы поднялись выше, на пустое место, и ничего кроме них там не было. Заранее спасибо.

**Comment by Alex-302** [comment]
1. vk.com###ads_left
2. не понял о чём речь
3. Для верхнего блока со скрина
```
vk.com###group_recom_wrap
```
