### ISSUE TITLE
www.google.com notifications - add to the annoyances filter

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1890]
https://www.google.com.ua/?gfe_rd=cr&ei=ZQz9VrmSIYSu8wfD9IfQAw&gws_rd=ssl and such

http://prntscr.com/amdfz8

**Comment by Alex-302** [comment]
@evgeniy-ADG 
не отображаются у меня почему-то. Удалённо бы посмотреть.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
можешь заскринить код элемента?

**Comment by Alex-302** [comment]
@evgeniy-ADG 
bump

**Comment by evgeniy-ADG** [comment]
у меня тоже уже, попітаюсь повторить.

**Comment by Alex-302** [comment]
пока закрываю, т.к. правило в ЭФ есть и вроде как работает
