### ISSUE TITLE
www.bestbuy.com - Hide your IP issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1891]
http://www.bestbuy.com/site/index.jsp?intl=nosplash

![image](https://cloud.githubusercontent.com/assets/15856304/14175607/bfeb50bc-f754-11e5-8d89-8851d567cc51.png)

**Comment by Alex-302** [comment]
на главную тоже не зайти

**Comment by Alex-302** [comment]
единственный выход - добавить в пользовательский фильтр
@@||bestbuy.com^
