### ISSUE TITLE
forum.xda-developers.com - empty ad placeholder

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1892]
Add this rule to english filter:
```
forum.xda-developers.com###posts>div[style*="min-height:"]
```

![screenshot_2016-03-31-14-20-56](https://cloud.githubusercontent.com/assets/5947035/14175781/014ab024-f756-11e5-9795-e8f515981dba.jpg)

**Comment by Alex-302** [comment]
@ameshkov 
added, but why not to Mobile?
