### ISSUE TITLE
http://www.sportstream.tv/ missed ad on all platforms

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1896]
![image](https://cloud.githubusercontent.com/assets/15856304/14177404/d2f7c15e-f75e-11e5-8d8d-ea76880c387a.png)

**Comment by Alex-302** [comment]
||sportstream.tv/img/left.gif
||sportstream.tv/img/top.gif
||sportstream.tv/img/right.gif
||sportstream.tv/img/big.gif
