### ISSUE TITLE
http://www.hotnewhiphop.com/ - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1897]
Incorrect blocking on page:
http://www.hotnewhiphop.com/

The slideshow on the main page shows black images on my iPhone 5s through Safari and white images on my MacBook Pro through Safari. If I turn off Adguard or use another ad blocker, the images are shown correctly.

<details>
adg is on ![image](https://cloud.githubusercontent.com/assets/15856304/14177444/00e0dc04-f75f-11e5-8444-0331a918969a.png)
Adg is off 
![image](https://cloud.githubusercontent.com/assets/15856304/14177459/0b84fdac-f75f-11e5-9751-ea64448de2c5.png)

**Comment by Alex-302** [comment]
added to English filter
@@||ulximg.com/image/*/banner/$domain=hotnewhiphop.com

**Comment by Alex-302** [comment]
@evgeniy-ADG 
user should to check it after filters update
