### ISSUE TITLE
[Stealth mode] Hide your referrer from third-parties blocks "Add to cart" on organicss.net

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1898]
http://organicss.net/g2445794-besfosfatnye-geli-dlya

![image](https://cloud.githubusercontent.com/assets/15856304/14180528/0b7dcda4-f76c-11e5-87ab-40c612a8e20e.png)

**Comment by Alex-302** [comment]
@@||my.prom.ua/remote/
добавил
