### ISSUE TITLE
[iOS] m.ekb.piluli.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1901]
http://m.ekb.piluli.ru/product/meldonij
![image1](https://cloud.githubusercontent.com/assets/14153331/14221021/a75f2ffa-f86c-11e5-8485-63b99121bd84.JPG)
HRI-368-35715

**Comment by Alex-302** [comment]
added to Mobile filter
piluli.ru##div[class^="ya_adv_"]
piluli.ru##div[id^="medads_banner"]
