### ISSUE TITLE
[Windows] www.foerderland.de - Missed Ads / Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1902]
![](http://i.imgur.com/T3PPSij.png)
![](http://i.imgur.com/YGLxIea.png)
![](http://i.imgur.com/TYzxCUk.png)
http://www.foerderland.de/technik/tipps/artikel/google-now-tipps/

I use current:
```
||laterpay.net^$domain=foerderland.de
foerderland.de##a[href^="http://www.coolstuff.de/"]
foerderland.de##a[href^="https://www.weka.de/mediadaten/portale/foerderland-de/"]
foerderland.de###footerFlyout
```

**Comment by Alex-302** [comment]
added

**Comment by Vincent-Michael** [comment]
@Alex-302 
``` foerderland.de#footerFlyout ``` in german filter
copy and paste fail?
