### ISSUE TITLE
[Windows] www.freenet.de - false positive / missed ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1903]
![](http://i.imgur.com/hXkpEgW.jpg)

Add:
```
freenet.de##div[id^="adBox"]
freenet.de##.veeseoRUN
```

Remove:
```
@@||freenet.de^$elemhide
||freenet.de/www/export/$script
```

Some strange filter from easylist :/

**Comment by Alex-302** [comment]
added end removed.
Why the last rule is unnecessary?

**Comment by Vincent-Michael** [comment]
this rule break this @Alex-302 

![](http://i.imgur.com/2VmftWh.jpg)

**Comment by Alex-302** [comment]
ok
