### ISSUE TITLE
[Windows] www.zdnet.com - false positive

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1905]
![](http://i.imgur.com/sOlkP8n.png)
http://www.zdnet.com/

I use current:
```
@@||googletagservices.com/tag/js/gpt.js$domain=zdnet.com
```

**Comment by Alex-302** [comment]
Added to Russian filter, because site is broken by it.

**Comment by Alex-302** [comment]
No, removed it from Russian.
