### ISSUE TITLE
solidfiles.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1907]
Link - https://www.solidfiles.com/v/GwjqyvGemGXDk
Recording - https://www.dropbox.com/s/ae2m0efpko5277h/solidfiles.mov?dl=0
Reporter - PUX-573-53673

**Comment by Alex-302** [comment]
added
solidfiles.com##div[style$="position: absolute; z-index: 999999; cursor: pointer;"]
