### ISSUE TITLE
http://tanken.t-online.de/search/diesel/harsefeld - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1908]
With Adguard

![image](https://cloud.githubusercontent.com/assets/15856304/14242156/7544bbdc-fa58-11e5-91f2-f1044f7a7ff0.png)

Without Adguard

![image](https://cloud.githubusercontent.com/assets/15856304/14242160/7d90a3d2-fa58-11e5-80b9-67f9db189001.png)

**Comment by Alex-302** [comment]
Added to English
@@||cdn.interactivemedia.net/live/t-o-auto/live/globalAdTag.min.js$domain=tanken.t-online.de
