### ISSUE TITLE
citibank.com site is distorted

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1914]
![image](https://cloud.githubusercontent.com/assets/15856304/14277603/a1cb92a0-fb2c-11e5-9146-ed457f5e5196.png)

https://online.citi.com/US/Welcome.c

**Comment by Vincent-Michael** [comment]
try:
``` @@||online.citi.com/GFC/branding/ ```

**Comment by Alex-302** [comment]
Thanks, added.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
which filers are enabled?
