### ISSUE TITLE
zhidao.baidu.com - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1918]
Missed ad on page:
http://zhidao.baidu.com/question/467872980.html?word=iphone3gs%E6%81%A2%E5%A4%8D%E6%A8%A1%E5%BC%8F&fr=wenda_ala&device=mobile&ssid=0&from=1099b&uid=0&pu=usm@1,sz@1320_2001,ta@iphone_1_9.3_3_601&bd_page_type=1&baiduid=10C2BD65E07226A108CE07A125E63BAB&tj=wenda_1_0_10_title

![image](https://cloud.githubusercontent.com/assets/15856304/14292374/79435676-fb70-11e5-8b35-e956ac4abab4.png)

**Comment by Alex-302** [comment]
added to Safari filter
zhidao.baidu.com##div[class^="mm-content-box kmb5707e0 wm-"]
||entry.baidu.com/rp/home?
