### ISSUE TITLE
[iOS] konachan.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1921]
http://konachan.net/post?page=1&tags=
![image1](https://cloud.githubusercontent.com/assets/14153331/14303469/aee3758e-fbb3-11e5-896c-3306d1d21dcc.PNG)
TWR-489-74391

**Comment by Alex-302** [comment]
@Bohdan-SUP 
please check this rule with user's filters list
```
konachan.net##iframe[src^="https://tbib.org/"]
```

**Comment by evgeniy-ADG** [comment]
@Alex-302 it works

**Comment by Alex-302** [comment]
@evgeniy-ADG 
thanks, added to Safari filter
