### ISSUE TITLE
bigcinema.tv - anti adblock script

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1926]
http://bigcinema.tv/series/razrushiteli-legend-serial-2003-mythbusters.html

![image](https://cloud.githubusercontent.com/assets/15856304/14314769/fb420870-fc01-11e5-96e7-27e8e451127c.png)

**Comment by Vincent-Michael** [comment]
``` @@||bigcinema.tv/uploads/partner/advert.js ```

**Comment by Alex-302** [comment]
Thanks, added.
