### ISSUE TITLE
rutracker.net - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1931]
rutracker.net
http://prntscr.com/ap6u9m

![image](https://cloud.githubusercontent.com/assets/15856304/14382087/e89dc64e-fd93-11e5-825e-5efa5225e221.png)

HQ,https, фильтры новые

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Чисто же. Ещё вчера правила добавлял. У тебя тоже реклама и всё отзеркалено?

**Comment by evgeniy-ADG** [comment]
@Alex-302 да, скрин мой

**Comment by Alex-302** [comment]
@evgeniy-ADG 
а какой браузер?
У нас на одном устройстве в фоксе чисто, а на другом есть баннер, но зеркальности нет.

**Comment by evgeniy-ADG** [comment]
и в хроме, и в фоксе. и в эдже.

**Comment by evgeniy-ADG** [comment]
вот само внезапно в хроме стало незеркальнім, в фф - так и осталось

**Comment by Alex-302** [comment]
фф правила JS не загружает при обновлении. Так мозилла придумала.
