### ISSUE TITLE
Can't play embed Coub videos in Vk.com

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/ExperimentalFilter#1932]
Can reproduce it with Yandex browser extension.
Also it is possible to reproduce using Chrome.

example: http://vk.com/adguard?z=video-50189302_456240509%2F0cb38a263936634576%2Fpl_post_-53764934_5043

Could be because we are blocking https://rs.mail.ru/crossdomain.xml with russian filter?

adding @@||rs.mail.ru/crossdomain.xml$domain=vk.com,third-party to user filter possibly helps but feels to be slowing down video loading

**Comment by Alex-302** [comment]
added
download speed is not changed
