### ISSUE TITLE
http://pb.wtf/ - ads + anti adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1938]
![image](https://cloud.githubusercontent.com/assets/15856304/14403394/4cd96c84-fe5d-11e5-928d-83688506cf26.png)

**Comment by Vincent-Michael** [comment]
https://dl.dropboxusercontent.com/u/28576971/advert.js funny xD

``` pb.wtf#%#window.ab = false; ```

**Comment by Alex-302** [comment]
added
