### ISSUE TITLE
[Android] lenta.ru - custom rule request

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1940]
Please provide a rule to block this element on Android:
http://prntscr.com/apzu0x

**Comment by crawlingroof** [comment]
https://lenta.ru/news/2016/04/08/saudifootball/

lenta.ru###root > SECTION.b-header-main:nth-child(4)
lenta.ru###root > SECTION.b-layout.js-layout.b-layout_main:nth-child(5) > DIV.g-layout > DIV.row > DIV.span4.b-sidebar-stickycolumn:last-child
lenta.ru###root > SECTION.b-tabloid:nth-child(7)
lenta.ru###footer
lenta.ru###root > NAV.b-sidebar-menu:nth-child(2)
lenta.ru###root > NAV.b-tags-list.js-tags:nth-child(5)
lenta.ru###root > DIV.b-topic-layout:nth-child(6) > DIV.g-layout > DIV.row:first-child > DIV.span4:last-child
lenta.ru###root > DIV.b-topic-layout:nth-child(6) > DIV.g-layout > DIV.row:first-child > DIV.span8:first-child > DIV.b-topic.b-topic_news > DIV.b-topic__content:first-child > DIV.b-text.clearfix:last-child > ASIDE.b-inline-topics-box.b-box_floated.b-inline-topics-box_wide.b-box_left:nth-child(4)
lenta.ru###root > DIV.b-topic-layout:nth-child(6) > DIV.g-layout > DIV.b-topic-longgrid.b-topic-addition:last-child
lenta.ru###root > DIV.b-topic-layout:nth-child(6) > DIV.g-layout > DIV.row:first-child > DIV.span8:first-child > DIV.b-topic.b-topic_news > SECTION.b-topic-addition.b-links:nth-child(4)
lenta.ru###root > SECTION.b-header-inner:nth-child(4)

**Comment by crawlingroof** [comment]
Works fine with browser plugin and doesn't work on the phone.
The rules was created by the mouse selection.

**Comment by Alex-302** [comment]
@crawlingroof 
this domain is encripted (HTTPS), so you should to install beta version and enable HTTPS filtering.

**Comment by crawlingroof** [comment]
Thank you very much, work like a charm.
