### ISSUE TITLE
megaserial.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1941]
Link - http://megaserial.net/2531-posledniy-chelovek-na-zemle.html 
Screenshots - http://prntscr.com/aq0hte
Reporter - https://yadi.sk/i/ldhhuNDCqqmAQ

**Comment by Vincent-Michael** [comment]
http://forum.adguard.com/showthread.php?10499-http-megaserial-net
