### ISSUE TITLE
[Android] OLX.ua Free Classifieds

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1942]
https://play.google.com/store/apps/details?id=ua.slando&hl=en
Не переходит в раздел "Избранные", выдает ошибку: http://prntscr.com/apn2q1
Помогает отключение Английского фильтра

**Comment by Alex-302** [comment]
Added to mobile filter:
@@||olx.ua/*/observed/getads/?json=

**Comment by Alex-302** [comment]
Проблема ж только с фильтрацией HTTPS?
