### ISSUE TITLE
http://www.digitaltrends.com/photography/what-is-golden-hour/ - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1945]
![image](https://cloud.githubusercontent.com/assets/15856304/14410825/04e77a6c-ff41-11e5-8b08-6abe11d21b23.png)

**Comment by Vincent-Michael** [comment]
``` digitaltrends.com##.m-bonus ```

**Comment by Alex-302** [comment]
added to English filter
