### ISSUE TITLE
Irremovable "Turn off your adblocker" pop-up appears on www.echoes.gr

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/ExperimentalFilter#1948]
Making it impossible to browse.

**Comment by Bohdan-SUP** [comment]
![screen shot 2016-04-11 at 8 55 59 am](https://cloud.githubusercontent.com/assets/14153331/14417942/3c00975e-ffc3-11e5-9d6d-e5736aad2abb.png)

**Comment by Alex-302** [comment]
added to Safari filter
```
@@||echoes.gr^$elemhide
@@||echoes.gr/*/adsManager
```
