### ISSUE TITLE
Remove ads from a 3DNews newsletter

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1949]
1. Sign up for newsletter here - http://www.3dnews.ru/subscribe
2. Get the following:
http://prntscr.com/aqees5
http://prntscr.com/aqrx1s

Is there any way to remove it from the body letter?

**Comment by Alex-302** [comment]
Подписался. Посмотрим.

**Comment by Alex-302** [comment]
it is impossible in general
