### ISSUE TITLE
[iOS] animeflv.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1953]
http://animeflv.net/
<details>
on iOS
![image1](https://cloud.githubusercontent.com/assets/14153331/14422675/a8175398-ffe0-11e5-95c8-ee12c6039cf1.PNG)
on a Mac - click anywhere and it opens a new tab:
![screen shot 2016-04-11 at 12 27 12 pm](https://cloud.githubusercontent.com/assets/14153331/14422714/d1cd7848-ffe0-11e5-9413-8b7f0bebfa2e.png)

**Comment by Alex-302** [comment]
added to English filter:
||cloudfront.net^$domain=animeflv.net
