### ISSUE TITLE
chatropolis.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#1955]
http://underground.chatropolis.com:1588/chat/amazing

When you enter the chat with Adguard enabled, no old or new messages are visible. The issue is not present when you enter the chat room with disabled Adguard. The problem is NOT with Stealth Mode, according to users observations.

Original post: http://forum.adguard.com/showthread.php?10458

**Comment by Alex-302** [comment]
I can't fix it without remote access. 
Closed here.
