### ISSUE TITLE
[Extension] https://www.usaa.com - false positive 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1956]
In order for me to view the information on the main tiles of my back website I have to tun of the protection on Ad Blocker. This does not make sense, since I am able to view the information in the sub-tiles.

Please check screenshots: OGA-788-20045

**Comment by evgeniy-ADG** [comment]
Customer added the site to the whitelist, it helped.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
в чём собственно проблема?

**Comment by evgeniy-ADG** [comment]
We should add this to the white list. Customer refused giving us a remote access.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
можешь попросить адрес испорченной страницы?
Передай на проверку:
```
@@||usaa.com^$generichide
```

**Comment by evgeniy-ADG** [comment]
Мы поссорились из-за моего не очень разумного предложения организовать тимвьювер сессию. Передал правило.

**Comment by Alex-302** [comment]
Неадекватный?)
Ответа от него нет?

**Comment by evgeniy-ADG** [comment]
Он говорит, что все работает и без правила,  потому что мы со своей стороны вроде как полностью завайтлистили домен. Ну, это банки там вряд лиесть реклама в принципе.

**Comment by Alex-302** [comment]
отключено только сокрытие элементов
закрываю
