### ISSUE TITLE
Can't sign in to Flickr

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1957]
I cannot sign in to Flickr from my main computer. I can sign in from another computer, and can view files in Flickr. I can sign in to Yahoo, but still cannot then access Flickr. I can publish to my Photostream in this account from within Lightroom which is already set up before this problem began. iF I DISBALE ADGUARD PROTECTION IT LETS ME SIGN IN.

<details>
Os version: Microsoft Windows NT 10.0.14295.0
Dot .net version: 2.0; 3.0; 3.5; 4.0 Client Profile; 4.0 Full Profile;
ApplicationId: feeafb9b83254c1cb65be4cada9c9c15
Language: en
AppVersion: 6.0.204.1025
Main settings: 
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:6 Name: German filter Url: http://adguard.com/ru/filter-rules.html?id=6
FilterId:10 Name: Filter for useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:113 Name: Liste FR Url: https://easylist-downloads.adblockplus.org/liste_fr.txt
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Wfp
Ads Blocked: 147689, Trackers Blocked: 118308
Filtering Mode: Driver
Application lifetime: 50.08:04:08.4641855
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false

**Comment by Alex-302** [comment]
@evgeniy-ADG 
please check these rules:
```
@@||login.yahoo.com/config/
@@||flickr.com/register_cookies.gne?
@@||flickr.com/signin/
@@||accounts-flickr.yahoo.com^
@@||flickr.com/cookie_
```
