### ISSUE TITLE
minigames.mail.ru - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1959]
https://minigames.mail.ru/preferans?_1lr=570ba5c21971a4ed-300-171859_866_0-171859_866_0&site_id=1_866_71859_0

![image](https://cloud.githubusercontent.com/assets/15856304/14428666/aa04a490-0002-11e6-83a0-b9dc409bc972.png)

включен руский, англ, спайвер, соушл, германский, изи лист чехия-словкая и изи лист италия

**Comment by Alex-302** [comment]
@evgeniy-ADG 
может фильтры старые, или исключение в пользовательском?
 У меня абсолютно чисто.

**Comment by Alex-302** [comment]
добавил в русский
mail.ru##.rb-container
