### ISSUE TITLE
http://www.btshoufa.net/forum.php - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1960]
![image](https://cloud.githubusercontent.com/assets/15856304/14428759/25ebb3fa-0003-11e6-8605-ff42735c2e4c.png)

![image](https://cloud.githubusercontent.com/assets/15856304/14428773/37546646-0003-11e6-9deb-00048ec08567.png)

**Comment by Alex-302** [comment]
These ads can be blocked by Easylist China(tested). Maybe this filter is not enabled.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
added to Safari filter
```
||cnbole.net^$third-party
||jisucn.com^$third-party
||qiqiww.com^$third-party
||vip.sc386.com^$third-party
```
user should to check this site after filters update
