### ISSUE TITLE
ABP Japanese blocks google maps features like street view, obtaining info about restaurants etc

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1964]
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:7 Name: Japanese filter Url: http://adguard.com/ru/filter-rules.html?id=7
FilterId:9 Name: Spanish/Portuguese filter Url: http://adguard.com/ru/filter-rules.html?id=9
FilterId:10 Name: Filter for useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:104 Name: EasyList China Url: https://easylist-downloads.adblockplus.org/easylistchina.txt
FilterId:200 Name: ABP Japanese Filters Url: https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abp_jp.txt

Worked fine on my side when disabled ABP Japanese

**Comment by Alex-302** [comment]
added to ABP Japanese on our side
```
@@||google.*/maps/_/js/
```
