### ISSUE TITLE
Hide your IP issue on www.foxnews.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1966]
![image](https://cloud.githubusercontent.com/assets/15856304/14475226/a23066fc-0109-11e6-83e9-ca7e94f1b358.png)

http://www.foxnews.com/us/2016/04/12/man-who-murdered-mother-and-brother-had-brain-injury-family-claims.html?intcmp=hpbt4

**Comment by Alex-302** [comment]
fixed
