### ISSUE TITLE
iemulators.com - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1967]
http://iemulators.com/airshou

![image](https://cloud.githubusercontent.com/assets/15856304/14475534/1c933d7e-010b-11e6-8764-00bb6715cecc.png)

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.81.39 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.27 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.32 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.24.84 Enabled=YES
ID=10 Name="Filter for useful ads" Version=1.0.0.89 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.8 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID=101 Name="EasyList" Version=1.0.55.83 Enabled=YES
ID=102 Name="ABPindo" Version=1.0.0.61 Enabled=YES
ID=103 Name="Bulgarian list" Version=1.0.0.6 Enabled=NO
ID=104 Name="EasyList China" Version=1.0.56.5 Enabled=YES
ID=117 Name="Adblock Polska" Version=1.0.0.52 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.55.73 Enabled=YES
ID=120 Name="Norsk adblockliste" Version=1.0.0.1 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.55.95 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.55.84 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.1.46 Enabled=YES
ID=205 Name="Schacks Adblock Plus liste" Version=1.0.1.29 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.55.88 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.59 Enabled=YES
ID=216 Name="Adblock polskie reguÅ‚y" Version=1.0.3.57 Enabled=YES
ID=217 Name="Adblock polskie reguÅ‚y cookies" Version=1.0.1.1 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.0.58 Enabled=YES
ID=220 Name="CJXsAnnoyanceList" Version=1.0.0.31 Enabled=YES

**Comment by Alex-302** [comment]
Please try to disable filters ```#101-220```
