### ISSUE TITLE
[iOS] vidoser.org

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1971]
PAS-807-95801
https://vidoser.org/video/HMQkV5cTuoY/be-deutsch-achtung-germans-on-the-rise-neo-magazin-royale-mit-jan-b-hmermann-zdfneo/
![screen shot 2016-04-13 at 6 16 18 am](https://cloud.githubusercontent.com/assets/14153331/14481820/50ea1154-013f-11e6-9d51-b9c529540de4.png)

**Comment by Alex-302** [comment]
added to Safari filter
```
@@||vidoser.org^$elemhide
```
