### ISSUE TITLE
[iOS] lifehacker.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1972]
http://lifehacker.com/5833969/the-best-calendar-app-for-iphone?utm_campaign=socialflow_lifehacker_twitter&utm_source=lifehacker_twitter&utm_medium=socialflow
![screen shot 2016-04-13 at 6 21 26 am](https://cloud.githubusercontent.com/assets/14153331/14481923/08538438-0140-11e6-9b9e-e6bbfc0f5f1e.png)
XME-189-45841

**Comment by Alex-302** [comment]
@Bohdan-SUP 
please check this rule
```
lifehacker.com##.ad-unit
```

**Comment by Alex-302** [comment]
added
