### ISSUE TITLE
[Windows] http://www.rf-cheats.ru/forum/index.php  missed adds 

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/ExperimentalFilter#1973]
screenshot: https://embed.gyazo.com/113ed7b8827181e6f3ef3fb609af4254.png

**Comment by Alex-302** [comment]
added
rf-cheats.ru##a[rel="nofollow"]:not([id="community"]) > img

**Comment by vozersky** [comment]
User states: "Правила работают, реклама не лезет, но режут лишнее, на скриншотах пример с включенным и выключенным фильтром, пропадают кнопки цитирования и другие. Так же пропадает кнопка создать новую тему на форуме. Если не сложно, исправьте, пожалуйста. Или скажите где что исправить. (дополнительных пользовательских фильтров нет)"

![9yiy-nfzbnu](https://cloud.githubusercontent.com/assets/17472907/15297653/f75318a0-1ba3-11e6-82d9-9dc1691616ad.jpg)
![nwgwzir8ppa](https://cloud.githubusercontent.com/assets/17472907/15297654/f7538aba-1ba3-11e6-8819-50f91fcf37f5.jpg)

**Comment by Alex-302** [comment]
@vozersky 
удалил это правило.Пусть проверит наличие рекламы.
