### ISSUE TITLE
Missed Ads city-n.ru

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#1974]
http://city-n.ru/

Проблема повторилась, фильтры базовые. расширений в браузере нет. По всему сайту реклама.

![imag33e](https://cloud.githubusercontent.com/assets/16462533/14495013/5f1d377c-0196-11e6-8ba3-3a1649cf47aa.png)

**Comment by Alex-302** [comment]
||ad.hutor.ru^
добавил в русский
