### ISSUE TITLE
http://www.serienjunkies.de/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1976]
![image](https://cloud.githubusercontent.com/assets/15856304/14504001/6d8e6bee-01bb-11e6-8060-948c89e408a7.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.81.67 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.29 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.34 Enabled=YES
ID=6 Name="German filter" Version=1.0.24.78 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.10 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.56.25 Enabled=YES

**Comment by Alex-302** [comment]
@evgeniy-ADG 
added to German filter
```
@@/ad_bomb/*$image,domain=serienjunkies.de
```
Waiting for user confirmation.
