### ISSUE TITLE
https://skladchik.com - blocking menu

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1977]
Adguard is off
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/14509045/1429d332-01d3-11e6-800e-486f3daaa644.png)
</details>
Adguard is off
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/14509219/e3a93454-01d3-11e6-88b8-3abac536f092.png)
Assistand hasn't appeared after 30 sec unblocking
</details>
Basic filter set. You need to log in, you may use yoji534 as a login and 99439943 as a pass

**Comment by Alex-302** [comment]
I need email as user name to login

**Comment by evgeniy-ADG** [comment]
saveenko@gmail.com

**Comment by evgeniy-ADG** [comment]
@Alex-302

**Comment by Alex-302** [comment]
added
skladchik.com#@#.shares
