### ISSUE TITLE
com.ideanomix.cooking.free - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1978]
https://play.google.com/store/apps/details?id=com.ideanomix.cooking.free

![photo_2016-04-14_18-58-26](https://cloud.githubusercontent.com/assets/5947035/14534729/1f88245e-0273-11e6-903e-80ad3bdc8797.jpg)
x

**Comment by Alex-302** [comment]
added to mobile filter:
```
||graph.facebook.com/network_ads$empty
