### ISSUE TITLE
www.fxp.co.il - no assistant, missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1981]
Works fine in chrome, the issue was spotted and reproduce in IE11 
https://www.fxp.co.il/forumdisplay.php?f=16

![image](https://cloud.githubusercontent.com/assets/15856304/14539027/2fe58db4-0287-11e6-8312-213d921e1bad.png)

Customer reported that he sees an ad where we see 404 not found banner. Please have a look.

ECU-279-60801

**Comment by Alex-302** [comment]
to English
fxp.co.il##div[style^="position: fixed;width: 162px; height: 600px;"]
