### ISSUE TITLE
http://www.porn.com/ - pop-ups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1982]
Steps to reproduce:

1. Go to the site
2. Open videos until you see a popup in a separate tab
3. URL of the popup constantly changes until it stops on smth like that http://randevu-euro.com/?btag=a_5792b_357c_porn.com

**Comment by Alex-302** [comment]
added to eng
porn.com#%#document.cookie = "pu_count=1";
