### ISSUE TITLE
http://kino-dom.org, linecinema.org - pop up 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1985]
до последнего обновления ни разу не выдавал редирект на сайтах kino-dom.org и linecinema.org, но после обновления пропускает один и тот же сайт - mxttrf.com, который перенаправляет на озон.

**Comment by evgeniy-ADG** [comment]
у меня повторяется

**Comment by Alex-302** [comment]
в русский, для обоих сайтов:
||log.kino-dom.org^
