### ISSUE TITLE
[iOS] Unable to open https://www.creditkarma.com from the email

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1986]
When clicking on an email link page doesn't close because of an error with Adguard 
https://www.creditkarma.com/events/redirect/mailing?nid=71801660&aid=2419977818&ooc=Z9FCYHAQQ4DP4ONXNWBF&campaignName=chase_freedom_2&returnurl=http%3A%2F%2Fclick.linksynergy.com%2Ffs-bin%2Fclick%3Fid%3D1r4CW8FNFWA%26offerid%3D413876.10002609%26type%3D3%26subid%3D0%26u1%3D%5Bckanonid%5D+&eventcode=TakeCCOffer&eventinformation=chase_freedom_2&ovkey=71801660&adcopy=CTAButton&site=CreditKarma&ovmtc=chase_freedom_2&adgroup=email

http://prntscr.com/asjetg - adg is enabled
http://prntscr.com/asjf65 - disabled

Caused by Mobile ad filter

**Comment by Alex-302** [comment]
@evgeniy-ADG 
please check this rule
```
@@||ad.doubleclick.net/ddm/clk/*?https://creditcards.chase.com/
```
I'm waiting for user's answer.

**Comment by evgeniy-ADG** [comment]
Ждем.

**Comment by Bohdan-SUP** [comment]
User confirmed this helps, please add to filters.

**Comment by Alex-302** [comment]
Added to mobile filter.
