### ISSUE TITLE
http://www.neodrive.co popups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1988]
http://www.neodrive.co/share/file/ANUN2KCRDSUZKDOUZ4UZXNAVWIIHHDPHOC

press the Play and the popup appear in the separate tab: https://www.favbet.com/static/media/promo/promo13/index.html

**Comment by evgeniy-ADG** [comment]
Also, please have a look:

orillavid isn't something I visit often but any link ends up saying this
after I close a pop up on new tab. "Request blocked by Adguard Ad Blocker
module. If you want to access this site, add it to exceptions."
http://gorillavid.in/36kwdd1dgow9 example

With videomega.tv I found a way to stop pop ups by adding this : ||
videomega.tv/pop$popup

Videowood.tv I noticed it's not an Adguard issue. I tried Ublock origin
with firefox and videowood still had pop ups. I guess their site must have
found a way to force some ads. but I noticed using this code : ||
videowood.tv/pop$popup closes pop ups for now.

**Comment by Alex-302** [comment]
added to Eng
neodrive.co##div[id]:not([id="container"]):not([style])

about gorillavid.in - video not found.
Please don't consolidate few issues to one.

**Comment by Alex-302** [comment]
http://gorillavid.in/i9zn5l2xrzr9
is absolutely clean on my end
