### ISSUE TITLE
[Windows] www.streamcloud.eu/ - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1990]
![](http://i.imgur.com/cjLgktI.png)
http://streamcloud.eu/oa3gnnlvzzjq/.html

``` ||badtopwitch.work^$third-party ```

**Comment by Alex-302** [comment]
@Vincent-Michael 
didn't you get clickunder when pressing "Watch..."?
If yes, please check
```
streamcloud.eu#%#Object.defineProperty(window, 'UAParser', { get: function() { return function() { }; } });
```

**Comment by Vincent-Michael** [comment]
> didn't you get clickunder when pressing "Watch..."?

nope

**Comment by Alex-302** [comment]
strange
added both rules
