### ISSUE TITLE
breitbart.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1991]
Link - http://www.breitbart.com/video/2016/04/14/ted-cruz-stands-by-claim-mitch-mcconnell-lied/
Screenshots - 
![screen](https://cloud.githubusercontent.com/assets/14153331/14574990/869253be-0367-11e6-9acf-270a241c7576.png)

Reporter - FCB-689-73584

**Comment by Alex-302** [comment]
I don't see the overlay on layer.
Top right buttons are just litks to their social blogs. We don't block them.
Big "like" button is blocked now:
```
breitbart.com###iscfbbblikewidget
```
For remains of ads:
```
breitbart.com###SideW > div[class="ad Hmobi SWW"]
```
@Bohdan-SUP 
could you check this overlay?

**Comment by Bohdan-SUP** [comment]
Yup, all good now.
