### ISSUE TITLE
appdnt.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1992]
appdn.net
![screen shot 2016-04-16 at 6 13 18 am](https://cloud.githubusercontent.com/assets/14153331/14578776/62784ff0-039a-11e6-800a-77aa29afab30.png)
OSZ-147-57544

**Comment by Alex-302** [comment]
@Bohdan-SUP 
не повторяется. У тебя выскакивает это сообщение?

**Comment by Bohdan-SUP** [comment]
Да, скрин мой.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
проверь
```
@@||appdnt.net^$generichide
```

**Comment by Bohdan-SUP** [comment]
Больше не повторяется проблема.
