### ISSUE TITLE
online.anidub.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1994]
http://online.anidub.com/anime_tv/full/9397-pozhiratel-bogov-god-eater-01-iz-13.html
http://prntscr.com/asv1zz
GTG-672-64194

**Comment by Alex-302** [comment]
@Bohdan-SUP 
для баннера
```
online.anidub.com###banner_test iframe
```
персонажа справа на иос не убрать.
