### ISSUE TITLE
ifirstrowuk.eu

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#1996]
http://ifirstrowuk.eu/
Make sure to check with **UK IP**
![screen shot 2016-04-16 at 5 26 35 pm](https://cloud.githubusercontent.com/assets/14153331/14581569/d39c10d2-03f8-11e6-89b1-859b525ddbcd.png)

**Comment by Alex-302** [comment]
can't reproduce.
Please try
```
@@||ifirstrow.eu/advertisement.js
```

**Comment by Alex-302** [comment]
also I need the filters list(always)

**Comment by Bohdan-SUP** [comment]
Seems to be fixed even without extra rule.

**Comment by Alex-302** [comment]
ok, closed
