### ISSUE TITLE
Cheatsheet "Paid Content" section isn't filtered

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/ExperimentalFilter#1997]
Example: http://www.cheatsheet.com/culture/5-ways-to-save-big-money-when-buying-meat.html

The (labeled) "Paid Content" section between the article navigation (toward page middle) & "More Articles Abound" should be erased.

Thanks in advance, @AdguardTeam! ☺

**Comment by Alex-302** [comment]
added
```
cheatsheet.com#%#Object.defineProperty(window, 'xh', { get: function() { return []; } });
```
