### ISSUE TITLE
club.foto.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2000]
http://club.foto.ru/forum/11
http://prntscr.com/atb5f1

реклама + нет значка Помощника

**Comment by Alex-302** [comment]
@Bohdan-SUP 
нужно проверить пользовательский фильтр. Похоже на исключение.

**Comment by Bohdan-SUP** [comment]
Там проблема очень нестабильная, рекламу то фильтрует, то нет. Фильтры все обновлены, в юзерфильтре пусто.
Последние несколько дней вот в порядке.
