### ISSUE TITLE
Broken website - klart.se

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2001]
ADG on:
![screen shot 2016-04-18 at 7 08 24 pm](https://cloud.githubusercontent.com/assets/14153331/14611044/0b6d00e2-0599-11e6-8331-0e5c5bcfeadc.png)
ADG off:
![screen shot 2016-04-18 at 7 08 38 pm](https://cloud.githubusercontent.com/assets/14153331/14611043/0b68a8a8-0599-11e6-8c72-cf16d5c655bf.png)

**Comment by Alex-302** [comment]
added to English filter:
klart.se###advertisement-top
klart.se#@#.advertisement
