### ISSUE TITLE
[iOS] ircity.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2004]
https://ircity.ru/news/11975/
![image1-2](https://cloud.githubusercontent.com/assets/14153331/14615654/6e192002-05af-11e6-98cc-437e5f2c4fe8.PNG)
WRK-337-64544

**Comment by Alex-302** [comment]
Добавил в мобильный фильтр
ircity.ru##.cr_mobile_banner
