### ISSUE TITLE
www.google.com - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2010]
Missed ad on page:
https://www.google.com/search?q=forex+broker&ie=UTF-8&oe=UTF-8&hl=en-cy&client=safari

![image](https://cloud.githubusercontent.com/assets/15856304/14645866/021ef2c6-0660-11e6-8d2b-336970a9bcec.png)

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.81.95 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.36 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.41 Enabled=YES
ID=10 Name="Filter for useful ads" Version=1.0.0.89 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.33.9 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.15 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES

**Comment by Alex-302** [comment]
@evgeniy-ADG 
вот причина
ID=10 Name="Filter for useful ads" Version=1.0.0.89 Enabled=YES
объясни, плиз, юзеру, что этот фильтр разблокирует контекстную рекламу
