### ISSUE TITLE
[Stealth mode] can't login to amazon.com / audible.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2011]
I can't log on to Amazon or Audible since I purchased Adguard. I tried to logon by disabling Adguard when at the logon page, but with no success. I have worked with Amazon and Audible tech support and I do have the correct logon id and password. I am not sure that Adguard is the issue. Still, it may be an attack by these companies to disuade people from using adguard. I have no idea. I have Googled for a solution, but canfind none so far. Can you help me please?

**Comment by Alex-302** [comment]
can't reproduce with enabled all options.

**Comment by Alex-302** [comment]
For audible added
@@||audible.com^$stealth
