### ISSUE TITLE
https://my.bmi.ir/portalserver/index

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2018]
https://my.bmi.ir/portalserver/index is blocked, it's a bank.

![image](https://cloud.githubusercontent.com/assets/15856304/14681413/a5afb438-0729-11e6-9067-611b18a55c00.png)

If you disable Adguard:
![image](https://cloud.githubusercontent.com/assets/15856304/14681425/b0f17bb0-0729-11e6-9b9b-47cfcf96935f.png)

TXH-521-31053

**Comment by Alex-302** [comment]
Added to English filter
@@||my.bmi.ir^$elemhide,jsinject
