### ISSUE TITLE
http://videowood.tv/embed/t4vu - pop up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2019]
![image](https://cloud.githubusercontent.com/assets/15856304/14682076/971a8530-072c-11e6-93bf-54412b32acb4.png)

Basic filters set.

LFG-505-45447

**Comment by Bohdan-SUP** [comment]
Check the recording as well:
https://www.dropbox.com/s/mj3qzi5en1hh9cn/videowood.mov?dl=0

**Comment by Alex-302** [comment]
Added
||videowood.tv/pop^$popup

**Comment by evgeniy-ADG** [comment]
About videowood.tv. I have Anti-Adblock Killer list and script, but I still have a message that I must disable adblock, so I added my own rule @@||videowood.tv$generichide
With this rule, adblock is not detected, but with my rule, this rule does not work ||videowood.tv/pop^$popup and I have a popups.
In my opinion $generichide should not allow for popups.
I made video - https://www.youtube.com/watch?v=gX9FMWddiG8&feature=youtu.be
Link - http://videowood.tv/embed/pi2l

Please advise

**Comment by Alex-302** [comment]
Please check these rules:
```
videowood.tv#%#document.cookie = "lvid_main=true"; document.cookie = "vid_sub=1"; document.cookie = "vid_subpub=3";
@@||videowood.tv$generichide
```

**Comment by Alex-302** [comment]
добавил
