### ISSUE TITLE
http://talisma.ru/ - we're blocking too much

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2020]
http://talisma.ru/catalog/rings/koltso_emiliya/

Скрывается div с id="carousel-example-generic". Думаю, потому, что одним из его стилей является "top_banner".

Мне кажется, это не очень эффективный метод фильтрации рекламы т.к. он влечет за собой множество ошибок определения.

![image](https://cloud.githubusercontent.com/assets/15856304/14684211/8008525e-0737-11e6-81f1-457b0cb7fa5c.png)

PYT-339-96366

**Comment by Alex-302** [comment]
Добавил в русский:
talisma.ru#@#.top_banner
Сработавшее правило редко даёт ложные срабатывания.
