### ISSUE TITLE
[Android] com.wGdeposyilka22

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2022]
https://play.google.com/store/apps/details?id=com.wGdeposyilka22&hl=ru

Реклама выходит как при открытии программы так и при закрытии.
http://prntscr.com/avb778
http://prnt.sc/avcfr8

Лог - IKS-519-96078

**Comment by Alex-302** [comment]
||splash.appsgeyser.com^$empty
||gdeposylka.ru/js/primatic.js?_=
