### ISSUE TITLE
newser.com - videos do not work in Safari

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#2024]
Example url:
http://www.newser.com/story/223823/science-reveals-freddie-mercurys-singing-secrets.html?utm_source=part&utm_medium=usatoday&utm_campaign=syn

Source report:
http://forums.macrumors.com/threads/the-el-capitan-safari-9-content-blocker-thread.1924936/page-11#post-22819828

Rules to fix (to Safari filter):
```
@@||static1-azcdn.newser.com/javascript/
@@||static2-azcdn.newser.com/javascript/
```

**Comment by Alex-302** [comment]
Added
