### ISSUE TITLE
photo.amc-club.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2029]
http://photo.amc-club.ru/Pbp#
User reported on iOS (IQT-886-73552), reproduced on desktop:
ADG on - ![screen shot 2016-04-23 at 5 18 49 pm](https://cloud.githubusercontent.com/assets/14153331/14761972/82d80654-0977-11e6-8947-2fe24d491021.png)

ADG off - ![screen shot 2016-04-23 at 5 18 40 pm](https://cloud.githubusercontent.com/assets/14153331/14761973/82ee6160-0977-11e6-832a-f19abcd377f8.png)

**Comment by Alex-302** [comment]
added to Russian
@@||photo.amc-club.ru/*/js/adbanner.js
