### ISSUE TITLE
market.cmbchina.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2031]
http://market.cmbchina.com/ccard/gqcard/

Click on this button:
![screen shot 2016-04-23 at 9 20 22 pm](https://cloud.githubusercontent.com/assets/14153331/14763297/28301e08-099a-11e6-93c0-ffc19eb95e01.png)

Adguard is blocking the following pop-up:
![screen shot 2016-04-23 at 9 26 21 pm](https://cloud.githubusercontent.com/assets/14153331/14763304/4a9017c8-099a-11e6-82ec-bf7238e4090f.png)

**Comment by Alex-302** [comment]
added to Eng
```
@@||cmbchina.com/ccard/gqcard/js/pop.js
```
