### ISSUE TITLE
forum.ykt.ru

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/ExperimentalFilter#2034]
http://forum.ykt.ru/
http://forum.ykt.ru/viewforum.jsp?id=29
http://forum.ykt.ru/viewtopic.jsp?id=3969350

![xagd-zdkjxe](https://cloud.githubusercontent.com/assets/17472907/14766527/9c20444c-0a16-11e6-9864-43ea15824b4f.jpg)
![tx59tqq9iwy](https://cloud.githubusercontent.com/assets/17472907/14766529/9fb3e276-0a16-11e6-893b-307aa42ac176.jpg)
![_rvlvlzsa1m](https://cloud.githubusercontent.com/assets/17472907/14766530/a1a9ca00-0a16-11e6-966a-682eabad49f4.jpg)

**Comment by vozersky** [comment]
пока посоветовал юзеру добавить в пользовательский фильтр most3.ykt.ru
насколько корректно будет внести в русский фильтр?

**Comment by Alex-302** [comment]
added to Russian filter
```
||most3.ykt.ru/session?
ykt.ru##.topic-adv
ykt.ru##.banner-desktop
ykt.ru##.static-adv
ykt.ru##.d-advs
joker.ykt.ru##img[title="Реклама!"]
```
