### ISSUE TITLE
eminem.pro

### ISSUE THREAD

**Issue by a-ladanov** [AdguardTeam/ExperimentalFilter#2035]
http://www.eminem.pro/
Для фильтра виджетов.
Справа пустые белые блоки. Убрать бы их.
![default](https://cloud.githubusercontent.com/assets/18179397/14769217/721761a6-0a6d-11e6-9647-c03edb9fae95.png)

**Comment by Alex-302** [comment]
добавил в фильтр соц сетей
eminem.pro,igromania.ru##div[id^="vk_groups"]
