### ISSUE TITLE
Postings (Craigslist App) - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#2036]
https://play.google.com/store/apps/details?id=com.trixiesoft.clapp&hl=en

Source report:
http://forum.xda-developers.com/showpost.php?p=66512108&postcount=1074

**Comment by Alex-302** [comment]
Can't reproduce. Asked for the log.

**Comment by Alex-302** [comment]
added to mobile filter:
```
||kinesis.us-east-1.amazonaws.com^$empty
||google.com/ads/search/app?*&caps=*sdkAdmobApiForAds$empty
```
