### ISSUE TITLE
tugahd.com - anti adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2041]
http://tugahd.com/index.php/filmes/novidades/5085-sky#hd

![image](https://cloud.githubusercontent.com/assets/15856304/14784273/688872c0-0afd-11e6-9633-09f26daddbef.png)

ERF-257-71261

**Comment by Alex-302** [comment]
added to English
||tugahd.com/modules/mod_adblockdetector/
