### ISSUE TITLE
[StealthMode] yourcinema.tv

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2042]
http://yourcinema.tv/serial/4270-rush-hour.html

Hide your Referrer from third-parties breaks the player:
http://prntscr.com/aw4h0o

TNY-129-64820

**Comment by Alex-302** [comment]
Что-то не повторяется.
Передай на пробу
@@||yourcinema.tv^$stealth

**Comment by Bohdan-SUP** [comment]
Правило исключения помогает. Проблема была именно с опцией "Hide your Referrer".

**Comment by Alex-302** [comment]
Ок, добавил.
