### ISSUE TITLE
http://pikabu.ru again

### ISSUE THREAD

**Issue by dtitbd** [AdguardTeam/ExperimentalFilter#2045]
Тот же самый war thunder. 
![screenshot_2016-04-26-02-04-24](https://cloud.githubusercontent.com/assets/17032471/14798936/55a6c67e-0b53-11e6-8ffd-6627c2a1044e.png)

**Comment by Alex-302** [comment]
почистил

**Comment by Bohdan-SUP** [comment]
https://i.imgur.com/n0TmH5D.png

**Comment by Bohdan-SUP** [comment]
Fixed now.
