### ISSUE TITLE
[Android] WeChat false positive

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#2048]
https://play.google.com/store/apps/details?id=com.tencent.mm&hl=en

Preview doesn't work in sticker shop. 

Also, 'wemoments' feature doesn't work unless you disable Adguard.

For more info, see the original post: https://forum.adguard.com/index.php?threads/9758/

**Comment by ameshkov** [comment]
No need, sorted out already.
