### ISSUE TITLE
[iOS] Missed Ads 4PDA

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#2049]
http://4pda.ru/ - проверено с базовыми последними фильтрами.
У Кастомера и не обновленные и лишние есть. Сюда не добавляю.
![image1](https://cloud.githubusercontent.com/assets/16462533/14819175/82251720-0bc9-11e6-9b3f-2c4c062f5b48.PNG)

**Comment by Alex-302** [comment]
@Serzh-SUP 
а можешь после обновления фильтров проверить?
Если не поможет, попробуй добавить
```
4pda.ru###ipbwrapper > div[class^="r"] > table[width="100%"] a>img[height="90"]
4pda.ru###wrapper > div[class^="r"] > div[class^="r"] > div[class^="r"] > a>img[height="90"]
4pda.ru##.sidebar_border_content > a > img[height="400"]
4pda.ru##body > div > div[id][onclick="return zat_click(this);"][href^="http://4pda.ru/"]
4pda.ru##body > div > div[id][onclick="return zat_click(this);"][href^="http://4pda.ru/"]
4pda.ru###wrapper > div[class^="r"] > div[class^="r"] > div[id^="r"] a[title][href*="http://4pda.ru/2016/"][class*=" "]
```

**Comment by Alex-302** [comment]
Проверил на айпаде - есть реклама только под полосой навигации(на скрине - танки), но её не убрать, т.к. на iOS не поддерживаются правила для изменения стилей элементов.

**Comment by Serzh-SUP** [comment]
@Alex-302
Проверил. У меня так:
![img_8756](https://cloud.githubusercontent.com/assets/16462533/14851649/f1f55ce8-0c89-11e6-9330-3e65755a340f.PNG)

**Comment by Alex-302** [comment]
Верхний точно должен блокироваться. Попробую поковыряться, но даже не знаю в какую сторону копать.
