### ISSUE TITLE
[Stealth mode] EverSync extension

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2051]
Расширение EverSync -
https://chrome.google.com/webstore/detail/eversync-sync-bookmarks-a/iohcojnlgnfbmjfjfkbhahhmppcggdog

При нажатии "Объединить" не происходит синхронизация:
http://prntscr.com/awz814

При отключении "Блокировать сторонние куки" все исправно работает:
http://prntscr.com/awz67p

**Comment by Alex-302** [comment]
добавил
@@||sync.everhelper.me^$stealth
