### ISSUE TITLE
https://www.youngliving.com/vo/#/login does not load

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2052]
Adg is on
![image](https://cloud.githubusercontent.com/assets/15856304/14820326/da74caba-0bce-11e6-9548-283325d20510.png)

Adg is turned off
![image](https://cloud.githubusercontent.com/assets/15856304/14820350/e76b483e-0bce-11e6-9d2e-7934e828b1df.png)

<details>
Os version: Microsoft Windows NT 10.0.10586.0
Dot .net version: 2.0; 3.0; 3.5; 4.0 Client Profile; 4.0 Full Profile;
ApplicationId: 41258b78b0694d0381b596bd2efce56a
Language: en
AppVersion: 6.0.226.1108
Main settings: 
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:10 Name: Filter for useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Wfp
Ads Blocked: 733, Trackers Blocked: 343
Filtering Mode: Driver
Application lifetime: 04:33:58.0081582
HTTPS filtering enabled: True
Do not filter EV: True
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": true,
  "HideUserAgent": true,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": true
}

**Comment by Alex-302** [comment]
Added to social filter:
@@||platform.linkedin.com/in.js$domain=youngliving.com
Please check it
