### ISSUE TITLE
[WIN] Missed Ads

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#2053]
Первый:  http://imgclick.ru/53/356433/
Весь в рекламе.
![default](https://cloud.githubusercontent.com/assets/16462533/14820653/37580bec-0bd0-11e6-828c-26a7d93b8f3a.jpg)

Второй: http://vampiretv.ru/index.php
Появляются всплывающие окна, при переходе по ссылкам, или же при нажатии на кнопки плеера.
![2](https://cloud.githubusercontent.com/assets/16462533/14820658/3e1bea70-0bd0-11e6-877b-a474e034353e.jpg)

Проверял на базовых фильтрах в браузере ФФ.

**Comment by Alex-302** [comment]
добавил
||ebuvpopku.ru^$third-party,script

**Comment by Serzh-SUP** [comment]
@Alex-302 
По второму сайту проблема осталась.

**Comment by Alex-302** [comment]
@Serzh-SUP 
не заметил второй. Лучше делать один сайт на одну ишью.
Добавил:
```
||vampiretv.ru/bn/
||vampiretv.ru/vamp.js

```
