### ISSUE TITLE
[Android] FrAndroid app ads

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2054]
https://play.google.com/store/apps/details?id=com.frandroid.app
![screenshot_20160425-123608](https://cloud.githubusercontent.com/assets/14153331/14821259/c2d614f0-0bd2-11e6-9f18-8cdb35298131.png)

Can't reproduce on my side, log here - BZI-957-64854

**Comment by Alex-302** [comment]
Added to mobile filter
||swelen.com^$empty
