### ISSUE TITLE
1plus1.ua - videos won't play with protection enabled

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2058]
http://1plus1.ua/rozsepleni-na-atomi/video/rozsepleni-na-atomi
![screen shot 2016-04-27 at 1 38 57 am](https://cloud.githubusercontent.com/assets/14153331/14836441/d4a48a90-0c18-11e6-8f8d-85fc640d6537.png)
TJZ-335-18445

**Comment by Alex-302** [comment]
@Bohdan-SUP 
на проверку
`@@||gaua.hit.gemius.pl/gplayer.js$domain=ovva.tv`

**Comment by Alex-302** [comment]
@Bohdan-SUP 
bump

**Comment by Bohdan-SUP** [comment]
Помогло.

**Comment by Alex-302** [comment]
Добавил.
