### ISSUE TITLE
[NSFW] lechenie-prostatita.info

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2059]
www.lechenie-prostatita.info/ihtiolovyie-svechi-pri-prostatite-primenenie/
![screen shot 2016-04-27 at 3 55 20 am](https://cloud.githubusercontent.com/assets/14153331/14838632/06fbddc8-0c2c-11e6-9846-e60b71ec71ab.png)
XNE-251-42839

**Comment by Alex-302** [comment]
какой-то странный сайт. Даже не знаю что с ним делать

**Comment by Alex-302** [comment]
ничего с ним делать не будем
