### ISSUE TITLE
yesilcin.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2060]
http://yesilcin.com/index.php
![screen shot 2016-04-27 at 5 24 12 am](https://cloud.githubusercontent.com/assets/14153331/14839996/60e88640-0c38-11e6-843e-aea9a2d7066a.png)
NSA-363-44333

**Comment by Alex-302** [comment]
added to Turkish filter
```
yesilcin.com###main_content_section > center > a > img
||serdardulger.com/dosya/$domain=yesilcin.com

```
