### ISSUE TITLE
[iOS] Missed Ads zfilm-hd

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#2062]
http://zfilm-hd.net
Фильтры: Англ., Русс., Сис. аналит., Для Сафари.
![image1](https://cloud.githubusercontent.com/assets/16462533/14847448/5678e7e8-0c71-11e6-8165-169295f392e7.PNG)

**Comment by Alex-302** [comment]
@Serzh-SUP 
добавил в русский
`||rettik.ru^$third-party`
юзеру нужно будет проверить после обновления фильтра(обычно через час после сообщения правила становятся доступны)
