### ISSUE TITLE
http://forum.print-forum.ru/ - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2066]
http://forum.print-forum.ru/forumdisplay.php?f=173

![image](https://cloud.githubusercontent.com/assets/15856304/14861960/1fcfacbc-0cb8-11e6-95f2-5008b3abd577.png)

**Comment by Alex-302** [comment]
в русский
print-forum.ru##a[href^="http://forum.print-forum.ru/rbs_banner.php"]
