### ISSUE TITLE
http://onlinedizi.co/ - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2067]
![image](https://cloud.githubusercontent.com/assets/15856304/14862047/6c8eac1a-0cb8-11e6-96a5-94e717fc5b83.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.82.67 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.50 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.54 Enabled=YES
ID=13 Name="Turkish filter" Version=1.0.1.74 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.30 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES

**Comment by Alex-302** [comment]
onlinedizi.co##.fixed-right
||onlinedizi.co/images/albet.gif
