### ISSUE TITLE
factroom.ru

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#2068]
```
factroom.ru#$#.mobile-pop-direct { display: none!important; height: 0px!important; }
factroom.ru##body>.head-horizontal
```

**Comment by Alex-302** [comment]
в мобильный 
`factroom.ru#$#.mobile-pop-direct { display: none!important; height: 0px!important; }`
в русский
`factroom.ru##body>.head-horizontal`
в соц фильтр
`factroom.ru##body > div[class^="facebook-"]`
