### ISSUE TITLE
[WIN] Missed Ads vtracker.org

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#2069]
http://vtracker.org/forum/index.php
Фильтры базовые.
![default](https://cloud.githubusercontent.com/assets/16462533/14885561/bea9cf10-0d54-11e6-8d2a-a788b01b1449.png)

**Comment by Alex-302** [comment]
добавил
`||vtomske.ru/js/*!*!*.js?ck=`
