### ISSUE TITLE
[Stealth mode] have to log in when open youtube's external links

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2071]
при переходе по https-ссылкам на youtube постоянно приходится логинится в аккаунт, хотя я уже был залогинен. Но если я перейду на главную страницу youtube, то видно, что я уже залогинен. http://savepic.ru/9444907.png http://savepic.ru/9498154.png

Поэкспериментировал с галочки в его
настройках. Помогло отключение "Блокировать сторонние куки-файлы (cookies)".

**Comment by Alex-302** [comment]
есть такое дело. Я это не могу исправить.
https://github.com/AdguardTeam/AdguardForWindows/issues/955
