### ISSUE TITLE
Video annoyance on answers.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2074]
http://www.answers.com/Q/What_is_somatogenic_pain
![screen shot 2016-04-29 at 5 24 54 am](https://cloud.githubusercontent.com/assets/14153331/14906969/bdd01fc4-0dca-11e6-858b-e3a1f5cd7510.png)
KZH-309-80890

**Comment by Alex-302** [comment]
`answers.com#%#AG_onLoad(function() { window.AG_removeElementBySelector('div[class^="module video_basic video_"]'); }); `
