### ISSUE TITLE
http://seasonvar.ru/serial-12106-Lyutcifer.html# - blocked html5 player 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2075]
![image](https://cloud.githubusercontent.com/assets/15856304/14936113/a4aef732-0ef0-11e6-877e-646c8086423c.png)

**Comment by vozersky** [comment]
Проблемное правило, по всей видимости, содержится в английском фильтре.

**Comment by evgeniy-ADG** [comment]
http://seasonvar.ru/serial-7744-Stand_Up-01-sezon.html#

Блокируется плеер на сайте
http://prntscr.com/ayyxav

Да, помогает отключение Английского фильтра

**Comment by Alex-302** [comment]
Уже исправлено.

**Comment by Alex-302** [comment]
Перед созданием задачи желательно проверять актуальность, т.к. исправление было добавлено почти сутки назад.

**Comment by evgeniy-ADG** [comment]
Я все проверял перед созданием заявки!

**Comment by evgeniy-ADG** [comment]
opened this issue 3 days ago, тогда у меня и у Вики повторялось. хз. так-то мы проверяем.
