### ISSUE TITLE
http://www.foxnews.com/ - "watch now" is hidden

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2076]
![image](https://cloud.githubusercontent.com/assets/15856304/14936328/2f2e7642-0ef3-11e6-8b6b-a3c5105e1449.png)

![image](https://cloud.githubusercontent.com/assets/15856304/14936315/233ea1a4-0ef3-11e6-8a21-836f0a38e0f3.png)

**Comment by Alex-302** [comment]
They use advertising network for loading this block.
Rules for user filter:
```
@@||tapestry.tapad.com/tapestry/1?ta_partner_id=*&ta_typed_did=$domain=foxnews.com
@@||securepubads.g.doubleclick.net^$domain=foxnews.com
```
