### ISSUE TITLE
http://www.dailymail.co.uk - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2077]
http://www.dailymail.co.uk/sciencetech/article-3559114/Is-happiness-DNA-Study-finds-genes-affect-mood-prone-depression-neuroticism.html

![image](https://cloud.githubusercontent.com/assets/15856304/14936415/ae641a60-0ef4-11e6-86b5-c86c07f273ca.png)

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.80.12 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.12 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.14 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES

**Comment by Alex-302** [comment]
Self promo. Added to Experimental filter
`dailymail.co.uk###smartBanner`
