### ISSUE TITLE
http://muzmo.ru/ - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2080]
http://muzmo.ru/
http://prntscr.com/azarzq

реклама появляется не сразу, нужно долго обновлять страницу, полазить по вкладкам и снова перейти на главную

**Comment by Alex-302** [comment]
added
||muzmo.ru/static/images/*_banners_ru/
muzmo.ru##div[id] > [style="width: 100%; max-width: 800px; margin: 0px auto;"]
