### ISSUE TITLE
http://gntm.connect.prosieben.de/ - anti adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2081]
![image](https://cloud.githubusercontent.com/assets/15856304/14953156/73a97da8-106f-11e6-8286-5e67f2195724.png)

ios, 

- The page detects the adblocker
- While the 'deactivate your adblocker'-message is open, the adguard Safari Integration shows an error:
![image](https://cloud.githubusercontent.com/assets/15856304/14953167/8ea35b10-106f-11e6-9cc3-a8089e25fe5b.png)

**Comment by Vincent-Michael** [comment]
try:

``` @@||gntm.connect.prosieben.de^$generichide ```

**Comment by evgeniy-ADG** [comment]
It works, ty.

**Comment by Alex-302** [comment]
added
