### ISSUE TITLE
can't unsubscribe from "Telerik and Progress" email 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2084]
Пытаюсь отписаться от рассылки неких. Жму в почте на [ссылку ](http://forms.progress.com/unsubscribe?elq_n=16Q2%20ALM%20WW%20Email%20Event-Web%20Bitbarwebinar&elqTrackId=546e7959f49942428bb399f5901d1cb3&elq=92df7fea28444e3cb4580933abf26b36&elqaid=8708&elqat=1&elqCampaignId=11892), подтверждаю отписку и вижу вот такое 

![image](https://cloud.githubusercontent.com/assets/15856304/14958120/b6de965e-1091-11e6-8267-3f416058b4c2.png)

так быть должно?

**Comment by Alex-302** [comment]
Нет, не должно быть так. Возможно баг.
Временно добавил в английский
```
@@||eloqua.com^$domain=forms.progress.com
```
Продублируй на всякий случай в виндовый раздел, а здесь закрой.
