### ISSUE TITLE
Приложение "Счетчик калорий" - пустое поле от рекламы

### ISSUE THREAD

**Issue by BusterN** [AdguardTeam/ExperimentalFilter#2085]
https://play.google.com/store/apps/details?id=com.bolsh.calorie
Скриншот 1 - без Adguard, скриншот 2 - с Adguard.
![screenshot_2016-05-03-10-20-02_com bolsh calorie](https://cloud.githubusercontent.com/assets/19163783/14977157/7fee9fd4-111a-11e6-8982-347ff1d4c189.png)
![screenshot_2016-05-03-09-54-28_com bolsh calorie](https://cloud.githubusercontent.com/assets/19163783/14977162/827fbefe-111a-11e6-987f-7643c91a5090.png)
При использовании фильтрации HTTPS реклама режется, но остается пустое поле от неё. Можно ли это исправить?

**Comment by Alex-302** [comment]
Не выходит. Если приложению не нужна сеть, можете заблокировать доступ брандмауэром, пустота должна будет пропасть.
