### ISSUE TITLE
http://seasonvar.ru/ - video player is broken 

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#2086]
Большое количество пользователей обратилось с проблемой, что не работает на сайте проигрыватель. Проверка подтвердила проблему. Фильтры базовые + экспериментальный. Выглядит это так:
![2016-05-03_12-44-17](https://cloud.githubusercontent.com/assets/16462533/14979737/e6058d0c-112c-11e6-988e-17af80683aee.png)

**Comment by a-talanov** [comment]
Проблема решена
https://forum.adguard.com/index.php?threads/%D0%A0%D0%B5%D1%88%D0%B5%D0%BD%D0%BE-http-seasonvar-ru-%D0%92%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE-%D1%83-%D0%92%D0%B0%D1%81-%D0%B2%D0%BE%D0%B7%D0%BD%D0%B8%D0%BA%D0%BB%D0%B8-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B.9413/

**Comment by Serzh-SUP** [comment]
@a-talanov 
У многих не так и не работает. Фильтры обновлены.
