### ISSUE TITLE
http://myfolder.ru/ - Missed AD

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#2087]
Базовые фильтры + Экспер., обновлены
![2016-05-03_18-35-05](https://cloud.githubusercontent.com/assets/16462533/14988778/0ee8e242-115e-11e6-9a09-3790bea9b0cd.png)
![2016-05-03_18-35-20](https://cloud.githubusercontent.com/assets/16462533/14988777/0ee79e96-115e-11e6-8085-4b608d058edc.png)

**Comment by Alex-302** [comment]
||inet-online.ru^$domain=myfolder.ru
