### ISSUE TITLE
http://lenovo-smart.ru/ - missed yandex ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2088]
http://lenovo-smart.ru/lenovo-pokinula-top-5-po-prodazham-smartfonov.html

![image](https://cloud.githubusercontent.com/assets/15856304/14989373/2ba4abb2-1160-11e6-8db9-10c272067717.png)

HTTPs filering, recent filters, all double checked and reproduced. The screen above is mine.

**Comment by Alex-302** [comment]
added
lenovo-smart.ru#%#Object.defineProperty(window, 'SocialMartDocumentHelper', { get: function() { return function SocialMartDocumentHelper(){} } });
