### ISSUE TITLE
http://www.dobreprogramy.pl/ - blank page

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2089]
![image](https://cloud.githubusercontent.com/assets/15856304/14989654/8946675a-1161-11e6-8f08-45be84731baf.png)

When disable protection:

![image](https://cloud.githubusercontent.com/assets/15856304/14989664/9be03b70-1161-11e6-85cf-552c8b94e831.png)

Basic filter set with the latest updates, Stealth mode disabled.

**Comment by Alex-302** [comment]
I think he has enabled Russian filter. User can just update filters.
