### ISSUE TITLE
Angry Birds Friends - fails to start

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2094]
https://play.google.com/store/apps/details?id=com.rovio.angrybirdsfriends&hl=en

При входе в игру и нажатии на Play, выходит сообщение - Check your internet connection
Отключение всех фильтров не помогает, помогает отключение защиты

логи тут: RAQ-512-85178

**Comment by Alex-302** [comment]
Это больше похоже на баг фильтрации HTTPS.
https://github.com/AdguardTeam/AdguardForAndroid/issues/546

**Comment by Revertron** [comment]
Оно и без Адгарда не работает совсем. Пусть Ровио и фиксит.
