### ISSUE TITLE
[iOS] Missed Ads - http://onlain-multiki.ru/

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#2097]
Проверил, подтвердилось.
Фильтры базовые, обновленные.
![image1](https://cloud.githubusercontent.com/assets/16462533/15030641/28f5d902-125c-11e6-99f8-b6739673e580.PNG)

**Comment by Alex-302** [comment]
to mobile
||onlain-multiki.ru/config.json
