### ISSUE TITLE
[iOS] https://www.buzzfeed.com/?country=us

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2100]
https://www.buzzfeed.com/?country=us is broken

![image](https://cloud.githubusercontent.com/assets/15856304/15049446/fe634bde-12f6-11e6-92b4-0d12e74157b1.png)

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.83.19 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.55 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.62 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.40 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID=116 Name="Wiltteri" Version=1.0.1.68 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.57.6 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.57.28 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.1.58 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.57.21 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.57.8 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.12 Enabled=YES

**Comment by Alex-302** [comment]
Can't reproduce

**Comment by oahon** [comment]
Hi, OP here. 

It seems that site went broken due to couple of things in the EasyList's Fanboy's Annoyance List. Going to report this one there. 

Best, 
Otto

**Comment by Alex-302** [comment]
Hi, @oahon 
so this site works correctly without Fanboy's Annoyance?

**Comment by oahon** [comment]
Hi, @Alex-302. Exactly.

**Comment by Alex-302** [comment]
So he will fix it?
