### ISSUE TITLE
[iOS] http://sneakernews.com/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2102]
Incorrect blocking on page:
http://sneakernews.com/
http://sneakernews.com/page/2/
http://sneakernews.com/page/3/

The page 3 and beyond will not be loaded if use the button on the page to browse the site normally.
It will keep showing the page 2 contents repeatedly.
And the URL will always be
http://sneakernews.com/page/2/

<details>
About the issue, I only found out this type of problem on this site for now, and there's no problem when AdGuard is turned off.

I'll explain it through text with pictures now :

Lets start from site(sneakernews.com)
then scroll to the bottom like the picture below
![image](https://cloud.githubusercontent.com/assets/15856304/15051866/6fb06a9a-1303-11e6-8780-530071e35f90.png)

then i click the (LOAD MORE POSTS) which will have more posts be loaded like how it is in the following picture, the URL should look like(sneakernews.com/page/2/) by now
![image](https://cloud.githubusercontent.com/assets/15856304/15051874/79f4a0c0-1303-11e6-8263-16ce5d4e7d5a.png)

And then I scroll to the bottom again
![image](https://cloud.githubusercontent.com/assets/15856304/15051881/841039de-1303-11e6-8d3c-173d0dbc3585.png)

The problem starts here!
If i click the (LOAD MORE POSTS) now it supposed to change the URL to (sneakernews.com/page/3/) and show the posts of page 3 but instead it repeats the posts of YEEZY footwear showed on page 2, and URL is still (sneakernews/page/2/) like how it looks like in the picture below.
![image](https://cloud.githubusercontent.com/assets/15856304/15051896/98c72f4a-1303-11e6-91ec-0c27db170650.png)

It will keep repeating the posts in page 2. If i keep scrolling down and click the (LOAD MORE POSTS), URL will repeat the(smeakernews.com/page/2/) and will not update further to page 3,4,5...etc

I checked the same site on Chrome to test which has no problem loading all the correct pages 1,2,3,4,5...etc. with all different posts.

Hope you understand what i'm saying, quite hard to explain this. Maybe browse the site from the beginning then load a couple more posts then you should probably understand what I'm talking about.

**Comment by Alex-302** [comment]
Added to Social filter:
`@@||apis.google.com/js/platform.js$domain=sneakernews.com`
