### ISSUE TITLE
[iOS] http://www.sixx.ch/ - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2103]
![image](https://cloud.githubusercontent.com/assets/15856304/15053005/1f6c5cc8-1309-11e6-980e-e55e636f639f.png)

<details>
Application version: 1.0.5.38
Application lifetime: 2016-05-02 19:17:44 +0000

Device: iPad
Platform: iPhone OS
OS: 9.3.1
ID: 477B5DD4-CF8E-461B-8EE9-77F71566AE13

Locale: de
Region: ch

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.83.39 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.57 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.64 Enabled=YES
ID=6 Name="German filter" Version=1.0.25.23 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.40 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID=101 Name="EasyList" Version=1.0.57.29 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.57.52 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.57.19 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.57.41 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.1.60 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.57.34 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.57.21 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.12 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.33 Enabled=YES

**Comment by Alex-302** [comment]
Fixed in German filter.
