### ISSUE TITLE
https://my.mail.ru/video - unable to upload video

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2105]
У Вики повторилось.

https://my.mail.ru/video
не загружается видео.
После 100% загрузки не появляется кнопка "Сохранить".

Отключение защиты не помогает. Помогает полное закрытие программы со службой.

Видео: https://cloud.mail.ru/public/N7Jt/6fd45KXch

**Comment by Alex-302** [comment]
@evgeniy-ADG 
попробуй добавить в исключения HTTPS, нажать Сохранить и перезапустить браузер
[CODE]upload.my.mail.ru[/CODE]

**Comment by evgeniy-ADG** [comment]
ок, попрошу Вику. у меня не повторяется это всё.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
есть новости?

**Comment by Alex-302** [comment]
@evgeniy-ADG 
ауyy

**Comment by evgeniy-ADG** [comment]
Все работает.

**Comment by Alex-302** [comment]
Исключение появится в следующей сборке.
