### ISSUE TITLE
https://my.mail.ru/?from=my - hide annoying element

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2106]
![image](https://cloud.githubusercontent.com/assets/15856304/15055235/22fb52a8-1314-11e6-8dd4-d7d3a3d9bf52.png)

Через помощник выделяю эту пленку вношу в пользовательский фильтр и побарабану ! Когда заново в мой мир заходишь опять эта пленка https://my.mail.ru/?from=my
Нашел как вызвать эту пленку наверняка ! нужно создать новый акк. Вот код

<details>
```
<div class="ui-popup b-subscription__rounded-popup" role="popup" data-ui-popup-name="Popup_1" style="height: 680px; margin-top: -340px; width: 610px; margin-left: -305.909px;"><div class="ui-popup__content-error"><div class="ui-popup__content-error_text"></div></div><div class="ui-popup__content"><div data-mru-fragment="subscription-community" style="" data-mru-fragment-ready="true">
<div class="b-subscription__category__head">
Софья, привет!
</div>
<div class="b-subscription__category__head-text">
Выбери, что тебе интересно читать в Моем Мире
</div>

<div class="b-subscription__category__list"><div class="b-subscription__category__item b-subscription__category__item-circle" data-item-id="animals">
<div class="b-subscription__category__item-pic" style="background-image: url(https://img2.imgsmail.ru/r/my/subscription_community/animals_110x110.jpg);" data-clns="d12442234">
<span class="b-subscription__category__item-selected-icon icon-checkmark_blue_round"></span>
</div>
<div class="b-subscription__category__item-name" data-clns="d12442234">Животные</div>
</div><div class="b-subscription__category__item b-subscription__category__item-circle" data-item-id="career">
<div class="b-subscription__category__item-pic" style="background-image: url(https://img2.imgsmail.ru/r/my/subscription_community/business_110x110.jpg);" data-clns="d12442234">
<span class="b-subscription__category__item-selected-icon icon-checkmark_blue_round"></span>
</div>
<div class="b-subscription__category__item-name" data-clns="d12442234">Карьера</div>
</div><div class="b-subscription__category__item b-subscription__category__item-circle" data-item-id="movies">
<div class="b-subscription__category__item-pic" style="background-image: url(https://img2.imgsmail.ru/r/my/subscription_community/movie_110x110.jpg);" data-clns="d12442234">
<span class="b-subscription__category__item-selected-icon icon-checkmark_blue_round"></span>
</div>
<div class="b-subscription__category__item-name" data-clns="d12442234">Фильмы</div>
</div><div class="b-subscription__category__item b-subscription__category__item-circle" data-item-id="style">
<div class="b-subscription__category__item-pic" style="background-image: url(https://img2.imgsmail.ru/r/my/subscription_community/beauty_and_style_110x110.jpg);" data-clns="d12442234">
<span class="b-subscription__category__item-selected-icon icon-checkmark_blue_round"></span>
</div>
<div class="b-subscription__category__item-name" data-clns="d12442234">Красота и стиль</div>
</div><div class="b-subscription__category__item b-subscription__category__item-rect" data-item-id="food">
<div class="b-subscription__category__item-pic" style="background-image: url(https://img2.imgsmail.ru/r/my/subscription_community/food_125x95.jpg);" data-clns="d12442234">
<span class="b-subscription__category__item-selected-icon icon-checkmark_blue_round"></span>
</div>
<div class="b-subscription__category__item-name" data-clns="d12442234">Кулинария</div>
</div><div class="b-subscription__category__item b-subscription__category__item-rect" data-item-id="fun">
<div class="b-subscription__category__item-pic" style="background-image: url(https://img2.imgsmail.ru/r/my/subscription_community/fun_125x95.jpg);" data-clns="d12442234">
<span class="b-subscription__category__item-selected-icon icon-checkmark_blue_round"></span>
</div>
<div class="b-subscription__category__item-name" data-clns="d12442234">Юмор и развлечения</div>
</div><div class="b-subscription__category__item b-subscription__category__item-rect" data-item-id="men">
<div class="b-subscription__category__item-pic" style="background-image: url(https://img2.imgsmail.ru/r/my/subscription_community/men_125x95.jpg);" data-clns="d12442234">
<span class="b-subscription__category__item-selected-icon icon-checkmark_blue_round"></span>
</div>
<div class="b-subscription__category__item-name" data-clns="d12442234">Отношения</div>
</div><div class="b-subscription__category__item b-subscription__category__item-rect" data-item-id="trip">
<div class="b-subscription__category__item-pic" style="background-image: url(https://img2.imgsmail.ru/r/my/subscription_community/trip_125x95.jpg);" data-clns="d12442234">
<span class="b-subscription__category__item-selected-icon icon-checkmark_blue_round"></span>
</div>
<div class="b-subscription__category__item-name" data-clns="d12442234">Путешествия</div>
</div><div class="b-subscription__category__item b-subscription__category__item-circle" data-item-id="family">
<div class="b-subscription__category__item-pic" style="background-image: url(https://img2.imgsmail.ru/r/my/subscription_community/family_110x110.jpg);" data-clns="d12442234">
<span class="b-subscription__category__item-selected-icon icon-checkmark_blue_round"></span>
</div>
<div class="b-subscription__category__item-name" data-clns="d12442234">Семья и дети</div>
</div><div class="b-subscription__category__item b-subscription__category__item-circle" data-item-id="sport">
<div class="b-subscription__category__item-pic" style="background-image: url(https://img2.imgsmail.ru/r/my/subscription_community/fitness_and_sport_110x110.jpg);" data-clns="d12442234">
<span class="b-subscription__category__item-selected-icon icon-checkmark_blue_round"></span>
</div>
<div class="b-subscription__category__item-name" data-clns="d12442234">Фитнес и спорт</div>
</div><div class="b-subscription__category__item b-subscription__category__item-circle" data-item-id="shopping">
<div class="b-subscription__category__item-pic" style="background-image: url(https://img2.imgsmail.ru/r/my/subscription_community/shopping_110x110.jpg);" data-clns="d12442234">
<span class="b-subscription__category__item-selected-icon icon-checkmark_blue_round"></span>
</div>
<div class="b-subscription__category__item-name" data-clns="d12442234">Хобби и шоппинг</div>
</div><div class="b-subscription__category__item b-subscription__category__item-circle" data-item-id="smartphones">
<div class="b-subscription__category__item-pic" style="background-image: url(https://img2.imgsmail.ru/r/my/subscription_community/smartphones_110x110.jpg);" data-clns="d12442234">
<span class="b-subscription__category__item-selected-icon icon-checkmark_blue_round"></span>
</div>
<div class="b-subscription__category__item-name" data-clns="d12442234">Смартфоны и планшеты</div>
</div></div>

<div class="b-subscription__community__list-block" style="display: none;">
<div class="b-subscription__community__list"></div>
</div>

<div class="b-subscription__category__button-block">
<span class="ui-button-main b-subscription__category__button disable">Далее</span>
<span class="ui-button-main b-subscription__button-goto" style="display: none;" data-clns="d12443422">Перейти в Мой Мир</span>
</div>

<script type="text/plain" data-type="config">
{	
"popupWidth": "610",
"popupHeight": "680",
"activeEmail": "sopdcb69@mail.ru",
"header": "Отлично, Софья!",
"headerText": "Мы нашли самые интересные группы для тебя",
"subscribeText": "Подписаться",
"unsubscribeText": "<i class='b-subscription__community__item-button__icon ui-icon icon-checkmark_gray'></i>Подписан",
"subscriptionModerateText": "На рассмотрении",
"subscriptionErrorText": "Ошибка",
"locales": {
"cityGroupText": "Мой город",
"subscribeButtonText": "Подписан"	
}
}
</script>
</div></div><div class="ui-popup__buttons"></div><div class="ui-popup__close"></div></div>
```
![image](https://cloud.githubusercontent.com/assets/15856304/15055253/31bec84c-1314-11e6-9eaa-bb6ac5b03185.png)

**Comment by Alex-302** [comment]
Для пользовательского:
`my.mail.ru##.ui-popup__sandbox`

**Comment by evgeniy-ADG** [comment]
Добавил фильтр my.mail.ru##.ui-popup__sandbox http://pic-mir.ru/allimage/0/1/4/8/1/148125.jpeg https://github.com/AdguardTeam/ExperimentalFilter/issues/2106 
теперь окно блокирует загрузки видео ! http://pic-mir.ru/allimage/0/1/4/8/1/148124.jpeg .Это же - my.mail.ru##.ui-popup__sandbox как я понял блок всплывающих окон ? Вот и когда нажимаешь " Загрузить видео" тоже получается всплывающее окно и правило блочит это окно .Вот и получается фильтр пленку убрал ,а в разделе "Мое видео" создает геморой

**Comment by Alex-302** [comment]
Видать код элементов одинаковый. Передай такое
`my.mail.ru##body > div[class="ui-popup__sandbox"][role="sandbox"]`

**Comment by aiv3006** [comment]
Алекс с правилом  my.mail.ru##body > div[class="ui-popup__sandbox"][role="sandbox"]  пленка не появляется ,окно загрузки блочит ! У тебя видео грузится вообще ? Я вопрос поднимал "Здравствуйте ! Не загружатся видео в "Мой Мир" на майле ! Пока не остановишь службу . Отключение фильтров ,приостановка защиты ,переустановка программы не помогает . ( проблемы в лисе,опере,гугл хроме ,хромиум) https://cloud.mail.ru/public/N7Jt/6fd45KXch "

**Comment by Alex-302** [comment]
тогда удалите эти правила. Не удачная у них вёрстка.
Про видео лучше ответьте в соответствующей теме, там предложен вариант
https://github.com/AdguardTeam/ExperimentalFilter/issues/2105

**Comment by aiv3006** [comment]
Алекс  ) Видео не загружается даже при отключенном адгуарде ( фильтры тут вообще не при чем ) Загрузка идет только когда служба остановлена вот в чем гемор  !

**Comment by Alex-302** [comment]
добавьте в исключения https
`upload.my.mail.ru`
и проверьте после перезапуска браузера

**Comment by aiv3006** [comment]
Алекс  если не отключить это правило  my.mail.ru##.ui-popup__sandbox  ,то upload.my.mail.ru не действует .А если не включать  my.mail.ru##.ui-popup__sandbox ( блок пленки)  ,то и upload.my.mail.ru как бы не к чему :( Как то так

**Comment by aiv3006** [comment]
Алекс и вот еще что : Я обратил внимание что в блоках рекламы яндекс директа отображаются товары которые я искал на других сайтах (например я на днях искал флешку по дешевле так в почте у меня в директе начали отображатся магазины с флешками  ,потом вчера  заказал роутер в ситилинке ,так в почте майл у меня в директе теперь отображаются магазины с роутерами ) Что за хрень ? Комп чист без вирусов расширения тоже вроде не причем ( пробовал на портабл чистом хроме .

**Comment by Alex-302** [comment]
>Алекс если не отключить это правило my.mail.ru##.ui-popup__sandbox ,то upload.my.mail.ru не действует .А если не включать my.mail.ru##.ui-popup__sandbox ( блок пленки) ,то и upload.my.mail.ru как бы не к чему :( Как то так

да при чём тут правила сокрытия? Я просил проверить загрузку видео с добавленным в хттпс исключения
`upload.my.mail.ru`

**Comment by aiv3006** [comment]
Нормалек ! Пошла загрузка (не правильно понял сначала вместо исключения https в фильтр правило занес ;)

**Comment by Alex-302** [comment]
ок, со следующим билдом исправится.

**Comment by aiv3006** [comment]
Алекс с лисой поможешь ? http://pic-mir.ru/allimage/0/1/4/8/8/148887.jpeg сертификат переустанавливал ,браузер тоже помогает только отключения фильтрации https ( в браузерах на базе хрома такой беды не наблюдаю)

**Comment by Alex-302** [comment]
<details> 
![](http://imagizer.imageshack.com/img922/6669/gsdJoz.png)
</details>

**Comment by aiv3006** [comment]
Яж написал сертификат переустанавливал ! https://cloud.mail.ru/public/7VEo/zSuEqHXA5

**Comment by Alex-302** [comment]
Браузер случайно не портативный?
Попробуй удалить все адгардовские сертификаты через настройки фокса и импортировать вручную из
`C:\ProgramData\Adguard\NetworkTemp\SSL\Adguard Personal CA.cer`

**Comment by aiv3006** [comment]
Благодарю все ОК  ! Не знал надо записать ( а браузер не портабл. ) 

Вот все равно не понятки с фильтрами вот детально заснял где лечит где колечит https://cloud.mail.ru/public/DtK5/9YMv3aX1j

**Comment by Alex-302** [comment]
не нужно использовать эти правила сокрытия. Их иначе не сделать, или сразу или позже что-нибудь сломают

**Comment by aiv3006** [comment]
Алекс ну это хрень тогда получается :( Что ж выходит расширение обычное по блокировке рекламы может одновременно и пленку убрать и окно загрузки видео не блокировать ,а Adguard не может :( У вас тем более целая команда над фильтрами думает , а возьмем к примеру расширение Дениса https://chrome.google.com/webstore/detail/stop-reclame/ohmkcnojelglgphmkgmofjlmpoelccjh он один над фильтрами колдует и тем не мене оно одновременно может и пленку блочить и окно загрузки видео не блочить . Это не есть гуд :(

**Comment by Alex-302** [comment]
Сделать-то можно, правило стрёмное получается. Подумаю чуть позже. Такие попапы не самая приоритетная проблема.
>У вас тем более целая команда над фильтрами думает

фильтрами занимаются два человека, но в основном я. Форумчане не считаются, т.к. правила в любом случае перепроверяем, но пользу определённо приносят.
