### ISSUE TITLE
www.thedodo.com - false positive, blocking all images

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2113]
https://www.thedodo.com/sparkle-llama-cat-best-friends-1775716896.html

I have a website thedodo.com that has multiple articles and stories. When I open an article, all the pictures within are apparently blocked. This has not always been the case - only recently.

![image](https://cloud.githubusercontent.com/assets/15856304/15092542/b44a59f4-1475-11e6-997d-7b4313ab17f5.png)

![image](https://cloud.githubusercontent.com/assets/15856304/15092543/c16bd054-1475-11e6-8c94-08e9d6537d57.png)

**Comment by Alex-302** [comment]
Fixed in Social filter.
