### ISSUE TITLE
http://www.neustadt-ticker.de - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2114]
http://www.neustadt-ticker.de/45417/aktuell/mai-und-soehne

![image](https://cloud.githubusercontent.com/assets/15856304/15092598/28d9cbb4-1477-11e6-8ee2-b14fd6fa4109.png)

24894 active rules, filters are up to date. The add does not appear constantly.

<details>
Application version: 1.0.5.38
Application lifetime: 2016-03-31 17:21:04 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.2
ID: 528ABE78-5821-4DB9-A084-A17D42B8FE61

Locale: de
Region: de

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.80.81 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.20 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.18 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.24.69 Enabled=YES
ID=10 Name="Filter for useful ads" Version=1.0.0.78 Enabled=NO
ID=6 Name="German filter" Version=1.0.24.53 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID=101 Name="EasyList" Version=1.0.55.34 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.55.57 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.55.24 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.55.46 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.55.35 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.1.42 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.55.39 Enabled=YES

**Comment by Alex-302** [comment]
Added to Safari filter
`##a[href*="/adrotate-out.php?"]`
