### ISSUE TITLE
cinefilmeshd.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2123]
http://www.cinefilmeshd.com/assistir-shadowhunters-hd-dublado-legendado/
![image](https://cloud.githubusercontent.com/assets/14153331/15113322/2ccf3b42-15fc-11e6-9742-587139368a09.png)
VJZ-534-58753

**Comment by Alex-302** [comment]
added to eng filter
@@||fxnews2016.info/embed/$generichide
