### ISSUE TITLE
orlandoweekly.com - broken slideshow

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2124]
http://photos.orlandoweekly.com/someone-left-this-fake-guestbook-at-a-florida-airbnb-and-its-hilarious/?slide=1&ht3fpwj
User reported on iOS, reproduced on Win.
![image](https://cloud.githubusercontent.com/assets/14153331/15113375/8e2d6512-15fc-11e6-80a9-b678e8bee01c.png)
![image](https://cloud.githubusercontent.com/assets/14153331/15113384/9ae02902-15fc-11e6-825e-3723d5fb0ca2.png)
SRC-806-14684

**Comment by Alex-302** [comment]
added to social filter
```
@@||orlandoweekly.com/wp-content/plugins/wpsocialite/Socialite/socialite.min.js$domain=orlandoweekly.com
```
