### ISSUE TITLE
http://www.cda.pl/video/695215da - blockin HTML5 player

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2125]
![image](https://cloud.githubusercontent.com/assets/15856304/15113569/bd71a2ce-15fd-11e6-876a-afd096034c12.png)

Basic filter set

**Comment by Alex-302** [comment]
Can't reproduce:
http://imagizer.imageshack.com/img922/5156/bSYP6v.png

**Comment by Bohdan-SUP** [comment]
Confirmed by user.
