### ISSUE TITLE
Ads in LastPass extension

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2126]
Is possible to block ads in Chrome extensions?
For example in LastPass - https://chrome.google.com/webstore/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd
I want block this - http://i.imgur.com/Fipn9eQ.png

**Comment by Alex-302** [comment]
no, we can't do it now. But you can make feature request.

**Comment by Bohdan-SUP** [comment]
Filed a request:
https://github.com/AdguardTeam/AdguardForWindows/issues/1100

**Comment by Alex-302** [comment]
thanks
