### ISSUE TITLE
[Stealth mode] Games on apps.facebook.com do not work with SM enabled

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2127]
Went into Pet Rescue Saga & played one level, with no issues. Before going onto the next level, I went into Filtered Apps & turned Google & Facebook back on. When I tried to play that level, nothing happened. Here's that link:
https://apps.facebook.com/petrescuesaga/?fb_source=bookmark&ref=bookmarks&count=0&fb_bmpos=_0

When GOOGLE CHROME is "ticked" under FILTERED APPS, I cannot enter the game (W10, FB apps). It appears to be stuck in a loop.
When GOOGLE CHROME is "unticked" under FILTERED APPS, there is no problem entering the game (W10, FB apps).

Disabled Stealth Mode & turned Google Chrome, under Filtered Apps, back on. Games are executing. Guess Stealth was the issue.

HAR-470-84443

**Comment by Alex-302** [comment]
@evgeniy-ADG 
у тебя получилось повторить? У меня игра запускается со всеми включенными опциями.

Передай на проверку
`@@||apps.facebook.com^$stealth`

**Comment by evgeniy-ADG** [comment]
Передал, у меня тоже все окей. Кастомер отключил стилс мод.

**Comment by Alex-302** [comment]
А повторялось?

**Comment by evgeniy-ADG** [comment]
Не повторялось.

**Comment by Alex-302** [comment]
ок, тогда не добавляю.
