### ISSUE TITLE
http://m.nettavisen.no/ - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2129]
Missed ad on page:
http://m.nettavisen.no/

https://www.norsk-tipping.no/mobile-internet/?game=lo&?WT.mc_id=Nettavisen_mobil_forsidetopp__Langoddsen&utm_source=Nettavisen&utm_medium=mobil&utm_content=Langoddsen_forsidetopp_&st

![image](https://cloud.githubusercontent.com/assets/15856304/15114366/4985f86a-1602-11e6-9219-87edb4be5cb7.png)

MNV-918-28685

**Comment by Alex-302** [comment]
added to mobile filter
nettavisen.no###sportspill-box-top
