### ISSUE TITLE
http://www.goroskop.ru/ - 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2130]
Пропущена реклама на странице:
http://www.goroskop.ru/publish/open_article/48693/

![image](https://cloud.githubusercontent.com/assets/15856304/15114453/c304af1a-1602-11e6-9d04-cdf4982d90c5.png)
HNE-656-64482
<details>

Application version: 1.0.5.38
Application lifetime: 2016-02-28 15:04:28 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.1
ID: E8B492CB-9776-4C42-B989-798A9ACA43AE

Locale: ru
Region: ru

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.78.28 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.89 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.72 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.24.24 Enabled=YES
ID=10 Name="Filter for useful ads" Version=1.0.0.89 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.31.41 Enabled=YES
ID=6 Name="German filter" Version=1.0.23.74 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.92.93 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.8.70 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.16 Enabled=YES
ID=13 Name="Turkish filter" Version=1.0.1.34 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.2.54 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.47 Enabled=YES

**Comment by Alex-302** [comment]
добавил в русский
```
://n.*.ru/a*?Id=$script,domain=goroskop.ru
||goodkind.ru^$third-party

```
