### ISSUE TITLE
http://www.myscore.ru/ - can't register an account and log in to the existing one

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2133]
adg is on
![image](https://cloud.githubusercontent.com/assets/15856304/15115858/a40209f8-1609-11e6-8aef-becf55998d95.png)

adg is off 
![image](https://cloud.githubusercontent.com/assets/15856304/15115893/c12f5e68-1609-11e6-8d2b-ee4305e592a8.png)

**Comment by Alex-302** [comment]
Adguard Assistant issue.
https://github.com/AdguardTeam/AdguardForWindows/issues/1088
