### ISSUE TITLE
Zona - missed video ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#2134]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=49438586

**Comment by Alex-302** [comment]
Что-то не повторяется видео реклама, даже без Адгарда, только статичный баннер.

**Comment by ayratus** [comment]
И что мне теперь сделать? Я же специально снял видео, а не скриншот, чтобы показать рекламу.

**Comment by Alex-302** [comment]
Отключите все фильтры, кроме русского и английского. Откройте журнал фильтрации, выберите "Заблокировано" и повторите ситуацию с рекламой. Скриншот(ы) нужно выложить здесь, посмотрю, есть ли среди заблокированного рекламный домен.
Если что, могу удалённо глянуть.

**Comment by ayratus** [comment]
А как открыть журнал фильтрации? Где он находится?

**Comment by Alex-302** [comment]
Смотря каким продуктом пользуетесь. Если расширение, то вот так
<details>
![image](http://imagizer.imageshack.com/img921/5706/nrM0Gb.png)
</details>
если программой, то через значёк на панели задач -> Инструменты -> Открыть журнал

**Comment by ayratus** [comment]
Вот, вроде бы так.

![default](https://cloud.githubusercontent.com/assets/19325361/15258542/a0b0c348-1965-11e6-9721-c5369c8089da.jpg)
![1](https://cloud.githubusercontent.com/assets/19325361/15258541/a0afa1e8-1965-11e6-8405-79cd77c6ff33.jpg)
![2](https://cloud.githubusercontent.com/assets/19325361/15258543/a0b29650-1965-11e6-9ea9-7a6fde3ce0a4.jpg)
![3](https://cloud.githubusercontent.com/assets/19325361/15258544/a0b2e2f4-1965-11e6-8978-cc9329f4909f.jpg)
![4](https://cloud.githubusercontent.com/assets/19325361/15258545/a0b4db5e-1965-11e6-9152-50b12caace80.jpg)
![default](https://cloud.githubusercontent.com/assets/19325361/15258546/a0b62f86-1965-11e6-87c3-dc2e9acfb396.jpg)

**Comment by ayratus** [comment]
Скриншоты с галочкой "заблокировано", без галочки и с галочкой "сторонние".

**Comment by Alex-302** [comment]
Ок, просмотрю запросы - выложу правила для проверки.

**Comment by ayratus** [comment]
Честно говоря, странно, что только я пожаловался на рекламу в Зоне. Я всё ждал, когда же наконец исправится эта ситуация, раз уж Зона внесена в список, а оно всё никак. Надеюсь, теперь с Вашей помощью наладится.
И ещё странно, что Вы не видите видео баннер со счётчиком. Может, антивирус режет? У меня то установлен простой MSE.

**Comment by Alex-302** [comment]
попробуйте это правило
||info.zonasearch.com/ad/admulti1.json

**Comment by ayratus** [comment]
Добавил это правило в пользовательский фильтр.
Запустил пару фильмов, пока рекламы нет. Буду собирать статистику день, два.
Такое же правило прописал на ноутбуке жены (у нас с ней одна лицензия RCG93KAR), но с одним нюансом - у неё уже была запущена Зона и шла серия Физрука, и Зону я не перезагрузил. После окончания серии Физрука опять появилась реклама, тогда я перезагрузил Зону, и пока рекламы у жены тоже нет.

**Comment by ayratus** [comment]
Сегодня, то есть 14 мая, мы с супругой на двух разных компах смотрели через Зону фильмы с настроенным вашим правилом, рекламы больше не было.
Надеюсь, это не совпадение, а законченное решение!
Спасибо за помощь!

P. S. Вы это правило будете добавлять в какой-нибудь штатный фильтр?

**Comment by Alex-302** [comment]
Да, сегодня добавлю.
