### ISSUE TITLE
[Android] publico.es

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2135]
publico.es
disabling https won't help
https://www.dropbox.com/s/y4nos5sftjptbq6/Screenshot_2016-05-10-00-23-09.png?dl=0
IVN-374-50099

**Comment by Alex-302** [comment]
added to Spahish filter
@@||m.publico.es/publico/js/ads.min.js$domain=m.publico.es
