### ISSUE TITLE
sodu.cc

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2136]
http://www.sodu.cc/wap/home.html
![image1](https://cloud.githubusercontent.com/assets/14153331/15129658/b0a4c9b0-164b-11e6-9818-24afd69468af.PNG)
ZTA-377-13748

**Comment by Alex-302** [comment]
added to mobile filter
```
||s.*.com/pp.php?uid=$third-party
||sodu.cc/js/tj1.js
```
