### ISSUE TITLE
zombie-tv.org

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2137]
Couple of issues:
- opens http://moneys-blog.com in background
- video is not playing
- and ads:
![screen shot 2016-05-10 at 1 53 09 am](https://cloud.githubusercontent.com/assets/14153331/15130564/12fbd2c4-1652-11e6-86ab-45ae347a38a8.png)
MMZ-332-53153

**Comment by Alex-302** [comment]
@Bohdan-SUP 
добавил
`||tv.zombie-tv.org^$script`
Видео скорее всего не работает потому, что ссылки с других сайтов взяты, и могли потерять актуальность.
