### ISSUE TITLE
Redirect from ukpirate.click

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/ExperimentalFilter#2141]
На [сайте](https://ukpirate.click/) как только, зашел на сайт, при клике на любую область идет открытие новой вкладке с редиректами. Повторилось как на фоксе, так и на хроме.
Фильтры базовые.
Видео [Видео](https://youtu.be/A2jdZlVkSpg)

**Comment by Alex-302** [comment]
added
`ukpirate.click#%#Object.defineProperty(window, '_gunggo', { get: function() { return []; } });`
