### ISSUE TITLE
http://compi-life.blogspot.ru 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2143]
http://compi-life.blogspot.ru/2016/05/akkumulyator-bl5204-dlya-smartfona-fly-iq447-era-life-1.html

сайт вот этот - http://compi-life.blogspot.ru/ , я туда 
устанавливал код виджета рекомендованных статей. Вы можете в *любую 
статью* зайти на этом сайте и проблема повторится в любой статье, потому 
что Адгуард блокирует весь трафик с сайта http://www.engageya.com , 
насколько я понимаю. При выключенной защите Адгуард - этот виджет 
работает нормально. Скриншот прилагаю во вложении, на скрине видно что 
при выключенном Адгуарде - этот виджет работает нормально и показывает 
рекомендованные статьи в блоге.

![image](https://cloud.githubusercontent.com/assets/15856304/15161061/584b04e0-1705-11e6-8530-77c691eb9ef0.png)

**Comment by Alex-302** [comment]
||engageya.com^$third-party
перенёс из языкового фильтра в фильтр аналитики
