### ISSUE TITLE
mimimi.tv

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/ExperimentalFilter#2146]
Example:
http://mimimi.tv/sobaka-vytashhila-kotyat-iz-ognya/

**Comment by vozersky** [comment]
![454252](https://cloud.githubusercontent.com/assets/17472907/15183610/6bdc4470-179a-11e6-8bae-71e96207750d.JPG)

**Comment by Alex-302** [comment]
added to social and experimantal filter
mimimi.tv#%#AG_onLoad(function() { window.bizpanda = {}; });
