### ISSUE TITLE
www.joyreactor.cc - sort of anti adblock script?

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2148]
Есть развлекательный портал www.joyreactor.cc

Если ваша программа отключена, то всё прекрасно работает, но как только активируешь adguard, то сайт начинает редиректить на различные ресурсы. Если с мобильного интернета (у меня билайн), то на порнуху:
http://prntscr.com/b2oy50

Если с вайфая то на кучу других рекламных ресурсов.

**Comment by evgeniy-ADG** [comment]
У меня не редиректит, у меня вот такое:

![image](https://cloud.githubusercontent.com/assets/15856304/15193834/812e6af0-17c8-11e6-92e8-807856785bd6.png)

**Comment by Alex-302** [comment]
Не похоже на правду. Операторы сами вмешиваются в работу сайтов. Попроси записать HTTP лог с указанием времени явления.

**Comment by evgeniy-ADG** [comment]
Oops, там iOS.

**Comment by Alex-302** [comment]
Детект на иОС не убрать, т.к. не весь функционал возможно реализовать.
