### ISSUE TITLE
http://www.nickelodeon.ru - blocking useful content

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2149]
http://www.nickelodeon.ru/shows/spongebob-squarepants/games/spongebob-squarepants-questpants-2/regnyd

Не открываются некоторые игры (просто идет загрузки):
http://prntscr.com/b2q04u

Помогает отключение Английского фильтра

**Comment by Alex-302** [comment]
добавил в англ фильтр
```
@@||btg.mtvnservices.com/aria/coda.html?site=nickelodeontv.ru$domain=nickelodeon.ru
```
