### ISSUE TITLE
http://worldcrisis.ru - redirects to some advertising sites

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2150]
Идет перенаправление на какой-то сайт при первом открытии и нажатии, к примеру, на раздел Новое - Популярное: http://prntscr.com/b2q52f
http://worldcrisis.ru/crisis/2333172/replic_p?OLD_WINDOW=YES
http://prntscr.com/b2q4hh

![image](https://cloud.githubusercontent.com/assets/15856304/15194031/6a69c552-17c9-11e6-8a0a-a34294cc63bf.png)

**Comment by evgeniy-ADG** [comment]
У Вики повторилось, у меня - тоже.

**Comment by Alex-302** [comment]
Добавил в русский
||trafstore.com^$third-party
