### ISSUE TITLE
Футбольный Клуб «Зенит» app doesn't work

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2153]
Футбольный Клуб «Зенит»

Вылетает приложение при входе. Вытет при таких фильтрах: Русский, Английский, Фильтр мобильной рекламы
https://play.google.com/store/apps/details?id=ru.infoshell.android&hl=ru
![image](https://cloud.githubusercontent.com/assets/15856304/15208142/a1a05b8a-1832-11e6-9036-04a9f1f1cfb9.png)

XNG-531-10382

**Comment by Alex-302** [comment]
.

**Comment by Alex-302** [comment]
в мобильный
@@||ads.adfox.ru/208108/getCode

**Comment by Alex-302** [comment]
Заменил на 
```
@@||ads.adfox.ru/*/getCode$app=ru.infoshell.android
```
