### ISSUE TITLE
stadt-bremerhaven.de - Pocket icon is not blocked

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2155]
http://stadt-bremerhaven.de/google-maps-losfahren-fuehrt-zu-direkter-navigation/
![adguard_enabled](https://cloud.githubusercontent.com/assets/14153331/15218020/ac5939a0-1866-11e6-8745-169b33283ff0.png)
![adguard_disabled](https://cloud.githubusercontent.com/assets/14153331/15218015/a9509690-1866-11e6-95e1-454dee3cf045.png)

**Comment by Alex-302** [comment]
added to social filter
stadt-bremerhaven.de###socialbar-mobile
