### ISSUE TITLE
xperia-droid.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2158]
http://xperia-droid.ru/zaryadnoe-ustrojstvo-sony-uch10-quick-charger-dlya-bystroj-zaryadki-xperia.html
UPW-140-90304
![screen shot 2016-05-12 at 8 21 52 pm](https://cloud.githubusercontent.com/assets/14153331/15223885/52e665aa-187f-11e6-9b8c-ed602431d963.png)

**Comment by Alex-302** [comment]
||xperia-droid.ru/smc/proxy.php?render=js&wid=
