### ISSUE TITLE
biernet.nl

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#2160]
http://www.biernet.nl/bier/aanbiedingen/heineken
You get redirected to http://www.biernet.nl/over-ons/ad-block
![screen shot 2016-05-13 at 10 23 30 am](https://cloud.githubusercontent.com/assets/14153331/15240823/df03f0dc-18f4-11e6-9b6c-0803f26f5f16.png)

**Comment by Alex-302** [comment]
added to Dutch filter
biernet.nl#@#.afs_ads
