### ISSUE TITLE
http://www.chefkoch.de/ - Assistant doesn't appear in Firefox

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2164]
Нет значка Помощника в Firefox.
http://www.chefkoch.de/
http://prntscr.com/b470sd

QAY-413-70748

**Comment by Alex-302** [comment]
Это лучше в баги перенести.

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/AdguardForWindows/issues/1107
