### ISSUE TITLE
https://www.eurovision.de - blocked useful content

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2165]
Блокируется видео на странице в Firefox, Chrome
Помогает отключение Русского фильтра
https://www.eurovision.de/videos/2016/Pressekonferenz-Jamala-nach-ihrem-Sieg-beim-ESC,esc2588.html
http://prntscr.com/b472br
http://prntscr.com/b47208

QAY-413-70748

**Comment by Alex-302** [comment]
В русский
@@||eurovision.de/common/mediaplayer/branding/eurovision/style.branding.css
