### ISSUE TITLE
http://www.chefkoch.de - blocked useful content

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2166]
Блокируется видео на странице в Firefox, Chrome
http://www.chefkoch.de/video/artikel/1330,0/Chefkoch/Kaesekuchen-ohne-Boden.html
http://prntscr.com/b472r1
http://prntscr.com/b472xc

Помогает отключение Английского фильтра

QAY-413-70748

**Comment by Alex-302** [comment]
@@||img.chefkoch-cdn.de/gujAd.min.js
