### ISSUE TITLE
http://www.animespirit.ru - Stealth mode blocks videoplayer

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2167]
Не работает видеоплеер Муви
http://www.animespirit.ru/anime/rsb/ova-russub/1259-v-dzhunglyax-vsyo-bylo-xorosho-poka-ne-prishla.html
http://prntscr.com/b48w4c

Помогает отключение опции в Антитрекинге, а конкретно "Блокировать сторонние куки"

**Comment by Alex-302** [comment]
@evgeniy-ADG проверь плиз
@@.myvi.ru^$stealth
@@||myvi.ru/player/
Добавил. Если работает - закрывай.

**Comment by evgeniy-ADG** [comment]
Работают.
