### ISSUE TITLE
http://dengo-free.ru/index.php - anti adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2175]
![image](https://cloud.githubusercontent.com/assets/15856304/15331811/ba78c36c-1c6b-11e6-95e1-9676d02f4cf8.png)

**Comment by Alex-302** [comment]
@@||dengo-free.ru^$generichide
для юзерфильтра
сайт с крайне низкой посещаемостью
