### ISSUE TITLE
https://pirateproxy.tf/- missed ads / popups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2176]
![image](https://cloud.githubusercontent.com/assets/15856304/15331937/4d5c4320-1c6c-11e6-890d-3db1245bb766.png)

![image](https://cloud.githubusercontent.com/assets/15856304/15331945/59def016-1c6c-11e6-9c49-7e3606b66755.png)

**Comment by Alex-302** [comment]
||popped.biz^$third-party
pirateproxy.tf#%#Object.defineProperty(window, '_gunggo', { get: function() { return []; } });
