### ISSUE TITLE
http://play.ludigames.com/ - can't start a game

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2177]
http://play.ludigames.com/
при нажатии на любую игру - черный экран
http://prntscr.com/alf5xw
Помогает приостановление фильтрации.

WWS-825-72814

**Comment by Alex-302** [comment]
Added to English filter
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=play.ludigames.com
@@||imasdk.googleapis.com/js/core/*$domain=play.ludigames.com
