### ISSUE TITLE
[Android] http://bzh.life/posts/serafim-romanov-o-serfinge - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2180]
![image](https://cloud.githubusercontent.com/assets/15856304/15362177/00e7e8d0-1d1d-11e6-9647-c392d305531b.png)

**Comment by Alex-302** [comment]
Can't reproduce it.
Added:
bzh.life##.article_bottom_banner
||bzh.life/system/brandings/
bzh.life##.right_cover
bzh.life##.left_cover
bzh.life##.branding_top
It should to block ads.
