### ISSUE TITLE
A bunch of rules to add

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2181]
GOK-235-26625

Просьба добавить следующие правила блокировки в Ваши продукты!

akvarelnn.com###banner > A:first-child > IMG
akvarelnn.com###banner > A:nth-child(2) > IMG
akvarelnn.com###banner > A:nth-child(3) > IMG
akvarelnn.com###banner > A:nth-child(4) > IMG
akvarelnn.com###banner > A:last-child > IMG
akvarelnn.com###contacts > P > A:first-child > IMG
akvarelnn.com###contacts > P > A:nth-child(2) > IMG
akvarelnn.com###contacts > P > A:last-child > IMG
strighi.ru###left-menu > A:nth-child(2) > IMG
strighi.ru###left-menu > A:nth-child(4) > IMG
strighi.ru###left-menu > A:nth-child(6) > IMG
strighi.ru###left-menu > A:nth-child(8) > IMG
strighi.ru###left-menu > A:nth-child(10) > IMG
strighi.ru###block-txt > P:nth-child(6) > A:first-child > IMG
strighi.ru###block-txt > P:nth-child(6) > A:nth-child(2) > IMG
strighi.ru###block-txt > P:nth-child(6) > A:last-child > IMG
demetrann.com###left-sidebar > CENTER:last-child > A:nth-child(3) > IMG
demetrann.com###left-sidebar > CENTER:last-child > A:first-child > IMG

**Comment by Alex-302** [comment]
1. Их собственный баннер
