### ISSUE TITLE
https://get-tune.cc/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2183]
![image](https://cloud.githubusercontent.com/assets/15856304/15405672/87858c82-1e0b-11e6-8368-345dcb9fe8b0.png)

![image](https://cloud.githubusercontent.com/assets/15856304/15405685/96982798-1e0b-11e6-811d-6ca7b20b01e5.png)

**Comment by Alex-302** [comment]
||get-tune.cc/banners/
get-tune.cc###brandingBanner
