### ISSUE TITLE
http://stimul.dp.ua/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2188]
![image](https://cloud.githubusercontent.com/assets/15856304/15412062/6648f96a-1e2d-11e6-8ee3-7af7122cd6b2.png)

![image](https://cloud.githubusercontent.com/assets/15856304/15412081/80ea41e8-1e2d-11e6-9b44-3f44cef073f9.png)

**Comment by Alex-302** [comment]
@@||stimul.dp.ua/media/files/banners_
