### ISSUE TITLE
yandex.ru - assistant location issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2194]
![image](https://cloud.githubusercontent.com/assets/15856304/15438772/70aef93c-1ed6-11e6-8c65-6ea8d2f03bfe.png)

мы можем его как-то поднимать вверх, когда этот баннер возникает? что нужно для решения вопроса? смена положения значка, видимо, клиента не устраивает. баннер бы тоже скрыть, наверное.

**Comment by Alex-302** [comment]
только положение значка менять. Высоту значка не изменить.
