### ISSUE TITLE
http://vipfiles.nu/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2206]
http://vipfiles.nu/

При нажатии на ссылку фильма перекидывает на другой сайт рунеток:
http://prntscr.com/b7b4vz

При новом заходе на сайт http://vipfiles.nu/index.php Adguard пропускает выплывающее окно которое блокируется только в следующем окне.Прошу вас исправить это. Открывается сайт http://runetki.tv/p1.php?id=12225&lng=ru&tp=13&sound=0&server=runetki.com&cmp=239416

![image](https://cloud.githubusercontent.com/assets/15856304/15484492/f788d414-2142-11e6-9840-87aad0791ed3.png)

**Comment by Alex-302** [comment]
vipfiles.nu#%#AG_onLoad(function() { window.doPopunder = true; });
