### ISSUE TITLE
http://dsvload.net/

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/ExperimentalFilter#247]
http://screencast.com/t/B8s71PcP

**Comment by Bohdan-SUP** [comment]
![screen shot 2016-04-11 at 10 05 59 am](https://cloud.githubusercontent.com/assets/14153331/14419242/1850743c-ffcd-11e5-9117-b11cb44d8d4e.png)

**Comment by Alex-302** [comment]
||prim.dsvload.net^
