### ISSUE TITLE
[android] com.icecoldapps.screenshoteasy - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#249]
Посмотритеэто приложение. Когда открываешь и выходишь кнопкой назад, появляется баннер на весь экран, как на скрине.

Рекламы самой не видно, а только кнопка закрытия. Специально отключил защиту, чтобы понятнее было. И таких приложений уже несколько видел. Adaway справляется с этим баннером.

**Comment by Alex-302** [comment]
Реклама удаляется. Пустое место непобедимое, но через пару секунд скрывается.
