### ISSUE TITLE
Android реклама в приложениях

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#282]
Не блокирует рекламу в WhatsApp и Clean Master Security. Проверь пожалуйста, у меня такое ощущение что все норм блокирует. Правда, юзер через http с рутом пользуется.

https://qcrm.cc/#/customer/631744

**Comment by vbagirov** [comment]
Пока отложим это, там юзер кажется запутался в впнах)

**Comment by Alex-302** [comment]
Ну что там? Может закрыть, если у него косяк?

**Comment by vbagirov** [comment]
Там вопрос сложнее оказался, пока не закрывай. Я закрою, как надо будет, либо напишу в скайп, если будут новые детали.
