### ISSUE TITLE
game.huoying.qq.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#284]
При включенном адгарде не запускается игра, останавливается на 14% загрузки (сайт на китайском, но можно методом тыка запустить), юзер дал логин/пароль: Demonik82@Gmail.com / qwerty123

**Comment by vbagirov** [comment]
Что-то я вообще больше не могу даже до экрана загрузки дойти. Если у тебя получается, можешь прям ссылку скинуть на экран, где игра сама запускается?

**Comment by Alex-302** [comment]
Не грузится у меня.

**Comment by ameshkov** [comment]
Вась, заведи дефект тогда, может баг действительно

**Comment by vbagirov** [comment]
А на кого завесить? Пока на тебя сделал в джире.

**Comment by ameshkov** [comment]
На Вову, не надо на меня. И перенеси в подзадачи к второму патчу

**Comment by vbagirov** [comment]
Сделано, http://jira.performix.ru/browse/AG-6801
