### ISSUE TITLE
[android] strelec.ucoz.ru

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#285]
http://forum.adguard.com/showthread.php?3648-%D0%A0%D0%B5%D0%BB%D0%B8%D0%B7-Adguard-%D0%B4%D0%BB%D1%8F-Android-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F-1-1&p=39862#post39862

**Comment by Alex-302** [comment]
Чисто. Повторить не получилось.
