### ISSUE TITLE
ru.parom.tv - site is broken

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#288]
На сайте http://ru.parom.tv/ru с расширением Adguard Антибаннер 1.0.3.8 для Chrome блокирует рекламу вместе с плеером для просмотра ТВ.

**Comment by Alex-302** [comment]
Установил - всё работает. Знать бы какие фильтры используются.

**Comment by vbagirov** [comment]
Вот например юзер с андроидом, у него такие фильтры: 
русский, англ, spyware, social, mobile ads, experimental

FYU-758-29282

**Comment by Alex-302** [comment]
У меня норм. А у тебя как?

**Comment by vbagirov** [comment]
Я не догоняю, как этот плагин то работает? Я качаю плагин и дальше ничего.

**Comment by Alex-302** [comment]
А разрешил выполнение?

**Comment by vbagirov** [comment]
Не совсем понимаю. Запускаю parompluginsetup.exe и после выполнения установки нихрена нет вообще.

**Comment by Alex-302** [comment]
Пусть кто-нибудь ещё проверит. У меня всё норм. Плагинов из exe не устанавливал.

**Comment by vbagirov** [comment]
Я поставил наконец, вроде тоже все норм. Юзер тоже не откликается, так что пока думаю закрыть можно.
