### ISSUE TITLE
6000.ru - javascript error

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#290]
http://forum.adguard.com/showthread.php?3787-%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%B0-%D1%81-JavaScript-%D0%BD%D0%B0-SPA-%D1%81%D0%B0%D0%B9%D1%82%D0%B5-%D0%B1%D0%B5%D0%B7-%D1%80%D0%B5%D0%BA%D0%BB%D0%B0%D0%BC%D1%8B

**Comment by Alex-302** [comment]
Добавил в ЭФ:
@@||yandex.ru/metrika/watch.js$domain=6000.ru

**Comment by Alex-302** [comment]
Юзер разобрался со spyware-фильтром.
