### ISSUE TITLE
[android] ru.kuchaknig.android.freebooks.fantasy missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#291]
https://play.google.com/store/apps/details?id=ru.kuchaknig.android.freebooks.fantasy)

https://qcrm.cc/#/customer/745563

**Comment by Alex-302** [comment]
Чёт пока не получается. Реклама при пролистывании десятка сраниц выскакивает внизу, но запрос не поймал.
Подозревал эти
http://litres.ru/static/pr/banners_mobile/
https://service.sponsorpay.com
но блокировка не помогла.

**Comment by ameshkov** [comment]
А пробовал кэш сбрасывать?

**Comment by Alex-302** [comment]
да.
Остаётся такое:
http://imagizer.imageshack.com/img538/5294/MS7lZ2.png
выделенное синим не убрать, а красным - хз откуда берётся/

Выбрал такие рекламные сети:
||adcamp.ru^$empty
и возможно
||sponsorpay.com^$empty
Со вторым вроде рекламы меньше, только баннер со скрина, но иногда ошибка соединения выскакивает.

**Comment by Alex-302** [comment]
О, default_banner_small.png - тобишь встроенный баннер.

**Comment by Alex-302** [comment]
Закрываю. Встроенный баннер остался.
