### ISSUE TITLE
outlook.com is broken (Adguard for Opera)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#292]
I use email on the https://*.live.com website. If this extension is enabled and I go to it the extension fails and I have to go to my extensions and reload it. For now I have white-listed the site, but I would like to be able to use this there.

https://addons.opera.com/ru/extensions/details/adguard/?display=en&reports

**Comment by Alex-302** [comment]
Как я понял, при посещении сайта с включенным расширением в Опере происходит сбой расширения? У меня не повторяется, даже если включить абсолютно все фильтры.

**Comment by ameshkov** [comment]
Ну да, там похоже у чувака другая проблема, ложная тревога:)
