### ISSUE TITLE
dnevnik.ru - broken javascript

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#293]
С Аdguard не работает клавиша enter и каретка не переводится в следующую ячейку.

https://qcrm.cc/#/customer/754217

**Comment by Alex-302** [comment]
Для доступа на проблемную страницу нужна авторизация. Регистрация там, как я понял, ручная, т.е. нужны данные для входа юзера либо удалённый доступ.

**Comment by ameshkov** [comment]
А зарегаться нельзя?

**Comment by Alex-302** [comment]
Не нашёл как. Инфа ж вроде как частная. Вряд ли свободно можно регистрироваться.

**Comment by ameshkov** [comment]
Может сайт в белый список просто добавить?

**Comment by Alex-302** [comment]
Добавил в белый список. Зарегаться там никак.

**Comment by palytsh** [comment]
Здравствуйте!
Там, после авторизации, все страницы напичканы баннерами AdFox. Как бы их, все же, победить?

**Comment by Alex-302** [comment]
palytsh, без доступа к сайту ничего не поделаем. Регистрация закрытая.

**Comment by palytsh** [comment]
Alex-302, я мог бы предоставить удаленный доступ через тимвьювер. Какие-то требования к софту у вас есть?

**Comment by Alex-302** [comment]
Нет.
ИД и пароль можете здесь написать, или через форум ЛС.

**Comment by palytsh** [comment]
А надолго примерно по времени доступ потребуется?

**Comment by Alex-302** [comment]
Не знаю. Может минут 10-20.

**Comment by Alex-302** [comment]
У вас программа или браузерное расширение?

**Comment by palytsh** [comment]
Программа. 
Я подготовлю виртуалку с тимвьювером и сообщу. Но это уже, видимо, завтра.

**Comment by palytsh** [comment]
Alex-302
Сеанс ожидает. 
Правильно я понимаю, что на форуме ваш ник Alex302? Я в личку скину реквизиты.

**Comment by Alex-302** [comment]
Да. Кидайте.

**Comment by palytsh** [comment]
Готово

**Comment by Alex-302** [comment]
Где Adguard-то?

**Comment by Alex-302** [comment]
Доступ никто не даёт. Частично исключено. Закрываю.
