### ISSUE TITLE
radikal.ru

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ExperimentalFilter#295]
Никак не получается выключить клик-андер:
```
<script type="text/javascript">
      Radikal.Ver2.RClickunder.SetRClickunder("ClickunderCasinoRamses", "http://casino-ramses.com/?partner=cklikunder@casino-ramses.com", true);
    </script>
```
Там ниже ещё подозрительный скрипт манипулирует кукой "ac":
http://imagizer.imageshack.com/img538/9413/M129M0.png

**Comment by ameshkov** [comment]
Надо бы dot-shop.me/counter добавить в фильтр счетчков:
    <script type="text/javascript">
      var img = new Image();
      img.src = 'http://dot-shop.me/counter/38/1010';
      Radikal.Ver2.RClickunder.SetRClickunder("ClickunderCasinoRamses", "http://casino-ramses.com/?partner=cklikunder@casino-ramses.com", true);
    </script>

Насчет кликандера, для винды/мака просто вырезай скрипт.
Для остальных:
||radikal.ru/Misc/JumpClick$popup

**Comment by Alex-302** [comment]
Т.е. два правила добавлять?

**Comment by ameshkov** [comment]
Ну да, два

**Comment by Alex-302** [comment]
radikal.ru,radikal.cc,f-picture.net$$script[tag-content="RClickunder"][max-length="300"]
