### ISSUE TITLE
fishki.net

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ExperimentalFilter#296]
На сайте чуть изменили рекламное сообщение - subscribe_link_543769 стало subscribe_link_******_543769, "img" стало "a"
Старый вариант:
```
fishki.net#%#AG_onLoad(function() { $('img[data-subscribe="subscribe_link_543769"]').closest('div[id^="post-"]').remove(); });
```
Чуть поправил скрипт, немного коряво, но работает:
```
fishki.net#%#AG_onLoad(function() { $('a[data-subscribe*="_543769"]').closest('div[id^="post-"]').remove(); });
```
Можно как-то случайное число в data-subscribe="subscribe_link_********_543769" сделать перевариваемым Адгардом? Или оставить data-subscribe*="_543769" ?

**Comment by ameshkov** [comment]
Вроде нельзя, я во всяком случае не умею.

**Comment by Alex-302** [comment]
Тогда так оставляю, вроде не должно лишнего порезать.
