### ISSUE TITLE
[android] nbcapp missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#297]
https://play.google.com/store/apps/details?id=com.nbcuni.nbcots.nbcnewyork.android&hl=en

**Comment by Alex-302** [comment]
Не хочет устанавливаться ни на эмулятор, ни на планшет
http://imagizer.imageshack.com/img661/3853/4qdQj2.png

**Comment by ameshkov** [comment]
В теории - оно для планшетов.

Кстати ты можешь просто вытащить их apk из стора и установить куда хочется.

**Comment by Alex-302** [comment]
А каким образом вытащить не устанавливая?

**Comment by ameshkov** [comment]
А ну погугли, куча сервисов есть для этого

**Comment by Alex-302** [comment]
Ага, есть онлайн сервис
http://apps.evozi.com/apk-downloader/?id=com.nbcuni.nbcots.nbcnewyork.android
Буду смотреть.

**Comment by Alex-302** [comment]
Добавил
||adcel.vrvm.com^$empty

**Comment by ameshkov** [comment]
Чот чувак говорит что не помогло

**Comment by Alex-302** [comment]
Странно. А кэш с остановкой программы он чистил?

**Comment by ameshkov** [comment]
Не, не чистил

**Comment by ameshkov** [comment]
После чистки - он говорит что первую видео-рекламу блочит, а дальше пропускает

**Comment by ameshkov** [comment]
Может прокси СШАшный попробовать?

**Comment by Alex-302** [comment]
Так adguard перестаёт работать. Запустил на компе тор, из эмулятора копм и сайты пингуются, но не открываются. Даже с выключенным Adguard'oм.

**Comment by Alex-302** [comment]
проверил снова - рекламы нет
