### ISSUE TITLE
isunnys.xyz missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#298]
http://www.isunnys.xyz/details/8988667/CCleaner-Pro--serial.html There you will see two layers without content (probably ads). DIV IDs are "xydleft" and "xydlright"

https://qcrm.cc/#/customer/668430

**Comment by Alex-302** [comment]
Скриншот бы. Таких ID не вижу.
И по скрину вопрос - надо ли блокировать эти элементы?
http://imagizer.imageshack.com/img905/6199/T72Btk.png

**Comment by ameshkov** [comment]
Да не вроде не надо

**Comment by Alex-302** [comment]
Добавил в ЭФ:
||happliances.com/center.js
Скриптов на сайте овер дофига. Не понятно на кой они нужны на трекере.

**Comment by Alex-302** [comment]
Вроде ничего больше не появляется.
