### ISSUE TITLE
sat-sharing.us missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#299]
http://sat-sharing.us/forum/showthread.php?t=369970 

Between the thread title "Sky Germany Full HD with all Option, without PPV Caid 098C " and the initial content a lot of ad banners are displayed.

**Comment by Alex-302** [comment]
Добавил в ЭФ:
sat-sharing.us##div[style="padding:0px 25px 0px 25px"] > p[align="center"]
sat-sharing.us##a[href^="http://www.flashdz.com/"]

**Comment by Alex-302** [comment]
Вроде всё норм.
