### ISSUE TITLE
online-life.me - missed video ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#300]
На сайте http://www.online-life.me/5073-vikingi-2014.html встроена видео-реклама с megogo.net

https://qcrm.cc/#/customer/756480

**Comment by Alex-302** [comment]
Добавил в ЭФ:
||megogo.net/e/*?autoplay=1$domain=online-life.me

**Comment by vbagirov** [comment]
Рекламы нет.
