### ISSUE TITLE
mcdownloads.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#302]
При клике по любому месту на сайте открывается вкладка.

**Comment by Alex-302** [comment]
Добавил в ЭФ:
||ocelot.mcdownloads.ru^

**Comment by vbagirov** [comment]
Спасибо, закрываю.

**Comment by vbagirov** [comment]
Снова здорова. Опять попапы при клике в любом месте сайта. Можно как-то исправить?

**Comment by Alex-302** [comment]
Добавил в  ЭФ:
||zurage.ru^

**Comment by vbagirov** [comment]
Пока работает, потом посмотрим.
