### ISSUE TITLE
http://beta.sberbank.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#303]
При включенном адгарде ломается отображение сайта.

https://qcrm.cc/#/customer/687635

**Comment by Alex-302** [comment]
А пусть юзер обновит фильтры, очистит кэш браузеров(очень рекомендуется) и проверит. Должно стать нормально.

**Comment by vbagirov** [comment]
Понял, вроде у меня все в норму пришло.
