### ISSUE TITLE
http://www.filmkorku.org/category/turkce-dublaj/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#304]
Рекламный фон на странице.

https://qcrm.cc/#/customer/776080

**Comment by Alex-302** [comment]
Добавил в ЭФ:
filmkorku.org#$#html body {background-image: url('/')!important; background-color: #3c0f10!important;}
||filmkorku.org/wp-content/plugins/wpsite-background-takeover/
Первое правило меняет цвет фона. Если не хочет, чтоб фон был чёрным, пусть экспериментальный держит включенным(твики в ЭФ оставляем)

**Comment by vbagirov** [comment]
Не совсем понял, если он отключит ЭФ, то ведь рекламный фон вернется. Так что выбора с цветом фона у него нет)

**Comment by Alex-302** [comment]
А это на будущее, если второе правило в основной уйдёт.
