### ISSUE TITLE
http://pornolab.net/forum/index.php

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#305]
Сверху рекламная надпись с внешней ссылкой: http://i64.fastpic.ru/big/2015/0113/1a/97b7ed6bfd57c302541846ee05989e1a.png

https://qcrm.cc/#/customer/677317

**Comment by Alex-302** [comment]
Добавил в ЭФ:
pornolab.net###page_container.cvPrIIzeW

**Comment by vbagirov** [comment]
Не помогает пока. Кэш чистил, пробовал в хроме и мозилле: http://screencast.com/t/pmiQW1URMJEW

**Comment by Alex-302** [comment]
Ага. Всё таки ID случайный. Позже гляну.

**Comment by Alex-302** [comment]
Решили на форуме.

**Comment by vbagirov** [comment]
Так не решили же. 
http://forum.adguard.com/showthread.php?4047-http-pornolab-net&highlight=pornolab

Или есть еще какая-то тема?

**Comment by Alex-302** [comment]
Изменили ссылку. Посмотрим.

**Comment by vbagirov** [comment]
А нельзя как-нибудь заблокировать как класс их? А то походу проблема как на mcdownloads, там тоже каждый раз ты пишешь правило и каждый раз спустя день или два она появляется снова.

**Comment by Alex-302** [comment]
На mcdownloads название рекламного домена меняют. Здесь не так.

**Comment by Alex-302** [comment]
Такое проверь
pornolab.net###page_container > a

**Comment by vbagirov** [comment]
Работает.
