### ISSUE TITLE
http://www.gorod.cn.ua/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#306]
Реклама не заблокирована.

https://qcrm.cc/#/customer/780210

**Comment by Alex-302** [comment]
Добавил в ЭФ:
gorod.cn.ua##div[class^="branding_"]
||prosto.cn.ua^$domain=gorod.cn.ua
||gorod.cn.ua/image/banners/
||gorod.cn.ua/pics/brending/
||grt03.com^

**Comment by vbagirov** [comment]
Все ок.
