### ISSUE TITLE
[Android] CvPad+ purchased

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#310]
https://play.google.com/store/apps/details?id=com.cvpadx.mobile.android.wt.unit&hl=en

При выборе конвертации курса валют, при включенном Adguard не обновляются сами курсы.

FYU-758-29282

**Comment by Alex-302** [comment]
Добавил в исключения:
@@||convertpad.com/ad/*
без * почему-то иногда не подгружает обновление курсов.

**Comment by ameshkov** [comment]
Это ж в мобильный фильтр надо было?

**Comment by Alex-302** [comment]
Ага. Привык что туда рекламные сети отправляются.
