### ISSUE TITLE
ru.chaturbate.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#311]
Судя по всему, у некоторых пользователей при использовании расширения произвольно открывается данное окно. Можно что-то сделать, как думаешь?

**Comment by Alex-302** [comment]
А какое окно?

**Comment by vbagirov** [comment]
ru.chaturbate.com

**Comment by Alex-302** [comment]
Нужен скрин.

**Comment by vbagirov** [comment]
Тут скрин есть

http://forum.adguard.com/showthread.php?2646-%D0%A0%D0%B5%D1%88%D0%B5%D0%BD%D0%BE-%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5-%D1%80%D0%B5%D0%BA%D0%BB%D0%B0%D0%BC%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BE%D0%BA%D0%BD%D0%B0&highlight=chaturbate

**Comment by Alex-302** [comment]
У тебя провявляется? У юзера видать не включены нужные фильтры. Версия прги какая?

**Comment by vbagirov** [comment]
У меня та же инфа, что и у тебя, с форума. У меня не получилось повторить, но я помню что как минимум несколько человек жаловались независимо.

**Comment by Alex-302** [comment]
хз. Пусть снова проверят. Какие фильтры у них включены? Из каких стран?

**Comment by Alex-302** [comment]
Понял когда попап лезет - когда кука np3=4, т.е. после 4х переходов. Но пока не поборол.
```
$(document).ready(function(){
  var ran_yet = false;
  $("a,body,input").live('click', function() {

    if (ran_yet) {
      return true;
    }
    ran_yet = true;
    var cookiename = 'np3';
    var val = $.cookie(cookiename);
    if (!val) {
      val = 1;
    } else {
      val = parseInt(val);
    }
    var d = new Date;
    // millisecs * seconds * minutes * hours
    d.setTime(d.getTime() + 1000 * 60 * 60 * 8);
    $.cookie(cookiename, val + 1, {expires: d, path: '/'});
    if (val != 3) {
      return true;
    }
    var windowprops = "width=1024,height=768,location=yes,toolbar=yes,menubar=yes,status=yes,scrollbars=yes,resizable=yes,top=1,left=1";

    var url = "/sitestats/openwindow/XEkg3mlz-xliSmtr/?url=http://www.ashleyrnadison.com/A112437+ad_lander";

    var myWin = window.open(url, "", windowprops);
    myWin.blur();
    window.focus();
    if (typeof mySurveyWin !== 'undefined') {
        mySurveyWin.focus();
    }
    return true;
  });
});
```

**Comment by vbagirov** [comment]
Вот это ты откопал старый тикет.

**Comment by Alex-302** [comment]
Добавил
chaturbate.com#%#document.cookie = "np3=5";
