### ISSUE TITLE
http://bb.is/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#312]
Реклама на странице

https://qcrm.cc/#/customer/783347

**Comment by Alex-302** [comment]
А мы похоже не можем там фильтровать, сайт корявый что ли.

**Comment by vbagirov** [comment]
Надо бы спросить у Андрея.

**Comment by Alex-302** [comment]
Добавил в ЭФ:
bb.is$$div[class="banner"]
