### ISSUE TITLE
[Android] http://yarportal.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#313]
Реклама пропущена

https://qcrm.cc/#/customer/699555

**Comment by Alex-302** [comment]
Добавил в ЭФ:
yarportal.ru##td[align="right"][valign="middle"][class="desc"]

**Comment by Alex-302** [comment]
И от пустых блоков сверху:
yarportal.ru##div[style="font-size: 0; border: 1px solid #1b4786; background-color: #1b4786; margin: 0; padding: 0px; display: block; overflow: hidden; height: 60px;"]
yarportal.ru##div[style="font-size: 0; border: 1px solid #FFE500; background-color: #FFE500; margin: 0; padding: 0px; display: block; overflow: hidden; height: 60px;"]
yarportal.ru##div[style="font-size: 0; border: 1px solid #1b4786; background-color: #1b4786; margin: 0; padding: 0px; display: block; overflow: hidden; height: 60px;"]
yarportal.ru##div[style="font-size: 0; border: 1px solid #67FDFB; background-color: #67FDFB; margin: 0; padding: 0px; display: block; overflow: hidden; height: 60px;"]
