### ISSUE TITLE
Не отображается кнопка "расшарить"

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#314]
https://blog.mozilla.org/blog/2015/01/13/firefox-enables-you-to-experience-and-share-more-on-the-web/

Отключение соцмедиа фильтра не помогает. 

https://qcrm.cc/#/customer/787647

**Comment by Alex-302** [comment]
А у тебя на этом сайте помощник с программой корректно работают - значок расширения синий?

**Comment by Alex-302** [comment]
Чёт повторить не могу. Один раз повторилось, а в дальнейшем не хочет пропадать даже в другом браузере.

**Comment by vbagirov** [comment]
Мы же про одно и то же говорим? Вот это поле? http://screencast.com/t/oopqYcIro

**Comment by Alex-302** [comment]
Ага

**Comment by vbagirov** [comment]
Блокируется соцфильтром у меня. Включаю логгирование, релевантно этого сайта следующие записи:

Address: http://secure.gravatar.com/avatar/f84bd67e8e3ab3bcc9676910aecf5700?s=24&d=https%3A%2F%2Fsecure.gravatar.com%2Favatar%2Fad516503a11cd5ca435acc9bb6523536%3Fs%3D24&r=G
Time: 01/20/2015 18:22:18
Status: Request processed
Request details:

The request was sent from the following web page:
https://blog.mozilla.org/blog/2015/01/13/firefox-enables-you-to-experience-and-share-more-on-the-web/

Bytes received: 1784
Bytes sent: 583


Address: http://ssl.google-analytics.com/ga.js
Time: 01/20/2015 18:22:19
Status: Request blocked
Request details:

The request was sent from the following web page:
https://blog.mozilla.org/blog/2015/01/13/firefox-enables-you-to-experience-and-share-more-on-the-web/

The request was blocked by the following filtering rule:

||google-analytics.com/ga.js$third-party


Address: http://secure.gravatar.com/avatar/f84bd67e8e3ab3bcc9676910aecf5700?s=68&d=https%3A%2F%2Fsecure.gravatar.com%2Favatar%2Fad516503a11cd5ca435acc9bb6523536%3Fs%3D68&r=G
Time: 01/20/2015 18:22:19
Status: Request processed
Request details:

The request was sent from the following web page:
https://blog.mozilla.org/blog/2015/01/13/firefox-enables-you-to-experience-and-share-more-on-the-web/

Bytes received: 5937
Bytes sent: 583

**Comment by Alex-302** [comment]
А сейчас как?

**Comment by vbagirov** [comment]
По-прежнему с соцфильтром блокируется. Может они и должны блокироваться соцфильтром, я так подумал?

**Comment by Alex-302** [comment]
а ты ж в начале писал "Отключение соцмедиа фильтра не помогает."
Похоже наоборот - без соц фильтра блокируется

**Comment by vbagirov** [comment]
Да нет, сейчас еще раз проверил. Отключил социалку - появляются элементу спустя несколько секунд после открывания менюшки. Включил назад, открыл, прождал секунд 20 - ничего.

**Comment by vbagirov** [comment]
Мой косяк, все работает как положено в общем.
