### ISSUE TITLE
kurier.at

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#316]
В правом верхнем углу при просмотре галлерей фото (например http://kurier.at/kultur/medien/ansturm-auf-charlie-hebdo-hefte-setzt-sich-fort/108.040.236#108129236,108067465 ) пропадают две кнопки: http://screencast.com/t/Oveq6SgarOx

http://forum.adguard.com/showthread.php?3974-kurier-at-(two-important-buttons-are-missing-in-the-photo-galleries)

**Comment by Alex-302** [comment]
Добавил в ЭФ
kurier.at#@#.adblock
