### ISSUE TITLE
[android] marble legend missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#320]
Пропускает рекламу в приложении Marble legend.Загрузка рекламных баннеров идет на флешку,в папку netimages

**Comment by Alex-302** [comment]
Как-то так:
||pub1.co^$empty
Добавил в ЭФ

**Comment by Alex-302** [comment]
Чисто вроде. Закрыть?

**Comment by ameshkov** [comment]
Давай
