### ISSUE TITLE
androidcentral.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#321]
Реклама не заблокирована с правой стороны страницы.

**Comment by Alex-302** [comment]
А передай юзеру такие правила. Всё ли почикал? Ничего нужного?
androidcentral.com##div[id$="-store-ad"]
||shopandroid.com/external_marketing/$domain=androidcentral.com
side-tshirts.png$domain=androidcentral.com

**Comment by vbagirov** [comment]
Юзер это Егор =) И вроде все работает нормально с такими правилами.

**Comment by Alex-302** [comment]
Добавил.
