### ISSUE TITLE
http://video.nydailynews.com/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#323]
После просмотра и остановки видео ссылки оказываются некликабельными. Повторилось как на маке, так и в винде.

http://forum.adguard.com/showthread.php?3976-MAC-Site-Issue-(http-video-nydailynews-com)

**Comment by Alex-302** [comment]
Видео запустилось. После паузы видео пошло, ссылки работают.
В винде, как я понял, повторилось у тебя?

**Comment by vbagirov** [comment]
Да, потестил и есть ощущение, что это спайвэр фильтр. Хотя поведение вообще странное на этом сайте.

**Comment by Alex-302** [comment]
Как сейчас? Проблема осталась?

**Comment by Alex-302** [comment]
Такое проверь
@@||omtrdc.net^$domain=nydailynews.com
Добавил в ЭФ.

**Comment by vbagirov** [comment]
Вроде работает. Закрыл.
