### ISSUE TITLE
dfiles.ru - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#324]
http://dfiles.ru/files/2vevdpfqv

Там много всякого.
Верхняя полоска, попап лезет

**Comment by ameshkov** [comment]
Попап надо глушить $popup-правилом (лезет в бэкграунде)

**Comment by Alex-302** [comment]
Хм.. попапа что-то не увидел, с разными ip...
По рекламе и остаткам:
||ads.dfiles.ru^
dfiles.ru##a[href="http://zillya.ua/ru/antivirus_free"]
dfiles.ru##.banner
dfiles.ru##div[id^="ads_zone"]
dfiles.ru##iframe[id^="ads_"]
От их качальщика:
dfiles.ru##.network_downloader
Всё добавил в ЭФ.

**Comment by ameshkov** [comment]
Есть он там, когда капчу вводишь

**Comment by Alex-302** [comment]
Вот никак не появляется. Могу тимвивером доступ дать

**Comment by Alex-302** [comment]
Наконец увидел описанное)
Имя полоски -  .submenu
Добавил два варианта - полный, и частичный(полоса останется, ссылка уберётся)
dfiles.ru###member_menu > .submenu
dfiles.ru##a[href^="http://ads.depositfiles.com/"]
Попапы убрал так:
||ggg.rambler.pw^$popup
А вот если выпилить ||adverigo.com^$third-party - то капча с попапом не появляется вообще.
Добавил оба варианта.
