### ISSUE TITLE
http://www.thefreedictionary.com/polemic

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#325]
Реклама не заблокирована справа.

https://qcrm.cc/#/customer/806451

**Comment by Alex-302** [comment]
Вот такое проверь
||thefreedictionary.com/_/track.ashx?r=

**Comment by vbagirov** [comment]
Работает, можно заносить в ЭФ.

**Comment by Alex-302** [comment]
Добавил.
