### ISSUE TITLE
http://m.ynet.co.il

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#327]
Тема на форуме: http://forum.adguard.com/showthread.php?4060-adguard-prevent-site-from-loading

У юзера при попытке перейти на сайт http://m.ynet.co.il загрузка останавливается на http://m.ynet.co.il/Promo.aspx

**Comment by ameshkov** [comment]
Ну самый простой вариант - просто разблокировать на Promo все, чтобы с нее выйти можно было.
Или разблокировать все кроме крестика

**Comment by Alex-302** [comment]
Добавил в ЭФ:
@@||m.ynet.co.il/Promo.aspx^$document

**Comment by vbagirov** [comment]
Ок, закрываю. Все равно на форуме есть тема.
