### ISSUE TITLE
roleplayer.me

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#328]
После авторизации появляется антиадблок.

**Comment by Alex-302** [comment]
Добавил в ЭФ
@@||roleplayer.me/adframe_

**Comment by vbagirov** [comment]
По прежнему: http://screencast.com/t/HNqZb80Q

**Comment by Alex-302** [comment]
Ты на какой странице проверяешь? Случайно не на http://www.roleplayer.me/notice.php ?)

**Comment by vbagirov** [comment]
Проблема в том, что куда мы не переходил на сайте, меня перекидывает на /notice.php как раз. Это только после авторизации происходит, насколько я могу судить.

**Comment by Alex-302** [comment]
Странно. У меня с правилом никуда не перекидывает. А кэш чистил?

**Comment by vbagirov** [comment]
Чистил, не помогает. Даже в разных браузерах пробовал - одно и то же.
