### ISSUE TITLE
[Android] Foreca Weather

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#331]
https://play.google.com/store/apps/details?id=com.foreca.android.weather&hl=en

У юзера остается черная подложка от рекламы. У меня ничего не повторилось такого. 

Фильтры русский, англ, spyware, соцсети и мобильный

https://qcrm.cc/#/customer/809095

**Comment by Alex-302** [comment]
У меня вот так:
http://imagizer.imageshack.com/img540/8247/Fh4LFp.png
А юзер пробовал кэш проги чистить?

**Comment by vbagirov** [comment]
Запросил.

**Comment by Alex-302** [comment]
Молчок?

**Comment by vbagirov** [comment]
Я дурак, отправил русскоговорящему юзеру на английском. Может потому и нет овтета. Сейчас еще раз спрошу, пока не закрывай.

**Comment by vbagirov** [comment]
В общем юзер удалил Адгард с телефона и не собирается тестировать больше. Закрываю, т.к. не повторяется.
