### ISSUE TITLE
[android] Stick Hero missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#333]
Жалоба с 4pda

**Comment by Alex-302** [comment]
У меня всё чисто.
В логе CONNECT ads=1 googleads.g.doubleclick.net
Задал юзеру вопрос во версии и фильтрам.

**Comment by ameshkov** [comment]
Спроси еще версию, вдруг он на 805-й, а не на 808-й

**Comment by Alex-302** [comment]
жду ответа

**Comment by Alex-302** [comment]
1,1,808
Помогает ||googleads.g.doubleclick.net^

||googleads.g.doubleclick.net^$popup,third-party похоже не работает.

**Comment by Alex-302** [comment]
добавил в мобильный:
||presselite.com/iphone/pushnotification/interstitiel_android.php
