### ISSUE TITLE
nnm-club.me - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#334]
Big frame on tha main page

**Comment by Alex-302** [comment]
Добавил в ЭФ
nnm-club.me##iframe[src^="http://www.mxttrf.com/"]

**Comment by ameshkov** [comment]
А сам mxttrf.com мы блочим?

**Comment by Alex-302** [comment]
Нет вроде. Добавил в англ
||mxttrf.com^$third-party
