### ISSUE TITLE
gametech.ru - missed branding and ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#335]

**Comment by Alex-302** [comment]
Добавил в ЭФ:
||gametech.ru/brand/
gametech.ru##.clickable_zone
___
gametech.ru#$#body {background:#eee!important;}
gametech.ru#$#body {margin-top: 0px!important;}

**Comment by ameshkov** [comment]
А #$# правила обязательно?

**Comment by Alex-302** [comment]
Не, я их в анноянсез кинул, забыл подписать. Это для возвращения оригинального фона.
