### ISSUE TITLE
lenta.ru - social filter breakes site

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#336]
http://lenta.ru/news/2015/01/27/boysgirlsschool/

пропадает кнопка "обсудить" с соц фильтром

**Comment by Alex-302** [comment]
Добавил в ЭФ:
lenta.ru#@##socials
lenta.ru##.share_btns

**Comment by vbagirov** [comment]
У меня работает отлично все.
