### ISSUE TITLE
[Android] Deer Hunter

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#338]
https://play.google.com/store/apps/details?id=com.glu.deerhunt2&hl=en

Реклама после прохождения миссии.

**Comment by Alex-302** [comment]
куча запросов. Позже гляну подробно.
ws.tapjoyads.com

**Comment by vbagirov** [comment]
https://play.google.com/store/apps/details?id=com.glu.dino

**Comment by Alex-302** [comment]
Добавил в ЭФ:
||nanigans.com^$empty
||gluservices.s3.amazonaws.com/PushNotifications2.0/^$empty
||playhaven.com^$empty
||adcolony.com^$empty
