### ISSUE TITLE
http://www.zdnet.com/pictures/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#342]
Когда открываешь статью, где несколько фотографий, кнопки "Next" и "Previous" не работают.

Chrome on Win 8.1

**Comment by Alex-302** [comment]
У меня они и без защиты не работают. Спроси у юзера, как у него они ведут себя с выключенной защитой.

**Comment by vbagirov** [comment]
У меня работают с выключенной. Егор на 8 потестил - тоже щелкается.

**Comment by Alex-302** [comment]
Ага. Хромовское расширение Blur мешает, типа шпионские штучки удаляет)

**Comment by Alex-302** [comment]
Вот такое правило проверь:
@@||cdn.optimizely.com/js/$domain=zdnet.com
В ЭФ добавил.

**Comment by vbagirov** [comment]
Все работает.
