### ISSUE TITLE
http://smallpdf.com/compress-pdf

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#347]
Сжатие "зависает" при включенном адгарде.

https://qcrm.cc/#/customer/827954

**Comment by Alex-302** [comment]
Добавляю в исключения - не работает, с выключенной защитой - тоже.

**Comment by vbagirov** [comment]
Да вроде все норм с выключенной защитой. Попробуй в инкогнито.

**Comment by Alex-302** [comment]
Странно. Всё вроде работает, только большой файл жмёт долго. Проверь у себя ещё раз, или свой файл скинь.

**Comment by vbagirov** [comment]
https://www.dropbox.com/s/kz7qpc0zmctbz2s/%D0%9A%D1%80%D0%B0%D1%82%D0%BA%D0%BE%D0%B5%20%D1%80%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE%20%D1%81%20%D1%87%D0%B5%D0%B3%D0%BE%20%D0%BD%D0%B0%D1%87%D0%B0%D1%82%D1%8C.pdf?dl=0

Тестил на этом, 100кб всего, ждал вплоть до минуты - ничего. Отключаю АГ - за секунду сжимает.

**Comment by vbagirov** [comment]
Тут есть какая-то надежда?

**Comment by Alex-302** [comment]
Работает же
http://imagizer.imageshack.com/img540/8423/oWyYwi.png

**Comment by vbagirov** [comment]
Да, работает. Закрываю.
