### ISSUE TITLE
http://megashara.com/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#350]
При переходе на сайт в верхней части появляется видео "ТВ мир", также рекламный фон не заблокирован.

https://qcrm.cc/#/customer/846067

**Comment by Alex-302** [comment]
Добавил в ЭФ:
```
||mcount.ru^$third-party
||tvmir.ru^$domain=megashara.com
```

**Comment by vbagirov** [comment]
Ок, спасибо.
