### ISSUE TITLE
radins.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#353]
Check it in IE11:
http://forum.adguard.com/showthread.php?4117-www-radins-com

**Comment by Alex-302** [comment]
Не понимаю, что не работает. Скрины упорно не даёт.

**Comment by ameshkov** [comment]
Ну понятно, давай закрывать тогда

**Comment by ameshkov** [comment]
Отпиши только в теме, что в IE11 у тебя все ок работает
