### ISSUE TITLE
http://carambatv.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#358]
При просмотре видео антиадблок не дает смотреть видео в высоком качестве при включенном блокировщике.

https://qcrm.cc/#/customer/853478

**Comment by Alex-302** [comment]
Пусть проверит:
@@||carambatv.ru/player/$elemhide

**Comment by vbagirov** [comment]
У меня работает.

**Comment by Alex-302** [comment]
Добавил в ЭФ.
