### ISSUE TITLE
oregonlive.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#360]
Англ фильтр режет шапку сайта

https://qcrm.cc/#/customer/856096

**Comment by Alex-302** [comment]
Спроси, так пойдёт?
oregonlive.com#@##adv_header

**Comment by vbagirov** [comment]
У меня норм.

**Comment by floam** [comment]
Any filter targeting [oregonlive.com](https://oregonlive.com) should likely be extended to all of the newspapers ran by Advance Digital (e.g. [nj.com](https://nj.com)). There is a partial list [here](http://advancedigital.com).

**Comment by Alex-302** [comment]
@floam why? Please make a screenshot of an issue.

**Comment by floam** [comment]
Because it looks like it is successfully hiding elements with the same names with a filter that is only applying to oregonlive.com - the sites essentially share a template. 

nj.com (header):

**Comment by Alex-302** [comment]
> but can't understand the conversation very well through Google Translate

the rule above is for unhiding the string with menu button and logo. But this issue was not confirmed by us.

All these sites looks like this:
<details>
![image](http://ipic.su/img/img7/fs/kiss_495kb.1470055615.png)
</details>

I don't understand what is the problem:)

**Comment by floam** [comment]
Yours looks good there. Look at my screenshot, there is a dark grey uncollapsed div above the the tan header. Maybe it's a problem with the filter lists converted over for WebKit content blocking JSON?

Sometimes it goes away after a refresh. It might not be on that leighvalleylive.com, but I'm seeing it here: http://www.syracuse.com/ and on http://nj.com.

**Comment by floam** [comment]
Or nola.com:
<img width="726" alt="screenshot 2016-08-01 at 7 19 35 am" src="https://cloud.githubusercontent.com/assets/291142/17297107/1e9d9a42-57b9-11e6-8de2-d7d55f390c4a.png">

**Comment by Alex-302** [comment]
It is possible, but I can't reproduce it also in Safari on Mac OS.
<details>
![image](http://i.imgur.com/E2izvS0.png)
</details>
Content blocker has a limit 50000 rules.
This element is hidden by generic rule(no domain restrictions)
```
###adv_network
```
Please check in in user filter.

**Comment by Alex-302** [comment]
Are you using full or optimized filters?

**Comment by floam** [comment]
Optimized. I don't know how to interrogate the plugin to have it reveal to me the rules it is really using.

These are flipped on: English, Experimental, Annoyances, Fanboy Annoyances, Spyware, Adblock Warning Removal, Safari Filter. It's not in the user filter.

**Comment by Alex-302** [comment]
I mean you should to add `###adv_network` to user filter and test the issue again.
http://i.imgur.com/YIrFnbf.png
