### ISSUE TITLE
http://www.silkeborgforsyning.dk/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#363]
Блокируем содержимое сайта

https://qcrm.cc/#/customer/859547

**Comment by Alex-302** [comment]
Возможно баг.
В проге, даже с выключенными фильтрами, нет части элементов(и в исходном тексте).
Без фильтрации:
http://imagizer.imageshack.com/img540/5262/OqQikN.png
с фильтрацией(даже если все фильтры выключены):
http://imagizer.imageshack.com/img661/6097/uoIpGH.png

С расширением - нормально.

**Comment by vbagirov** [comment]
Завел баг: http://jira.performix.ru/browse/AG-6998

**Comment by ameshkov** [comment]
В сегодняшней бете заработает.

Юзеру можно сказать, что баг в ближайшем обновлении исправится.

**Comment by vbagirov** [comment]
Юзеру ответил, в бете все отображается как надо на сайте. Закрывать?

**Comment by ameshkov** [comment]
Да
