### ISSUE TITLE
http://moevideo.net/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#364]
Появляется реклама после просмотра ролика, например:
http://moevideo.net/video/01159.06d5a871dd8ffe79691792c9d54d

https://qcrm.cc/#/customer/854713

**Comment by Alex-302** [comment]
Пока не знаю как заблокировать. заготовка
||c.cblevt.com^
||cpanetwork.ru^

**Comment by Alex-302** [comment]
Добавил в ЭФ:
||moevideo.net/img/promo/*.mp4$mp4
Заработает после удаления исключения при переносе в основной фильтр.

**Comment by vbagirov** [comment]
Ок, закрываю.
