### ISSUE TITLE
Некорректно отображаются сайты Concrete5

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#365]
Среди них такие как: 
gloryon.com
newayseurasia.com
nikken.com
nikken.ru
nnpcto.ru
staraya-lavka.ru
timeweb.com
xango.ru

Юзер говорит, что есть еще. Можно как-то исправить?

https://qcrm.cc/#/customer/737277

**Comment by Alex-302** [comment]
newayseurasia.com, nikken.com, xango.ru, gloryon.com - не понятно что не работает. Пусть уточнит, желательно со скринами.

staraya-lavka.ru - гороскоп по делу почикан, т.к. при любом клике перекидывает на другой сайт. Если ему нужен, то пусть добавит @@||informers.ukr.net/horo/

Добавил в ЭФ:
@@||newayseurasia.com/assets/images/banners/
@@||newayseurasia.com/assets/cache/images/banners/home/
@@||nikken.ru/images/banners/
@@||nnpcto.ru/banners/
@@/banner.jpg$domain=timeweb.com

**Comment by vbagirov** [comment]
Пока закрываю.
