### ISSUE TITLE
gazeta.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#370]
Соцфильтр блокирует кнопку комментариев к статьям

**Comment by Alex-302** [comment]
пока не добавляю
gazeta.ru#@#.b-social_like_buttons
gazeta.ru##a.lj_new_send
gazeta.ru###vk_like2
||vk.com/widget_like.php - почему-то не работает

**Comment by vbagirov** [comment]
У меня с этими правилами комментарии есть.

**Comment by Alex-302** [comment]
Уже починили.
