### ISSUE TITLE
http://www.androidfreeware.net/download-youtube-tubemate.html

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#371]
Остаются артефакты в приложении:
http://screencast.com/t/jStaSroaqSO

https://qcrm.cc/#/customer/864901

**Comment by Alex-302** [comment]
Добавил в ЭФ:
||tapit.com^$empty
||cdn.lfstmedia.com/~cdn/Ads/$empty

**Comment by vbagirov** [comment]
Спасибо, закрываю.

**Comment by vbagirov** [comment]
По-прежнему остается реклама: http://screencast.com/t/y5zgDSKO3JHn

**Comment by vbagirov** [comment]
По-прежнему остается реклама: http://screencast.com/t/y5zgDSKO3JHn
Иногда с задержкой где-то в минуту.

**Comment by Alex-302** [comment]
попробуй такой вариант(расширенный вариант имеющегося правила)
||cdn.lfstmedia.com^$empty

**Comment by Alex-302** [comment]
Проверил снова - чисто.
