### ISSUE TITLE
doulci.net

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#372]
Антиадблок
Также на doulci-registration.com

https://qcrm.cc/#/customer/628002

**Comment by Alex-302** [comment]
Добавил в ЭФ:
- doulci-registration.com
||doulci-registration.com/wp-content/plugins/!!!adbuddy-adblocker-detection/
- doulci.net
doulci.net#@##adlabel
doulci.net#@##advertbox3
doulci.net#@##bottomAd
doulci.net#@##mini-ad
doulci.net#@#rightAd
doulci.net#@##sky_advert
doulci.net#@##top_ad_game
doulci.net#@##ads
doulci.net#@##adsense
doulci.net#@##rightAd

**Comment by vbagirov** [comment]
Спасибо, закрыл.
