### ISSUE TITLE
http://nuzhnyrabochie.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#374]
Исчезает поиск, исчезает меню

https://qcrm.cc/#/customer/881697

**Comment by Alex-302** [comment]
Если нужны счётчики - пусть выключит соответствующий фильтр.
Для поиска добавил в ЭФ:
@@||nuzhnyrabochie.ru/themes/1/css/adv.css
На счёт меню не понял, где и какое.

**Comment by vbagirov** [comment]
Работает, закрыл.
