### ISSUE TITLE
http://simplylinux.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#375]
"Убиваем" сайт.

https://qcrm.cc/#/customer/885001

**Comment by Alex-302** [comment]
Нужен список фильтров. У меня всё нормально.

**Comment by vbagirov** [comment]
Буду уточнять, вроде у меня вчера еще была проблема, а сейчас уже все ок.

**Comment by Alex-302** [comment]
Работает вроде.

**Comment by vbagirov** [comment]
Ок, пока закрываю.
