### ISSUE TITLE
http://maskme.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#376]
Spyware фильтр блокирует ссылки в шапке сайта (типа инстаграм и т.д.), а вот соцфильтр - не блокирует.

**Comment by Alex-302** [comment]
Добавил в ЭФ:
maskme.ru#@#img[width="88"][height="31"]
maskme.ru#$#img[width="88"][height="31"] {visibility: hidden!important;}

**Comment by vbagirov** [comment]
А, ну соцфильтр и не должен блокировать. Все работает.
