### ISSUE TITLE
rusfootball.info

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#379]
Реклама в верху страницы.

**Comment by Alex-302** [comment]
А английский фильтр включен?

**Comment by vbagirov** [comment]
Да, включены рус, англ, ЭФ, счетчики и соцсети.

**Comment by Alex-302** [comment]
Даже не знаю. У тебя повторяется?

**Comment by vbagirov** [comment]
Ну да, у себя скрин сделал только что: http://screencast.com/t/oa1wDWQL2

**Comment by Alex-302** [comment]
Чисто должно быть. Рекламу сверху удаляет это правило:
/pagead2.

**Comment by vbagirov** [comment]
Не понял насчет правила /pagead2. Просто /pagead2? Такое не работает...

**Comment by Alex-302** [comment]
Да, оно в английском фильтре.
Удалённо смотреть надо.

**Comment by Alex-302** [comment]
Похоже рекламу поменяли. Добавил
rusfootball.info##body > noindex > a
rusfootball.info##body > noindex > div[id*="branding"]
