### ISSUE TITLE
[mobile] yahoo mail missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#381]
Он работает по HTTPS, так что шанс невелик, но хотя бы попытаться нужно

**Comment by Alex-302** [comment]
Это приложение или web-версия(на ней вроде чисто)?

**Comment by Alex-302** [comment]
На планшете в web-версии вроде чисто, да и в приложении тоже.

**Comment by ameshkov** [comment]
Попросил скриншот у Boo, вот здесь обсуждение:
http://forum.adguard.com/showthread.php?3239-Adguard-for-Android-1-1-beta-version/page5

**Comment by Alex-302** [comment]
Перенёс в профильную ветку
http://forum.adguard.com/showthread.php?4591

**Comment by Alex-302** [comment]
Реклама повторилась с американским прокси, но правила не срабатывают
yahoo.com##.type_ads_default
yahoo.com##.rmx-ad

**Comment by adguard** [comment]
Надо third-party запросы поискать, может с какого-нибудь домена конкретного тянется

**Comment by Alex-302** [comment]
Вот так верхний баннер выглядит http://imagizer.imageshack.com/img909/1240/KLBS57.png
В винде он блокируется так(судя по журналу):
<img id='ad_img' src='https://s.yimg.com/cv/ae/us/audience/030311/728x90xyk7tzbsh.jpg' width='728' height='90' alt='Toyota 3/16 Tablet' border='0'> (||s.yimg.com^*/audience/)
На планшете не хочет.

Элементы со "Sponsored" - в огромном CSS
Возможно загружаются по конкретной ссылке, ибо в коде нет соответствующих элементов. Доковырять не получилось, т.к. с ВПН перестали грузиться баннеры "Sponsored", а с прокси они не отображались.


https://s.yimg.com/zz/combo?nn/lib/metro/g/fp/fp_500_0.0.139.css&nn/lib/metro/g/universalheader/universalheader_0.0.43.css&nn/lib/metro/g/eyebrowpromo/eyebrowpromo_0.0.3.css&nn/lib/metro/g/tabbar/tabbar_0.0.159.css&nn/lib/metro/g/login/login_0.0.75.css&nn/lib/metro/g/mail/mail_0.0.61.css&nn/lib/metro/g/trendingnow/trendingnow_0.0.46.css&nn/lib/metro/g/trendingnow/trendingnow_anim_0.0.12.css&nn/lib/metro/g/sda/sda_0.1.66.css&nn/lib/metro/g/navrail/navrail_0.0.118.css&nn/lib/metro/g/adsfallback/adsfallback_0.0.55.css&nn/lib/metro/g/trendingnowcarousel/trendingnowcarousel_0.0.23.css&nn/lib/metro/g/games/games_0.0.25.css&nn/lib/metro/g/livenationpromo/livenationpromo_0.0.16.css&nn/lib/metro/g/specialevents/specialevents_0.0.119.css&nn/lib/metro/g/appscontainer/appscontainer_desktop_0.0.58.css&nn/lib/metro/g/specialevents/specialevents_mm_app_0.0.13.css&nn/lib/metro/g/topheadlines/topheadlines_0.0.20.css&nn/lib/metro/g/magpromote/magpromote_0.0.22.css&nn/lib/metro/g/weather/weather_0.1.58.css&nn/lib/metro/g/location/location_0.0.24.css&nn/lib/metro/g/finance/finance_base_0.0.10.css&nn/lib/metro/g/finance/finance_0.1.143.css&nn/lib/metro/g/sportacular/sportacular_0.0.50.css&nn/lib/metro/g/flickr/flickr_0.0.20.css&nn/lib/metro/g/topvideos/topvideos_base_0.0.12.css&nn/lib/metro/g/topvideos/topvideos_0.0.27.css&nn/lib/metro/g/horoscope/horoscope_base_0.0.7.css&nn/lib/metro/g/horoscope/horoscope_0.1.92.css&nn/lib/metro/g/comics/comics_0.0.21.css&nn/lib/metro/g/footer/subfooter_0.0.38.css&nn/lib/metro/g/windowshade/windowshade_0.0.17.css&nn/lib/metro/g/todaycontainer/todaycontainer_0.0.21.css&nn/lib/metro/g/fptoday/fptoday_flex_0.1.102.css&nn/lib/metro/g/offlead/offlead_0.0.31.css&nn/lib/metro/g/livevent/livevent_0.0.16.css&nn/lib/metro/g/fstream/fstream_desktop_0.0.33.css&nn/lib/metro/g/stream/stream_0.0.312.css&nn/lib/metro/g/stream/rmx_ads_0.0.20.css&nn/lib/metro/g/stream/stream_tweets_0.0.32.css&nn/lib/metro/g/stream/stream_action_drawer_desktop_0.0.27.css&nn/lib/metro/g/stream/video_manager_0.0.6.css

**Comment by Alex-302** [comment]
Вот так верхний баннер выглядит http://imagizer.imageshack.com/img909/1240/KLBS57.png
В винде она блокируется так(судя по журналу):
<img id='ad_img' src='https://s.yimg.com/cv/ae/us/audience/030311/728x90xyk7tzbsh.jpg' width='728' height='90' alt='Toyota 3/16 Tablet' border='0'> (||s.yimg.com^*/audience/)
На планшете не хочет.

Элементы со "Sponsored" - в огромном CSS
https://s.yimg.com/zz/combo?nn/lib/metro/g/fp/fp_500_0.0.139.css&nn/lib/metro/g/universalheader/universalheader_0.0.43.css&nn/lib/metro/g/eyebrowpromo/eyebrowpromo_0.0.3.css&nn/lib/metro/g/tabbar/tabbar_0.0.159.css&nn/lib/metro/g/login/login_0.0.75.css&nn/lib/metro/g/mail/mail_0.0.61.css&nn/lib/metro/g/trendingnow/trendingnow_0.0.46.css&nn/lib/metro/g/trendingnow/trendingnow_anim_0.0.12.css&nn/lib/metro/g/sda/sda_0.1.66.css&nn/lib/metro/g/navrail/navrail_0.0.118.css&nn/lib/metro/g/adsfallback/adsfallback_0.0.55.css&nn/lib/metro/g/trendingnowcarousel/trendingnowcarousel_0.0.23.css&nn/lib/metro/g/games/games_0.0.25.css&nn/lib/metro/g/livenationpromo/livenationpromo_0.0.16.css&nn/lib/metro/g/specialevents/specialevents_0.0.119.css&nn/lib/metro/g/appscontainer/appscontainer_desktop_0.0.58.css&nn/lib/metro/g/specialevents/specialevents_mm_app_0.0.13.css&nn/lib/metro/g/topheadlines/topheadlines_0.0.20.css&nn/lib/metro/g/magpromote/magpromote_0.0.22.css&nn/lib/metro/g/weather/weather_0.1.58.css&nn/lib/metro/g/location/location_0.0.24.css&nn/lib/metro/g/finance/finance_base_0.0.10.css&nn/lib/metro/g/finance/finance_0.1.143.css&nn/lib/metro/g/sportacular/sportacular_0.0.50.css&nn/lib/metro/g/flickr/flickr_0.0.20.css&nn/lib/metro/g/topvideos/topvideos_base_0.0.12.css&nn/lib/metro/g/topvideos/topvideos_0.0.27.css&nn/lib/metro/g/horoscope/horoscope_base_0.0.7.css&nn/lib/metro/g/horoscope/horoscope_0.1.92.css&nn/lib/metro/g/comics/comics_0.0.21.css&nn/lib/metro/g/footer/subfooter_0.0.38.css&nn/lib/metro/g/windowshade/windowshade_0.0.17.css&nn/lib/metro/g/todaycontainer/todaycontainer_0.0.21.css&nn/lib/metro/g/fptoday/fptoday_flex_0.1.102.css&nn/lib/metro/g/offlead/offlead_0.0.31.css&nn/lib/metro/g/livevent/livevent_0.0.16.css&nn/lib/metro/g/fstream/fstream_desktop_0.0.33.css&nn/lib/metro/g/stream/stream_0.0.312.css&nn/lib/metro/g/stream/rmx_ads_0.0.20.css&nn/lib/metro/g/stream/stream_tweets_0.0.32.css&nn/lib/metro/g/stream/stream_action_drawer_desktop_0.0.27.css&nn/lib/metro/g/stream/video_manager_0.0.6.css

**Comment by adguard** [comment]
Эх, не подойдет. Для https мы только полностью можем блочить, а этот домен не чисто рекламный.

**Comment by Alex-302** [comment]
Пока закрываю
