### ISSUE TITLE
[Extension for Chrome] tvrain.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#382]
Рекламу не блокируем перед видео, а вот сам видеоплеер не работает.

http://forum.adguard.com/showthread.php?4456-%D0%91%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D1%83%D0%B5%D1%82-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE

**Comment by Alex-302** [comment]
У меня норм. А у тебя как?

**Comment by vbagirov** [comment]
У меня при включенном расширении в хроме нет плеера. Отключаю - появляется. http://screencast.com/t/g5H41607 - фильтры.

**Comment by Alex-302** [comment]
Не получается сделать так, чтобы не работало:)

**Comment by Alex-302** [comment]
Нужна прямая ссылка. Я открывал - везде ютубовский плеер, он работает.

**Comment by vbagirov** [comment]
Например: http://tvrain.ru/articles/ja_by_hotel_umeret_kak_boris_nemtsov_belkovskij_o_tom_chem_putin_objazan_nemtsovu_pochemu_on_tjagotil_sistemnyh_liberalov_i_zachem_na_marshe_pamjati_shvatili_ukrainskogo_deputata-383183/

**Comment by Alex-302** [comment]
Странно. Работает и дома, и на работе. Тоже удалённо лучше посмотреть.

**Comment by Alex-302** [comment]
Юзер в теме пишет, что работает. У меня тоже. Можно наверное закрывать.

**Comment by vbagirov** [comment]
Закрываю.
