### ISSUE TITLE
ok.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#383]
http://ok.ru/game/piratetreasures
http://ok.ru/game/candyvalley

Во всех играх не работает звук, в консоли ошибки Failed to load resource: net::ERR_BLOCKED_BY_CLIENT. При отключении расширения звук появляется.

Реально ли исправить?

https://qcrm.cc/#/customer/899810

**Comment by Alex-302** [comment]
У меня работает, даже при наличии тех ошибок. Можешь у себя проверить, или у фанатов соц сетей?
И ещё нужет список фильтров.

**Comment by vbagirov** [comment]
У меня вот так при включенном расширении в хроме: 
http://screencast.com/t/Udv08bopRCGg
http://screencast.com/t/dxWulgbAI04

Без расширения все ок. 
Фильтры: http://screencast.com/t/g5H41607

**Comment by Alex-302** [comment]
Работает. Надо через тимвивер смотреть.

**Comment by vbagirov** [comment]
Ну давай через тимвьюер.

**Comment by Alex-302** [comment]
Как поступим? У тебя ж работает

**Comment by vbagirov** [comment]
Давай еще спрошу у юзера. У меня действительно теперь работает.

**Comment by vbagirov** [comment]
А, все, у юзера норм. Закрываю.
