### ISSUE TITLE
yandex-музыка

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/ExperimentalFilter#385]
http://music.yandex.ru/ 
При попытке поделиться треком с включенными виджетами соц. сетей происходит следующее:  http://screencast.com/t/A0IkmNR2pk6 (это после нескольких кликов)

**Comment by Alex-302** [comment]
у меня вот так, если выключить соц фильтр
http://imagizer.imageshack.com/img537/4505/lBbRuc.png

**Comment by Alex-302** [comment]
Добавил:
@@||yastatic.net/share/share.js$domain=music.yandex.ru

**Comment by adguard** [comment]
Хм, а разве мы не должны вообще кнопку поделиться скрывать с включенными виджетами?

**Comment by Alex-302** [comment]
Ага, убрал. Думал там ссылка для скачивания.
