### ISSUE TITLE
http://rosrealt.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#388]
Портим разметку сайта, блокируем изображения. 

С: https://www.dropbox.com/s/r15rl4sqn22hfbl/Screen%20Shot%202015-02-25%20at%2010.26.04%20AM.png?dl=0

Без: https://www.dropbox.com/s/rpday7ludrz6o2l/Screen%20Shot%202015-02-25%20at%2010.24.00%20AM.png?dl=0

https://qcrm.cc/#/customer/893864

**Comment by vbagirov** [comment]
Кроме того, блокируем код подтверждения в области для комментариев

**Comment by Alex-302** [comment]
Добавил в ЭФ:
@@||rosrealt.ru/pics/
Пока не закрывай, рекламу почистить надо ещё. Юзеру можешь передать чтоб включил ЭФ и обновил фильтры(чтоб не ждать автоматического обновления).

**Comment by vbagirov** [comment]
Спасибо, закрываю.
