### ISSUE TITLE
http://ru.bongacams.com/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#391]
Не блокируем рекламу на сайте.

https://qcrm.cc/#/customer/923216

**Comment by Alex-302** [comment]
Это из собственная. Не блокируем.

**Comment by vbagirov** [comment]
http://screencast.com/t/NBQNSkBL

**Comment by Alex-302** [comment]
Это у тебя такое? У меня там они своё рекламируют, типа подарки.

**Comment by vbagirov** [comment]
Ну да, у меня так, у юзера вообще вот: http://screencast.com/t/xemaN4oZQ

**Comment by Alex-302** [comment]
Пусть такое проверит. Только вот этот баннер не всегда выходит
||i.bongacams.com/b/
Добавил в ЭФ.
