### ISSUE TITLE
http://vseverske.info/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#393]
Реклама не заблокирована на сайте.

https://qcrm.cc/#/customer/910517

**Comment by Alex-302** [comment]
На проверку:
vseverske.info##div.place.top > a > img
vseverske.info##.left_column div[class^="place left_"]
vseverske.info##.right_column div[class^="place right_"]
vseverske.info##.floating.righ

**Comment by vbagirov** [comment]
Кажется, все ок. Надо добаваить в ЭФ.

**Comment by Alex-302** [comment]
Добавил, но скорее всего в основной не пойдёт.

**Comment by Alex-302** [comment]
Правила остались в ЭФ из-за неоднозначности.
