### ISSUE TITLE
oldi.ru - personal account does not work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#394]
http://forum.adguard.com/showthread.php?2112-%D0%92%D1%82%D0%BE%D1%80%D0%B0%D1%8F-%D0%B1%D0%B5%D1%82%D0%B0-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F-Adguard-5-10&p=45210#post45210

**Comment by Alex-302** [comment]
Добавил в ЭФ:
oldi.ru$@$script[tag-content="ad.adriver.ru"][max-length="3000"]

**Comment by Alex-302** [comment]
Юзер подтвердил нормальную работу корзины.
Закрываю.
