### ISSUE TITLE
http://pogodavtomske.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#395]
Не блокируем рекламу вообще. 

https://qcrm.cc/#/customer/940023

**Comment by Alex-302** [comment]
Добавил в ЭФ:
||i.solo.rde.ru^$domain=pogodavtomske.ru

**Comment by vbagirov** [comment]
Слева ссылка на tomsk.ru - не стал убирать?

**Comment by Alex-302** [comment]
Не. Это всё один портал. pogodavtomske.ru - подраздел сайта tomsk.ru
