### ISSUE TITLE
[android] extratorrent.cc - missed ads on android

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#397]

**Comment by Alex-302** [comment]
А какие фильтры включены, и версия какая? У меня чисто, как в винде.

**Comment by ameshkov** [comment]
Да, чот больше не повторяется. Можешь глянуть сторонние скрипты есть ли какие?

**Comment by Alex-302** [comment]
Да, есть файлы с vipcpms.com, но почему-то в Хроме они загружаются, вопреки правилу из англ фильтра, но на рекламу вроде не влияют
||vipcpms.com^$third-party
В IE вроде блокируются.

**Comment by ameshkov** [comment]
Может исключение какое? Или хттпс или еще чо

**Comment by Alex-302** [comment]
Странно - на работе в Хроме блокируется. Завтра дома ещё проверю.

**Comment by Alex-302** [comment]
Всё чисто, даже с одним английским фильтром.
Может в нём косяк был, да поправили?

**Comment by ameshkov** [comment]
Видимо да
