### ISSUE TITLE
http://www.povarenok.ru/

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ExperimentalFilter#398]
В SRware Iron 40.0.2150.0 частично не блокируется реклама. Например, не работает это правило:
||beta.mediafort.ru^$third-party
Но имеющееся в русском фильтре ||delta.mediafort.ru^$third-party работает как надо.
В обычном Хроме и Фоксе проблемы нет.

**Comment by ameshkov** [comment]
В SRWare Iron режутся рефереры, поэтому куча всего не блокируется нормально.

**Comment by Alex-302** [comment]
Точно. Вспомнил.
