### ISSUE TITLE
http://narutoplanet.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#399]
Без Адагрда: http://prntscr.com/6d5pmm
С Адгардом: http://prntscr.com/6d5q37

Аниме радио - не отображается громкость.

ILD-201-11538

**Comment by Alex-302** [comment]
Добавил в ЭФ:
narutoplanet.ru#@#.top-banner

**Comment by Alex-302** [comment]
Закрываю.
Если не работает - открывай.
