### ISSUE TITLE
http://footballhd.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#401]
Реклама на сайте не заблокирована

https://qcrm.cc/#/customer/919363

**Comment by Alex-302** [comment]
Для проверки:
footballhd.ru###rec_bg
footballhd.ru##.bloc_right > div.bloc0
||footballhd.ru/templates/ball/images/rec/

**Comment by vbagirov** [comment]
Работает. Добавишь в ЭФ?

**Comment by Alex-302** [comment]
Добавил.
