### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#402]
Антиадблок на сайте, правда там польский прокси нужен. Хз даже где найти.

https://qcrm.cc/#/customer/695843

**Comment by Alex-302** [comment]
Hola не помог, проксей рабочих не нашёл.

**Comment by Alex-302** [comment]
Пусть по отдельности проверит такие исключения, как временный вариант:
@@||player.pl^$urlblock
@@||player.pl^$urlblock,elemhide
@@||player.pl^$elemhide
@@||player.pl^$content
@@||player.pl^$jsinject

**Comment by vbagirov** [comment]
Спросил у юзера, ждем.

**Comment by vbagirov** [comment]
Говорит, не помогает.

**Comment by Alex-302** [comment]
Пусть ещё такое проверит @@||player.pl^$urlblock,elemhide,content
Польских проксей не нашёл, без доступа сложно что-то дельное придумать.

**Comment by vbagirov** [comment]
Запросил.

**Comment by Alex-302** [comment]
Заработал с Hola. C нашими фильтрами помогает
@@||player.pl^$elemhide
Лишнее не разблокируется вроде.

**Comment by vbagirov** [comment]
Закрываю.
