### ISSUE TITLE
http://rutube.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#403]
Антиадблок при прсомотре видео

https://qcrm.cc/#/customer/639189

**Comment by Alex-302** [comment]
Добавил в ЭФ:
@@||adsrv.gpm-digital.com/crossdomain.xml$domain=rutube.ru

**Comment by vbagirov** [comment]
Работает, закрыл.

**Comment by vbagirov** [comment]
А нет. В фоксе реклама не блокируется, в хроме антиадблок остается.

**Comment by vbagirov** [comment]
Кстати, после окончания видео в хроме тоже начинается реклама.

**Comment by Alex-302** [comment]
Что-то не повторяется. В инкогнито проверил ссылку из заявки - всё работает вроде.

**Comment by vbagirov** [comment]
Согласен.
