### ISSUE TITLE
 [Android] Voice aloud reader app

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#404]
Не блокирует рекламу в приложении

https://qcrm.cc/#/customer/951635

**Comment by Alex-302** [comment]
Если речь об этом
http://imagizer.imageshack.com/img537/2949/TUDEEc.png
то тут не поможем. Этот баннер встроен. При запуске с отключенным интернетом и чисткой кэша он появляется всё равно. Пропадает, если зайти и выйти из меню программы.

**Comment by vbagirov** [comment]
Уточню у юзера, пока не закрывай.
