### ISSUE TITLE
megogo.net

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#406]
Антиадблок на сайте. У юзера проблема в Mozilla и IE.

https://qcrm.cc/#/customer/955270

**Comment by Alex-302** [comment]
Ага, а в Хроме работает нормально.
Будем смотреть.

**Comment by Alex-302** [comment]
Проверь такие правила:
@@||megogo.net/s/js/v3/advertisement.js
megogo.net#@##advertisementBlock
@@||vclicks.net/scripts/trackjs.js
@@||ad.jamba.net/crossdomain.xml

**Comment by vbagirov** [comment]
Кажется, работает. Будешь добавлять в ЭФ?

**Comment by Alex-302** [comment]
Чуть позже. Последние два перепроверить надо.

**Comment by Alex-302** [comment]
Для пробы, пока только для включенного одного английского фильтра:
@@||ad.rambler.ru/crossdomain.xml$domain=megogo.net

**Comment by Alex-302** [comment]
@@||megogo.net/crossdomain.xml
@@||tns-counter.ru/crossdomain.xml
@@||mggcdn.net/crossdomain.xml
@@||vcdn.biz/crossdomain.xml
@@||ads.adfox.ru/crossdomain.xml
@@||ad.rambler.ru/crossdomain.xml
@@||log.cnt.re:7080/crossdomain.xml
@@||ad.jamba.net/crossdomain.xml
@@||ad.turn.com/crossdomain.xml
@@||b.scorecardresearch.com/crossdomain.xml

**Comment by vbagirov** [comment]
Что-то после добавления первой "порции" реклама не блокируется. Старые правила надо удалить может?

**Comment by Alex-302** [comment]
Никак не могу понять на что он ругается.
Можешь попробовать такое
@@/crossdomain.xml
Старые можно не добавлять.

**Comment by vbagirov** [comment]
Вроде работает у юзера, у меня тоже нет антиадблока.
