### ISSUE TITLE
http://kurs.com.ua/mejbank

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#410]
Антиадблок http://i.imgur.com/DaqRuNs.png

Похоже, только с украинской проксей повторяется.

https://qcrm.cc/#/customer/628002

**Comment by Alex-302** [comment]
У меня не повторяется. Андрей вроде чинил, на руборде упоминание видел.
Пусть юзер обновит вручную фильтры и проверит снова.

**Comment by vbagirov** [comment]
Запросил, пока закрываю.
