### ISSUE TITLE
[android] mail.ru - false positive

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#413]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=38882234

Открываю почту @mail.ru через любой мобильный браузер (полная версия сайта, вид для ПК) - далее в почте открываю «История общения в Агенте» и страница грузится раз через раз, с ошибкой, иногда приходится раз 5 обновлять, чтобы история отобразилась. Если отключить адгуард, всё открывается нормально. Исправьте эту оплошность, добавив историю агента в исключение.

**Comment by Alex-302** [comment]
Маловато информации, попробую пообщаться с ним.

**Comment by Alex-302** [comment]
Его ответ:
```
 Включены фильтры по умолчанию: английский, счетчиков и системы аналитики, виджетов социальных сетей, русский фильтр и фильтр мобильной рекламы. Выключение по одному ничего не даёт! Даже если всё выключить, без изменений.

Архив Агента находится здесь:
https://e.mail.ru/agent/archive
трафик ведь зашифрованный https. Добавление этой ссылки в белый список тоже ничего не даёт! Страница то открывается нормально, то раз 5 - 7 приходится обновлять. Браузер хром. Adguard работает через VPN, а если адгуард отключить, то всё нормально открывается сразу.
```
У меня не повторяется, возможно из-за пустой истории, ибо мэйлом не пользуюсь. С Хромом позже проверю.

**Comment by Alex-302** [comment]
```
Скрины вот:
http://i57.fastpic.ru/…a47eea42f51dc530a3.png

либо просто пустая страница
http://i57.fastpic.ru/…1e4147b823aff0c0c2.png

С 5 - 10 раза после обновления страницы всё же открывается. Без адгуард открывается сразу. От браузера не зависит, на стоковом то же самое.
```
У тебя повторяется? У меня норм.

**Comment by vbagirov** [comment]
У меня повторилось в том плане, что иногда просто пустая страница открывается. После выключения Adguard вроде как прекратилось это.

**Comment by Alex-302** [comment]
какая-то неуловимая хрень. Дважды вроде повторилось, не нет закономерности

**Comment by adguard** [comment]
А какая версия адгарда? Бета?

А у юзера какая?

**Comment by Alex-302** [comment]
У меня последняя бета. У юзера спросил.

**Comment by Alex-302** [comment]
Юзер пишет, что с 1.1.887 всё норм.
Пока закрываю.
