### ISSUE TITLE
http://online.anidub.com/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#415]
Реклама в левой части страницы. 
При клике на баннере с девочками сверху открывается попап.

**Comment by Alex-302** [comment]
Добавил в ЭФ:
online.anidub.com##a[href^="http://www.dragonknight.ru/ref/"]
online.anidub.com##object[width="230"][height="380"]
Это, часом, не с форума заявка?

**Comment by vbagirov** [comment]
Кажется, с форума. Работает.
