### ISSUE TITLE
http://carambatv.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#416]
Антиадблок на сайте.

https://qcrm.cc/#/customer/1004682

**Comment by Alex-302** [comment]
Похоже это чел с форума.
Проверь у себя такие правила:
```
@@||ads.adfox.ru/crossdomain.xml
@@||ads.adfox.ru/*/getDefaultImage
carambatv.ru$@$script[tag-content="ads.adfox."][max-length="1600"]
@@||ads.adfox.ru/*/prepareCode?p1=
@@||ads.adfox.ru/*/goDefaultLink?p1=
@@||ads.adfox.ru/*/getCode?p1=
@@||content.adfox.ru/*/defaults/adfox/ 
@@||ads.adfox.ru/*/getCodeTest?p1=
@@||content.adfox.ru/transparent.gif
@@||ads.adfox.ru/*/getCode?pp=
@@||ads.adfox.ru/*/goLink?ifd=
@@||b.scorecardresearch.com/beacon.js
@@||x.ulogix.ru/?rand=
@@||tns-counter.ru/V13a
||vcdn.biz^
```
http://carambatv.ru/movie/bad-comedian/caucausian/
А то у меня работают, а у него не понятно что творится.

**Comment by Alex-302** [comment]
Короче в ЭФ добавил нужные правила. Эти не нужны. В расширении и проге всё должно работать после обновления фильтров.

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/ExperimentalFilter/issues/420#issuecomment-87613567
решили оставить как есть
