### ISSUE TITLE
http://hentaichan.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#417]
Реклама не заблокирована.

https://qcrm.cc/#/customer/998292

**Comment by Alex-302** [comment]
Вроде ж чисто. На скрине бы увидеть.

**Comment by vbagirov** [comment]
http://hostingkartinok.com/show-image.php?id=3af1f3da2b15d24139c107534a3ff990
Вот такой скрин, у меня тоже больше не повторяется. Попробую уточнить.

**Comment by Alex-302** [comment]
Если ещё актуально - пусть из инструментов разработчика сделает скрин вкладки Sources

**Comment by vbagirov** [comment]
Не актуально, юзер не отвечает.
