### ISSUE TITLE
[Android] https://play.google.com/store/apps/details?id=com.maildroid&hl=ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#418]
Реклама не заблокирована в приложении:
http://screencast.com/t/JjEdXUjtmceC

https://qcrm.cc/#/customer/1004549

**Comment by Alex-302** [comment]
у меня чисто:
https://www.dropbox.com/s/wimdcqhxkbf7m2i/Screenshot_2015-03-27-15-46-31.png?dl=0
на всякий случай добавил:
||met.adzmobi.com^$empty

**Comment by vbagirov** [comment]
Я вообще не могу там аккаунт создать. Попробую дать правило юзеру.

**Comment by vbagirov** [comment]
Не помогает правило. Скрин от юзера: http://screencast.com/t/qaojX3eHr92

**Comment by Alex-302** [comment]
У меня иначе выглядит прога. Хз почему. Может поэтому у меня нет баннера.

**Comment by vbagirov** [comment]
Тогда хз. Наверное, закрываю.
