### ISSUE TITLE
hayhaytv.vn

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#419]
1. Go to this website: www.hayhaytv.com (a Vietnamese movie sharing site). 2. Click on any movies, shows. 3. Then click orange button "Xem phim" in the description area. 4. Bam! It detects Adguard and won't let you watch the video unless you disable Adguard.

**Comment by Alex-302** [comment]
Пусть проверит:
@@||static.hayhaytv.com/advertisement.js
Желательно в режиме инкогнито или с полной чисткой кэша/куков.

**Comment by vbagirov** [comment]
У меня что-то теперь плеер не запускается, даже с выключенным АГ. НЕ могу даже сказать, работает ли правило.

**Comment by Alex-302** [comment]
Пусть сделает нам аккаунт, а то я свой забыл.

**Comment by vbagirov** [comment]
Да я уже не найду его. Придется пока закрыть если вопрос не повторится.
