### ISSUE TITLE
carambatv.ru

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ExperimentalFilter#420]
плеер определяет блокировку
http://carambatv.ru/movie/bad-comedian/caucausian/

http://forum.adguard.com/showthread.php?4847-*-http-carambatv-ru-humor-100500-action&p=46967&viewfull=1#post46967

при добавлении правил в расширение ломается сайт.

**Comment by adguard** [comment]
Есть предложение оставить как есть, пусть определяет блокировку.
