### ISSUE TITLE
"премиум обои hd" перестали грузиться обои

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ExperimentalFilter#421]
http://4pda.ru/forum/index.php?showtopic=601691&view=findpost&p=39046875

**Comment by Alex-302** [comment]
Похоже на баг. С включенной защитой, антифишингом, выключенными фильтрами и фильтрацией приложений, ничего не грузит.

**Comment by adguard** [comment]
Завел дефект AG-7337 в нашем баг-трекере, тут дефект закрою, чтобы не дублировать.
