### ISSUE TITLE
http://besplatnyeprogrammy.ws/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#425]
Баннер с котом блокируем.

https://qcrm.cc/#/customer/996138

**Comment by Alex-302** [comment]
А зачем? Это ж партнёрка ЯБа.

**Comment by vbagirov** [comment]
Уже вообще пропал баннер. А так как раз и не должны были блокировать, скрывали зря его.

**Comment by Alex-302** [comment]
А почему так?

**Comment by vbagirov** [comment]
Ну баннер вел же по внутренней ссылке. Пока закрываю, т.к. юзер не отвечает.
