### ISSUE TITLE
[Android] bubluoteka.org

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#428]
Баннер не заблокирован снизу.

https://qcrm.cc/#/customer/1009323

**Comment by Alex-302** [comment]
На проверку:
||adsmo.ru^$third-party

**Comment by vbagirov** [comment]
Недообрезает, остается фон плашки, текст "Онлайн казино вулкан", и артефакты изображений.

**Comment by Alex-302** [comment]
добавил в эф:
||adsmo.ru^$empty
bubluoteka.org##a[href^="http://go.octobird.com/"]
пустоту убирать опасно
