### ISSUE TITLE
Не удается авторизоваться

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#429]
Не удается авторизоваться через соцсети (вконтакте) при включенном Adguard на сайтах 
https://arenaprizov.ru/registration
http://promo.purinaone.ru/#/

https://qcrm.cc/#/customer/949572

**Comment by Alex-302** [comment]
на пурине вроде норм.
По https://arenaprizov.ru/registration похоже баг - все фильтры и антифишинг выключены, а не заходит. Подозреваю фильтрацию SSL
http://imagizer.imageshack.com/img673/4971/OHUnkf.png

**Comment by vbagirov** [comment]
Завел баг http://jira.performix.ru/browse/AG-7373

**Comment by Alex-302** [comment]
Здесь тогда закрою.
