### ISSUE TITLE
[Mac] http://market.yandex.ua/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#430]
На маке на сайте market.yandex.ua блокирует подборки и рекомендации сверху.

https://qcrm.cc/#/customer/1012165

**Comment by Alex-302** [comment]
Мака не имею, надо удалённо смотреть.

**Comment by vbagirov** [comment]
Как сможешь - напиши Егору в скайп, подключишься к нему.
