### ISSUE TITLE
vestifinance.ru - some placeholders missed

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#434]

**Comment by Alex-302** [comment]
Если правильно понял, но нужно убрать эти блоки:
http://imagizer.imageshack.com/img633/3447/US0CvF.png
Добавил в ЭФ:
||vestifinance.ru/img/banners/

**Comment by Alex-302** [comment]
добавил ещё
vestifinance.ru###ADV60
