### ISSUE TITLE
[Firefox extension] http://ultimatv.org

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#435]
Не блокируется реклама IPTV в видеоплеере.

**Comment by Alex-302** [comment]
вообще это правило должно работать(как в Хроме, например), но почему-то не хочет
||clients.cdnet.tv/lockadb.php$popup

**Comment by adguard** [comment]
А ты в какой версии расширения для фокса проверял?

**Comment by Alex-302** [comment]
2.0.6

**Comment by Alex-302** [comment]
Уже вроде чисто.
