### ISSUE TITLE
http://vivo.vn/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#440]
Блокируем флэш-плеер + Антиадблок на сайте
с АГ: http://puu.sh/h24B7/fdce02da20.png
без АГ: http://puu.sh/h24Ik/8649013bdf.png
антиадблок: https://www.dropbox.com/s/4f1q8jsvq1ndor6/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0.png?dl=0

https://qcrm.cc/#/customer/1016749

**Comment by Alex-302** [comment]
Проверь плиз или передай юзеру(только чтоб отписался)
@@||pq-direct.revsci.net/pql$domain=vivo.vn
@@||admicro1.vcmedia.vn/ads_codes/*$domain=vivo.vn
||eclick.vn^$third-party

**Comment by Alex-302** [comment]
Добавил.
