### ISSUE TITLE
tabsbook.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#442]
Реклама не заблокирована. Данные по аккаунту в скайпе, только акк не мой, поэтому ничего там лучше не трогать. Что интересно, в новом акке рекламы нет, появляется спустя две недели.

(из соцсети)

**Comment by vbagirov** [comment]
данные по аккаунту: 
list212@bk.ru
23X5hJ3srF%u

**Comment by Alex-302** [comment]
Рекламы не вижу.

**Comment by vbagirov** [comment]
У меня тоже не повторяется больше, закрываю.
