### ISSUE TITLE
http://login.vmet.ro/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#444]
http://login.vmet.ro/am/UI/Login?switch_url=http://1.1.1.1/login.html&ap_mac=c4:14:3c:7a:74:c0&client_mac=1c:b0:94:0e:72:8e&wlan=MosMetro_Free&redirect=www.google.ru/?gfe_rd=cr&ei=M0kiVYa0C4vL0wWa0oGYBw&org=mac&ForceAuth=true

Портим форму авторизации.

**Comment by Alex-302** [comment]
Вижу исключение для страницы авторизации появилось, и всё стало работать)

**Comment by vbagirov** [comment]
Я сам не могу протестировать, кто-то может подтвердить?

**Comment by Alex-302** [comment]
Я в метро езжу, всё работает. Но при первом запуске браузера  с открываемого сайта при перекидывании на страницу авторизации происходит блокировка перехода. Не разобрался почему.

**Comment by vbagirov** [comment]
Тогда закрываем пока? Или попробуешь еще разобраться?

**Comment by Alex-302** [comment]
Пусть повисит.

**Comment by Alex-302** [comment]
Вот это ещё разблокировал:
||authrad.vmet.ro^$document
