### ISSUE TITLE
[Android] http://adbuddiz.com/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#445]
При попытке открыть страницу с андроида с включенным АГ она через секунд возвращается на предыдущую.

https://qcrm.cc/#/customer/781956

**Comment by Alex-302** [comment]
Зарегался. Никаких незапланированных переходов нет. Надо бы ещё где-то проверить.

**Comment by Alex-302** [comment]
Чето затупил - с компа работает, а в дроиде - нет, т.к. в мобильном фильтре есть правило
||adbuddiz.com^$empty
Если ему нужно заходить с дроида на этот сайт, пусть добавит в собственный фильтр такое исключение:
@@||adbuddiz.com^$empty

**Comment by vbagirov** [comment]
Закрываю.
