### ISSUE TITLE
http://magazynauto.interia.pl

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#447]
http://magazynauto.interia.pl/uzywane/opinie/news-uzywana-toyota-mr2-1989-1999,nId,1691987

Блокируем галерею изображений внизу

https://qcrm.cc/#/customer/968150

**Comment by Alex-302** [comment]
Разблокировал и подчистил мусор. Юзер может проверять. В ЭФ добавил.
@@||interia.hit.gemius.pl/hitredir/$domain=interia.pl
interia.pl##.social-socialButtons
interia.pl#%#document.cookie = "lltsg=1";
interia.pl##div[class*="ad ad_"]
interia.pl##div[class^="box ad box"]
interia.pl##.adStandardTop
Для ещё одного сайта из сообщения юзера:
||filmweb.pl/welcomeScreenJS
Для третьего пусть даст ссылки с рекламой.
