### ISSUE TITLE
[android] LazyIPTV missed ads

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#448]
не блокируется реклама в приложении LazyIPTV ( https://play.google.co…catsoftware.iptv&hl=ru ).
не могли бы Вы посмотреть и исправить?

**Comment by Alex-302** [comment]
Сама кнопка встроена, но можно заблокировать переход по ней
||apptornado.com^$empty
Пока не добавляю, на проверку.

**Comment by adguard** [comment]
Стремновато. Тогда забьем
