### ISSUE TITLE
[android] gizmobolt.com - false positive

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#449]
ещё страничка http://www.gizmobolt.com/ не открывается (или открывается главная страница а когда хожу по ссылкам, то не идет) пока не внесу ее в белый список,а после этого соответственно не вырезается реклама на ней.

**Comment by Alex-302** [comment]
в эф(мобильный)
gizmobolt.com#@#.custom-ad
gizmobolt.com#@#.header-ad
