### ISSUE TITLE
http://www.hdkinomax.com/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#451]
1. Середина страницы - реклама сайта с левой стороны
2. верхняя часть сайта
3. реклама во время просмотра фильма.

https://qcrm.cc/#/customer/1017382

**Comment by Alex-302** [comment]
Добавил в ЭФ:
||hdkinomax.com/argo/
hdkinomax.com##.argo-bg
hdkinomax.com###CGCandy399
||hdkinomax.com/reklama-offf.jpg
||megogo.net/e/*?autoplay=1$domain=hdkinomax.com
в фиксы цсс:
hdkinomax.com#$##subheader {padding: 0px 0 0 0!important;}
