### ISSUE TITLE
[Android] https://play.google.com/store/apps/details?id=nexti.android.bustaipei&hl=zh_TW

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#452]
http://screencast.com/t/PsBxE1hRQR
http://screencast.com/t/wSgpY6968T
http://screencast.com/t/u2jzKypwVh8

Ещё юзер говорит, что не блокируем хосты adbert.com.tw и dsp.adbert.com.tw и что помогают следующие правила:
||*.vpon.com
||*.adbert.com.tw

https://qcrm.cc/#/customer/972462

**Comment by Alex-302** [comment]
А у меня там вообще рекламы нет.

**Comment by vbagirov** [comment]
Ну тогда пока закрою, если что - позже открою снова.

**Comment by vbagirov** [comment]
Юзер говорит, по-прежнему реклама

**Comment by Alex-302** [comment]
Видать нужна прокся тайваньская. Можешь у него узнать про наличие рабочих проксей?
Его правила не прокатят, ибо блокируют много лишнего.
Ещё, если он продвинутый, может установить Android SDK и после запуска
android-sdk\tools\monitor.bat
подключит тел к компу(прога должна его увидеть), запустит прогу, дождётся баннера, отрубит тел и сохранил лог. Иначе не получится, повторить у меня не получается.

**Comment by vbagirov** [comment]
Спросил, посмотрим что ответит.

**Comment by Alex-302** [comment]
Не возможно воспроизвести. Закрываю.
