### ISSUE TITLE
some filters for annoyances section

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#453]
Правила составлял сам, некоторые с вашей помощью, некоторые подглядел в adblock+
Выкладываю лишь для популярных сайтов, использую фильтры больше полугода - проблем нет. Некоторые элементы грузятся только при первоначальном посещении сайта. 
Если возникнут неясности - прошу сообщить.

http://hdclub.org/browse.php?tag=new-films
Блок "Рекомендуем". Главное что изображения в нем оч.большие, в этом блоке они уменьшены в несколько раз, по факту грузятся большие.
[code]hdclub.org$$table[tag-content="HDClub рекомендует"][/code]
[url=http://jpegshare.net/][img]http://jpegshare.net/images/e4/42/e44267246191f619f58cd911734ef255.jpg[/img][/url]
```
Вес картинок маленький, наверное удалять их не лучшая идея
```

***
http://hdclub.org/
Ярко выделяющийся блок о donate, постоянные пользователи уже знают что к чему, к тому же уже есть блок справа, напоминающий о помощи. Правило не будет трогать другие уведомления админов - проверено временем.
[code]hdclub.org###bannertop[/code]
[url=http://jpegshare.net/][img]http://jpegshare.net/images/a9/13/a913eb3b51c3cf36d88d9322d00420c8.jpg[/img][/url]
```
Там достаточно кликнуть, и больше не появится.
```

***
http://hdclub.org/
Блок, ведущий на посторонний сайт. Возможно подойдет и для русского фильтра.
[code]hdclub.org##a[href="http://www.gradedexchange.com/servlet/the-template/about/Page"][/code]
[url=http://jpegshare.net/][img]http://jpegshare.net/images/89/1e/891e11a3b29244085999aaf04e05e31a.jpg[/img][/url]
```
Можно добавить
||hdclub.org/pic/oppo3dblu-ray
hdclub.org##a[href="http://seedbox.org.ua/"]
```

***
http://hdclub.org/details.php?id=21960
Блок со словом "загрузка", присутствует почти на всех страницах, возможно подойдет для русского фильтра.
[code]hdclub.org###bn_f3F6SlRmQH[/code]
[url=http://jpegshare.net/][img]http://jpegshare.net/images/68/2a/682a48991552b604d5905fcc2497fd10.jpg[/img][/url]
```
hdclub.org##.outer > div[id^="bn_"]
```

***
http://hdclub.org/details.php?id=21960
Большущий нескрываемый блок. Правило делал Алекс. Тема на [url=https://github.com/AdguardTeam/ExperimentalFilter/issues/176]github[/url]. Нужна авторизация.
[code]hdclub.org##form[action="thanks.php"][/code]
[url=http://jpegshare.net/][img]http://jpegshare.net/images/68/e1/68e1477c1c700e732fe1bcb80732a1bf.jpg[/img][/url]
```
Наверное не помешает.
```

http://fishki.net/
Удаляет посты профиля "реклама", выкладывает топики под видом юзера. 
[code]fishki.net$$div[tag-content="/profile/543769/"][/code]
[url=http://jpegshare.net/][img]http://jpegshare.net/images/31/4a/314af9f9860fc6f996d4e3dc560f5c42.jpg[/img][/url]
```
Можно так в дополнение к нашему:
fishki.net##div[id^="smi2-"]
```

***
http://fishki.net/1497602-top-12-samyh-vkusnyh-zhirnyh-i-kalorijnyh-bljud.html
Уведомление поставить лайк
[code]fishki.net##.post-face[/code]
[url=http://jpegshare.net/][img]http://jpegshare.net/images/3c/8d/3c8d8ea4c19aca657ff55ebb8fdbfe45.jpg[/img][/url]
```
Добавил в соц фильтр.
```

***
http://fishki.net/1497602-top-12-samyh-vkusnyh-zhirnyh-i-kalorijnyh-bljud.html
Громадный блок внизу "с самым интересным на сайте". Ну очень большой...
[code]fishki.net##.related-posts.related-posts-bottom.clearfix[/code]
[url=http://jpegshare.net/][img]http://jpegshare.net/images/8f/92/8f92b077d236288e76563efd599a3ec8.jpg[/img][/url]
```
Тоже можно добавить.
```

***
https://twitter.com/salt1s
Блок регистрации, блокирующий весь сайт. Правила сделали вы.

[code]twitter.com###signup-dialog
twitter.com##.modal-overlay
twitter.com#$#.modal-enabled {position: inherit!important; overflow: inherit!important}[/code]
[url=http://jpegshare.net/][img]http://jpegshare.net/images/10/da/10da5689628a56a779a3fbe418cec0be.jpg[/img][/url]
```
Сомнительно. Достаточно один раз закрыть и больше не появится.
```

***
http://www.sports.ru/
Всплывающее сообщение
[code]sports.ru##.tooltips[/code]
[url=http://jpegshare.net/][img]http://jpegshare.net/images/72/af/72af20bcb98a47e19474852a0bd48290.jpg[/img][/url]
```
Вот так лучше
sports.ru##.js_favteam > .tooltips
```

***
http://www.sports.ru/football/1028768028.html
Блок "За кого вы болеете?", "Зарегистрируйтесь" и пр. Везде присутствует.
[code]sports.ru##.c-suggest-block[/code]
[url=http://jpegshare.net/][img]http://jpegshare.net/images/f0/72/f072499b4d207a3b8588f8d13810c6e7.jpg[/img][/url]
```
Добавлю
sports.ru##.c-favorite-team
```

***
http://www.sports.ru/football/1028768028.html
Вездесущие блоки "подписаться"
[code]sports.ru##.c-tag-subscription[/code]
[url=http://jpegshare.net/][img]http://jpegshare.net/images/08/96/089610f5d63111cbdbb8fa538dc4d9f3.jpg[/img][/url]
```
Добавлю
sports.ru##.c-tag-subscription
```

http://www.igromania.ru/
Остаются пустые разделы, если использовать фильтр виджетов. Возможно правила подойдут для фильтра соц.сетей.
[code]igromania.ru###imdailyvk.full_block1[/code]
[url=http://jpegshare.net/][img]http://jpegshare.net/images/c5/c5/c5c5bc85d8c0663fb3030e6390e61be6.jpg[/img][/url]
```
Здесь всё норм.
```

***
http://www.igromania.ru/
[code]igromania.ru###instatwitter_twdoub.full_block3[/code]
[url=http://jpegshare.net/][img]http://jpegshare.net/images/1e/86/1e8643de5d8e909f8c1904305aa886e4.jpg[/img][/url]
```
Добавлю:
igromania.ru#$##intwcontainer-1 {height: 20px!important;}
```
***
http://rutracker.org/forum/viewtopic.php?p=67441398#67441398
Против подписей под постами.
[code]rutracker.org##.signature[/code]
[url=http://jpegshare.net/][img]http://jpegshare.net/images/82/cf/82cfe635f5097dfe33a6e8716234780b.jpg[/img][/url]
```
Наверное лучше оставить.
```

***
https://translate.google.ru
Для зоны .ru
[code]translate.google.ru###gt-community-promo[/code]
[url=http://jpegshare.net/][img]http://jpegshare.net/images/73/00/7300f9335e459995aad028f5fdb76a1c.jpg[/img]
```
Добавлю.
```

**Comment by Alex-302** [comment]
Основную массу добавил, но некоторые не стал - сомнительная необходимость(откомментил).
