### ISSUE TITLE
http://www.solidfiles.com/ 

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#454]
реклама на сайте: http://www.solidfiles.com/ 
ссылка для примера: http://www.solidfiles.com/d/48a568b092/test.txt 
зеленая кнопка и давнлоадер или хз что: http://givemeclip.com/n/32959709/test.txt.exe 
заблочьте!

**Comment by Alex-302** [comment]
Добавил в ЭФ
solidfiles.com###dlm-btn.dlm-dl
