### ISSUE TITLE
free-torrents.org

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#455]
http://www.free-torrent.org/ - увы нет... 
к примеру эта новость: http://free-torrent.org/forum/viewtopic.php?t=206187 
ссылка на зеленой кнопке выглядит так: http://dl.free-torrent.org/forum/dl.php=152199 (если вставить вручную в браузер = 404 Not Found) 
нажав получаем это: http://formulate.bestseek.ru/ 
MTA0NTQ7aHR0cDovL2RsLmZyZWUtdG9ycmVudC5 
vcmcvZm9ydW0vZGwucGhwP2lkPTE1MjE5OSZhZH 
NfaWQ9cHJvZml0cmFmMjQyNDM0MzI0O25hbWU9 
JTVCZnJlZS10b3JyZW50Lm9yZyU1REtWSzA0MjAx 
NS5wZGYudG9ycmVudDtzaXplPTU4NzIwMjU2O3R 
5cGU9dG9ycmVudA== 
редирект в IDM - качает: http://dlc.trand-pro.ru/download/f8/i5yOjozQlot0cTgsK2NpdWtseSVoYmN7ZXN3YWFmOGVtNn1+aEJ0bE9PHQLr6dA/free-torrent_org_kvk042015_pdf.exe?sign=planeta_soft?nofid?static

**Comment by Alex-302** [comment]
Добавил в ЭФ
Удаление кнопки:
```
free-torrents.org##a[freet_href*="&ads_id="]
```
рекламная строка в новостях:
```
free-torrents.org##.post_body a[href^="http://cp.inferno.name/view.php?product="]
```
