### ISSUE TITLE
http://vseriale.tv/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#459]
Антиадблок при просмотре видео. У юзера иногда не блокируется видеореклама.

https://qcrm.cc/#/customer/1020607

**Comment by Alex-302** [comment]
Добавил в ЭФ: 
vseriale.tv##.banner-sidebar
vseriale.tv###flash_layer
||uakino.net/js/jquery.iframetracker.js$domain=vseriale.tv
