### ISSUE TITLE
civic-club.ru/forum/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#460]
Блокируем вообще почти весь контент на сайте.

**Comment by Alex-302** [comment]
Разблокировал
civic-club.ru#@##ad_global_below_navbar
и убрал рекламу
||civic-club.ru/static/partners/
civic-club.ru##div[style="float:right"] > span.smallfont
civic-club.ru##img[title="civic-tuning"]
в эф добавил
