### ISSUE TITLE
[android] seasonvar.ru

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#461]
При просмотре видео с seasonvar.ru на Android приходиться выключать VPN т.к. после просмотра 10-15 мин. видеоплеер (html5 в Chrome, UC Browser) перестаёт показывать.

**Comment by Alex-302** [comment]
Не могу подтвердить. На своём китайском планшете запустил сериал(45 минут), отыграло без проблем. Может с количеством ОЗУ связано? У меня 2 ГБ.

**Comment by Alex-302** [comment]
На самсунге тоже не повторяется. Возможно проблема только у старой версии, или с прошивкой что-то.
