### ISSUE TITLE
http://skidrowcrack.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#462]
Антиадблок на сайте, появляется не сразу, а спустя некоторое время

https://i.imgur.com/gZkSrBh.png

https://qcrm.cc/#/customer/664887

**Comment by Alex-302** [comment]
На проверку:
skidrowcrack.com##[id^="bsa"][style*="opacity:"]

**Comment by Alex-302** [comment]
добавил в эф
