### ISSUE TITLE
ads on .by websites (available through proxy only)

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#463]
torrents.by, sharkeva.com

**Comment by Alex-302** [comment]
torrents.by##img[width="240px"][height="400px"]
torrents.by###tr_main_cats
||torrents.by/forum/Skoda.jpg
добавил в эф
по sharkeva.com не понял что блокировать

**Comment by Alex-302** [comment]
Пока закрываю. На sharkeva.com нечего блокировать вроде.
