### ISSUE TITLE
[windows] malwarebytes ads

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#464]
Details are here:
http://forum.adguard.com/showthread.php?1036-Browsers-gt-Applications&p=48704#post48704

Please check if it's possible to block this and reply to the forum with the result.

**Comment by Alex-302** [comment]
Похоже не заблокировать такие сообщения. При выключенном имете вылезли.

**Comment by adguard** [comment]
Ну так и отпиши тогда на форуме
