### ISSUE TITLE
http://fotostrana.ru/play/logic/sssr/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#465]
Русский фильтр не дает запустить приложению. Пишет "Обновите Flash Player".

https://qcrm.cc/#/customer/1021298

**Comment by Alex-302** [comment]
Добавил в эф
@@.nevomedia.ru/fs/rel/?apiUrl=$urlblock,domain=nevomedia.ru|fotostrana.ru
и ещё для некоторых игр
@@||wysegames.com/login/$jsinject,domain=wysegames.com|fotostrana.ru
