### ISSUE TITLE
http://news.lent.az/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#466]
Рекламный баннер справа.

https://qcrm.cc/#/customer/1025051

**Comment by Alex-302** [comment]
Добавил в ЭФ:
||news.lent.az/upload/rebans/
news.lent.az##.header_rebans
news.lent.az##.menu_bottom_rebans
news.lent.az##.article_rebans
news.lent.az##.right_rebans_box > object[width="200"][height="250"]
news.lent.az##.face_rebans
news.lent.az##.rebans_bottom
юзер должен его включить
