### ISSUE TITLE
gamer.ru - full screen ads

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#469]
http://forum.adguard.com/showthread.php?5125-%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%BE-http-www-gamer-ru&p=48937#post48937

**Comment by Alex-302** [comment]
К стилю особо не привязаться, некоторые параметры рассчитываются(размеры затемнения)
gamer.ru#%#document.cookie = "megafullscreen_banner=1";

**Comment by adguard** [comment]
Переоткрыл, глянь на форуме мой коммент.

**Comment by Alex-302** [comment]
Заменил твоим.
