### ISSUE TITLE
http://kissanime.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#47]
http://kissanime.com/Anime/Akame-ga-Kill/Episode-010?id=80033 и другие видео - выдает просьбу отключить адблокер. http://screencast.com/t/CiMVoe9S39h

IEX-736-14293

https://qcrm.cc/#/customer/629137

**Comment by vbagirov** [comment]
Снова проблема с антиадблоком появилась. Спустя какое-то время после запуска видео появляется http://screencast.com/t/CiMVoe9S39h

**Comment by Alex-302** [comment]
Для проверки:
kissanime.com#%#AG_onLoad(function() { window.DoDetect2  = function() {} });

**Comment by vbagirov** [comment]
Правило работает, но в ЭФ его пока нет.

**Comment by Alex-302** [comment]
Скоро появится
https://github.com/AdguardTeam/ExperimentalFilter/blob/master/Russian/specific_web_sites.txt

**Comment by Alex-302** [comment]
Всё норм. Закрываю.
