### ISSUE TITLE
[android] Bizon TV issue

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#470]
From 4pda.ru:

Заметил такую вещь. Стояла программа Bizon TV, и останавливалась на заставке программы и тв не работало. Отключил adguard, включил Bizon TV и тв заработало. Включил adguard и Bizon TV тоже работает. Проверено одинаково на двух устройствах.

**Comment by Alex-302** [comment]
Выключал все фильтры - не помогло.

**Comment by adguard** [comment]
Закрывай, заведу баг
