### ISSUE TITLE
http://www.amazon.ca

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#472]
http://www.amazon.ca/gp/help/customer/display.html/ref=gw_m_b_he?ie=UTF8&nodeId=915404

Не работает кнопка contact us

https://qcrm.cc/#/customer/1026486

**Comment by Alex-302** [comment]
Добавил в ЭФ:
@@||amazoncustomerservice.d2.sc.omtrdc.net/b/ss/acsca-prod/$domain=amazon.ca|amazon.com|amazon.co.uk
