### ISSUE TITLE
multoigri.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#476]
Игры не запускаются при включенном Adguard

https://qcrm.cc/#/customer/1028065

**Comment by Alex-302** [comment]
Если не ошибаюсь, играть можно только в IE?
Пусть попробует такие правила и отпишется заработало или нет, появилась ли реклама:
@@||2mdn.net/instream/flash/v3/adsapi_3.swf
@@||s0.2mdn.net/instream/flash/v3/3.191.0/adsapi.swf
@@||googleads.g.doubleclick.net/pagead/ads?ad_type=
||r2---sn-hvguvo-n8ve.googlevideo.com/videoplayback?c=$mp4

**Comment by Alex-302** [comment]
Добавил в основной:
multoigri.ru###preloader
multoigri.ru###gameadtop
multoigri.ru###gameadbottom
Пусть отпишется
