### ISSUE TITLE
[android] Next Browser ads

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#478]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=39636358

**Comment by Alex-302** [comment]
Такое правило убирает у меня ркламу:
||launchermsg.3g.cn/golaunchermsg/advservice.do
но юзеру почему-то не помогло.

**Comment by adguard** [comment]
А он кэш приложения чистил / данные сбрасывал?

**Comment by Alex-302** [comment]
Говорит чистил. Пишет что блокировка фейсбука помогает, но это не вариант

**Comment by adguard** [comment]
Ну да, это не для основных фильтров.

**Comment by adguard** [comment]
Короче, думаю он залогинен в Facebook, и из-за этого подтягивается реклама из фейсбучной рекламной сети.

Мы пока что не можем ее нормально заблочить.

**Comment by Alex-302** [comment]
пока прикрою
