### ISSUE TITLE
[android] Heroes Charge is broken

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#479]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=39643907

**Comment by Alex-302** [comment]
Похоже баг. Выключение фильтров не помогает.

**Comment by adguard** [comment]
Дефект завел, можно закрывать:
http://jira.performix.ru/browse/AG-7606

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/12070669/e3d5d84a-b08b-11e5-9646-ca241d94070f.png)
снова есть проблема, отключение фильтров не помогает.
AHY-501-21967

**Comment by ameshkov** [comment]
@evgeniy-ADG помогает ли добавление в pref.net.exclusions?
