### ISSUE TITLE
[android] CityGuide and Viber issues

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#480]
http://forum.adguard.com/showthread.php?5225-%D0%91%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D1%83%D1%8E%D1%82%D1%81%D1%8F-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B9

**Comment by Alex-302** [comment]
по пробкам и чату не повторилось

**Comment by Alex-302** [comment]
с viber тоже проблем не заметил

**Comment by Alex-302** [comment]
поправили
