### ISSUE TITLE
http://www.strikeout.co/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#481]
Антиадблок

https://qcrm.cc/#/customer/1028531

**Comment by Alex-302** [comment]
strikeout.co#$#.vip_052x003 {height: 150px!important;}
strikeout.co#$#.vip_09x827 {height: 25px!important;}
@@||cdn.vipbox.tv/js/ads.js

**Comment by Alex-302** [comment]
Добавил в основной
