### ISSUE TITLE
interia.tv

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#484]
Реклама перед видео.

GBE-339-48097

**Comment by Alex-302** [comment]
Пусть напишет фильтры. С нашими всё норм играет.

**Comment by Alex-302** [comment]
У меня чисто. Пусть напишет какие использует фильтры.

**Comment by vbagirov** [comment]
Запросил.

**Comment by vbagirov** [comment]
Тут апдейта нет и не будет, пользователь удалил Адгард.
