### ISSUE TITLE
fs.to ads

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#486]
реклама на http://fs.to (по центру) 
редиректит: http://ad.adriver.ru/cgi-bin/click.cgi?sid=1&ad=518662&bt=21&pid=1932800&bid=3804674&bn=3804674&rnd=81661180 
сделайте запрет в фильтре чтобы не открывало эту помойку с сайта: ad.adriver.ru

**Comment by Alex-302** [comment]
Починил. На форуме заявка была.

**Comment by Alex-302** [comment]
Пусть проверит.

**Comment by Alex-302** [comment]
||fsua.dotua.org/cssmin/*/branding_banner.ie.min.css
в основном уже есть
