### ISSUE TITLE
allmult.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#489]
На сайте http://allmult.com/ не работают раскрывающиеся списки в которых вставлено видео из vk.com, например на странице: http://allmult.com/9747-klass-ubiyc-ansatsu-kyoushitsu-assassination-classroom.html

https://qcrm.cc/#/customer/1030629

**Comment by Alex-302** [comment]
Поправил в фильтре.
Для пробы:
allmult.com#@##dle-content noindex>div[style]
