### ISSUE TITLE
http://univer-sasha-tanya.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#491]
На сайте рутуб-плеер не дает проигрывать в высоком качестве.

https://qcrm.cc/#/customer/1028491

**Comment by vbagirov** [comment]
Похоже, на самом рутубе у юзера та же проблема остается.

**Comment by vbagirov** [comment]
Сообщение о низком качестве видео может появляться не сразу, а через ~10 секунд, даже на самом рутубе.

**Comment by Alex-302** [comment]
рутуб. Пока вариантов не особо...
