### ISSUE TITLE
http://www.schlock.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#492]
http://www.schlock.ru/dom-2-efir-27-aprelya-onlajn-dom-2-27-04-2015.html

Реклама перед видео, в рутуб-плеере нельзя выбрать лучшее качество.

http://vk.com/topic-53764934_29576319?offset=860

**Comment by Alex-302** [comment]
C рутубом какая-то лажа, наверное рекламу придётся разблокировать.
По второму плееру - заблокировать может только программа, в расширении такой функции нет(подмена рекламного видео).

**Comment by vbagirov** [comment]
То есть с рутубом окончательно все плохо?

**Comment by Alex-302** [comment]
Даже не знаю. Посмотрим несколько дней.

**Comment by vbagirov** [comment]
Есть какой-то апдейт?

**Comment by Alex-302** [comment]
Пока нет. Не получается заблокировать так, чтоб качество работало.
При переходе на сам рутуб(кликнув на названии ролика в плеере) всё работает нормально.

**Comment by Alex-302** [comment]
рутуб...
