### ISSUE TITLE
[Android] https://play.google.com/store/apps/details?id=tw.idv.arlen

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#495]
Реклама в приложении.

https://qcrm.cc/#/customer/972462

**Comment by Alex-302** [comment]
И тут чисто. Пусть попробует включить русский фильтр и отпишется по результату.

**Comment by vbagirov** [comment]
Он включил, говорит часть реклам пропала, часть осталась: 
http://screencast.com/t/NjXFQhel
http://screencast.com/t/eVsVvg92Qnjw

Такое ощущение, что там два рекламных хоста, один из которых заблокировался, а второй нет

**Comment by Alex-302** [comment]
Никак не могу повторить.

**Comment by vbagirov** [comment]
У меня тоже не повторяется. Закрываю.
