### ISSUE TITLE
[android] ads on kg sites

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#496]
ts.kg
torernt.kg
diesel.elcat.kg
namba.kg - ну там просто реклама в рекламе в рекламе, рай для адблокера
files.kg

**Comment by Alex-302** [comment]
torernt.kg не доступен
diesel.elcat.kg рекламы не вижу
files.kg чисто вроде
Добавил в foreign
ts.kg##.oops-branding
ts.kg#$#body {background:url('/')!important;}
ts.kg#$#.main-container {margin-top: 0px!important;}
||base.namba.kg/www/base/base_frame.php?pppzoneid=
namba.kg##.deals-banner
namba.kg##object[width="520"][height="155"]
namba.kg##.layout-content > #branding
namba.kg##.banner
namba.kg##iframe[width="230"][height="270"]
namba.kg#$#body {background:url('/')!important;}

**Comment by adguard** [comment]
В русский можно добавлять

**Comment by Alex-302** [comment]
Добавил.
