### ISSUE TITLE
http://nude-moon.com/view.php.

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#497]
1) Чистим куки
2) Кликаем по сайту, пару-тройку ссылок
3) Появляются попапы. 

Повторяется во всех браузерах.

https://qcrm.cc/#/customer/795479

**Comment by Alex-302** [comment]
Пусть такое проверит:
||apcvq.pw^$third-party,popup

**Comment by vbagirov** [comment]
Передал юзеру, пока закрываю.
