### ISSUE TITLE
[Android] libertycity.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#500]
Реклама на сайте не заблокирована.

https://qcrm.cc/#/customer/1009236

**Comment by Alex-302** [comment]
Чё-то не вижу. А можешь у него конкретные ссылки на страницы с рекламой запросить?

**Comment by vbagirov** [comment]
Если будет ответ от юзера - напишу. У меня тоже не повторяется.

**Comment by vbagirov** [comment]
Походу у него английский фильтр был выключен. Можно закрывать.
