### ISSUE TITLE
adguard blocks adaway hosts file URL

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#501]
Совместно с Adguard использую Adaway для блокировки рекламы через host.Так вот:Adguard постоянно блокирует доступ к источнику списка host http://hosts-file.net/ad_servers.asp .Исправьте,пожалуйста

**Comment by Alex-302** [comment]
добавил в англ исключения:
@@||hosts-file.net/ad_servers.$document
