### ISSUE TITLE
[android] mmamania.com unblocked social widgets

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#502]
That's strange because social widgets are blocked ok on desktop.

Either we miss some rules on Android or they use HTTPS widgets.
In the second case we should block this with element hiding rules.

**Comment by Alex-302** [comment]
блокировка урл не поможет. В винде кнопки скрытв. Но в дроиде почему-то не скрывается правилом, которое есть в соц фильтре и работает в винде, например
:~facebook.com##a[href^="https://www.facebook.com/sharer/sharer.php?u="]

**Comment by adguard** [comment]
А если через chrome://inspect посмотреть, есть ли вообще эти стили на странице?
Или проверь, отдаются ли эти правила с mobile.adtidy.org (может для дроида их обрезало).

**Comment by Alex-302** [comment]
Похоже не встраивается стиль. На других - нормально.

**Comment by adguard** [comment]
Это только с качественной фильтрацией?

**Comment by Alex-302** [comment]
в обоих режимах не инжектится

**Comment by Alex-302** [comment]
Исправили.
