### ISSUE TITLE
[android] vintera tv

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#507]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=39829246

**Comment by Alex-302** [comment]
Похоже фильтрацию надо отключать для проги. Пробовал исключить заблокированные запросы - всё равно ошибку выдаёт.
Ещё вопрос - возможно ли сделать модификатор для правил - исключение для определённого приложения по его ID в Маркете? Типа такого:
@@||googleads.g.doubleclick.net^$app=com.ghisler.android.TotalCommander

**Comment by adguard** [comment]
Не, пока что нельзя.

Если много такого будет - придется добавить такую функцию.

**Comment by Alex-302** [comment]
В исключения пойдёт, или чёто можно придумать?

**Comment by adguard** [comment]
Получается в исключения, да

**Comment by Alex-302** [comment]
Тогда закрываю.
