### ISSUE TITLE
chatovod.ru missed ads

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#510]
http://000a.chatovod.ru/

**Comment by Alex-302** [comment]
Не получается что-то.
Пробовал с задержкой
#%#AG_onLoad(function() { $('.obl').remove().delay(5000); });	
и без толку. В консоли работает.

**Comment by adguard** [comment]
delay - нет такой функции

**Comment by Alex-302** [comment]
blondoubezhishe.chatovod.ru,mobile-files.chatovod.ru,minecraft-chat1.chatovod.ru,ortherd.chatovod.ru,gold-warez.chatovod.ru,chatovod.ru,spiritix.eu,chat.muz-tv.ru,подростковыйчат.рф,детскийчат.рф,чатволчат.рф,чаткроватка.рф,чатобщения.рф,animeski.chatovod.ru###aevents *

**Comment by Alex-302** [comment]
Опять он display: block important влепил. Скрипт удаления почему-то не работает.

**Comment by adguard** [comment]
Так а ты сделай #$#aevents * { visibility: hidden; height: 0px; }

**Comment by Alex-302** [comment]
Помогло. Но на долго ли?)

**Comment by adguard** [comment]
Ох не знаю:) Ну проверь еще разок, если все чисто, значит повезло:)

**Comment by Alex-302** [comment]
Пока чисто)
