### ISSUE TITLE
http://vkrugudruzei.ru/x/video/my

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#514]
Реклама на странице.

https://qcrm.cc/#/customer/1034424

**Comment by Alex-302** [comment]
Добавил в русский:
vkrugudruzei.ru##iframe[src*="facebook.com/plugins/likebox.php"]
vkrugudruzei.ru##div[class^="zeusadv"]
||reklamastatic.vkdrt.ru/posting/zeusadv/$domain=vkrugudruzei.ru
