### ISSUE TITLE
[Extension] http://tushkan.net/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#515]
Не до конца вырезаем рекламу: http://screencast.com/t/sCwlVbgh

**Comment by Alex-302** [comment]
Пустоту не убрать, нижние блоки не переместятся на место остатков баннера.
Почистил другие остатки:
||tushkan.net/js/banners/
tushkan.net###banner_left_top
Если не хочет видеть белый прямоугольник, пусть добавит
tushkan.net##td[width="250"] td[style*="height: 390px; vertical-align: top;"]
