### ISSUE TITLE
http://surfingbird.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#522]
Если залогиниться, то при клике на любой статье экран затемняется вместо перехода по ссылке.

https://qcrm.cc/#/customer/1035928

**Comment by Alex-302** [comment]
Пусть аккаунт сделает. Зарегаться не получается, у них что-то видать сломалось.

**Comment by Alex-302** [comment]
Исправил правило:
~surfingbird.ru,~samsung.com,~imgur.com,~rockstargames.com#%#var addthis = { init: function() {}, addEventListener: function() {}, button: function() {}, counter: function() {} };
