### ISSUE TITLE
http://fastpic.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#523]
Если кликнуть на пустое место слева или справа - переход на сайты.

https://qcrm.cc/#/customer/838042

**Comment by Alex-302** [comment]
Добавил в русский
fastpic.ru#%#AG_onLoad(function() { $('body').unbind('click'); });
Для пользовательского, если курсор засмущает
fastpic.ru#$#body {cursor: default!important;}
