### ISSUE TITLE
[Android] https://play.google.com/store/apps/details?id=com.neurondigital.exercisetimer

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#524]
http://screencast.com/t/0jnBrkSRKoew - выключенная защита
http://screencast.com/t/h4WYMfdfGx - включенная

https://qcrm.cc/#/customer/1032913

**Comment by Alex-302** [comment]
Спроси плиз юзера, при каких условиях реклама лезет. У меня не повторяется. Вообще не вижу сетевой активности.

**Comment by vbagirov** [comment]
4й Андроид, бета последняя, VPN, качественный режим фильтрации.
Фильтры русский, англ, spyware, соцфильтр и мобильный

**Comment by Alex-302** [comment]
А в какой стране юзер? Может там привязка географическая.

**Comment by vbagirov** [comment]
Судя по скринам где-то в Швеции. Прислал логи, если помогут.

**Comment by Alex-302** [comment]
Даже хз. Не вижу, чтоб прога куда-то в инет ломилась.

**Comment by vbagirov** [comment]
Еще раз запросил лог у пользователя.
