### ISSUE TITLE
[android] FS VideoBox broken

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#525]
Установлен Adguard 1.1.888; режим фильтрации Локальный HTTP прокси.
При включенном Adguard в программе FS VideoBox версия: 1.8.6 раздел "в Процессе" не отображается ничего. Когда же отключаю Adguard видны все имеющиеся там фильмы. В предыдущей версии Adguard работало все нормально.

**Comment by Alex-302** [comment]
Не нашёл пункта "в Процессе". Жду ответа юзера.

**Comment by Alex-302** [comment]
На китайском планшете без Адгарда категорий нет.
