### ISSUE TITLE
[android] [nsfw] pornhub.com and redtube.com are broken

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#526]
Доброго дня. На версии 1.1.888 блокируются сайты redtube.com и pornhub.com - иногда титульная страница открывается, но любой переход по ссылкам блокируется эдгаром.
В версии 1.1.835 всё нормально. Иногда появляются всплывающие плохие окна, но вот уже они заблокированными становятся.

Ах, забыл главное: добавление в белый список - полностью разрешает рекламу на данных сайтах. Нужно другое решение)

**Comment by Alex-302** [comment]
Добавил в игнор
||redtube.com^$subdocument,~third-party
