### ISSUE TITLE
4shared anti-adblock

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#527]
On 4shared when I try to download a file the waiting time increases from 20 sec. to 1000 sec. because 4shared notices that a adblocker is active.

I use only the standard Adguard filters.

Russian filter
English filter
Dutch filter
Filter for useful ads

**Comment by adguard** [comment]
Possible fix:
http://www.wilderssecurity.com/threads/adguard-ad-blocker.342850/page-34#post-2489165

**Comment by Alex-302** [comment]
Их правило помогло.
Нашёл в скрипте в коде страницы проверку
```
Config.detectAd = {
    allowedUri: 'empty.js',
    blockedUri: '/show_ad_.xml'
  };
```
Можем изменить значение blockedUri на такое, которое под блокировку не попадает?(если вдруг на аналогичное сменят)
Пока добавил в antiadblock:
@@||4shared.com/show_ad
