### ISSUE TITLE
torr.by and torrents.by

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#528]
http://lostpic.net/?photo=1958513
http://lostpic.net/?photo=1958514
Это пример. Где эти 3 точки, это реклама. Из-за них слегка долгая загрузка страницы. Каждый раз приходится добавлять подобное в ручную.
Подобные точки есть на домене sharkeva.com (внизу)

Доступен только через прокси.

**Comment by Alex-302** [comment]
Добавил:
||torrents.by/forum/Skoda.jpg
##img[width="240px"][height="400px"] - в bannersizes
torr.by,torrents.by##.pluso - можно наверное без привязки к домену
