### ISSUE TITLE
[Android] my-hit.org

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#530]
Пропускаем рекламу в Андроиде 

https://qcrm.cc/#/customer/394317

**Comment by Alex-302** [comment]
Сайт на HTTPS. В Дроиде пока не вычистить этот баннер.

**Comment by vbagirov** [comment]
Закрывать пока?

**Comment by Alex-302** [comment]
Да. Пока нет решения.
