### ISSUE TITLE
http://kinobar.kz/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#531]
Реклама на фоне 

https://qcrm.cc/#/customer/1036949

**Comment by Alex-302** [comment]
Добавил:
~kinobar.kz,~allmult.com,~latino-serialo.ru,~tvpult.net,~smeshnoevideo.com,~rusdtp.ru,~novinkionlain.ru,~vidoser.com,~video-school.kz,~kinoimperiya.net,~zerx.tv,~xrust.ru###dle-content noindex>div[style]
