### ISSUE TITLE
[Extension] http://onejournal.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#532]
Реклама в верхней части страницы.

https://qcrm.cc/#/customer/741799

**Comment by Alex-302** [comment]
Добавил в русский:
||onejournal.ru/images/banners/

**Comment by vbagirov** [comment]
По-прежнему остатки рекламы
http://screencast.com/t/fbITSsaetHM

**Comment by Alex-302** [comment]
Добавил в русский:
onejournal.ru/##.bannergroup

**Comment by Alex-302** [comment]
Проверь снова. В правило ненужный слэш затесался.
