### ISSUE TITLE
[Android] http://m.fishki.net/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#533]
http://m.fishki.net/1527369-16-sms-ot-nashih-ljubimyh-mam.html

Виджеты появляются если просматривать страницу, а потом промотать немного вверх.

ZNC-330-30522

**Comment by Alex-302** [comment]
Добавил в моб фильтр
fishki.net##.mobile-float-nav.visible-xs.visible
fishki.net###fixed-mobile
