### ISSUE TITLE
dumpert.nl 

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#534]
При проигрывании видео появляется такая ошибка: http://screencast.com/t/zTEqfBlgUulI

Появляется не каждый раз, но если появляется, то помогает обнволение страницы.

WEN-384-59332

**Comment by Alex-302** [comment]
Добавил в голландский:
@@||cdn-static.liverail.com/swf/v4/plugins/jwplayer/6.7/LiveRail.swf$domain=dumpert.nl
@@||cdn-static.liverail.com/swf/v4/admanager.swf$domain=dumpert.nl
Пусть вручную обновится и проверит, и включит если этот фильтр выключен.
