### ISSUE TITLE
http://winestyle.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#535]
Не открываются ссылки при нажатии на кнопки на странице.

https://qcrm.cc/#/customer/1029715

**Comment by Alex-302** [comment]
На проверку:
@@||google-analytics.com/analytics.js$domain=winestyle.ru
@@||google-analytics.com/plugins/$domain=winestyle.ru

**Comment by vbagirov** [comment]
У меня работает, можно заносить в фильтры

**Comment by Alex-302** [comment]
Добавил.
