### ISSUE TITLE
adultmult.tv missed ads and anti-adblock script

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#539]

**Comment by Alex-302** [comment]
Добавил:
adultmult.tv#@##Ads
adultmult.tv#@##ads
adultmult.tv#@##ads_160
adultmult.tv#@##adsense
adultmult.tv#@##bbo_ad1
adultmult.tv#@##cubead
adultmult.tv#@##cubeAd
adultmult.tv#@##midrect_ad
adultmult.tv#@##secondad
adultmult.tv#@##showAd
adultmult.tv#@##showad
adultmult.tv#@##yahoo_ads

||adultmult.tv/fonn/bg.css

**Comment by Alex-302** [comment]
Добавил:
adultmult.tv#%#window.setTimeout=function() {};
||adultmult.tv/fonn/bg.css
