### ISSUE TITLE
http://www.incredibox.com/ anti-adblock script

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#540]

**Comment by Alex-302** [comment]
incredibox.com###bbox-fd
incredibox.com###box-abp
пока не добавляю, ещё сам скрипт гляну

**Comment by Alex-302** [comment]
incredibox.com###bbox-fd
incredibox.com###box-abp
пока не добавляю, ещё сам скрипт гляну
/////
во
incredibox.com#%#var fuckAdBlock = false;
какой вариант добавлять?
