### ISSUE TITLE
[android] SimpleNote is blocked

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#544]

**Comment by Alex-302** [comment]
Юзер крайне подробно описал проблему:)
Синхронизация работает. Возможно у него версия с брандмауэром который блочит по-умолчанию. Запросил подробности.

**Comment by Alex-302** [comment]
Обещал логи сделать, с то не понятно что за проблемы.

**Comment by Alex-302** [comment]
Чудесным образом починилось.

**Comment by Bohdan-SUP** [comment]
HTTPs filtering breaks sync, we should consider adding it to exceptions:
com.automattic.simplenote

**Comment by Alex-302** [comment]
@Bohdan-SUP 
лучше в раздел Дроида перетащи. Я здесь не помогу.

**Comment by Bohdan-SUP** [comment]
Done:
https://github.com/AdguardTeam/AdguardForAndroid/issues/540
