### ISSUE TITLE
[social] travelask.ru

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#552]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=40135348

**Comment by Alex-302** [comment]
В соц фильтр:
travelask.ru##.post_shares
travelask.ru###facebook-popup
travelask.ru###vk-popup
travelask.ru##.fixed-like-box
travelask.ru##.rats
travelask.ru##.facebook-toolbar
