### ISSUE TITLE
[android] com.ludia.dragons is broken when VPN is enabled

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#554]
https://play.google.com/store/apps/details?id=com.ludia.dragons

**Comment by Alex-302** [comment]
а какой симптом? Виснет на загрузке при 70%?

**Comment by adguard** [comment]
Попробуй чуть позже еще разок.

**Comment by adguard** [comment]
Может с серверами у них проблемы например.

**Comment by Alex-302** [comment]
Не повторилось в общем. Возможно, юзер не дождался окончания загрузки. Там почти 500 МБ загружается.

**Comment by adguard** [comment]
Нехило. Ок, давай закрывать.
