### ISSUE TITLE
[Android] Vintera.tv

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#557]
https://play.google.com/store/apps/details?id=tv.vintera.smarttv&hl=en

Adguard блокирует работу приложения

https://qcrm.cc/#/customer/1039437
https://qcrm.cc/#/customer/1034700

**Comment by Alex-302** [comment]
Боюсь, что придётся исключать из фильтрации.

**Comment by Alex-302** [comment]
прога уже в исключениях
