### ISSUE TITLE
kinomoov.net

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#558]
http://kinomoov.net/film2015/4108-iz-mashiny-2015.html

Антиадблок в видео.

**Comment by Alex-302** [comment]
Добавил:
@@||uakino.net/templates/uakino/images/banner.gif
kinomoov.net#@#img[width="88"][height="31"]

**Comment by Alex-302** [comment]
И такое пусть проверит
kinomoov.net#%#AG_onLoad(function() { window.flashLayerAdShowed = true; });
Должен пропасть отсчёт перед стартом видео.
