### ISSUE TITLE
http://torrent-windows.net/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#561]
При включенном расширении (может быть и программе тоже) не прогружаются страницы сайта.

**Comment by Alex-302** [comment]
Похоже сайт тормозной. Без фильтрации тоже еле грузится.

**Comment by Alex-302** [comment]
Вроде норм всё.
Добавил ещё от кликандера
||torrent-windows.net/romeo1.js

**Comment by evgeniy-ADG** [comment]
http://torrent-windows.net/ 
При переходе на любую вкладку, открывается мгновенно окно и закрывается:
http://prntscr.com/b1y4im

**Comment by Alex-302** [comment]
Добавил
||j.tg2016.net^$third-party
||zoro.torrent-windows.net^

**Comment by Alex-302** [comment]
Разнотипные проблемы лучше в разных темах размещать.
