### ISSUE TITLE
ultimatv.org

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#569]
Реклама перед видео.

**Comment by Alex-302** [comment]
Если речь о надписи в плеере, то пока её убрать не можем.

**Comment by vbagirov** [comment]
Такая хрень появляется на первые 10-20 секунд: http://screencast.com/t/zMeh7UV1oEiC

**Comment by Alex-302** [comment]
такое пока не можем убрать. Закрою
