### ISSUE TITLE
[android] missed ads on fotohost.by

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#570]
http://fotohost.by/image/I6f

**Comment by Alex-302** [comment]
fotohost.by - чисто
на форуме, который на скрине - чисто, английский фильтр убирает баннер.
Если что - пусть даст удалённый доступ

**Comment by adguard** [comment]
w1tf с 4pda, напиши ему

**Comment by Alex-302** [comment]
Добавил в моб
||webtransfer-finance.com^ (из-за https)
