### ISSUE TITLE
http://online.anidub.com/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#578]
Реклама перед видео например 
http://online.anidub.com/anime_ova/anime_ona/9162-sozdano-s-dushoy-yaponskiy-anime-ekspo-nihon-animator-mihonichi-02-iz-30.html

**Comment by Alex-302** [comment]
Добавил в русский:
||kadam.net^$third-party
Пусть отпишется, или у себя проверь.

**Comment by vbagirov** [comment]
Да, все нормально.
