### ISSUE TITLE
minfin.com.ua

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#579]
В хедере пустое место остается, нельзя убрать? Юзер вообще говорит что у него оно кликается, у нас не повторилось.

https://qcrm.cc/#/customer/838042

**Comment by Alex-302** [comment]
Да, вчера поправил.
По отступу - добавил в русский:
minfin.com.ua#$#.mfz-page-wrap {margin: 0px auto 50px!important;}
