### ISSUE TITLE
mobilmania.cz - video does not play

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#580]
http://www.mobilmania.cz/clanky/on-line-sledovali-jsme-uvodni-keynote-google-io/sc-3-a-1330840/default.aspx

**Comment by Alex-302** [comment]
Знать бы какие фильтры включены.
С нашими повторилось, вроде помогло такое исключение:
@@||mf.advantage.as/if/imcreat.php$domain=mobilmania.cz
Добавил в foreign.

**Comment by adguard** [comment]
Говорит исправилось вроде

**Comment by Alex-302** [comment]
Ок. Тогда закрываю.
