### ISSUE TITLE
fonstola.ru

### ISSUE THREAD

**Issue by Fot0n** [AdguardTeam/ExperimentalFilter#581]
Тизеры внизу каждой страницы.

**Comment by Alex-302** [comment]
Чисто вроде. Какие фильтры?

**Comment by Fot0n** [comment]
> Чисто вроде. 
![1](https://cloud.githubusercontent.com/assets/6566055/7903809/5e8906c4-07f0-11e5-9805-09aa4d451b1b.png)

> Какие фильтры?
![2](https://cloud.githubusercontent.com/assets/6566055/7903815/7650cddc-07f0-11e5-9879-8bc5d6a3f78f.png)

**Comment by Alex-302** [comment]
Странно. Реклама блокируется правилами
||d-agency.net^$third-party
||marketgid.com^$third-party
А в другом браузере как?
