### ISSUE TITLE
zoomby.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#583]
Реклама перед видео, например
http://www.zoomby.ru/watch/doktor-i?source=showspage:block_promo_carusel_small

**Comment by Alex-302** [comment]
Добавил исключение в фильтр счётчиков:
@@||stats.g.doubleclick.net/dc.js$domain=universarium.org

**Comment by Alex-302** [comment]
Проверь плиз такой вариант:
```
.zoomby.ru/a/
```

**Comment by vbagirov** [comment]
Работает.

**Comment by Alex-302** [comment]
Добавил.
