### ISSUE TITLE
http://karanpc.com/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#584]
При включенной защите содержимое сайта не отображается.

https://qcrm.cc/#/customer/1044749

**Comment by Alex-302** [comment]
что-то не получилось

**Comment by vbagirov** [comment]
Не получилось повторить или не получилось исправить?

**Comment by Alex-302** [comment]
Уже получилось)
Проверь такое правило:
@@||mcc.godaddy.com/park/$domain=karanpc.com
только смысла особого не вижу в фильтры тащить
