### ISSUE TITLE
http://uploadimagex.com/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#589]
Реклама + при клике на картинку попап.

Например, http://uploadimagex.com/view.php?image_id=23285

http://forum.adguard.com/showthread.php?5746-http-shtrafopoveshenie-ddns-net-epjail-law-php

**Comment by Alex-302** [comment]
добавил:
||blog.uploadimagex.com^
||uploadimagex.com/js/skybox.js
||uploadimagex.com/js/helmnow.js
