### ISSUE TITLE
[android] ru.pascal4eg.pddexamfree missed ads

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#596]
https://play.google.com/store/apps/details?id=ru.pascal4eg.pddexamfree

http://s020.radikal.ru/i701/1506/2d/2a30ae30f959.png

**Comment by Alex-302** [comment]
проверил - чисто. На 4pda юзеру  ответил, но он вроде не отреагировал

**Comment by Alex-302** [comment]
Возможно это поможет
||startappservice.com/*/gethtmlad
||appodeal.com^$empty
из чьего-то лога

**Comment by Alex-302** [comment]
помогло
