### ISSUE TITLE
[Android] ПДД Экзамен

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#598]
https://play.google.com/store/apps/details?id=ru.pascal4eg.pddexamfree

Реклама через раз в приложении: http://www.youtube.com/watch?v=NiC-PUkEHUo&feature=youtu.be
При запуске и при окончании ответа на вопросы билета.

https://qcrm.cc/#/customer/1050613

**Comment by Alex-302** [comment]
Там не понятно - то ли брандмауэр что-то пропускает, либо прога показывает рекламу из кэша, если есть сеть, но нет интернета(заблокирован брандмауэром)

**Comment by vbagirov** [comment]
Мб попробовать в версии без фаерволла?

**Comment by Alex-302** [comment]
Юзера не устроит. Если это тот же чел что и на 4пда.

**Comment by vbagirov** [comment]
Дай что ли ссылку на 4pda посмотреть

**Comment by Alex-302** [comment]
В основном в личке перепсывались.
http://4pda.ru/forum/index.php?showtopic=601691&view=findpost&p=40919290

**Comment by vbagirov** [comment]
Да похоже тот же самый. Я так понимаю, не победить тут?

**Comment by Alex-302** [comment]
Даже не знаю. У меня частично повторяется если проге дать подгрузить рекламу. При отсутствии инета но подключенной сети показывает из кэша. Если такого не допускать  - всё будет чисто.
