### ISSUE TITLE
[android] FS VideoBox

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#601]
Дело в том, что ADGuard прекрасно режет рекламу, но вместе с рекламой режет и функционал.
Вот с работающим ADGuard: http://fastpic.ru/view/71/2015/0619/ef87f92ae5719cb0273344f5f1f87b4c.png.html, 

а вот с неработающим: 
http://fastpic.ru/view/72/2015/0619/319a26879cc073fbb1285a2150728951.png.html

То бишь чтобы видеть категории в избранном и переключаться между ними, нужно отключать ADGuard. Полностью добавлять в исключение FSVideoBox нельзя - реклама прорвётся. 

А как отследить - что нужно добавить в исключение, а что заблокировать - я не представляю как выяснить.

**Comment by adguard** [comment]
От юзера DenchikK на 4pda

**Comment by Alex-302** [comment]
Похоже проблема с прокси. С VPN всё норм, а с прокси даже без фильтров не работает. Судя по логу, авторизоваться на сайте не может для получения избранного.

**Comment by adguard** [comment]
С прокси с рутом или с прокси с ручной настройкой?

**Comment by Alex-302** [comment]
С ручной проверял

**Comment by adguard** [comment]
Может просто криво ручную прокси поддерживает.

А с рутовой?

**Comment by Alex-302** [comment]
C автоматической норм.

**Comment by ameshkov** [comment]
Уточнение:
https://www.youtube.com/watch?v=UPcNHDWYIYI&feature=youtu.be

Режим прокси+авто

**Comment by Alex-302** [comment]
Не понятная ситуация - то проблема повторяется, то нет. Сейчас вот и с прокси и с VPN всё норм.

**Comment by Alex-302** [comment]
От Адгарда, похоже, не зависит. На моём планшете, после установки с выключенным Адгардом категорий нет.

**Comment by ameshkov** [comment]
Ну закрывай тогда чо уж
