### ISSUE TITLE
http://watch-series-tv.to/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#604]
http://watch-series-tv.to/episode/the_simpsons_s16_e6.html - щелкаем по ссылке, например, gorillavid, затем открывается окно и далее при клике на 'continue' рекламный попап. Затем ещё один и, наконец, "ркестик" от рекламы в самом плеере.

https://qcrm.cc/#/customer/1052974

**Comment by Alex-302** [comment]
добавил в англ
||178.17.164.58^$third-party
gorillavid.in###video_ad
gorillavid.in###wrad_container
