### ISSUE TITLE
[Android] Накрутка подписчиков в контакте

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#606]
https://qcrm.cc/#/customer/1008432

Реклама в приложении, если пару раз покликать там, то появляется окно с предложением установить игры и т.д.

**Comment by Alex-302** [comment]
Почему-то не блокируются запросы рекламы.

**Comment by Alex-302** [comment]
Не убрать здесь.
Может такое добавить себе
||applift-a.apptornado.com/offerwall/$empty
