### ISSUE TITLE
m.rays.mlb.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#612]
http://m.rays.mlb.com/news/article/132605362/colabello-homers-in-estradas-near-perfect-game

Не работают кнопки, отвечающие за "раскрытие" кнопок типа More и т.д.

https://qcrm.cc/#/customer/1054022

**Comment by Alex-302** [comment]
Добавил
@@||livefyre.com/wjs/v1.0/javascripts/CommentCount.js$domain=mlb.com
