### ISSUE TITLE
http://printdirect.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#619]
Много чего блокируем на сайте при включенной защите. Например, верхнюю панель или варианты оплаты при оформлении заказа, может ещё что-то.

https://qcrm.cc/#/customer/1055729

**Comment by Alex-302** [comment]
Пусть проверит это правило
@@||printdirect.ru^$elemhide

**Comment by vbagirov** [comment]
Передал

**Comment by Alex-302** [comment]
Добавил на всякий случай.
