### ISSUE TITLE
http://kinokrad.net/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#621]
Реклама перед видео, например, тут: http://kinokrad.net/279831-odnazhdy.html

(из контакта)

**Comment by Alex-302** [comment]
Добавил:
||vs.qrm24.com/cdn/vast.php
||kinokrad.net/_brand/

**Comment by evgeniy-ADG** [comment]
http://kinokrad.net/287203-vikingi-4-sezon-2016.html
http://prntscr.com/b06k6q

**Comment by Alex-302** [comment]
||gqer.ru^$third-party
