### ISSUE TITLE
[Android] sinoptik.ua

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#622]
Реклама на сайте

https://qcrm.cc/#/customer/1056374

**Comment by Alex-302** [comment]
На планшете не получается зайти, но в винде с дроидовыми фильтрами чисто(только один баннер). Если в поддержке кто-то знает как подключить тел к компу для отладки, то могу удалённо глянуть.

**Comment by Alex-302** [comment]
https...
