### ISSUE TITLE
[android] com.laurencedawson.reddit_sync missed ads

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#623]
http://forum.xda-developers.com/android/apps-games/adguard-ad-blocker-doesnt-require-root-t2958895/post61695399#post61695399

https://play.google.com/store/apps/details?id=com.laurencedawson.reddit_sync

**Comment by Alex-302** [comment]
Повторить не получается. Один раз с VPN США выскочило, и больше не повторяется.

**Comment by adguard** [comment]
Давай закрывать тогда
