### ISSUE TITLE
[android] kz.slando broken

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#625]
https://play.google.com/store/apps/details?id=kz.slando

http://forum.adguard.com/showthread.php?5947-%D0%9A%D0%BE%D0%BD%D1%84%D0%BB%D0%B8%D0%BA%D1%82-%D1%81-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F%D0%BC%D0%B8-%D0%B8%D0%B7-Play-%D0%9C%D0%B0%D1%80%D0%BA%D0%B5%D1%82

**Comment by Alex-302** [comment]
У меня не повторилась проблема, предложил вариант по аналогии с украинским
@@||olx.kz/i2/ajax/
