### ISSUE TITLE
[Android] Все сканворды

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#634]
https://play.google.com/store/apps/details?id=com.crosswordshop

Нужно выбрать любой кроссворд в бесплатной версии и полистать дальше. Появиться реклама от Google Play на весь экран.

https://qcrm.cc/#/customer/1058124

**Comment by Alex-302** [comment]
Не убрать её. Она в архивах с кроссвордами загружается.
Например
http://www.cros-shop.ru/pshop/magazines/ru/115708.zip
