### ISSUE TITLE
economictimes.indiatimes.com missed social widgets

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#638]
http://economictimes.indiatimes.com/markets/stocks/news/shanghai-stocks-plunge-over-1200-chinese-companies-halt-trading/articleshow/47982047.cms

buttons
popups

**Comment by Alex-302** [comment]
Added:
- social
indiatimes.com##.sharingBox
indiatimes.com##.share
- ads
indiatimes.com##.li_banner_wrap
