### ISSUE TITLE
fastpic.ru missed ads

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/ExperimentalFilter#639]
http://fastpic.ru/view/72/2015/0708/760ce893e7558fd7cd554680e2d38191.jpg.html

**Comment by Alex-302** [comment]
Добавил:
fastpic.ru##a[href^="http://777-888.ru/"]
fastpic.ru#$#body { background: url(/) #000000!important;}
и убрал не актуальные.

**Comment by chirag127** [comment]
![image](https://user-images.githubusercontent.com/76880977/115108458-2cc1c180-9f8e-11eb-8068-22ef7f146bd3.png)
ad leftover gray box

**Comment by Alex-302** [comment]
Enable Russian filter.
