### ISSUE TITLE
http://fishki.net/

### ISSUE THREAD

**Issue by Embos** [AdguardTeam/ExperimentalFilter#644]
http://fishki.net/1593494-byla-v-otpuske-privezla--12-millionov-fotografij.html

Первый раз с таким столкнулся. На сайте перестала откликаться кнопка "войти" и сортировка комментов по условию.
Интересно что фильтры не виноваты... То есть помогает только отключение фильтрации.
Если отключить все фильтры и расширения, но оставить фильтрацию - проблема не исчезает.
Помогите разобраться.
Скрин:
http://jpegshare.net/c7/b3/c7b357fd9797e1b4c7b056a9f1fd9e23.jpg.html

И еще справа пустое место от рекламы остается
http://jpegshare.net/77/92/779252bf25a8ccec0d19aa08f7bedaed.jpg.html

Программа Adguard 5.10.2051.6368
Win7x64 + Chrome x32
Расширений, антивирусов, фаерволов и прочей хероборы не имею.

**Comment by Alex-302** [comment]
Даже не знаю в чём причина. Расширение так не ломает.

**Comment by adguard** [comment]
Ломает инжект в страницу.

**Comment by Alex-302** [comment]
Добавил твоё правило
@@||fishki.net/user/login/$document,xmlhttprequest
