### ISSUE TITLE
http://fishki.net/

### ISSUE THREAD

**Issue by Embos** [AdguardTeam/ExperimentalFilter#645]
http://fishki.net/1593494-byla-v-otpuske-privezla--12-millionov-fotografij.html
Спасибо, починили вход.
Но ранжировка комментариев так и не работает.
Их найти можно под постом
http://jpegshare.net/c7/b3/c7b357fd9797e1b4c7b056a9f1fd9e23.jpg.html
Правило @@||fishki.net/user/login/$document,xmlhttprequest
как видно очень частное.
Другие элементы могут тоже не работать, так как не попадают под правило.

**Comment by Alex-302** [comment]
Добавил для сортировки комментов
@@||fishki.net/comment/$document,xmlhttprequest
Что ещё не работает?

**Comment by Embos** [comment]
Пока не закрывай тему. Я попозже как следует все гляну - тогда отпишусь

**Comment by Embos** [comment]
Проверил. Все нормально. Спасибо!
