### ISSUE TITLE
http://www.sports.ru/

### ISSUE THREAD

**Issue by Embos** [AdguardTeam/ExperimentalFilter#646]
http://www.sports.ru/
На странице вечная загрузка (не всегда, но часто - попробуйте обновлять страницу чтобы словить)
Если не получится повторить, подскажите, как можно вычислить причину "вечной загрузки"?
Через средства разработчика браузера? Где именно посмотреть?

У меня есть для сайта свои правила, но как выяснил они не являются причиной, но вдруг.

Программа Adguard 5.10.2051.6368
Фильтры: Eng, Rus, Виджеты, Счетчики.
Win7x64 + Chrome x32
Расширений, антивирусов, фаерволов не имею.

**Comment by Alex-302** [comment]
Не подтверждаю. Надо смотреть удалённо.

**Comment by Embos** [comment]
Как можно вычислить причину "вечной загрузки"?
Через средства разработчика браузера? Где именно посмотреть?

**Comment by Alex-302** [comment]
Да по разному. В основном встроенный в рекламный страницу код пытается достучаться до заблокированного элемента. Иногда что-то разблокировать аккуратно приходится, чтоб реклама не полезла, а иногда - удалять iframe. Можешь в инструментах удалять iframe, и если поможет, нажми ctrl+z и напиши его имя.

**Comment by Embos** [comment]
Ох не знаю, не могу вычислить. Не хватает знаний.
Выяснил только что это связано с adfox, но какой именно элемент - не могу найти, куча разделов.
Вот такое правило избавляет от вечной загрузки
@@ads.adfox.ru
Но оставлять его конечно не буду - реклама полезет отовсюду.

Тему пока не закрывайте. Я еще позже поищу

**Comment by Embos** [comment]
Вечная загрузка получается когда блокируются вот такие запросы


![default](https://cloud.githubusercontent.com/assets/9648798/8680658/3d071852-2a7c-11e5-8298-5f80731e442b.png)


Посмотрел Русский фильтр - там уже есть правила для adfox и вечной загрузки
Вот похожее правило
! sostav.ru - вечная загрузка
@@||ads.adfox.ru/*/prepareCode?pp=$domain=sostav.ru
Также есть и в ruadlist
Но они все ограничены доменами.

Я сделал вот такое
@@||ads.adfox.ru/*/prepareCode?pr=$domain=sports.ru

Вечной загрузки больше нет, но иногда вот такое стало проскакивать


![2](https://cloud.githubusercontent.com/assets/9648798/8680728/b4d5fa1a-2a7c-11e5-8c25-62451d22eceb.png)

Все же надеюсь вам удастся повторить случай

**Comment by Alex-302** [comment]
Не повторяется. Давайте лучше через тимвивер гляну. Разблокировать - не наш метод, есть спецсредства:)

**Comment by Embos** [comment]
Алекс, да я бы сразу и с удовольствием! Но у меня интернет очень медленный. Тебе не удобно будет и мне неловко.
Но если у тебя есть терпение - то я не против, но тогда все будет медленным и отзыв будет долго идти.  в лучшем случае 1-2 мегабита
Попробуешь?

**Comment by Embos** [comment]
Вот если что
409 955 546

3961

**Comment by Alex-302** [comment]
Добавил
```
sports.ru#%#AG_onLoad(function() { window.AG_removeElementBySelector('iframe[id^="AdFox_iframe_"]'); });
```

**Comment by Embos** [comment]
Блин, проблема не исчезла((
А ничего что эти iframe продолжают оставаться в коде?


![default](https://cloud.githubusercontent.com/assets/9648798/8684273/e1fc8694-2a90-11e5-8da7-b6c334bef5aa.jpg)

вечная загрузка пропадает если их удалить вручную через панель разработчика, их там штук пять

**Comment by Embos** [comment]
sports.ru$$aside[data-control="Banners.AdFox"]
sports.ru$$div[data-control="Banners.AdFox"]

Вот так все вырезал. Вечной загрузки больше нет и в коде iframe adfox не встречается.

**Comment by Alex-302** [comment]
с фреймами подумаем. А попробуй выключить свои правила и выключить в русском фильтре это правило:
@@||ads.adfox.ru/*/goLink$domain=sports.ru

**Comment by Alex-302** [comment]
Проверь такое правило:
||st.s5o.ru/source/_desktop/build/banners/main.js
ифреймы не удалялись, т.к. внедрялись когда мы уже отработали

**Comment by Embos** [comment]
Работает! Вот же гадский скрипт закопался)
Спасибо

**Comment by Embos** [comment]
Добавишь в фильтры или оставить в пользовательском?

**Comment by Alex-302** [comment]
оно в фильтрах уже
