### ISSUE TITLE
[Android] MX Player

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#648]
Реклама в приложении, скриншоты в тикете.

https://qcrm.cc/#/customer/1058870

**Comment by Alex-302** [comment]
для пользовательского
||52.0.252.115^$empty
возможно это CDN Амазона, в основные не пойдёт

**Comment by Bohdan-SUP** [comment]
Ad is not blocked:
https://www.dropbox.com/s/hi9z54oh8btn03o/Screenshot_2015-10-25-03-02-58.png?dl=0
WSJ-274-68931

**Comment by Alex-302** [comment]
still can't reproduce. I need HTTP requests log.
Or you can install Fiddler, configure it like this
http://imagizer.imageshack.com/img903/7727/gnJe5l.jpg
and set in android wifi proxy settings - ip of pc with Fiddler and port(8888 by default)
Then stop MX player, clear cache and run again. When ad will be loaded,save all sessions
http://imagizer.imageshack.com/img905/8687/vKQJcR.jpg
and send me *.saz file.

**Comment by rxorz** [comment]
Is Fiddler an android app? Based on the screenshots, it looks like a desktop program. Issue with MX player happens on my android phone.. (I currently don't have access to a desktop machine)

**Comment by Alex-302** [comment]
Fiddler is Win app.
Can you stop the MX in settings, clear their cache, switch Adguard log to "record http requests", start MX, wait for ads and after minute send me log file?

**Comment by rxorz** [comment]
Ok, let me try that. Where can I find the created log file?

**Comment by Alex-302** [comment]
You can also download logs directly:

/storage/emulated/Android/data/com.adguard.android/cache/log

or, depending on device,

/sdcard/Android/com.adguard.android/cache/log or

/sdcard/data/Android/com.adguard.android/cache/log or

/sdcard/Android/data/com.adguard.android/

**Comment by rxorz** [comment]
I think clearing the cache and data of the MX player fixed my problem with the ads. In case this happens again, at least I'll know how to generate and retrieve the logs. Thank you for your help!

**Comment by vbagirov** [comment]
YZF-387-95489 - HTTP requests logs from user who still has ads there.

**Comment by Alex-302** [comment]
As you can see on the screenshots of the sniffer, ads are loading from Facebook. FB works on HTPS, so we can't block this ads now.
Please ask what the sniffer he uses.

**Comment by vbagirov** [comment]
Sniffer he uses is "Packet Capture", https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture&hl=en

Will this be of any help?

**Comment by Alex-302** [comment]
It will helps to me:)
These ads are from Facebook. We will try to block them after adding HTTPS filtering.

**Comment by rxorz** [comment]
Cool. :) Excited to learn that there will be HTTPS filtering!

**Comment by Alex-302** [comment]
Now I closу this issue, but I will return when HTTPS support will be ready.

**Comment by Alex-302** [comment]
Alpha version blocks facebook ads.

**Comment by rxorz** [comment]
Cool. How do we get the alpha version?

-Ed. E.

**Comment by Alex-302** [comment]
There:
https://github.com/AdguardTeam/AdguardForAndroid/releases

With the one of the next builds(but not now) you can install Move Certs app for moving Adguard certificate to internal storage for disabling additional unnecessary lockscreen
https://f-droid.org/repository/browse/?fdid=com.nutomic.zertman
After insalling Adguard cert, you can move it by Move Certs, reboot the device and go to
Android settings -> "Security" -> and press "Clear credentials" and reboot again. Then you can disable aditional lockscreen.
