### ISSUE TITLE
talkers.ru - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#650]
Reported on 4pda.ru:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=41492820

**Comment by Alex-302** [comment]
Added:
talkers.ru##a[href="http://sakh.tv/"]
talkers.ru##a[href="http://sakh.tv"]

or common rule will be better?
talkers.ru##.page > div[style="padding:0px 25px 0px 25px"] > center > a[target="_blank"]

**Comment by ameshkov** [comment]
I believe second rule is better in this case.

Hiding links could lead to some false positives.

**Comment by Alex-302** [comment]
OK, done
