### ISSUE TITLE
skidkaonline.ru - anti-adblock

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#651]
http://skidkaonline.ru/moskva/shops/magnit/

Tested in Adguard for Mac.

**Comment by Alex-302** [comment]
Social:
skidkaonline.ru##.share-item
skidkaonline.ru##.social-like
skidkaonline.ru##.share
Anti-adblock:
skidkaonline.ru#%#var canRunAds = true;
Russian:
skidkaonline.ru##.ads-item
