### ISSUE TITLE
Видеоплеер pladform.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#655]
ok.ru/video/6239098037 - например, тут, блокируем видеоплеер.

https://qcrm.cc/#/customer/1059882

**Comment by Alex-302** [comment]
Пусть проверит:
@@||out.pladform.ru/getPlaylist$domain=ok.ru
@@||out.pladform.ru/getVideo$domain=ok.ru
В фильтр добавил.
