### ISSUE TITLE
mvideo.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#663]
http://www.mvideo.ru/televizory-i-cifrovoe-tv/televizory-65

Фильтры поиска слева не срабатывают при включенном адгарде.

https://qcrm.cc/#/customer/1062897

**Comment by Alex-302** [comment]
Выключить в русском:
@@.mvideo.ru$elemhide
добавить:
@@||mvideo.ru^$xmlhttprequest

**Comment by vbagirov** [comment]
Не работает у меня по прежнему
