### ISSUE TITLE
http://www.sports.ru/    (не помешала бы быстрая реакция)

### ISSUE THREAD

**Issue by Embos** [AdguardTeam/ExperimentalFilter#668]
На главной странице черный прямоугольник. Это из-за adfox.
Без adguard все норм.
Нужна быстрая реакция, так как обычно новость долго там не висит.
Скрин:
![default](https://cloud.githubusercontent.com/assets/9648798/8889619/2c6a1f12-32fb-11e5-8a99-46ce5f719aa4.jpg)

**Comment by Alex-302** [comment]
Добавил
sports.ru##.main-wrap > section.super-top
ниже ссылку на новость можно увидеть.
Разблокировка adfox может привести к появлению рекламы.

**Comment by Embos** [comment]
Это очень жесткое правило. Эти объявления они вешают почти каждый день. Там главная новость дня. Юзаю сайт каждый день, но вот такая черная фигура первый раз. 
Мне кажется вырезать целый блок лишнее. Может еще что-то можно придумать?

**Comment by Embos** [comment]
Во! Работает. только через adfox, но ничего лишнего не загружается
sports.ru#$#a.super-top__link.link.link_color_white {display: block !important}

**Comment by Alex-302** [comment]
Действительно:)
Добавил в русский
sports.ru#$#a.super-top__link {display: block!important;}

**Comment by Embos** [comment]
Алекс а чего предыдущее то не удалил) Оно так и осталось в русском.
sports.ru##.main-wrap > section.super-top

**Comment by Alex-302** [comment]
А зачем его убирать? Оно скрывает баннер(кубок чегототам)

**Comment by Embos** [comment]
Не, это правило удаляет блок главной новости. Выделил его красным прямоугольником.
![default](https://cloud.githubusercontent.com/assets/9648798/9280815/63166a5e-42da-11e5-9fcc-464053121792.jpg)

**Comment by Embos** [comment]
![default](https://cloud.githubusercontent.com/assets/9648798/9282211/35516740-42e4-11e5-9143-e51f070939d4.jpg)

**Comment by Embos** [comment]
![default](https://cloud.githubusercontent.com/assets/9648798/9282227/539d6f96-42e4-11e5-8e51-6a195155a82d.jpg)

**Comment by Alex-302** [comment]
Убрал.
