### ISSUE TITLE
[android] deviantart.com - missed ad placeholder

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#671]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=41751949

**Comment by Alex-302** [comment]
Добавил в англ 
||da-ads.com^$third-party
в моб
deviantart.com#$#div[class^="dp-ad-"] {height:0px!important; width:0px!important;}
deviantart.com##.mobile_adhesion

отрепортил
https://forums.lanik.us/viewtopic.php?f=62&t=24317

**Comment by Alex-302** [comment]
http://4pda.ru/forum/index.php?showtopic=601691&view=findpost&p=41858745
