### ISSUE TITLE
[Расширение] http://channelawesome.com/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#675]
При включенном расширении (с прогой не проверял) видео на сайте не запускается.

**Comment by Alex-302** [comment]
Работает.
Нужна ссылка, где не работает, и фильтры.

**Comment by vbagirov** [comment]
фильтры: https://dl.dropboxusercontent.com/u/12629675/Screenshots/Screenshot(20h.58m.30s)-(3.8.2015).jpg

Примеры негрузящихся видео: http://channelawesome.com/nostalgia-critic-are-kids-shows-better-now-than-ever/
http://channelawesome.com/nostalgia-critic-osmosis-jones/

**Comment by Alex-302** [comment]
Баг в расширении.
Временно добавил в английский:
@@||imasdk.googleapis.com/flash/sdkloader/adsapi_3.swf
@@||imasdk.googleapis.com/flash/core/*/adsapi.swf
Не закрывай пока.

**Comment by Alex-302** [comment]
Баг поправили, правила убрал. Пусть обновит расширение до 2.0.14 и проверит снова.
