### ISSUE TITLE
agent.mail.ru is offline all the time when Adguard is on

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#681]
Использую Adguard под Windows, и бесит,что когда защита включена, веб-агент всегда оффлайн, по идеи если нажать на него,я должен выйти в online (хотя по умолчанию он все время должен быть online), и не могу выйти в online, даже если тыкаю на него. Отключаю защиту-все ОК. Я имею ввиду веб-агент,который появляется на этой странице https://agent.mail.ru/ внизу справа, если конечно есть учетка mail.ru

**Comment by Alex-302** [comment]
Аваст с Адгардом как-то мешают друг другу. Выключение одной из двух прог исправляет отображение значка. Баг похоже.

**Comment by ameshkov** [comment]
Вот же странность то какая...

**Comment by ameshkov** [comment]
Давай тогда закрывать, мы это так просто не исправим

**Comment by Alex-302** [comment]
ок
