### ISSUE TITLE
3dnews.ru

### ISSUE THREAD

**Issue by Embos** [AdguardTeam/ExperimentalFilter#687]
http://www.3dnews.ru/
Просят отключить фильтрацию (сообщение вверху)

![5252](https://cloud.githubusercontent.com/assets/9648798/9280927/1baa7060-42db-11e5-8d6a-02fc1ae7ab15.jpg)

**Comment by Alex-302** [comment]
Поправил. С обновлением будет чисто.

**Comment by Embos** [comment]
Этого правило будет мало. Они сейчас еще сайт сделали серым и блеклым

**Comment by Alex-302** [comment]
добавил
@@||ad.3dnews.ru/*/ajs.php?zoneid=

**Comment by Embos** [comment]
Так тоже стремно чего-то. Реклама вылезла.
![default](https://cloud.githubusercontent.com/assets/9648798/9284363/b8ba92cc-42f4-11e5-8362-0fcb018d193f.jpg)

**Comment by Alex-302** [comment]
3dnews.ru#%#window.__AT_detected = true;
теперь вроде норм

**Comment by Embos** [comment]
Да, теперь отлично.
Значит два правила
3dnews.ru#%#window.__AT_detected = true;
3dnews.ru###adwarn

Они поменяют что-нибудь в ближайшее время, раз уж взялись. Так помониторить их надо будет

**Comment by Embos** [comment]
Алекс а куда правило 3dnews.ru###adwarn
пропало из русского фильтра?
Сообщение вверху опять вылезло.

**Comment by Alex-302** [comment]
Без него работало. Другой метод применял. Но уже не актуально, т.к. они переделали.
Проверь после обновления фильтров.

**Comment by Embos** [comment]
Сообщение есть, но может еще фильтр не обновился.
Алекс, они сейчас сделали так что это сообщение можно закрыть. Очевидно что они сейчас его проверяют во всех блокировщиках и тестируют - измениться что-нибудь много раз.
Может подождать недельку пока устаканиться и они отладят эту систему, а потом уже резануть.

**Comment by Alex-302** [comment]
Вручную же можно. У меня ничего не выскакивает.

**Comment by Embos** [comment]
И вручную тоже. Запилил скрин

![default](https://cloud.githubusercontent.com/assets/9648798/9292584/8d3c1c14-441c-11e5-9daf-081d841f34fe.jpg)

**Comment by Alex-302** [comment]
Очень странно. Можно удалённо глянуть?
Браузер - Фокс?

**Comment by Alex-302** [comment]
Увидел. Они куки пишут. После закрытия не должно появляться.

**Comment by Embos** [comment]
Да, в куки. Проверяю всегда в инкогнито (chrome)
