### ISSUE TITLE
optwear.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#690]
http://www.optwear.ru/forum/sp7-lakomanyakam-interesnie-novinki-t53567.html - например тут

fclmfan / comawhite пароль для входа

https://qcrm.cc/#/customer/1071860

**Comment by Alex-302** [comment]
вроде ничего не блокирует.
Пусть даст ссылку на страницу которая на скрине.

**Comment by Alex-302** [comment]
@@||optwear.ru^$xmlhttprequest,document
надо посмотреть, не разблокировалось ли чего
