### ISSUE TITLE
reduktoren.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#691]
Реклама на сайте пропущена.

**Comment by Alex-302** [comment]
сайт с оч низкой посещаемостью, поэтому только в ЭФ
||allpumps.ru/img/
||reduktoren.ru/img/technoros
||reduktoren.ru/img/tdreduktor
||reduktoren.ru/img/techresurs.swf
reduktoren.ru##table[style="border-style: solid; border-width: 2px; border-color:#333333;"]
reduktoren.ru##table[style="border-style: solid; border-width: 2px; border-color:#ff9933;"]
reduktoren.ru##table[style="border-style: solid; border-width: 1px; border-color:#000066;"]
reduktoren.ru##object[width="170"][height="250"]
reduktoren.ru##table[style="border-style: solid; border-width: 2px; border-color:#FF6600;"]
