### ISSUE TITLE
[false] prosieben.de

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#692]
There is a problem when blocking third-party cookies is enabled in Stealth Mode.

http://www.prosieben.de/tv/2-broke-girls/video/420-staffel-4-episode-20-das-kindische-problem-ganze-folge

http://forum.adguard.com/showthread.php?6048-Early-Access-Adguard-6-0-Alpha-Version&p=58244&viewfull=1#post58244

**Comment by Alex-302** [comment]
Resolved
