### ISSUE TITLE
sf.mail.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#695]
Блокируем строку на сайте:
http://f-picture.net/lfp/s008.radikal.ru/i304/1508/0d/4c0bc3622ec1.jpg/htm - выключен АГ
http://f-picture.net/lfp/s019.radikal.ru/i629/1508/50/eda4b84c8e32.jpg/htm - включен АГ

https://qcrm.cc/#/customer/997164

**Comment by Alex-302** [comment]
Добавил:
@@||mail.ru/dynamic/auth/$document
