### ISSUE TITLE
mmov.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#698]
Блокируем плеер

http://mmov.ru/drama/53716-zhenschina-ne-sklonnaya-k-avantyuram-tv.html например

https://qcrm.cc/#/customer/1073341

**Comment by Alex-302** [comment]
Нужен список фильтров. Ещё надо утонить, исплользует ли он платную подписку. Бесплатные фильмы работают.

**Comment by Alex-302** [comment]
Добавил
@@||tvzavr.ru^$domain=mmov.ru
@@||tvzavr.ru/js/$domain=tvzavr.ru
