### ISSUE TITLE
[android] livejournal app is broken

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#701]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=42393322

**Comment by Alex-302** [comment]
не повторилось. Уточняю конфиг.

**Comment by evgeniy-ADG** [comment]
@Alex-302 MPR-631-91352 вот тут посмотри, пожалуйста, аналогичная пробелма.

**Comment by Alex-302** [comment]
@evgeniy-ADG
повторилось без фильтров. Исключения урлов не помогают. Похоже баг. Передал зазработчику.

**Comment by Alex-302** [comment]
здесь закрываю.
https://github.com/AdguardTeam/AdguardForAndroid/issues/291
