### ISSUE TITLE
freebitco.in

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#703]
Антиадблок на странице, когда логинишься и нажимаешь "ролл".

Логин: fclmfan13@yandex.ru
pass: 111111111111
кошелек: 17fJcnvbbH7ttWCrk9jLSmJWKkZecgraG5

https://qcrm.cc/#/customer/1073799

**Comment by Alex-302** [comment]
Без общих исключений не обойтись.
