### ISSUE TITLE
http://unionpeer.org/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#706]
Реклама например тут: http://unionpeer.org/topic/1172497-naked-weed-report-obnazhenniy-reportazh.html

https://qcrm.cc/#/customer/997164

**Comment by Alex-302** [comment]
поправил

**Comment by Bohdan-SUP** [comment]
Adblocking is detected:
![screen shot 2016-02-15 at 10 15 19 pm](https://cloud.githubusercontent.com/assets/14153331/13059292/c8d6d426-d431-11e5-8109-e490182e9dd8.png)

ZKC-325-33095

**Comment by Alex-302** [comment]
@Bohdan-SUP 
А что у него за браузер? В логе вроде виндовая прога, а на скрине - Сафари.

**Comment by Bohdan-SUP** [comment]
Проблема была на Винде и Маке, я прикрепил скрин с последнего.
Сейчас проблема уже не повторяется.

**Comment by Alex-302** [comment]
Закрываю тогда

**Comment by Alex-302** [comment]
Если проблема решилась сама собой, можешь закрывать, чтоб не висели.
