### ISSUE TITLE
[Android] TrackChecker Mobile

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#711]
Реклама в приложении

http://screencast.com/t/MIECIT4Y

https://qcrm.cc/#/customer/1074516

**Comment by Alex-302** [comment]
рамку не убрать, она встроена. А рекламы быть не должно. Пусть с качественной фильтрацией проверит.

**Comment by Bohdan-SUP** [comment]
http://prntscr.com/an3hsp

**Comment by Alex-302** [comment]
Фейсбучная вроде же. Только с фильтрацией HTTPS блокируется.

**Comment by Alex-302** [comment]
@Bohdan-SUP

**Comment by Bohdan-SUP** [comment]
С https вот так - https://www.dropbox.com/s/wqee5h4um6flk3l/Screenshot_2016-04-03-20-06-54.png?dl=0
Можно плашку снизу удалить?

**Comment by Alex-302** [comment]
Это автор программы так сделал. Не убрать.

**Comment by vgavrish** [comment]
1095491
Реклама в приложении.
Лог время 22.09

<details>

[debug (4).txt](https://github.com/AdguardTeam/AdguardFilters/files/701313/debug.4.txt)

![image](https://cloud.githubusercontent.com/assets/18548949/21885505/b3c9b60e-d8c0-11e6-9e00-3e7fee74666b.png)

2.8.76
 "sslMitmConfiguration" : "{\"certificateInstalledToSystemStorage\":null,\"mitmList\":\"1024 domains\",\"mitmListMode\":\"WHITELIST\"}",
 "proxyMode" : false,
enabledFilterIds" : [ 2, 3, 14, 1, 11, 15 ]
"filteringQuality" : "FULL",

**Comment by Alex-302** [comment]
У себя не замечал рекламу.
Вариантов минимум два:
- устройство было перезагружено, и приложение запустилось раньше защиты Адгарда
- кэш
В логе рекламные запросы заблокированы(гугловые).
Если нажать на баннер, что открывается?

**Comment by CaesarRulezzz** [comment]
googleads

**Comment by Alex-302** [comment]
Какой режим и алгоритм фильтрации?
Судя по логу защита включилась параллельно с запуском приложения. См. коментарий выше.

**Comment by CaesarRulezzz** [comment]
Режим: локальный VPN
Алгоритм: качественный

**Comment by Alex-302** [comment]
Кэш приложения попробуйте очистить, предварительно его остановив.

**Comment by CaesarRulezzz** [comment]
Не помогает.  Через несколько секунд реклама появляется.

**Comment by Alex-302** [comment]
странно. Сам этим приложением пользуюсь - рекламы сто лет не видел.
Может защиту часто выключаете, или устройство перезагружаете?

**Comment by CaesarRulezzz** [comment]
Защита выключактся атоматом только в режиме модема. Устройство я перезагружаю раз в неделю.

**Comment by Alex-302** [comment]
Значит пока в режиме можема, реклама подгрузиться устпевает, или пока идёт переключение в обычный режим и запуск защиты(он не мгноверрый).Если тел с рутом, попробуйте режим прокси с автоматической настройкой.
