### ISSUE TITLE
facebook.com - share does not work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#717]
Maybe Stealth Mode problem?

**Comment by Alex-302** [comment]
Стелс был выключен.

**Comment by Alex-302** [comment]
Stealth Mode is off. The problem is only with Fanboy Annoyances.

**Comment by Alex-302** [comment]
added to foreign.txt
@@||facebook.com/share/share_now_menu/$domain=facebook.com
