### ISSUE TITLE
Ad is not blocked at zuketapaajabhisa.blogspot.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#726]
URL: zuketapaajabhisa.blogspot.com/2015/08/vmware-workstation-pro-1200-build.html
Screen: imgur.com/SzSoYpS
https://qcrm.cc/#/customer/629039

**Comment by Alex-302** [comment]
added
zuketapaajabhisa.blogspot.com##html > body #fanback
