### ISSUE TITLE
Anti-adblok@http://www.needrom.com/

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/ExperimentalFilter#727]
Example:
http://www.needrom.com/download/color2-1i/
http://screencast.com/t/2xBo06ckOzd

**Comment by Alex-302** [comment]
Не повторяется. Нужен список фильтров и версия Адгарда.

**Comment by gshumihin** [comment]
http://screencast.com/t/E3EaugInYH6d
сегодняшняя альфа, Леш.
надо залогиниться

**Comment by Alex-302** [comment]
добавил в английский
@@||cdn.needrom.com/advert*.js
