### ISSUE TITLE
pipec.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#728]
Ads are not blocked on Windows and Android.
http://snag.gy/lEPrW.jpg

**Comment by Alex-302** [comment]
Чисто вроде.

**Comment by Bohdan-SUP** [comment]
Android: imgur.com/7NoKbox

**Comment by Alex-302** [comment]
added
||kd.pipec.ru^
||dev.xyya.net/news/$domain=pipec.ru

**Comment by vbagirov** [comment]
Тогда закрываю.
