### ISSUE TITLE
forum.allnokia.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#729]
The buttons for changing fonts in top right don't work with Ad Blocker enabled.
http://imgur.com/aodd0xP
https://qcrm.cc/#/customer/1078635

**Comment by Alex-302** [comment]
Only disabling oа hiding rules will helps. Not for filters.
@@||forum.allnokia.ru^$elemhide
If user want bigger fonts, we can make the CSS rule.
