### ISSUE TITLE
[Android] Tennis 3D ad

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#731]
Ads are not blocked in Tennis 3D - https://play.google.com/store/apps/details?id=com.cg.tennis
User - http://imgur.com/G3M4qgE
On our side - http://imgur.com/YabxdfU
https://qcrm.cc/#/customer/1075829

**Comment by Alex-302** [comment]
Added to mobile filter
||doodlemobile.com/feature_server/fullScreen/get.php
||doodlemobile.com/feature_server/geo-ip/test.php
