### ISSUE TITLE
pcworld.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#734]
[Windows]: Both main video and more videos on the right do not play.
imgur.com/4JG9Ewq
[Android]: Main video plays, more videos on the bottom - don't.
imgur.com/SgosDf0

https://qcrm.cc/#/customer/1077476

**Comment by Alex-302** [comment]
Added to spyware
@@||b.scorecardresearch.com/r?c2=$domain=pcworld.com
@@||omtrdc.net^$domain=pcworld.com
