### ISSUE TITLE
Facebook comments do not pop-up at mlb.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#738]
http://m.mlb.com/news/article/147870786/matt-harvey-likely-wont-exceed-innings-limit

With Adguard enabled, clicking the comments section (highlighted in red) does nothing:
https://qcrm.cc/message/attachment/699619/Screenshot%202015-09-07%2014.02.07.png
https://qcrm.cc/message/attachment/699618/Screenshot%202015-09-07%2014.03.15.png
https://qcrm.cc/#/customer/1080051

**Comment by Alex-302** [comment]
added
@@||partner.googleadservices.com/gpt/pubads_$domain=mlb.com
@@||googletagservices.com/tag/js/gpt.js$domain=mlb.com
