### ISSUE TITLE
mail.qip.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#741]
Yandex.Browser advert:
http://imgur.com/RESySXM
http://snag.gy/J1zpc.jpg
https://qcrm.cc/#/customer/1073287

**Comment by Alex-302** [comment]
Don't see it. Give me a code of this element of archived page.

**Comment by Alex-302** [comment]
resolved

**Comment by Bohdan-SUP** [comment]
Still relevan for user. Please check the details in KZB-549-84155.

**Comment by Alex-302** [comment]
Added
qip.ru###zfix
