### ISSUE TITLE
Google Photos broken

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#743]
Some AG filter hinders placing of individual photos to albums on Google Photos. If you choose to place a photo to album a window opens but this window is white/empty, you cannot choose from albums. Also when you want to attach a photo in gmail it happens the same.

Adblocker and Browsing security (parental disabled). All AG generic filters + Czech easylist, Norsk adblock list and Fanboy's annoyances.

Stealth Mode: all except miscellaneous

**Comment by Alex-302** [comment]
Can't reproduce with his filters and Stealth Mode options. Maybe the problem was in one of foreign filters.

**Comment by ameshkov** [comment]
Any news on this?

**Comment by Alex-302** [comment]
No. Answered on wilderssecurity.com 
Maybe Adguard injections can boke the site

**Comment by Alex-302** [comment]
The problem was in his User Filter (*.ico)
