### ISSUE TITLE
tvn24.pl with Polish IP

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#744]
Embedded movies are blocked from playing.
Adguard generic filters + AdBlock Polska
http://imgur.com/doXCe2m

**Comment by Alex-302** [comment]
All generic filters?

**Comment by Bohdan-SUP** [comment]
English, Russian, Spyware, AdBlock Polska. Reproduces only with polish IP.

**Comment by Alex-302** [comment]
Don't work with Polish IP and disabled 
http://imagizer.imageshack.com/img673/1486/ygfbWt.png
Do you know other Polish proxy?
