### ISSUE TITLE
[Android] ads + pop-ups at torrentz.eu

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#745]
Ad (it's https site, though) - http://imgur.com/7e4h4Kr
Also, new tabs are opening and closed by Adguard randomly (no exact STR).

**Comment by Alex-302** [comment]
What filters are enabled? Filtering mode is fast or quality?

**Comment by Bohdan-SUP** [comment]
High-quality, VPN.
English, Russian, Spyware, Social Media, Experimental.

**Comment by Alex-302** [comment]
Added
thetechjournal.com,torrents.de,torrentz.ch,torrentz.com,torrentz.eu,torrentz.in,torrentz.li,torrentz.me,torrentz.ph,torrentz.unblockt.com###mgid
Banners are only in search result.
