### ISSUE TITLE
Social media button is not blocked - https://minigames.mail.ru/durak_perevodnoi

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#748]
Screen - http://i.imgur.com/J11NldG.png
Please add new rule to Social media filter.

**Comment by Alex-302** [comment]
Don't see this button without Adguard. Please make a screenshot of code of this element(in development tools)

**Comment by Nick-SUP** [comment]
![screen shot 2015-09-17 at 19 19 53](https://cloud.githubusercontent.com/assets/14073255/9939098/29678570-5d71-11e5-8bfe-6c3c675444cd.png)

**Comment by Alex-302** [comment]
Need more code.
Can you upload saved page?(full html + other files)
