### ISSUE TITLE
Videos don't play - welt.de

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#753]
http://www.welt.de/videos/article146327570/Fluechtling-spuckt-auf-Saudi-Arabien-und-Katar.html
Only preview pic is shown, both ad before video and video itself is blocked.

**Comment by Alex-302** [comment]
Added
welt.de$@$script[tag-content=".adblock"][max-length="1500"]
Video ads will be unbloced. We can't block VAST and now.

**Comment by Alex-302** [comment]
It was possible in Adguard 6
Rules are in experimental filter.
