### ISSUE TITLE
[Android] CM locker screen app ads

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#755]
Ads in https://play.google.com/store/apps/details?id=com.cmcm.locker&hl=en app

https://qcrm.cc/#/customer/1081224

**Comment by Alex-302** [comment]
Похоже он не верное выразился - у него в программе с погодой реклама CM locker

**Comment by Alex-302** [comment]
Нужно описание где увидеть рекламу.

**Comment by Alex-302** [comment]
Blocked by ||adkmob.com^$empty from mobile filter
