### ISSUE TITLE
[Android] Top Eleven Football Manager

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#757]
Server connection peoblem in app while Adguard is on

https://play.google.com/store/apps/details?id=eu.nordeus.topeleven.android

https://qcrm.cc/#/customer/1078854

**Comment by Alex-302** [comment]
Запускается, подключается без проблем.

**Comment by vbagirov** [comment]
Still doesn't work with all the filters disabled.
