### ISSUE TITLE
overclockers.ru - block banner images (see video)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#759]
https://youtu.be/OY7s_8DYOcE

**Comment by Alex-302** [comment]
Can't reproduce in FF with extension.This banner hidden by ###topbanners Maybe pc very slow

**Comment by ameshkov** [comment]
Maybe but anyway it's better to block these banners by URL (or they will be loaded in background even if you don't see them).

**Comment by Alex-302** [comment]
Added
||overclockers.ru/images/citi/
Other images has random urls.
