### ISSUE TITLE
[Extension] http://kolyan.net/

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#766]
http://f4.s.qip.ru/OgbqioMp.png
CZM-592-51110

**Comment by Alex-302** [comment]
Added
||ivi.ru/player/?videoid=*&enableseries=1&autostart=1$third-party
||g-tv.ru/ivi.php?host=$third-party
||allroll.biz^$domain=kolyan.net
||megogo.net/s/video/embed/index.html?video_id=*&autoplay=1$third-party
||rteneme.ru^$third-party
||kolyan.net/cl1.js
