### ISSUE TITLE
speedtest.net - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#769]
speedtest.net###dfp-ab-leaderboard iframe

**Comment by Alex-302** [comment]
This element is empty now:
![](http://imagizer.imageshack.com/img540/2576/WHMFiJ.png)

**Comment by ameshkov** [comment]
It is not empty with US ip:)

**Comment by Alex-302** [comment]
Added, but I don't see it with US VPN
