### ISSUE TITLE
[android] netflix app is broken - cannot watch anything there

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#776]

**Comment by Alex-302** [comment]
Can' finish registration - payment is required

**Comment by ameshkov** [comment]
There is a free trial there, nothing will be charged from the credit card (don't forget to cancel subscription after fixing the bug).

**Comment by Alex-302** [comment]
Registered with US VPN, Adguard in proxy mode - no problems with netflix(filtering is working, ads in browser are blocked)

**Comment by ameshkov** [comment]
Browser? I mean app

**Comment by Alex-302** [comment]
No, I checked filtration in browser, when Adguard Proxy and US VPN on the droid. Then opened the Netflix app.

**Comment by ameshkov** [comment]
waiting for user logs in ticket JKM-539-43556

**Comment by Alex-302** [comment]
ok

**Comment by Alex-302** [comment]
No reply from user.

**Comment by ameshkov** [comment]
Oh, sorry, I forgot. He said the issue is resolved with the latest AG version.
