### ISSUE TITLE
msn.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#779]
Не грузятся видео с msn.com

Напрмиер - http://www.msn.com/ru-ru/video/trending/россия-в-цифрах-отечественный-кинематограф/vi-AAeFP7G?refvid=AAeHadB

UTB-589-40343

**Comment by Alex-302** [comment]
Добавил
@@||rad.msn.com/crossdomain.xml
@@||rad.msn.com/ADSAdClient31.dll$domain=msn.com
