### ISSUE TITLE
[Android] - реклама в приложении "Не коснись белой плитки"

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#781]
https://play.google.com/store/apps/details?id=com.umonistudio.tile&hl=ru
http://snag.gy/m6exu.jpg
CCI-295-21021

**Comment by Alex-302** [comment]
Добавил
||pianotiles2.cmcm.com^$empty
Может потребоваться очистка кэша игры.

**Comment by Alex-302** [comment]
Added
||mi.gdt.qq.com^$empty
Don't forget to check it

**Comment by Kima0384** [comment]
Спасибо, исправлено

**Comment by Kima0384** [comment]
Thanks, fixed
