### ISSUE TITLE
[Android] Ads are not blocked in CM Security Antivirus AppLock

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#782]
https://play.google.com/store/apps/details?id=com.cleanmaster.security&hl=en
http://snag.gy/WlpUe.jpg
CCI-295-21021

**Comment by Alex-302** [comment]
Can't reproduce. Need describe where it is.

**Comment by TPS** [comment]
When using AppLock (which is CM AV's app pattern- or PIN-locking mechanism), it often displays an ad on the lock screen while said pattern or PIN is being entered.

**Comment by vbagirov** [comment]
User doesn't use CM Locker anymore.

**Comment by TPS** [comment]
@vbagirov This bug isn't about CM Locker, #755 is.  But if you're saying #755's fix solved this, then that I gotta test.
