### ISSUE TITLE
http://xalyava.tv/ - branding is not blocked

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#784]
http://xalyava.tv/
http://snag.gy/GAVjp.jpg
NTL-746-70058

**Comment by Alex-302** [comment]
Added
xalyava.tv#$#body { background-color: #efefef!important; background-image:url(/)!important; }
xalyava.tv#$#.page_wrapper { margin: 50px auto 0 auto!important; }
xalyava.tv###banlink
xalyava.tv##a[href^="http://cityadspix.com/click-"]
