### ISSUE TITLE
[Extension] megashara.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#786]
http://snag.gy/CvG5e.jpg
http://f5.s.qip.ru/OgbqioTh.png
XPW-252-38836

**Comment by Alex-302** [comment]
Added:
megashara.com##.brand_click
megashara.com##iframe[src^="http://advkino.ru/"]
megashara.com#$#.brand_bg { padding-top: 0px!important; }
