### ISSUE TITLE
http://www.pmr.md/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#790]
http://www.pmr.md/88225975121205363b99884e40046007/selena_ooo_firma_ost_merkuriy.html - реклама, скриншот есть в комментариях тут: https://blog.adguard.com/ru/windows/adguard-6-first-look.html#comment-2274379941

**Comment by Alex-302** [comment]
Добавил
||tan.pridnestrovie.com/js/displayer.js
