### ISSUE TITLE
Google captcha is broken by "Hide referrer" feature

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#796]
http://kgmoa.org/register

http://forum.adguard.com/showthread.php?7000-quot-Hide-your-referrer-from-third-parties-quot-blocks-google-captcha

**Comment by delixyr** [comment]
I can duplicate this

**Comment by Alex-302** [comment]
Fixed
@@||google.com/recaptcha/api/

**Comment by delixyr** [comment]
Thank you.
