### ISSUE TITLE
office365 stealth mode problem

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#797]
http://forum.adguard.com/showthread.php?7003-Issue-with-Adguard-6-and-accessing-office-365-through-my-College

**Comment by Alex-302** [comment]
There are no free registration. Requested remote access.

**Comment by Bohdan-SUP** [comment]
The issue is still there.
Disabling Stealth Mode or adding login.microsoftonline.com^stealth to User filter helps.

**Comment by Alex-302** [comment]
Added
`@@||login.microsoftonline.com^$stealth`
