### ISSUE TITLE
[Android] Subway surfers

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#798]
Ads in this app: https://play.google.com/store/apps/details?id=com.kiloo.subwaysurf&hl=en

Logs should be available here: ESH-846-98365

**Comment by Alex-302** [comment]
Added
||chartboost.com^$empty
||upsight.com^$empty
||nativex.com^$empty
||ads.mdotm.com^$empty
||hoodrunner.kiloo.com/newonlinesettings.php?platform=android$empty
||engine.fyber.com^$empty
||advertiser.fyber.com^$empty
||engine-dsa.fyber.com^$empty
||vungle.com/*/requestAd
