### ISSUE TITLE
[IE9] Не отображается содержимое страницы

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#801]
kaztorka.org

В IE9 при переходе на страницу раздачи не видно содержимое страницы (в отличие, например, от Chrome)

UPO-524-42559

**Comment by Alex-302** [comment]
Не в сем проверить. Удалённо лучше посмотрю

**Comment by vbagirov** [comment]
Отписал ему про тимвьюер.
