### ISSUE TITLE
nat-geo.ru - image slider is broken

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#810]
http://snag.gy/2VPkw.jpg
http://www.nat-geo.ru/travel/46567-norilsk/#full
BOJ-614-98933

**Comment by Alex-302** [comment]
Added
@@||googletagservices.com/tag/js/gpt.js$domain=nat-geo.ru
@@||partner.googleadservices.com/gpt/pubads_$domain=nat-geo.ru
