### ISSUE TITLE
[Android] BZ Reminder

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#816]
https://play.google.com/store/apps/details?id=com.bzzzapp

Якобы реклама в приложении, повторить не удается.

Лог и скриншот тут: LMR-319-20406

**Comment by Alex-302** [comment]
Пусть сделает лог HTTP запросов после остановки и чистки кэша проги, а то в этом ничего не понятно.

**Comment by vbagirov** [comment]
Запросил.

**Comment by vbagirov** [comment]
Логи в тикете.

**Comment by Alex-302** [comment]
Ничего нет в логе.
Пусть попробует остановить эту прогу, очистить кэш, и с выключенным инетом запустить.

**Comment by gshumihin** [comment]
ПРоблема решилась переустановкой
