### ISSUE TITLE
taker.im - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#819]
http://www.taker.im/phpBB2/topic/136320-paypal-%D0%BF%D0%BE%D0%BB%D0%BD%D1%8B%D0%B9-%D1%80%D0%B5%D1%84%D1%83%D0%BD%D0%B4-%D0%BD%D0%BE-%D0%BD%D0%B5-%D0%B2%D1%81%D0%B5-%D0%B4%D0%B5%D0%BD%D1%8C%D0%B3%D0%B8-%D0%B2%D0%B5%D1%80%D0%BD%D1%83%D0%BB%D0%B8%D1%81%D1%8C-%D1%8D%D1%82%D0%BE-%D0%BA/

**Comment by Alex-302** [comment]
Added
taker.im##.btop > div#logo > a > img
