### ISSUE TITLE
[Mac, Windows] http://maxthon.org.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#820]
Остаются кнопки Facebook на странице, даже при включенном соцфильтре.

ECQ-871-21053

**Comment by Alex-302** [comment]
Это iframe с фейсбука. Там не блокируем соц кнопки.

**Comment by Alex-302** [comment]
Можно передать:
facebook.com##.embeddedLikeButton
facebook.com##a[href^="/sharer/sharer.php?"]
