### ISSUE TITLE
[Android] m.yandex.store.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#823]
Пропущены некоторые изображения на главной странице.

При выборе какого-либо, например, мобильного телефона и переходе на вкладку "Детали" (http://snag.gy/iWuXp.jpg) не работает кнопка "Показать все детали".

HRB-680-76822

**Comment by Alex-302** [comment]
Если включена фильтрация DNS, то пусть добавит такое правило и перегрузит телефон:
@@||awaps.
В фильтры не пойдёт, т.к. слишком общее. В описании опции есть предупреждение на этот счёт.
