### ISSUE TITLE
http://www.thg.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#825]
Фоновая реклама

DUT-406-23980

**Comment by Alex-302** [comment]
добавил
thg.ru##.left_banner
thg.ru##.right_banner
thg.ru###right_adblock
thg.ru###left_adblock
thg.ru#$#body { background: url(/)!important; }
thg.ru#$#div[style^="width:1010px; margin-top: 250px;"] { margin-top: 0px!important; }
