### ISSUE TITLE
ES File Explorer File Manager

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#827]
http://forum.adguard.com/showthread.php?7057-Adguard-%D0%B4%D0%BB%D1%8F-Android-%D0%91%D0%B5%D1%82%D0%B0-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F-2-0-156&p=62587&viewfull=1#post62587

**Comment by Alex-302** [comment]
added to mobile
||glispa.com^$empty
||admobile.me^$empty
