### ISSUE TITLE
ancestry.co.uk and ancestry.com - broken interface

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#830]
ADG on - http://imgur.com/lSNTipK
ADG off - http://imgur.com/UZxtCZb
Happens across all platforms.

**Comment by Alex-302** [comment]
Added
@@||myfamilycominc.tt.omtrdc.net^$domain=ancestry.com|ancestry.co.uk|ancestry.ca|ancestry.de|ancestry.it|ancestry.fr|ancestry.se|ancestry.mx
@@||b.scorecardresearch.com/r$domain=ancestry.com|ancestry.co.uk|ancestry.ca|ancestry.de|ancestry.it|ancestry.fr|ancestry.se|ancestry.mx
Please check this
