### ISSUE TITLE
[Android] - Geometry Dash Lite

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#831]
после завершения уровня, появляется черный баннер, который нельзя закрыть. Без нас там есть реклама и видно кнопку, которой рекламу можно закрыть/свернуть, с нами - лишь черный экран. Приходится выключать игру и запускать заново.
http://snag.gy/pvwAJ.jpg
https://play.google.com/store/apps/details?id=com.robtopx.geometryjumplite

**Comment by Alex-302** [comment]
Пусть попробует по одному
@@||a.applovin.com/2.0/ad?os=
@@||inv-nets.admixer.net/fs/br.aspx
@@||d.applovin.com/device?api_key=
@@||applovin.com^
Ещё нужен лог.

**Comment by Alex-302** [comment]
Приложение будет добавлено в исключения.
