### ISSUE TITLE
Full page advertisement missed on http://filext.com/

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#837]

**Comment by Alex-302** [comment]
Added:
```
filext.com###sc-overlay
filext.com##.dap-wrap
||static.uniblue.com/media/spacecleaner/sc-post-script.min.js$domain=filext.com
```
Without third rule scrolling was broken (when overlay is hidden).

**Comment by TPS** [comment]
@ameshkov @Alex-302 Scrolling is still broken on e.g., http://filext.com/file-extension/TXT (to test properly, hold device in landscape orientation).

**Comment by Alex-302** [comment]
@TPS,

**Comment by TPS** [comment]
@Alex I didn't get the rest of  this.  Did you have a question for me?

On Thu, Oct 15, 2015, 4:39 AM Alex <notifications@github.com> wrote:

> @TPS <https://github.com/TPS>,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AdguardTeam/ExperimentalFilter/issues/837#issuecomment-148318543>
> .
>
-- 

https://zhjf9h10ji3.ting.com/

**Comment by Alex-302** [comment]
@TPS Please check again

**Comment by TPS** [comment]
@Alex-302 Better! Still scroll-locked on 1st page-load, but reloading fixes for all subsequent loads!
