### ISSUE TITLE
[Android] volkskrant.nl

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#838]
При включенном Adguard портится верстка при вертикальном положении планшета/телефона.

**Comment by vbagirov** [comment]
Лог:
[adguard.txt](https://github.com/AdguardTeam/ExperimentalFilter/files/11698/adguard.txt)

**Comment by Alex-302** [comment]
It is broken by Adguard injections
It fixed by partially exclusion, but I don't have this problem
@@||volkskrant.nl^$elemhide,jsinject
