### ISSUE TITLE
[Android] CM Keyboard

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#839]
Link to the app: https://play.google.com/store/apps/details?id=com.cmcm.emoji&hl=en

Adguard blocks access to vocabulraies, backgrounds and such.

Ticket ID MSE-593-90636

**Comment by Alex-302** [comment]
Added
@@||cm.ksmobile.com/api/GetCloudMsgAdv?pkg=com.cmcm.emoji
