### ISSUE TITLE
http://www.macapp.so/super-vectorizer/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#846]
При выключенной фильтрации при выделении текста справа от иконки "проявляются" белые символы на белом фоне. При включенной фильтрации символы пропадают.

Пользователь просит сделать так, чтобы символы не блокировались.

QDH-266-14194

**Comment by Alex-302** [comment]
добавил
macapp.so#$##m2 { height: 5px!important; }
