### ISSUE TITLE
[Android] ai.type keyboard

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#848]
https://play.google.com/store/apps/details?id=com.aitype.android&hl=en

вкл. режим полета, ждем отключения АДГ, включаем, ждем минуту - есть реклама: http://snag.gy/ElAiR.jpg

YQI-339-54227

**Comment by Alex-302** [comment]
добавил
||ads.aitype.net/server/getAdServlet
пусть проверит
