### ISSUE TITLE
mygiftcardsupply.com - broken sign up process

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#849]
STR:
1. Go to mygiftcardsupply.com and add any product to cart.
2. Proceed to checkout.
3. Try to set up new account.
AR: Registration pane won't open.
RAT-147-93069

**Comment by timbojangles** [comment]
Thanks for addressing this issue. Another problem with the checkout page on www.mygiftcardsupply.com is the user is unable to login in some cases as well with Ad Guard's Ad Blocker enabled. Please address this as soon as possible as customers are having trouble buying gift cards from our site.

**Comment by Alex-302** [comment]
@timbojangles 
@Bohdan-SUP 
added
```
@@||mygiftcardsupply.com/remote.php$document
```
Please check two problems with this rule.

**Comment by timbojangles** [comment]
Alex, what do you mean by check two problems with this rule?

**Comment by Alex-302** [comment]
@timbojangles 
1. see the first message
2. "user is unable to login in some cases as well with Ad Guard's Ad Blocker enabled"
I mean you should to add this rule to Adguard user filter.

**Comment by timbojangles** [comment]
It isn't affecting me personally, it is affecting my customers. mygiftcardsupply.com is my store, and I receive several messages per day from customers trying to purchase gift cards saying your software is preventing them from logging into their accounts or completing purchases.

**Comment by Alex-302** [comment]
Ok. The exclusion is added. I hope the problem is fixed.
