### ISSUE TITLE
milli-firka.org

### ISSUE THREAD

**Issue by Fot0n** [AdguardTeam/ExperimentalFilter#851]
У сайта странно организованная навигация — страницы открываются во всплывающих окнах и поэтому их содержимое блокируется.

**Comment by Alex-302** [comment]
добавил:
@@||addthis.com/js/*/addthis_widget.js$domain=milli-firka.org
~milli-firka.org#%#var addthis = { init: function() {}, addEventListener: function() {}, button: function() {}, counter: function() {} };
