### ISSUE TITLE
Broken sign up at BigCommerce sites

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#855]
http://imgur.com/NI724Jq

Reported websites:
mygiftcardsupply.com (https://github.com/AdguardTeam/ExperimentalFilter/issues/849)
cuttingboard.com
icewraps.com
standmodern.com

**Comment by Alex-302** [comment]
Added
@@/remote.php$domain=mygiftcardsupply.com|icewraps.com|cuttingboard.com|standmodern.com,document
Need to check(in shopping cart -> checkout)

**Comment by Bohdan-SUP** [comment]
The rule works fine.
We have more websites in question:
replacementtablelegs.com
FilterElementStore.com

Is there any way to detect the BigCommerce platfom and apply the rule?

**Comment by Alex-302** [comment]
Replaced by generic rule
```
@@/remote.php$document,xmlhttprequest,~third-party
```
