### ISSUE TITLE
http://darkmoney.cc/ - lots of banners missed

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#857]

**Comment by Alex-302** [comment]
Added
darkmoney.cc##body > div[align="center"] > a > img[alt][title]
darkmoney.cc##body > div[style^="margin:"] > div[align="center"] > a > img[alt][title]
darkmoney.cc##body > div[align="center"] > div.page > div[align="center"] > a > img[alt][title]
