### ISSUE TITLE
[Android] spaces.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#858]
Не выгружаются файлы с  spaces.ru, прогресс встает на 13%. 

Логи в тикете: TLP-408-21761

**Comment by Alex-302** [comment]
Проблема не из-за фильтров. Нужно проверить с последней бетой.

**Comment by evgeniy-ADG** [comment]
http://spaces.ru/lenta/?Link_id=370223
![image](https://cloud.githubusercontent.com/assets/15856304/12348736/8be84dce-bb72-11e5-8af5-4c8f4bcf45c6.png)

AOI-170-29042
