### ISSUE TITLE
[Android] DVG download manager

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#862]
https://play.google.com/store/apps/details?id=com.dv.get
http://snag.gy/Al60M.jpg
BBB-760-86381
Disabling ads is a part of a Pro package for the app.

**Comment by Alex-302** [comment]
I need the HTTP log(always for apps).

**Comment by Bohdan-SUP** [comment]
Log provided in QNG-589-72938.

**Comment by Alex-302** [comment]
This ad is built in.
If user have a rooted device, he cen install MyAndroidTools and turn off one activity - AdActivity.
