### ISSUE TITLE
vz.ru - remove ad placeholders

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#863]
http://forum.adguard.com/showthread.php?7171-%D0%A0%D0%B0%D0%B7%D1%8B%D1%81%D0%BA%D0%B8%D0%B2%D0%B0%D1%8E%D1%82%D1%81%D1%8F-%D0%B1%D0%B5%D1%82%D0%B0-%D1%82%D0%B5%D1%81%D1%82%D0%B5%D1%80%D1%8B-%D0%B4%D0%BB%D1%8F-iOS-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B8&p=63750&viewfull=1#post63750

**Comment by Alex-302** [comment]
These rules are in experimental player
```
vz.ru##.fixed_wrap div.shadow
vz.ru##td#right > div.fixed_wrap > div
```

**Comment by Alex-302** [comment]
Moved to Russian
