### ISSUE TITLE
[Android] FotoRus app

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#866]
https://play.google.com/store/apps/details?id=com.wantu.activity&hl=en
http://snag.gy/s3B3q.jpg
The ad leads to app of the same developer.
AUK-776-78403

**Comment by Alex-302** [comment]
Added
@@||vle.aston.ac.uk/branding/themes/

**Comment by Alex-302** [comment]
It is built in,
