### ISSUE TITLE
http://zerkalo-rutor.org/ - missed clickunder

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#867]

**Comment by Alex-302** [comment]
Can't reproduce. It is clean on my end.

**Comment by ameshkov** [comment]
Hm, and now I cannot reproduce it too. Weird.

**Comment by ameshkov** [comment]
This problem is in Firefox 38 ESR
@Alex-302 Could you please check it?

**Comment by ameshkov** [comment]
Ops, no, don't need it. Caused by hiding referrer
