### ISSUE TITLE
[Android] CM's BoostCharge ad

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/ExperimentalFilter#869]
Similar to #755, #782, & #870, [CleanMaster](http://play.google.com/store/apps/details?id=com.cleanmaster.mguard)'s BoostCharge feature also has an advertisement that isn't currently blocked.  This ad usually only comes up a few seconds after the BoostCharge screen is activated on a full-charged, plugged-in device (e.g., first touching phone after overnight charge).

**Comment by Alex-302** [comment]
I don't see ads.
Can you make this? Install Fiddler, configure it like this
http://imagizer.imageshack.com/img903/7727/gnJe5l.jpg
and set in android wifi proxy settings - ip of pc with Fiddler and port(8888 by default)
Then stop app with ads, clear cache and run again. When ad will be loaded,save all sessions
http://imagizer.imageshack.com/img905/8687/vKQJcR.jpg
and send me *.saz file.

**Comment by TPS** [comment]
As [I mentioned elseplace](https://github.com/AdguardTeam/AdguardForAndroid/issues/23#issuecomment-144745988), I haven't had a working PC for a while (hopefully will change soon), so it looks like Fiddler is out.…

Can some combination of internal "Log Everything" +  new PCAP option replicate Fiddler's functionality for the purpose, @Alex-302? @ameshkov?

**Comment by Alex-302** [comment]
You can make the http requests log. Before it, you should stop the app with ads and clear cache.

**Comment by TPS** [comment]
& where do I send it when I have it?  Just fike report through app?

**Comment by Alex-302** [comment]
You can attach it here(below the comment), but you should remove your key from log.

**Comment by TPS** [comment]
@Alex-302 There may be a different cause for this, but I did file ticket# OXG-496-68436.

**Comment by Alex-302** [comment]
Too many trash. Can you stop these apps - org.wahtod.wififixer, com.amazon.venezia, then clean Adguard's cache and make a new log?

**Comment by TPS** [comment]
Can't do anything about com.amazon.venezia — that's the Amazon Appstore, & that's what AdGuard is installed through, so that will reactive regularly even if killed.  I _could_ disable org.wahtod.wififixer, but you may not get anything at all — my phone is often at the edge of a wifi signal, & that's what keeps it up.

Can't you just filter these logs? Else I'll just have to retry in about 14 hours, & resend in about 24 hours.

**Comment by Alex-302** [comment]
Please try these rules:
||up.cm.ksmobile.com/cleanmaster/controller/controller.php
||up.cm.ksmobile.com/cleanmaster//controller/CloudCfg.php
||up.cm.ksmobile.com/cleanmaster/controller/config//main_cfg.ini
||n.m.ksmobile.com/news/fresh
||dl.sj.ijinshan.com/duba/updateintl/version_data.ini
||zj.dcys.ksmobile.com/data/config_cmsecurity_version.json
||up.cm.ksmobile.com/cleanmaster/version_data2.php
||cb.ksmobile.com/trend?mcc=310
You can save to TXT on SD card and import ti User Filter.

**Comment by TPS** [comment]
Copy/paste work?  I'll try this tonight. ☺ Thanks.

**Comment by ameshkov** [comment]
I remember once I was looking into all these CM apps and what information do they get from the server.

Don't you think it would be better simply to ban this app in the Firewall?
Anyway it does not need net access to work.

**Comment by TPS** [comment]
Unfortunately, I thought of that, too, then realized internal virus checker definitions & weather information (_that_'s some wide scope for an app, no? ;)  require 'Net connection.… :disappointed:

**Comment by ameshkov** [comment]
As I understand CM Antivirus is a separate app?

**Comment by TPS** [comment]
CM AV _is_ separate, with some additional functions, but CM itself has a builtin AV, also.

@Alex-302 The rules from above seem not to help, but I think the issue is more https://github.com/AdguardTeam/AdguardForAndroid/issues/2 than a rule problem — I seem not to get the ads here or in #870 if I can confirm the VPN is live.  This is difficult, as I cannot always catch what's happening behind a lockscreen!

**Comment by Alex-302** [comment]
Their ads are loaded from
https://ws.ksmobile.net/api/GetCloudMsgAdv?lan=ru_RU&apkversion=1043&channelid=null&osversion=5.1.1&mcc=250&device=D5503&resolution=1184*720&mem_size=1739&pkg=cmcm.weather.asus&version=1&aid=f6dcb2781bccd23f
We can't block it until Adguard not support HTTPS

**Comment by Alex-302** [comment]
Added
||ksmobile.net/api/GetCloudMsgAdv$empty
