### ISSUE TITLE
Broken purchase process - csgo.party

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#875]
1) Go to site http://csgo.party/
2) Click on button http://prntscr.com/8uxfcd
3) Put this link in window https://steamcommunity.com/tradeoffer/new/?partner=246685307&token=xQZm0W0v
4) And click on button http://prntscr.com/8uxfyy
Error on site - http://prntscr.com/8uxd8v

VUV-761-54325

**Comment by Alex-302** [comment]
Added
@@||csgo.party/app/public/js/advert.js
@@||csgo.party/page/buy/$document,xmlhttprequest
