### ISSUE TITLE
[Android] controversialtimes.com - content blocked

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#876]
controversialtimes.com
Adguard off - http://imgur.com/XqOSbPW
Adguard on - http://imgur.com/Tc3B293
The issue is with English filter.
JYV-650-54364

**Comment by Alex-302** [comment]
Try this with his filters:
controversialtimes.com#@#.header-ad

**Comment by Alex-302** [comment]
E
