### ISSUE TITLE
Invalid option in the rule

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#877]
WARNING, AdguardSvc, 3, 28.10.2015 1:52:05.615, Unknown option ~blitzkrieg.com|~coca-cola.ru|~coca-cola.ua|~halens.ru|~interneturok.ru|~kaspersky.com|~mail.ru|~nowystyl.com.ua|~workle.ru|~zyxel.ru in rule /banner_$third-party,domain=~patra.com,~blitzkrieg.com|~coca-cola.ru|~coca-cola.ua|~halens.ru|~interneturok.ru|~kaspersky.com|~mail.ru|~nowystyl.com.ua|~workle.ru|~zyxel.ru

**Comment by Alex-302** [comment]
Fixed.
