### ISSUE TITLE
[Android] Не загружает посты в приложении Livejournal

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#879]
https://play.google.com/store/apps/details?id=com.livejournal.android

https://qcrm.cc/message/attachment/726664/Screenshot_2015-10-21-16-27-49.png - скриншот

CKM-330-40143

**Comment by Alex-302** [comment]
Отклыл баг в разделе Android
Здесь закрываю

**Comment by Alex-302** [comment]
@vbagirov 
попроси юзера установить новую бету и проверить
