### ISSUE TITLE
https://kat.cr/ - broken interface

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#881]
https://kat.cr/marvel-s-agents-of-s-h-i-e-l-d-tv16547/
http://s17.postimg.org/5pqdkcdbz/Image_1.png
http://s17.postimg.org/t19vvp27z/Image_2.png
KDE-361-32421

**Comment by Alex-302** [comment]
Added
kat.cr,katproxy.is,kickass.unblocked.la,kickassto.co,thekat.tv#@#div:first-child > [onclick]
