### ISSUE TITLE
[Android] FS Videobox

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#882]
Скачать можно, например, тут: http://www.softportal.com/software-38310-fs-videobox.html

В режиме VPN при просмотре сериалов через FS Videobox иногда выбрасывает на 
середине серии и перекидывает на следующую. Проблема наблюдается при использовании "качественного" режима фильтрации, после переключения на "быстрый" не повторяется.

UDZ-178-34076

**Comment by Alex-302** [comment]
У меня никогда с ним проблем не было.
