### ISSUE TITLE
"puzzles for friends" won't load

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#884]
https://apps.facebook.com/puzzwithfriends/list.php
http://snag.gy/GgAFZ.jpg
ZVL-341-85181

**Comment by Alex-302** [comment]
у меня нормально открывается. У вас повторилось?

**Comment by vbagirov** [comment]
Повторилось у первой линии поддержки - скриншот от них как раз.

**Comment by gshumihin** [comment]
у меня тож норм все работает

**Comment by Bohdan-SUP** [comment]
Больше не повторяется.
