### ISSUE TITLE
shz.de

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#891]
For example: shz.de/hamburg/alle-fluechtlingszelte-in-hamburg-sind-beheizbar-id10966016.html

Screenshot: http://snag.gy/x2FqI.jpg

Unblocked ads; can't reproduce on our side.

OMK-241-77958

**Comment by Alex-302** [comment]
Added
shz.de#%#window.uabInject = function() {};

**Comment by vbagirov** [comment]
These ads are also shown on other websites such as rp-online.de and others.

Is it possible to block all instances of this ad?

**Comment by Alex-302** [comment]
rp-online.de#%#window.uabInject = function() {};
