### ISSUE TITLE
[Android] - Cookie messages not blocked

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#897]
m.quoka.de
www.golem.de
www.mein-schoener-garten.de
www.shpock.com
www.med1.de

HNE-447-77797

**Comment by Alex-302** [comment]
Added to Experimental filter:
quoka.de###msgCookie
mein-schoener-garten.de,med1.de##.cc_banner-wrapper
shpock.com###cookie-modal
golem.de###golem-cookie-accept
User should to enable it.

**Comment by M-w-N** [comment]
Enabled experimental filter and updated adguard. 
Opend chrome on my mobile and test http://www.mein-schoener-garten.de
Cookie banner still there 
Reloaded page
Cookie banner still there 
Other sites i didn't check

**Comment by Alex-302** [comment]
@M-w-N, this filter still not updated... Please, wait 1-2 hours.

**Comment by M-w-N** [comment]
http://www.the-area51.com

**Comment by M-w-N** [comment]
http://www.slatedroid.com/

**Comment by M-w-N** [comment]
On chrome mobile, with experimental adguard filters:
www.pc-magazin.de
www.golem.de

**Comment by Alex-302** [comment]
http://www.the-area51.com, http://www.slatedroid.com/ - I don't see the cookie notification

www.pc-magazin.de
added to EF
pc-magazin.de##.cc_banner-wrapper

http://www.slatedroid.com/ - I see only their own app's banner
added to EF
slatedroid.com###tt_mobile_banner
slatedroid.com###banner_div_empty

www.golem.de - is clean on my phone. What browser are you using?

**Comment by M-w-N** [comment]
I'm using Chrome browser v46.0.2490.76

Gesendet mit BlueMail

**Comment by Alex-302** [comment]
Please update filters and check again.

**Comment by M-w-N** [comment]
Adguard updated on android chrome. 

Cookie nag still there:
m.quoka.de
www.golem.de
www.mein-schoener-garten.de
www.shpock.com
http://www.med1.de
http://www.slatedroid.com
http://www.the-area51.com

No more cookie nag:
forum.frag-mutti.de
green-24.de

**Comment by M-w-N** [comment]
Cookie Nag android chrome 
http://decuro.de

**Comment by M-w-N** [comment]
m.chip.de
www.chip.de

**Comment by M-w-N** [comment]
http://sourceforge.net

**Comment by Alex-302** [comment]
m.quoka.de,golem.de,mein-schoener-garten.de,med1.de,slatedroid.com,the-area51.com,green-24.de - don't see
added:
frag-mutti.de###cookie-notice
