### ISSUE TITLE
com.belous.v.yapik - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#900]
https://play.google.com/store/apps/details?id=com.belous.v.yapik

http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=44310484

**Comment by Alex-302** [comment]
Sended to user
@@||api.appodeal.com/get
||api.appodeal.com/stats
||api.appodeal.com/show
||amazonaws.com/appodeal-campaign-images/$empty
||startappservice.com/InApp/$empty
