### ISSUE TITLE
[Android] - Flashlight

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#902]
https://play.google.com/store/apps/details?id=com.surpax.ledflashlight.panel
http://snag.gy/XPP0M.jpg
CIW-233-63346

**Comment by Alex-302** [comment]
Лог в данном случае бесполезен, т.к. запросов в нём нет.
Если в приложениях реклама, то сразу просите чистить кэш проги и лог HTTP-запросов, и очень желательно время запуска приложения.

**Comment by vbagirov** [comment]
CIW-233-63346 HTTP логи

**Comment by Alex-302** [comment]
он лог не прикрепил
и время пусть тоже указывает, лог слишком большой

**Comment by vbagirov** [comment]
Запросил новый лог и время появления рекламы.

**Comment by Alex-302** [comment]
реклама с фейсбука рузится.Пока закрываю, до поддержки https
