### ISSUE TITLE
dreamfilmhd.bz

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#904]
dreamfilmhd.bz
http://imgur.com/a/EE2Mm

ZAY-274-64484

**Comment by Alex-302** [comment]
added to Eng
||dreamvtt.com/imagehost/data/uploads/users/d6e25263-8a53-42c2-bb43-12de0e9b8bb9/117026338.gif
dreamfilmhd.bz##a[href^="http://casino-x.com/"]
||dreamvtt.com/imagehost/data/uploads/users/d6e25263-8a53-42c2-bb43-12de0e9b8bb9/114115514.jpg
dreamfilmhd.bz##a[href^="http://www.hagopro.se"]

**Comment by ameshkov** [comment]
Again a popunder there

**Comment by Alex-302** [comment]
Added to English filter:
```
||cdn.drnxs.com/js/gp.min.js
```
