### ISSUE TITLE
Broken links - www.sueddeutsche.de

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#906]
Issue with Spyware filter.
http://snag.gy/rzvZO.jpg

1. Enable adguard, go to http://www.sueddeutsche.de/
2. Move the cursor to any of the menu link like Politik Wirtschaft and so on
3. Click on any link in dropdown menu - nothing happens
4. Disable adguard and do the same - it works fine

LLI-635-66199

**Comment by Alex-302** [comment]
added to German
@@||de.sitestat.com/sueddeutsche/sueddeutsche/*$domain=sueddeutsche.de
to social
sueddeutsche.de##li[data-linktrack^="onclick.sharingbar"]
sueddeutsche.de###article-sidebar-action-twitter
