### ISSUE TITLE
radiovtomske.ru

### ISSUE THREAD

**Issue by Fot0n** [AdguardTeam/ExperimentalFilter#907]
Определяет использование Adguard'а и перенаправляет на заглушку с требованием отключить.

**Comment by Alex-302** [comment]
добавил
@@||radiovtomske.ru/js/advert.js

**Comment by Fot0n** [comment]
Блин, сайт изменил домен. :) Видимо, хотят занять нишу питер.фм и москва.фм
Теперь radio-archive.ru
