### ISSUE TITLE
[Adguard for iOS] market.yandex.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#910]
При включённой блокировке некорректно работает Яндекс.Маркет (мобильная версия сайта). В частности не работает кнопка "показать все детали" на вкладке "Детали" какого-либо товара. Также со вкладкой "цены". При выборе варианта сортировки ничего не происходит. Лишь анимация бесконечной загрузки фильтра.

RRO-793-24181

**Comment by Alex-302** [comment]
возможно проблема с блокировкой поддомена **awaps.**
В дроиде такие же симптомы, когда блокировался при фильтрации DNS.

**Comment by vbagirov** [comment]
Включены следующие фильтры:
 - Английский фильтр;
 - Фильтр счетчиков и систем аналитики;
 - Фильтр виджетов социальных сетей;
 - Русский фильтр;
 - Фильтр мобильной рекламы;
 - Фильтр для мобильного Safari.

**Comment by Alex-302** [comment]
Не повторяется, но я на Маке проверял в мобильном режиме

**Comment by ameshkov** [comment]
Надо будет проверить еще раз с мобильными фильтрами. Расширение сейчас использует полные фильтры. Но скоро там появится галка "Использовать мобильные фильтры".

**Comment by Alex-302** [comment]
Повторилось/ Помогло исключение
```
@@||mc.yandex.ru/metrika/watch.js$domain=m.market.yandex.ru
```
Проверить бы на реальном устройстве,

**Comment by ameshkov** [comment]
Да нормально, добавляй в сафари исключения

**Comment by Alex-302** [comment]
Добавил.
