### ISSUE TITLE
[NSFW] dreamfilmhd.bz - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#914]

**Comment by Alex-302** [comment]
added
||dreamfilmhd.org/0QoifjU.png
dreamfilmhd.org##a[href^="http://cdn.adsrvmedia.net/"]

**Comment by ameshkov** [comment]
There is a popup there, take a look:
![dream](https://cloud.githubusercontent.com/assets/5947035/11227328/5f7824c6-8d96-11e5-95fe-cce85cfb67a7.jpg)

**Comment by ameshkov** [comment]
Also a banner:
![screenshot_2015-11-17-22-53-44](https://cloud.githubusercontent.com/assets/5947035/11227349/82a53cfe-8d96-11e5-8aed-2e1357762ec8.png)

**Comment by Alex-302** [comment]
Added
||dreamvtt.com/imagehost/data/uploads/users/d6e25263-8a53-42c2-bb43-12de0e9b8bb9/326470942.gif
dreamfilmhd.bz##a[href^="http://re-directme.com/"]

Clickunder is in this script
http://vkpass.com/token/bdrxwnlzfjpq/vklhash/Pw7Iy8MztzzwN6xh7nOhf6o80rxCAYIhP8xiQFZ2fGVY72GssVNwZRlCNVvSYV5aJLrNFHAIE63P7rWPRxudpg==
<script>window.setTimeout(function(){ document.body.appendChild(document.createElement("img")).src="http://goo.gl/jyOr2Q" },1E3)</script>

**Comment by ameshkov** [comment]
And what about "swf" file, what is it?

**Comment by Alex-302** [comment]
Tried to block it, but no result.

**Comment by ameshkov** [comment]
```
||dreamvtt.com/imagehost/data/uploads/users/d6e25263-8a53-42c2-bb43-12de0e9b8bb9/326470942.gif
```

Seems pretty bad, can't you do it with CSS?

**Comment by Alex-302** [comment]
It is hidden by
dreamfilmhd.bz##a[href^="http://re-directme.com/"]
Should I remove the URL rule?

**Comment by ameshkov** [comment]
Yep

**Comment by Alex-302** [comment]
Done

**Comment by ameshkov** [comment]
Two more rules:
```
||dreamfilmhd.bz/amr.html$domain=dreamfilmhd.bz
||vkpass.com/palavro/*.js
```

**Comment by Alex-302** [comment]
added

**Comment by ameshkov** [comment]
Still some banners missing.

Android:
![e4a9d0f6-dae6-4de4-9f08-cc0a591b3315](https://cloud.githubusercontent.com/assets/5947035/11671459/960dddc6-9e19-11e5-9e93-3cc059e4fb2f.png)


Desktop (seems that player is broken):
![pop up](https://cloud.githubusercontent.com/assets/5947035/11671465/a56886ea-9e19-11e5-8c40-a156f923df36.jpg)

**Comment by Alex-302** [comment]
Added to English
```
dreamfilmhd.bz##a[href^="http://removeadsnow.info/"]
```
The player is not broken on my side, and no ads there
http://imagizer.imageshack.com/img907/3825/TzQSqz.jpg

**Comment by ameshkov** [comment]
Seems all ads have returned now

**Comment by ameshkov** [comment]
So?

**Comment by Alex-302** [comment]
added to English
```
dreamfilmhd.bz##a[rel="nofollow"] > img
dreamfilmhd.bz##a[href^="http://bit.ly/"]
```

**Comment by ameshkov** [comment]
And here we are again, new ad script:
http://cdn.trafficbee.com/tags/dfap.js

**Comment by Alex-302** [comment]
Added.

**Comment by ameshkov** [comment]
One more popup script:
http://dreamfilmhd.bz/testpop3/sikko3.js

**Comment by Alex-302** [comment]
Added
```
||dreamfilmhd.bz/testpop
```
but I don't get popups.
