### ISSUE TITLE
[Adguard for iOS] ozon.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#917]
На сайте Озон отсутствуют изображения товаров.

IOS-243-45262

**Comment by Bohdan-SUP** [comment]
Теперь блокируем все содержимое
http://snag.gy/DYE4U.jpg

**Comment by ameshkov** [comment]
Даже сейчас? Проверил на ipad'е, все хорошо вроде

**Comment by Alex-302** [comment]
Повторилось на
http://www.ozon.ru/catalog/1133763/
Добавил в фильтр Сафари
```
@@||bundle.ozon.ru/ozon/$script,domain=ozon.ru
```
Проверьте у себя
