### ISSUE TITLE
[Windows] vk.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#922]
Пользователь хочет скрыть некоторые элементы на vk.com, но они появляются снова при переходе на другие вкладки. Видео бага тут: 
https://www.youtube.com/watch?v=FAIv1ckaqfA&feature=youtu.be

Правило vk.com#$#html > body > div#utils > div#chat_onl_wrap { right: 9000px;!important; } не помогло

Логи и другие подробности в тикете YPV-592-47611

**Comment by Alex-302** [comment]
vk.com#%#AG_onLoad(function() { window.AG_removeElementBySelector('div[id="chat_onl_wrap"] '); });
