### ISSUE TITLE
[iOS] baskino.club | coldfilm.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#923]
Видео не воспроизводится / воспроизводится только в низшем качестве. На Windows повторить не удалось. 

JLD-598-22681

**Comment by Alex-302** [comment]
Повторяется в Винде с расширением.
Для первого добавил
@@||hdserials.tv/upload/banners/banner.jpg

**Comment by Alex-302** [comment]
coldfilm.ru - пусть включает нужные фильтры по одному с проверкой, и напишет при включении какого появляется проблема.

**Comment by Alex-302** [comment]
@vbagirov Есть новости?

**Comment by evgeniy-ADG** [comment]
QTM-937-88684 - baskino

**Comment by Alex-302** [comment]
@@||moonwalk.cc/video/*/iframe$elemhide
||securewebboard.com^$third-party
||skycdnhost.com^$third-party
