### ISSUE TITLE
[Android] Broken login - https://pgu.mos.ru/ru/auth/

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#926]
http://snag.gy/RQMbx.jpg
http://snag.gy/dpOsQ.jpg
FRO-659-58104

**Comment by Alex-302** [comment]
у меня открывается.
Проверь
@@||mos.ru/ru/auth/

**Comment by Bohdan-SUP** [comment]
У меня снова открывается. Ждем ответа от пользователя.

**Comment by Bohdan-SUP** [comment]
Логи тут:
LOI-619-53212

**Comment by Alex-302** [comment]
там же на сертификат ругается. Пусть без фильтров проверит.

**Comment by evgeniy-ADG** [comment]
Вопрос актуален, у пользователя Мегафон.

**Comment by Alex-302** [comment]
>Пусть без фильтров проверит.
нужен результат этой проверки в режиме прокси(очень желательно) и VPN.

**Comment by evgeniy-ADG** [comment]
Попросил, ждем.

**Comment by Alex-302** [comment]
Вообще мне кажется не в Адгарде дело. Браузер ругается на сертификат, а Адгард для дроида сертификаты пока не умеет менять

**Comment by Alex-302** [comment]
У нас авторизация на этом сайте проходит без проблем.

**Comment by evgeniy-ADG** [comment]
Первый скрин - мой, сейчас сменил прошивку - и всё ок, больше проблему воспроизвести не могу, ни с VPN, ни proxy.

**Comment by Alex-302** [comment]
Закрою пока. У нас ни разу не повторилось.
