### ISSUE TITLE
[Android] Catch-up TV issues

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#928]
Following apps don't work with Adguard enabled:

- 9Jumpin - https://play.google.com/store/apps/details?id=au.com.mi9.jumpin.app
- tenplay - https://play.google.com/store/apps/details?id=au.com.tenplay
- PLUS7 - https://play.google.com/store/apps/details?id=com.yahoo.mobile.client.android.plus7

^ In these apps video just loads forever and never actually starts.

- SBS On Demand - https://play.google.com/store/apps/details?id=com.sbs.ondemand.android

^ When a video is first played, it shows the last few seconds of the video then ends. When you play the video again, it then starts from the beginning. However, some videos have ads in the middle, which can be seen by the little yellow marker intervals in the timeline. When it hits the first yellow marker (first ad spot), the video then seems to have the same issue as the others above, in that it loads forever and never plays again.

Originally from forum thread:
http://forum.adguard.com/showthread.php?7632

**Comment by Alex-302** [comment]
Replied on the forum.

**Comment by evgeniy-ADG** [comment]
JAU-345-76643

[state.txt](https://github.com/AdguardTeam/ExperimentalFilter/files/66565/state.txt)
[debug.txt](https://github.com/AdguardTeam/ExperimentalFilter/files/66566/debug.txt)

**Comment by Alex-302** [comment]
Replied

**Comment by Alex-302** [comment]
closed here
