### ISSUE TITLE
[Android] Приложение "Дребеденьги"

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#930]
https://play.google.com/store/apps/details?id=ru.surfstudio.personalfinance&hl=ru

При включенном Adguard синхронизация в приложении крайне тормозит. С выключенной защитой проходит за 1 секунду. 

Лог в тикете: TWY-263-12683

**Comment by Alex-302** [comment]
У меня мгновенно синхронизирует.

**Comment by vbagirov** [comment]
Запросил уточнение у пользователя.

**Comment by vbagirov** [comment]
Отключение фильтров с включенной защитой не решает проблему.

**Comment by Alex-302** [comment]
@vbagirov Тогда на Рому наверное перевешивай
