### ISSUE TITLE
https://vk.com/horoscoper

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#933]
Пользователь не хочет блокировать рекламу в iFrame-приложениях
Например, https://vk.com/horoscoper
http://snag.gy/8RUHY.jpg
GEY-575-48890

**Comment by Alex-302** [comment]
@@||talon.by/squeeze/
@@||uoot.ru/apps/$document
@@||vk.com/ads_$document
