### ISSUE TITLE
Ad on spiegel.de 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#935]
The banner appears on the top of the screen after the site is fully loaded.

http://snag.gy/AePV0.jpg
http://snag.gy/CgW2D.jpg

QAE-404-19454
BDA-948-91167

**Comment by Alex-302** [comment]
added to German
spiegel.de##div#wrapper > div#spColumnAd+div[id][class] > img
spiegel.de##div#spOasTop+div[class] > div[id] > img

**Comment by evgeniy-ADG** [comment]
The issue still persists: http://snag.gy/ON6n0.jpg

**Comment by Alex-302** [comment]
Check this rule:
spiegel.de#%#window.uabInject = function() {};
Added to German.

**Comment by evgeniy-ADG** [comment]
The customer will check if it helps. How it looks at my end after updating German filter: http://snag.gy/uJU4e.jpg

**Comment by Alex-302** [comment]
You should to add that rule.

**Comment by evgeniy-ADG** [comment]
Works fine with it: http://snag.gy/Ek1dT.jpg
