### ISSUE TITLE
Adguard hangs after clicking on "install the office insider build now"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#941]
https://products.office.com/en-us/office-insider

http://forum.adguard.com/showthread.php?7406-Adguard-%D0%B4%D0%BB%D1%8F-Windows-%D0%91%D0%B5%D1%82%D0%B0-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F-6-0-84-487&p=66131&viewfull=1#post66131

**Comment by Alex-302** [comment]
This rules should help:
```
@@||stores.office.com/authredir
@@||stores.office.com/myaccount/advancedinstalls.aspx
@@||login.live.com/logout.srf
@@||login.live.com/ppsecure/post.srf
```

**Comment by Alex-302** [comment]
The user has confirmed fixing.
Added to English filter.
