### ISSUE TITLE
http://ardano.ru/ is distorted by Adguard extension

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#942]
When the browser extension is on, the site ardano.ru looks distorted in the top of the screen

adg on  http://snag.gy/KRnVF.jpg http://snag.gy/CEMQ0.jpg
adg off  http://snag.gy/yIL4F.jpg

TICKET ID: SLI-710-76700

**Comment by Alex-302** [comment]
Added
ardano.ru#@#img[width="728"][height="90"]
