### ISSUE TITLE
http://lixty.net - не работает радио

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#943]
При включённом Adguard сайт выглядит след. образом: http://snag.gy/YOIe8.jpg
Радио начинает воспроизводиться сразу после отключения фильтрации: http://snag.gy/C8V4p.jpg

TICKET ID VTT-887-74212

**Comment by Alex-302** [comment]
Added to Social filter
@@||yastatic.net/share/share.js$domain=lixty.net
