### ISSUE TITLE
[Android] Google privacy settings page won't open

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#944]
http://snag.gy/VZT5v.jpg
http://snag.gy/exMRd.jpg
KTP-233-36725

**Comment by Alex-302** [comment]
User can add this rules to the User Filter
```
@@||googleads.g.doubleclick.net^
@@||ads.youtube.com^
```
We can't add them to main filter until HTTPS support will not implemented
