### ISSUE TITLE
[Android] Dead Trigger 2

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#945]
https://play.google.com/store/apps/details?id=com.madfingergames.deadtrigger2&hl=ru

Пользователь наблюдал темный экран при входе в приложение при включенном Adguard. Затем характер проблемы изменился - теперь происходит выход из аккаунта.

CCX-823-86468

**Comment by Alex-302** [comment]
нужно узнать чем он авторизуется. Я зарегался, прошёл пару уровней, закрыл-открыл - всё нормально.

**Comment by vbagirov** [comment]
Запросил.

**Comment by Alex-302** [comment]
Есть новости?

**Comment by Alex-302** [comment]
@vbagirov пока закрываю
