### ISSUE TITLE
Пустой баннер на http://www.prof-police.ru/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#947]
На страницах сайта, например, http://www.prof-police.ru/gu-mvd-rossii-po-g-moskve/1909-spisok-voprosov-i-predlozhenij-sotrudnikov-k-a-i-yakuninu.html, появляется белый баннер

Пример: http://snag.gy/vRlO4.jpg

TICKET ID
YBN-668-71969

**Comment by Alex-302** [comment]
добавил
prof-police.ru##.jPanelModule
