### ISSUE TITLE
ok.ru is broken by stealth mode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#948]
https://yadi.sk/i/TJ-wIdNAkc9Jo

**Comment by Alex-302** [comment]
For test:
@@||mycdn.me^$domain=ok.ru
@@||odnoklassniki.ru/get$domain=ok.ru
@@||wmf1.ok.ru/init
@@||ok.ru/web-api/music/conf

**Comment by ameshkov** [comment]
Why so many?

**Comment by ameshkov** [comment]
Also here is the source complaint:
http://forum.adguard.com/showthread.php?7728-Adguard-%D0%B4%D0%BB%D1%8F-Windows-%D0%91%D0%B5%D1%82%D0%B0-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F-6-0-103-580&p=66480&viewfull=1#post66480

**Comment by Alex-302** [comment]
Sent to user:
```
@@||odnoklassniki.ru/get$domain=ok.ru
@@||ok.ru/web-api/music/conf
```

**Comment by Alex-302** [comment]
Added to English.
