### ISSUE TITLE
 http://f-picture.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#951]
http://f-picture.net/fp/1de161c868fe4adca8cbadf3c57185a7
http://f6.s.qip.ru/OgbqipQ9.png
NPT-934-13659

**Comment by Alex-302** [comment]
Added
||9fine.ru^$third-party
/Content/ClientsNews/$domain=f-picture.net|radical-foto.ru|radikal.cc|radikal.ru
