### ISSUE TITLE
Comments won't load on http://footballhd.ru/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#952]
http://footballhd.ru/liga4emp/117892-shahter-malme-obzor-matcha-03112015.html

Aduard on: http://snag.gy/oeyP8.jpg
Adguard off: http://snag.gy/n664G.jpg

TICKET ID
ARZ-328-94413

**Comment by Alex-302** [comment]
added
@@||footballhd.ru/engine/ajax/$document
