### ISSUE TITLE
Ad on http://www.sueddeutsche.de/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#957]
http://snag.gy/Yo6ON.jpg

It seems to be a new ad technique that other German websites are using as well, https://github.com/AdguardTeam/ExperimentalFilter/issues/935

TICKET ID
BDA-948-91167

**Comment by Alex-302** [comment]
added
@@||sueddeutsche.de^$elemhide
