### ISSUE TITLE
Фоновая реклама на http://filmix.net/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#958]
Проблема аналогична, те же баннеры, что и в https://github.com/AdguardTeam/ExperimentalFilter/issues/954

1: http://snag.gy/BI6l7.jpg
2.: http://snag.gy/stPf9.jpg

ALS-330-43026

**Comment by Alex-302** [comment]
added
||berdent.com/sys/$third-party
||pentoch.com/sys/$third-party
