### ISSUE TITLE
[Android] redtube.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#960]
Ads on mobile redtube website. It seems that about 50% of the time when clicking next to go from page 1 to 2 on redtube, a new tab will open that will render an ad. 

Also happens when clicking on video - new tab opens. Doesn't happen every time after first one, unless you clear cache.

RJN-319-60152

**Comment by Alex-302** [comment]
Added
||slopeaota.com^$popup,domain=redtube.com
