### ISSUE TITLE
Pop-ups on http://www.tvmuse.com/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#962]
A pop-up appears when you click the link on tvmuse.com: http://snag.gy/jMMPI.jpg
We reproduced it on our side, it pops in a random way.

TICKET ID
WEV-976-51650

**Comment by Alex-302** [comment]
I don't see popups. I need the filters list.

**Comment by evgeniy-ADG** [comment]
Will update as soon as I receive the list from the customer.

**Comment by evgeniy-ADG** [comment]
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0
ID=2 Name="English filter" Version=1.0.71.60
ID=3 Name="Spyware filter" Version=1.0.3.85
ID Name="Filter for useful ads" Version=1.0.0.72
ID1 Name="EasyList" Version=1.0.47.92
ID5 Name="EasyList Czech and Slovak" Version=1.0.0.46
ID9 Name="EasyList Italy" Version=1.0.47.84
ID8 Name="EasyPrivacy" Version=1.0.47.79
ID9 Name="Icelandic ABP List" Version=1.0.0.18
ID 7 Name="Adblock Warning Removal List" Version=1.0.47.97
[state (23).txt](https://github.com/AdguardTeam/ExperimentalFilter/files/43850/state.23.txt)
<img width="1440" alt="screen shot 2015-11-25 at 1 08 48 am" src="https://cloud.githubusercontent.com/assets/15856304/11397984/2bd07e70-9386-11e5-8d84-510c50b7dd8a.png">

**Comment by evgeniy-ADG** [comment]
Any news here? it's been awhile.

**Comment by Alex-302** [comment]
I will check it again.

**Comment by Alex-302** [comment]
Added to English
||xaxoro.com^$third-party
Checked on Win.
Please check it on Mac.

**Comment by evgeniy-ADG** [comment]
@Bohdan-SUP could you check it on Mac?

**Comment by Bohdan-SUP** [comment]
Yes, all good.
