### ISSUE TITLE
adf.ly detects adguard

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#963]
http://adf.ly/1SD2dC

**Comment by Alex-302** [comment]
This antiblock doesn't prevent download.

**Comment by Aokromes** [comment]
Yes, but you must click a button to skip it.

**Comment by Aokromes** [comment]
Also, you get audio adds from it.

**Comment by ameshkov** [comment]
@Alex-302 can we at least block the audio?

Also let's leave this issue open as we have not solved it.
One day we'll return to it, but right now it's a nightmare to decrypt&read the js they use for the anti-adblock.

**Comment by Alex-302** [comment]
Audio? I don't hear nothing, and don't find an audio in the resources.

**Comment by Aokromes** [comment]
It's not allways. but some ads comes with audio.

**Comment by Alex-302** [comment]
But ads are blocked by English filter.

**Comment by Aokromes** [comment]
http://pastebin.com/FAM6GgqC
pastebin of one adf.ly with audio add.
http://i.imgur.com/fhU6Him.png
notice the right side adf.ly comes with speaker icon.

**Comment by ameshkov** [comment]
@Alex-302, frame is hidden now, not blocked.

Try this rule:
```
||adf.ly/1market.php
```

**Comment by Alex-302** [comment]
@Aokromes 
I don't understand where this audio is. Can you provide me remote access by TeamViewer?

**Comment by ameshkov** [comment]
@Alex-302 have you read what I've posted?

Hidden iframe contains RANDOM ads.

**Comment by Aokromes** [comment]
@ameshkov after adding that rule i don't have seen any new audio ad (ofc the page still detects adguard).

**Comment by Alex-302** [comment]
@ameshkov, I haв opened tab, and not refreshed it. The rule added.

**Comment by Aokromes** [comment]
New pop-under into adf.ly http://adf.ly/1ThQEM
