### ISSUE TITLE
watchfree.to - missed popup ads on Android

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#965]
Everything is good on desktop, I haven't checked it on Android though

UPD: you should switch to another player a couple of times.
Ads are missed for some players, not all.

**Comment by Alex-302** [comment]
Should I click on the links on the right site?
http://imagizer.imageshack.com/img903/8727/KRahUn.jpg

**Comment by Alex-302** [comment]
added
nosvideo.com#%#document.cookie = "B0E93=4";
||bestreams.net/jquery.mn.js
||fungoiddempseyimpasse.info^$third-party
||mdn2015x1.com^$third-party
||mintake.com^$third-party
||trklnks.com^$third-party
