### ISSUE TITLE
[Android] Реклама на yaplakal.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#966]
Баннер в фоне и справа у края экрана.
http://snag.gy/RvvF2.jpg
http://snag.gy/hD2Sh.jpg
Баннер в правой части экрана у меня не появляется, вместо него отображается пустое место.

TICKET ID
ZDT-425-13846

**Comment by Alex-302** [comment]
added
yap.ru,yaplakal.com,yaplakal.ru##ins[data-width="240"][data-height="400"]
