### ISSUE TITLE
[Android] Ads in Speedtest app 

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#967]
https://play.google.com/store/apps/details?id=org.zwanoo.android.speedtest&hl=en

Ads in the app, starting in about 3-4 minutes after app start. 

HTTP requests log: HAN-669-24820

**Comment by Alex-302** [comment]
Cannot reproduce. Maybe user sent default log, not HTTP requests.

**Comment by vbagirov** [comment]
HTTP requests log in HAN-669-24820

**Comment by evgeniy-ADG** [comment]
Пользователь пишет: 

И снова здравствуйте. Я так понимаю, что решение проблемы зависло. Но за 
прошедшее время обнаружил еще одну закономерность - реклама в 
приложениях пробивается только при мобильной сети (4G, 3G, и тд), по 
WiFi рекламы нет. Может, эта информация поможет?

**Comment by Alex-302** [comment]
Значит у него не фильтруется мобильное подключение. У него впн или прокси?

**Comment by evgeniy-ADG** [comment]
...... У него вообще вот так: "org.zwanoo.android.speedtest" : [ "MOBILE", "WIFI" ],
[speedtest state.txt](https://github.com/AdguardTeam/ExperimentalFilter/files/66570/speedtest.state.txt)
Я ему напишу, уточним. Думал, что наличие задачи подразумевает, что с этим все ок.

**Comment by Alex-302** [comment]
а где "AD_FILTERING"? Пусть в файерволе проверит, может блокировку рекламы выключил для приложения.

**Comment by evgeniy-ADG** [comment]
Ну, я тоже об этом.

**Comment by Bohdan-SUP** [comment]
Проблема решена. Он сам отключил фильтрацию рекламы.
Сейчас все хорошо.
