### ISSUE TITLE
audiusa.com - javascript is broken

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#970]
I suppose it's due to blocked "optimizely.com"

**Comment by Alex-302** [comment]
added to analytics filter
@@||audiag.112.2o7.net^$domain=audiusa.com

**Comment by ameshkov** [comment]
The same issue with these filters:

English Filter
Spyware Filter
Social media Filter
Mobile ads Filter
Safari Filter
EasyList
EasyPrivacy
Fanboy's Annoyances (includes Fanboy's Social Blocking List)
Fanboy's Enhanced Tracking List
Peter Lowe's List
Adblock Warning Removal List
Prebake
Anti-Adblock Killer

**Comment by Alex-302** [comment]
Can't reproduce with added exclusion.

**Comment by ameshkov** [comment]
Me too. I asked user to send a bug report from the app so we can check what exact filters are used.
