### ISSUE TITLE
metacritic.com - missed sharing block

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#971]
http://www.metacritic.com/movie/chi-raq

Look at the clickable red square.
Also all three buttons are visible in mobile site version.

Also there're some suspicious background requests.

**Ad servers:**
ifmnwi.club

**Tracking servers:**
arlime.com

**Comment by Alex-302** [comment]
to analytics:
||arlime.com^$third-party
||beanstock.com^$third-party
to English
||ifmnwi.club^$third-party

**Comment by ameshkov** [comment]
Share buttons are still there on mobile

**Comment by Alex-302** [comment]
added
metacritic.com##.sharing 
metacritic.com##.social_btm
checked on android
