### ISSUE TITLE
www.gametrailers.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/ExperimentalFilter#974]
For example: http://www.gametrailers.com/videos/view/gametrailers-com/116427-Paragon-Dekker-Reveal-Teaser

Video doesn't play with enabled Adguard

FPK-810-30391

**Comment by Alex-302** [comment]
Added
```
@@||liverail.com/swf/*/vpaid-player.swf
@@||liverail.com/swf/*/admanager.swf
@@||liverail.com^$domain=cdn-static.liverail.com
```
