### ISSUE TITLE
spaces.ru - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#977]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=44806743

**Comment by Alex-302** [comment]
This rule was added yesterday:
spaces.ru##.ofk_main
The site is clean on my phone.

**Comment by evgeniy-ADG** [comment]
I still can see the ad after I have added the rule in the user filter: http://snag.gy/OMy39.jpg
LBB-473-56189

**Comment by ameshkov** [comment]
Господа, внутри тикета можно и по русски общаться, чего вы в самом деле:)

**Comment by Alex-302** [comment]
А в каком браузере? я В Хроме проверял - чисто, а в UC Browser - не скрылся.

**Comment by evgeniy-ADG** [comment]
У меня хром, режим прокси, high-quality, стандартные фильтры. 
Фильтры обновил, не помогло, добавил руками spaces.ru##.ofk_main - тоже. Сбросил кеш и данные хрома - тоже есть реклама. На других сайтах рекламы нет.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
А можешь подключить телефон к компу по usb и перейти по этой ссылке?
slimjet://inspect/#devices
Если запущен ADB, то в списке должен будет появиться телефон, и можно будет посмотреть код.

**Comment by ameshkov** [comment]
Правильная ссылка:
chrome://inspect

**Comment by ameshkov** [comment]
А режим фильтрации точно не упрощенный?

**Comment by evgeniy-ADG** [comment]
У меня - точно, пользовтелям, у которых speedy, рекомендуем сменить. Через 2 часа сделаю и сообщу.

**Comment by evgeniy-ADG** [comment]
@Alex-302 
Сайт лежал, сейчас заработал. Подключил, запустил, работает. Какая информация нужна?

**Comment by Alex-302** [comment]
Нужно тел по usb подключить к компу. В дроиде и на компе запустить хромы и в адрусную строку вбить
chrome://inspect

**Comment by evgeniy-ADG** [comment]
153 494 607
7833
Вот, прошу : ) Тел появился, сайт видно.

**Comment by Alex-302** [comment]
добавил
spaces.ru###page_ofk

**Comment by evgeniy-ADG** [comment]
Вопрс снова актуален, в UC Browser не блокируется и у меня: http://snag.gy/GyfRJ.jpg
Cloud boost, preload page и т. д. отключены. 

В Chrome баннера нет. 
На других сайтах рекламы не замечаю.

LBB-473-56189

**Comment by Alex-302** [comment]
в uc browser сокрытие не работает, т.к. трафик через них идёт.

**Comment by evgeniy-ADG** [comment]
Спасибо. Пользователя проинформировал.

**Comment by Bohdan-SUP** [comment]
Не блокирует в Хроме:
https://www.dropbox.com/s/tfeac25urazn540/Screenshot_2016-01-03-02-29-57.png?dl=0

**Comment by ameshkov** [comment]
@Alex-302 переоткрыл, надо перепроверить

**Comment by Alex-302** [comment]
@ameshkov имена элементов часто меняют
Добавил:
```
spaces.ru###index_page > div[class][id]:last-child
```

**Comment by evgeniy-ADG** [comment]
HPJ-867-66451 - этому пользователю не помогло

![image](https://cloud.githubusercontent.com/assets/15856304/12092130/f1f3bddc-b303-11e5-8bd7-5edcf28be712.png)

**Comment by Alex-302** [comment]
добавил
spaces.ru###page_xpj
