### ISSUE TITLE
cbs.com - Anti-adblock

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#978]
http://www.cbs.com/shows/60_minutes/
http://snag.gy/W72bQ.jpg
YDG-906-18491 and RHH-504-35645

**Comment by Alex-302** [comment]
Added
@@||b.ifmnwi.club/adblockr.javascript$domain=cbs.com
@@||b.ifmnwi.club/ads.bmp$domain=cbs.com

**Comment by Bohdan-SUP** [comment]
http://www.cbs.com/shows/code-black/video/vXJFcO4QbL8lg_pFdv7tUicyphar6uLu/code-black-the-son-rises/
http://imgur.com/4Pu3rC5
FHN-398-28263

**Comment by Alex-302** [comment]
@Bohdan-SUP 
у меня с нашими фильтрами видео работает.
какие фильтры включены? Антитрекинг используется? Если да - какие опции включены?
У тебя повтоорилось?

**Comment by Alex-302** [comment]
юзер с форума из США тоже не подтвердил проблему

**Comment by Alex-302** [comment]
Попросите удалённый доступ. Подключусь - посмотрю в чём дело.

**Comment by evgeniy-ADG** [comment]
Попросил, ждём ответа.
