### ISSUE TITLE
ign.com - videos are broken

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#980]

**Comment by Alex-302** [comment]
@@||b.scorecardresearch.com/beacon.js$domain=ign.com
Can you check this rule?

**Comment by ameshkov** [comment]
Maybe it's better to unblock whole domain?

**Comment by Alex-302** [comment]
I can't reproduce this problem now. Can you check again without exception?
>unblock whole domain?
this site requests only one script
b.scorecardresearch.com/beacon.js
and send statistiscs.
I see many exclusions for @@||b.scorecardresearch.com/beacon.js in our Spyware filter and EasyPrivacy.

**Comment by ameshkov** [comment]
Resolved, thank you @Alex-302
