### ISSUE TITLE
[Adguard for iOS] http://www.soccer.ru/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#981]
Пропущена реклама
1. http://snag.gy/8h1NY.jpg
2. баннер в центре есть также на Android и ПК: http://snag.gy/X5jsX.jpg

TICKET ID
YBN-668-71969

**Comment by Alex-302** [comment]
Added to Russian
```
||soccer.ru/images/rivalo_
soccer.ru##div[style="width:240px;height:400px;"]
soccer.ru##div[style*="width:100%; height:120px;"]
```
The first banner should be removed by
```
||hgdat.com^$third-party
```
