### ISSUE TITLE
macworld.com - picture links are not clickable

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#982]
http://www.macworld.com/

**Comment by Alex-302** [comment]
added to spyware filter
@@||b.scorecardresearch.com/r?$domain=macworld.com
@@||omtrdc.net/b/ss/$domain=macworld.com

**Comment by ameshkov** [comment]
This is the correct rule:
```
@@||b.scorecardresearch.com^$domain=macworld.com
```
