### ISSUE TITLE
video.foxnews.com - player is broken in extension

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#983]
video.foxnews.com

**Comment by Alex-302** [comment]
Can't confirm(Chrome for Win, Eng, Rus, Soc, Analytics)

**Comment by Alex-302** [comment]
Added:
- to spyware
@@||partner.googleadservices.com/gpt/pubads_$domain=video.foxnews.com
@@||analytics.edgesuite.net/html5/akamaihtml$domain=video.foxnews.com
- to English(reported)
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=video.foxnews.com

**Comment by ameshkov** [comment]
I am pretty sure first rule (pubads_) should be added to the English filter.

**Comment by Alex-302** [comment]
OK, moved.
