### ISSUE TITLE
Missed ads http://www.cnbeta.com/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#984]
1. http://snag.gy/Fjk4P.jpg and http://snag.gy/fPxry.jpg
2. on the customer's side:  http://snag.gy/lw1K4.jpg

filters: http://snag.gy/bizSp.jpg

TICKET ID
IKI-240-49791

**Comment by Alex-302** [comment]
Looks like clean with his filters list.

**Comment by evgeniy-ADG** [comment]
The customer says that the problem still exists. What do I do? Should I ask for some more information?

**Comment by Alex-302** [comment]
I can look for ads via TeamViewer.

**Comment by evgeniy-ADG** [comment]
Жду подтверждения от пользователя.
