### ISSUE TITLE
Фоновая реклама на http://tfile.me/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#985]
http://snag.gy/sIeVq.jpg
Похожая проблема: https://github.com/AdguardTeam/ExperimentalFilter/issues/958 https://github.com/AdguardTeam/ExperimentalFilter/issues/954

TICKET ID
MQI-293-58721

**Comment by Alex-302** [comment]
Added
||wedtor.com^$third-party
||reborko.com^$third-party
tfile.me#$#body { padding: 0 0 0!important; background: transparent!important; }
