### ISSUE TITLE
[Adguard for iOS] cuidad.com.ar

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#990]
ads and white spaces
http://snag.gy/1El30.jpg
http://snag.gy/81e6r.jpg
WBP-871-61860

**Comment by Alex-302** [comment]
У меня какая-то ерунда открывается
http://imagizer.imageshack.com/img910/4374/yvdELj.jpg
судя по скринам юзера - не то что надо.
Уточни куда надо заходить. Зарегаться не получается, выдаёт ERROR_SEND_MAIL

**Comment by evgeniy-ADG** [comment]
Правильный линк http://ciudad.com.ar/
cIUdad, not cUIdad

**Comment by Alex-302** [comment]
У меня чисто. У вас повторяется?

**Comment by evgeniy-ADG** [comment]
@Bohdan-SUP ты можешь как-то на iOS проверить? У меня на Android все ок.

**Comment by Alex-302** [comment]
Нужно на реальном устройстве проверить, т.к. в iOS возможностей сокрытия рекламы меньше(не работают правила вида #$#)

**Comment by Alex-302** [comment]
Пока закрываю, т.к. не вижу проблем
