### ISSUE TITLE
[Android] rollingstone.com - Disqus

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/ExperimentalFilter#994]
Disqus plug-in is blocked
http://www.rollingstone.com/music/features/the-inside-story-of-david-bowies-stunning-new-album-blackstar-20151123?page=3
DCD-563-86674

**Comment by Alex-302** [comment]
added to spyware filter
@@||googletagmanager.com/gtm.js$domain=rollingstone.com
